// ==UserScript==
// @name           AdsBypasser
// @namespace      AdsBypasser
// @copyright      2012+, Wei-Cheng Pan, https://adsbypasser.github.io/
// @version        7.29.0
// @license        BSD
// @homepageURL    https://adsbypasser.github.io/
// @supportURL     https://github.com/adsbypasser/adsbypasser/issues
// @updateURL https://raw.githubusercontent.com/siritami/test1/release/release/adsbypasser.full.es7.meta.js
// @downloadURL https://raw.githubusercontent.com/siritami/test1/release/release/adsbypasser.full.es7.user.js
// @icon           https://raw.githubusercontent.com/adsbypasser/adsbypasser/v7.29.0/resources/img/logo.png
// @grant          GM_deleteValue
// @grant          GM_getResourceURL
// @grant          GM_getValue
// @grant          GM_info
// @grant          GM_openInTab
// @grant          GM_registerMenuCommand
// @grant          GM_setValue
// @grant          GM_xmlhttpRequest
// @grant          GM.deleteValue
// @grant          GM.getResourceUrl
// @grant          GM.getValue
// @grant          GM.info
// @grant          GM.openInTab
// @grant          GM.setValue
// @grant          GM.xmlHttpRequest
// @grant          unsafeWindow
// @resource       alignCenter https://raw.githubusercontent.com/adsbypasser/adsbypasser/v7.29.0/resources/css/align_center.css
// @resource       scaleImage https://raw.githubusercontent.com/adsbypasser/adsbypasser/v7.29.0/resources/css/scale_image.css
// @resource       bgImage https://raw.githubusercontent.com/adsbypasser/adsbypasser/v7.29.0/resources/img/imagedoc-darknoise.png
// @noframes
// @run-at         document-start
// @include        http://*
// @include        https://*
// @connect        *
// ==/UserScript==
(()=>{function z(r){var p=E[r];if(void 0!==p)return p.exports;p=E[r]={exports:{}};I[r](p,p.exports,z);return p.exports}function J(){try{B.usw.open=function(){return{closed:!1}}}catch(r){(0,D.warn)("cannot mock window.open")}B.usw.alert=F.nop;B.usw.confirm=F.nop}function G(r){if(r){var p=function(){(0,D.info)("blocked onbeforeunload")};r.onbeforeunload=void 0;K?r.__defineSetter__("onbeforeunload",p):B.usw.Object.defineProperty(r,"onbeforeunload",{configurable:!0,enumerable:!1,get:void 0,set:p});var m=
r.addEventListener;r.addEventListener=function(a){if("beforeunload"===a)(0,D.info)("blocked addEventListener onbeforeunload");else return m.apply(this,arguments)}}}async function L(r){const p=await (0,H.dumpConfig)();(0,D.info)("working on\n%s \nwith\n%s",window.location.toString(),JSON.stringify(p));G(B.usw);J();await r.start()}async function M(r){G(B.usw.document.body);document.title+=" - AdsBypasser";await r.ready()}function N(){return new Promise(r=>{"loading"!==document.readyState?r():document.addEventListener("DOMContentLoaded",
()=>{r()})})}var I=[,(r,p,m)=>{function a(c,d){return h(c)?Array.prototype.forEach.call(c,d):Object.keys(c).forEach(l=>d(c[l],l,c))}function b(c,d){return h(c)?Array.prototype.every.call(c,d):Object.keys(c).every(l=>d(c[l],l,c))}function t(c,d){if(h(c))return Array.prototype.map.call(c,d);const l=Object.assign({},c);Object.getOwnPropertyNames(l).forEach(v=>{l[v]=d(c[v],v,c)});return l}function u(c,d){for(const [l,v]of w(c)){const y=d(v,l,c);if(y!==e)return[l,v,y]}return[e,e,e]}function*w(c){if(h(c))yield*Array.prototype.entries.call(c);
else{var d=Object.getOwnPropertyNames(c);for(const l of d)yield[l,c[l]]}}function h(c){return Array.isArray(c)||"NodeList"===c.constructor.name}function f(c,...d){if("function"!==typeof c)throw new x("must give a function");return(...l)=>c(...d.concat(l))}function g(c){return"string"===typeof c||c instanceof String}function k(){}function q(c){return new Promise(d=>{setTimeout(d,c)})}function n(c,d){return new Promise(l=>{const v=setInterval(function(){const y=d();y!==e&&(clearInterval(v),l(y))},c)})}
m.r(p);m.d(p,{AdsBypasserError:()=>x,every:()=>b,find:()=>u,forEach:()=>a,isString:()=>g,map:()=>t,none:()=>e,nop:()=>k,partial:()=>f,tryEvery:()=>n,wait:()=>q});class x extends Error{constructor(c){super(c)}get name(){return"AdsBypasserError"}}const e=k},(r,p,m)=>{function a(k){g.push(k)}function b(k,q){k=(0,f.map)(k,(n,x)=>{if(n instanceof RegExp)return q[x].match(n);if(Array.isArray(n))return[,,n]=(0,f.find)(n,e=>q[x].match(e)||f.none),n!==f.none?n:null;throw new f.AdsBypasserError("invalid rule");
});return(0,f.every)(k,n=>!!n)?k:null}function t(k,q,n,x){[,,k]=(0,f.find)(k,e=>(e=w(e,q,n,x))?e:f.none);return k!==f.none?k:null}function u(k,q){var n=/\*|https?|file|ftp|chrome-extension/;let x=/\*|(\*\.)?([^/*]+)/;var e=/\/.*/;n=`^(${n.source})://(${x.source})?(${e.source})$`;n=new RegExp(n);e=k.match(n);if(!e)return null;n=e[1];x=e[2];const c=e[3];k=e[4];e=e[5];if("*"===n&&!/https?/.test(q.scheme)||n!==q.scheme)return null;if("file"!==n&&"*"!==x)if(c){if(n=q.host.indexOf(k),0>n||n+k.length!==
q.host.length)return null}else if(x!==q.host)return null;n=e.replace(/[*.[\]?+#]/g,d=>"*"===d?".*":"\\"+d);e=new RegExp(`^${n}$`);return e.test(q.path)?q:null}function w(k,q,n,x){return Array.isArray(k)?t(k,q,n,x):"function"===typeof k?k(q,n,x):k instanceof RegExp?q.match(k):(0,f.isString)(k)?u(k,n):b(k,x)}function h(){const k=window.location.toString(),q={scheme:window.location.protocol.slice(0,-1),host:window.location.host,path:window.location.pathname+window.location.search+window.location.hash},
n={scheme:window.location.protocol,host:window.location.hostname,port:window.location.port,path:window.location.pathname,query:window.location.search,hash:window.location.hash},[x,e,c]=(0,f.find)(g,d=>(d=w(d.rule,k,q,n))?d:f.none);return x===f.none||!e.start&&!e.ready?null:{start:e.start?(0,f.partial)(e.start,c):f.nop,ready:e.ready?(0,f.partial)(e.ready,c):f.nop}}m.r(p);m.d(p,{findHandler:()=>h,register:()=>a});var f=m(1);const g=[]},(r,p,m)=>{function a(h){if(null===h||!(h instanceof Object)||h===
unsafeWindow)return h;if(h instanceof String)return h.toString();if(h instanceof Function)return exportFunction(h,unsafeWindow,{allowCrossOriginArguments:!0});if(h instanceof Array){const g=new unsafeWindow.Array;for(let k=0;k<h.length;++k)g.push(a(h[k]));return g}const f=new unsafeWindow.Object;(0,b.forEach)(h,(g,k)=>{f[k]=a(g)});return f}m.r(p);m.d(p,{GMAPI:()=>w,rawUSW:()=>t,usw:()=>u});var b=m(1);const t=function(){let h=null;try{h=unsafeWindow}catch(f){try{h=(0,eval)("this").global}catch(g){}}return h?
h:(0,eval)("this").window}(),u=function(){if("Greasemonkey"!==("object"===typeof GM_info&&GM_info?GM_info:"object"===typeof GM&&GM&&GM.info?GM.info:{}).scriptHandler)return t;const h={set(f,g,k){if("__adsbypasser_reverse_proxy__"===g)return!1;f[g]=a(k);return!0},get(f,g){if("__adsbypasser_reverse_proxy__"===g)return f;f=f[g];g=typeof f;return null===f||"function"!==g&&"object"!==g?f:new Proxy(f,h)},apply(f,g,k){k=Array.prototype.slice.call(k);f===unsafeWindow.Object.defineProperty&&(k[0]=k[0].__adsbypasser_reverse_proxy__);
f===unsafeWindow.Function.apply&&(g=g.__adsbypasser_reverse_proxy__,k[1]=Array.prototype.slice.call(k[1]));f===unsafeWindow.document.querySelector&&(g=g.__adsbypasser_reverse_proxy__);f===unsafeWindow.document.write&&(g=g.__adsbypasser_reverse_proxy__);k=a(k);return f.apply(g,k)},construct(f,g){g=Array.prototype.slice.call(g);g.unshift(void 0);g=a(g);return new (unsafeWindow.Function.prototype.bind.apply(f,g))}};return new Proxy(unsafeWindow,h)}(),w=function(){if(t.global)return null;const h={};h.openInTab=
"function"===typeof GM_openInTab?GM_openInTab:GM.openInTab;h.getValue="function"===typeof GM_getValue?(f,g)=>Promise.resolve(GM_getValue(f,g)):GM.getValue;h.setValue="function"===typeof GM_setValue?(f,g)=>Promise.resolve(GM_setValue(f,g)):GM.setValue;h.deleteValue="function"===typeof GM_deleteValue?f=>Promise.resolve(GM_deleteValue(f)):GM.deleteValue;h.xmlHttpRequest="function"===typeof GM_xmlhttpRequest?GM_xmlhttpRequest:GM.xmlHttpRequest;h.registerMenuCommand="function"===typeof GM_registerMenuCommand?
GM_registerMenuCommand:b.nop;"function"===typeof GM_getResourceURL?h.getResourceUrl=f=>Promise.resolve(GM_getResourceURL(f)):"object"===typeof GM&&GM&&GM.getResourceUrl&&(h.getResourceUrl=GM.getResourceUrl);return h}()},(r,p,m)=>{function a(c){return"boolean"===typeof c}function b(c){return!!c}function t(c){return parseInt(c,10)}async function u(){let c=x.map(async d=>{const l=await n.GMAPI.getValue(d.key);return d.verify(l)});c=await Promise.all(c);(0,k.every)(c,d=>d)||await n.GMAPI.setValue("version",
0)}async function w(){let c=await n.GMAPI.getValue("version");if(0!==c&&!c)throw new k.AdsBypasserError("invalid version");for(;c<e.length;)e[c](),++c;await n.GMAPI.setValue("version",c)}async function h(){await u();await w();(0,q.register)({rule:{host:/^adsbypasser\.github\.io$/,path:/^\/configure\.html$/},async ready(){await f();n.usw.commit=async c=>{for(const [d,l]of Object.entries(c))await n.GMAPI.setValue(d,l)};n.usw.render({version:await n.GMAPI.getValue("version"),options:{align_center:{type:"checkbox",
value:await n.GMAPI.getValue("align_center"),label:"Align Center",help:"Align image to the center if possible. (default: enabled)"},change_background:{type:"checkbox",value:await n.GMAPI.getValue("change_background"),label:"Change Background",help:"Use Firefox-like image background if possible. (default: enabled)"},redirect_image:{type:"checkbox",value:await n.GMAPI.getValue("redirect_image"),label:"Redirect Image",help:"Directly open image link if possible. (default: enabled)<br/>\nIf disabled, redirection will only works on link shortener sites."},
scale_image:{type:"checkbox",value:await n.GMAPI.getValue("scale_image"),label:"Scale Image",help:"When image loaded, scale it to fit window if possible. (default: enabled)"},log_level:{type:"select",value:await n.GMAPI.getValue("log_level"),menu:[[0,"0 (quiet)"],[1,"1 (default)"],[2,"2 (verbose)"]],label:"Log Level",help:"Log level in developer console. (default: 1)<br/>\n0 will not print anything in console.<br/>\n1 will only print logs on affected sites.<br/>\n2 will print on any sites."}}})}})}
function f(){return new Promise(c=>{const d=setInterval(()=>{n.usw.render&&(clearInterval(d),c())},50)})}async function g(){let c=x.map(async l=>[l.key,await n.GMAPI.getValue(l.key)]);c=await Promise.all(c);const d={};for(const [l,v]of c)d[l]=v;return d}m.r(p);m.d(p,{dumpConfig:()=>g,loadConfig:()=>h});var k=m(1),q=m(2),n=m(3);const x=[{key:"version",default_:0,verify(c){return"number"===typeof c&&0<=c},normalize:t},{key:"align_center",default_:!0,verify:a,normalize:b},{key:"change_background",default_:!0,
verify:a,normalize:b},{key:"redirect_image",default_:!0,verify:a,normalize:b},{key:"scale_image",default_:!0,verify:a,normalize:b},{key:"log_level",default_:1,verify(c){return"number"===typeof c&&0<=c&&2>=c},normalize:t}],e=[async()=>{const c=await n.GMAPI.getValue("align_center"),d=await n.GMAPI.getValue("change_background"),l=await n.GMAPI.getValue("scale_image"),v=await n.GMAPI.getValue("redirect_image"),y="boolean"===typeof c;"boolean"!==typeof d&&await n.GMAPI.setValue("change_background",y?
c:!0);"boolean"!==typeof l&&await n.GMAPI.setValue("scale_image",y?c:!0);y||await n.GMAPI.setValue("align_center",!0);"boolean"!==typeof v&&await n.GMAPI.setValue("redirect_image",!0)},async()=>{"boolean"!==typeof await n.GMAPI.getValue("external_server_support")&&await n.GMAPI.setValue("external_server_support",!1)},async()=>{"number"!==typeof await n.GMAPI.getValue("log_level")&&await n.GMAPI.setValue("log_level",1)},async()=>{await n.GMAPI.deleteValue("external_server_support")}]},(r,p,m)=>{function a(h,
f){f=Array.prototype.slice.call(f);(0,w.isString)(f[0])?f[0]="AdsBypasser: "+f[0]:f.unshift("AdsBypasser:");h=console[h];"function"===typeof h&&h.apply(console,f)}function b(){a("debug",arguments)}function t(){a("info",arguments)}function u(){a("warn",arguments)}m.r(p);m.d(p,{debug:()=>b,info:()=>t,warn:()=>u});var w=m(1)},(r,p,m)=>{m.r(p);var a=m(7);a._.register({rule:{host:/^ak\.sv$/},async ready(){await a._.wait(1E3);(0,a.$)("html").click();await a._.wait(6E3);const b=(0,a.$)('a[class="download_button"]');
await a.$.openLink(b)}});a._.register({rule:{host:/^(www\.)?apunkasoftware\.net$/},async ready(){const b=(0,a.$)("div#proceed-now > a#dlink");await a.$.openLink(b.href)}});a._.register({rule:{host:/^thefileslocker\.net$/},async ready(){(0,a.$)("#downloadbtn").click()}});a._.register({rule:{host:[/^(www\.)?indishare\.org$/,/^uploadrar\.com$/]},async ready(){const b=(0,a.$)("button#downloadbtn.downloadbtn");b.removeAttribute("disabled");b.click()}});a._.register({rule:{host:/^infidrive\.net$/},async ready(){await a._.wait(4E4);
(0,a.$)("button.inline-flex:nth-child(2)").click()}});a._.register({rule:{host:/^k2s\.cc$/},async ready(){await a._.wait(35E3);const b=(0,a.$)("a.link-to-file");await a.$.openLink(b.href)}});a._.register({rule:{host:/^katfile\.com$/},async ready(){const b=(0,a.$)('a[id="dlink"]');await a.$.openLink(b.href)}});a._.register({rule:{host:/^(www\.)?keeplinks\.org$/},async ready(){(0,a.$)('[id="btnproceedsubmit"]').click()}});a._.register({rule:"https://www.mirrored.to/files/*",async ready(){const b=(0,a.$)(".col-sm.centered.extra-top a");
await a.$.openLink(b.href)}});a._.register({rule:{host:/^multiup\.io$/},async ready(){(0,a.$)(".btn-info.btn-lg.btn-block").click()}});a._.register({rule:{host:/^www\.onlinefreecourse\.net$/},async ready(){const b=(0,a.$)('a[class="btn btn-success"]');await a.$.openLink(b)}});a._.register({rule:{host:/^sfile\.mobi$/},async ready(){await a._.wait(8E3);(0,a.$)("#download").click()}});a._.register({rule:{host:/^uploadhaven\.com$/,path:/^\/download\//},async ready(){await a._.wait(18E3);(0,a.$)(".btn-submit-free.btn-download-free").click()}});
a._.register({rule:{host:/^usersdrive\.com$/},async ready(){const b=(0,a.$)(".btn-download");await a.$.openLink(b.href)}});a._.register({rule:{host:/^1ink\.cc$/},async ready(){const b=(0,a.$)("#countingbtn");await a.$.openLink(b.href)}});a._.register({rule:{host:/^1link\.club$/},async ready(){const b=(0,a.$)("#download.btn");await a.$.openLink(b.href)}});a._.register({rule:{host:/^1v\.to$/,path:/^\/t\/[a-zA-Z0-9/=]+/},async start(){const b=window.location.href.replace("/t/","/saliendo/");await a.$.openLink(b)}});
a._.register({rule:{host:/^a2zapk\.io$/},async ready(){const b=(0,a.$)("#dlbtn li a");await a.$.openLink(b.href)}});a._.register({rule:{host:/^adfoc\.us$/},async ready(){const b=(0,a.$)(".skip");await a.$.openLink(b.href)}});a._.register({rule:{host:/^adshnk\.com$/},async ready(){await a._.wait(16E3);(0,a.$)('button[class="ui right labeled icon button primary huge fluid"]').click();await a._.wait(18E3);const b=(0,a.$)('a[id="final_redirect"]');await a.$.openLink(b.href)}});a._.register({rule:{host:/^www\.adz7short\.space$/},
async ready(){const b=(0,a.$)("#continue");await a._.wait(1E4);b.click()}});a._.register({rule:{host:/^bcvc\.ink$/},async ready(){await a._.wait(5E3);(0,a.$)("#getLink").click()}});a._.register({rule:{host:/^(www\.)?biglistofwebsites\.com$/,path:/^\/go\/(\w+\.\w+)$/},async start(b){await a.$.openLink("http://"+b.path[1])}});a._.register({rule:[{host:/^(www\.)?([a-zA-Z0-9]+\.)?binbox\.io$/,path:/\/o\/([a-zA-Z0-9]+)/}],async start(b){b=window.atob(b.path[1]);await a.$.openLink(b)}});a._.register({rule:{host:/^bioskopkeren\.boo$/},
async ready(){await a._.wait(1E3);(0,a.$)(".reklamgec").click()}});a._.register({rule:{host:/^boost\.ink$/},async start(){const b=(0,a.$)("body").getAttribute("result");b&&await a.$.openLink(atob(b))}});a._.register({rule:{host:/^cocoleech\.com$/},async ready(){const b=(0,a.$)(".btn.btn-block.btn-success");await a.$.openLink(b.href)}});a._.register({rule:{host:/^cpmlink\.net$/},async ready(){const b=(0,a.$)("#btn-main");await a.$.openLink(b.href)}});a._.register({rule:{host:/^ctr\.sh$/},async ready(){await a._.wait(12E3);
(0,a.$)(".btn.btn-primary.btn-captcha").click()}});a._.register({rule:{host:/^cutpaid\.com$/},async ready(){let b=(0,a.$)(".btn-primary");b&&(await a._.wait(2E4),b.click());b=(0,a.$)(".btn-success.btn-lg.get-link");await a._.wait(9E3);await a.$.openLink(b.href)}});a._.register({rule:{host:/^www\.dlink3\.com$/},async ready(){await a._.wait(12E3);const b=(0,a.$)('[class="myButton"]');await a.$.openLink(b.href)}});a._.register({rule:{host:/^dlupload\.com$/},async ready(){await a._.wait(3500);(0,a.$)(".btn-block.btn-primary.text-white.shadow.m-1.position-relative.up-tooltip-container").click();
await a._.wait(6E3);(0,a.$)(".btn-block.continue-btn-bg").click()}});a._.register({rule:{host:/^earnlink\.io$/},async ready(){const b=a.$.searchFromScripts(/"([^"]+)"\)\.html\("Continue"\)/);await a.$.openLink(b[1])}});a._.register({rule:{host:/^forex-trnd\.com$/},async ready(){await a._.wait(1E4);(0,a.$)(".get-link").click()}});a._.register({rule:{host:/^exeo\.app$/},async ready(){(0,a.$)(".link-button.button").click();await a._.wait(2E3);(0,a.$)(".link-button").click();await a._.wait(6E3);(0,a.$)(".link-button.get-link").click()}});
a._.register({rule:{host:/^fc-lc\.(com|xyz)$/},async ready(){await a._.wait(2E3);(0,a.$)(".btn-primary.btn-captcha.mb-4").click()}});a._.register({rule:{host:/^loaninsurehub\.com$/},async ready(){var b=(0,a.$)("#glink");b&&b.click();await a._.wait(12E3);a.$.remove("#overlay");(b=(0,a.$)("#surl"))&&b.click()}});a._.register({rule:{host:/^fir3\.net$/},async ready(){await a._.wait(12E3);(0,a.$)(".btn.btn-success.btn-lg.get-link").click()}});a._.register({rule:{host:/^get-click2\.blogspot\.com$/},async ready(){const b=
(0,a.$)("button#gotolink");b.removeAttribute("disabled");await a._.wait(1);b.click()}});a._.register({rule:{host:/^getthot\.com$/},async ready(){await a._.wait(12E3);const b=(0,a.$)(".skip-btn");await a.$.openLink(b.href)}});a._.register({rule:{host:/^gplinks\.co$/},async ready(){await a._.wait(8E3);(0,a.$)(".get-link").click()}});a._.register({rule:{host:/^hen-tay\.net$/,path:/^\/go\//},async ready(){const b=(0,a.$)("#download_url div a");await a.$.openLink(b.href)}});a._.register({rule:{host:/^hotshorturl\.com$/},
async ready(){const b=(0,a.$)("frame[scrolling=yes]");await a.$.openLink(b.src)}});a._.register({rule:{host:/^icutlink\.com$/},async ready(){await a._.wait(1E4);const b=(0,a.$)(".btn-success.btn-lg.get-link");await a.$.openLink(b)}});a._.register({rule:{host:/^zegtrends\.com$/},async ready(){await a._.wait(12E3);(0,a.$)("div > button.bsub").click()}});a._.register({rule:{host:/^imagetwist\.netlify\.app$/},async ready(){const b=(0,a.$)(".btn.btn-dark");await a.$.openLink(b.href)}});a._.register({rule:{host:/^www\.javlibrary\.com$/,
query:/url=([^&]+)/},async start(b){await a.$.openLink(decodeURIComponent(b.query[1]))}});a._.register({rule:{host:/^kimochi\.info$/,path:/^\/inter$/},async ready(){const b=(0,a.$)("a#next");await a.$.openLink(b.href)}});a._.register({rule:{host:/^(www\.)?kingofshrink\.com$/},async ready(){const b=(0,a.$)("#textresult > a");await a.$.openLink(b.href)}});a._.register({rule:{host:/^linegee\.net$/},async ready(){(0,a.$)("p.kecil a").click()}});a._.register({rule:{host:/^link\.turkdown\.com$/},async ready(){await a._.wait(5E3);
const b=(0,a.$)(".btn-success.btn-lg.get-link");await a.$.openLink(b.href)}});a._.register({rule:{host:/^link1s\.com$/},async ready(){await a._.wait(1E4);(0,a.$)(".btn.btn-success.btn-lg.get-link").click()}});(function(){async function b(h){let f=a.$.window.$;for(;!f;)await a._.wait(50),f=a.$.window.$;h=f(h);return 0<h.length?h:null}function t(h){return new Promise((f,g)=>{h.is("a")&&h.attr("href")&&f(h.attr("href"));a.$.window.$.ajax({dataType:"json",type:"POST",url:h.attr("action"),data:h.serialize(),
success:k=>{k.url?f(k.url):g(new a._.AdsBypasserError(k.message))},error:(k,q,n)=>{a._.warn(k,q,n);g(new a._.AdsBypasserError("request error"))}})})}a._.register({rule:{host:[/^adsafelink\.com$/,/^birdurls\.com$/,/^dz4link\.com$/,/^(linkmoni|shrinkcash)\.com$/,/^shrt10\.com$/,/^tmearn\.net$/,/^vinaurl\.net$/,/^payskip\.org$/,/^clik\.pw$/,/^miniurl\.pw$/,/^aylink\.co$/,/^(clk|oko)\.sh$/,/^cpmlink\.pro$/,/^gitlink\.pro$/,/^megalink\.pro$/,/^met\.bz/,/^mitly\.us$/,/^oke\.io$/,/^pahe\.plus$/,/^pingit\.im$/,
/^thotpacks\.xyz$/]},async ready(){await (new w).call()}});class u{constructor(){this._overlaySelector='[class$="Overlay"], #__random_class_name__, #headlineatas, #myModal, .opacity_wrapper, #overlay';this._formSelector='#go-link, .go-link, #originalLink.get-link, form[action="/links/go"]'}removeOverlay(){a.$.remove(this._overlaySelector);a.$.block(this._overlaySelector,document.body);setInterval(()=>{document.body.style.overflow="initial"},500)}removeFrame(){a.$.remove("iframe")}async call(){if(await this.prepare()){var h=
await this.getMiddleware();h?(h=await this.getURL(h),await a.$.openLink(h)):this.withoutMiddleware()}}}class w extends u{async prepare(){this.removeOverlay();if(!a.$.$("#captchaShortlink, div.g-recaptcha"))return!0;a._.info("recaptcha detected, stop");a._.info("trying to listen submit button");if(!a.$.$("#invisibleCaptchaShortlink"))return!1}async submitListen(h){(new MutationObserver(()=>{h.disabled||h.click()})).observe(h,{attributes:!0})}async getMiddleware(){return await b(this._formSelector)}withoutMiddleware(){(0,a.$)("#link-view").submit()}async getURL(h){for(;;){await a._.wait(1E3);
try{const f=await t(h);if(f)return f}catch(f){a._.warn(f)}}}}})();a._.register({rule:{host:/^n\.fcd\.su$/},async ready(){const b=(0,a.$)("a.btn:nth-child(2)");await a.$.openLink(b.href)}});a._.register({rule:{host:/^linkpoi\.me$/},async ready(){await a._.wait(6E3);(0,a.$)(".btn.btn-primary.btn-block.redirect.get-link").click()}});a._.register({rule:{host:/^linkshrink\.net$/,path:/^\/[a-zA-Z0-9]+$/},async start(){a.$.window._impspcabe=0},async ready(){let b=a.$.searchFromScripts(/revC\("([^"]+)"\)/);
b=atob(b[1]);await a.$.openLink("/"+b)}});a._.register({rule:{host:/^linksly\.co$/},async ready(){(0,a.$)(".btn-primary").click()}});a._.register({rule:{host:[/^go\.linksly\.co$/,/^go\.bitcosite\.com$/]},async ready(){await a._.wait(8E3);const b=(0,a.$)(".btn-success.btn-lg.get-link");await a.$.openLink(b.href)}});a._.register({rule:{host:/^lnk2\.cc$/,path:/^\/go\//},async ready(){a.$.remove("iframe, .popupOverlay");await a._.wait(18E3);(0,a.$)("#getLink").click()}});a._.register({rule:{host:/^www\.lolinez\.com$/,
query:/\?(.+)/},async start(b){await a.$.openLink(b.query[1])}});a._.register({rule:{host:/^mangalist\.org$/},async ready(){await a._.wait(1E3);(0,a.$)(".btn-primary.url.text-center").click()}});a._.register({rule:{host:/^mylink\.us$/},async ready(){await a._.wait(8E3);(0,a.$)("div.skip_btn a").click()}});a._.register({rule:{host:/^nmac\.to$/,path:/^\/dl\/(.+)/},async ready(){const b=(0,a.$)(".btn-medium.btn-block");await a.$.openLink(b.href)}});a._.register({rule:{host:/^noriskdomain\.com$/},async ready(){await a._.wait(1E4);
(0,a.$)(".uk-button-primary.go-to-button").click();await a._.wait(1E3);(0,a.$)(".uk-button-primary.go-to-button").click()}});a._.register({rule:{host:/^noweconomy\.live$/},async ready(){const b=(0,a.$)('[class="btn-main get-link"]');await a.$.openLink(b.href)}});a._.register({rule:{host:/^www\.oni\.vn$/},async ready(){a.$.remove("iframe");var b=a.$.searchFromScripts(/data:"([^"]+)"/);if(!b)throw new a._.AdsBypasserError("pattern changed");b=b[1];b=await a.$.get("/click.html",b);await a.$.openLink(b)}});
a._.register({rule:{host:/^otomi-games\.com$/,path:/^\/go\//},async ready(){const b=(0,a.$)("#wpsafe-link a");await a.$.openLink(b.href)}});a._.register({rule:{host:/^(www\.)?ouo\.(io|press)$/,path:/(^\/\w+$|^\/go\/\w+$)/},async ready(){(0,a.$)("form").submit()}});a._.register({rule:{host:/^paylinnk\.com$/},async ready(){await a._.wait(2E3);(0,a.$)("div.banner.banner-captcha").click();(0,a.$)(".btn.btn-success.btn-lg.get-link").click()}});a._.register({rule:{host:/^icerik\.site$/,path:/^\/go/},async ready(){await a._.wait(500);
(0,a.$)("#get_link_btn").click()}});a._.register({rule:{host:[/^realsht\.mobi$/]},async ready(){(0,a.$)("#download_link").click()}});a._.register({rule:{host:/^preview\.rlu\.ru$/},async ready(){const b=(0,a.$)("#content > .long_url > a");await a.$.openLink(b.href)}});a._.register({rule:{host:/^segmentnext\.com$/,path:/^\/interstitial\.html$/,query:/return_url=([^&]+)/},async start(b){await a.$.openLink(decodeURIComponent(b.query[1]))}});a._.register({rule:{host:[/^shink\.me$/,/^shon\.xyz$/]},async ready(){(0,a.$)("#skip").submit()}});
a._.register({rule:{host:/^(short|srt)\.am$/},async ready(){await a._.wait(5E3);await a.$.openLink("",{post:{_image:"Continue"}})}});(function(){function b(t){const u=a.$.searchFromScripts(/xpid:"([^"]+)"/),w={adSessionId:t},h={Accept:"application/json, text/javascript"};u&&(h["X-NewRelic-ID"]=u);const f=setInterval(function(){a.$.get("/shortest-url/end-adsession",w,h).then(function(g){g=JSON.parse(g);if("ok"==g.status&&g.destinationUrl)return clearInterval(f),a.$.removeAllTimer(),g=decodeURIComponent(g.destinationUrl),
a.$.openLink(g)})},1E3)}a._.register({rule:{host:[/^(cllkme|clkmein|corneey|ceesty)\.com$/,/^(destyy|festyy|gestyy)\.com$/,/^sh\.st$/],path:/^\/[\d\w]+/},async ready(){a.$.remove("iframe");a.$.removeAllTimer();const t=a.$.searchFromScripts(/sessionId: "([\d\w]+)",/);if(t)b(t[1]);else{var u=new MutationObserver(w=>{w.forEach(()=>{const h=a.$.searchFromScripts(/sessionId: "([\d\w]+)",/);h&&(u.disconnect(),b(h[1]))})});u.observe(document.body,{childList:!0})}}})})();a._.register({rule:{host:[/^shortlinkto\.biz$/,
/^uplinkto\.hair$/]},async ready(){const b=(0,a.$)(".view-well a");await a.$.openLink(b.href)}});a._.register({rule:{host:/^(www\.)?shortly\.xyz$/},async ready(){await a._.wait(8E3);(0,a.$)(".btn-success.btn-lg.get-link").click()}});a._.register({rule:{host:/^shortmoz\.link$/},async ready(){(0,a.$)(".btn.btn-primary.btn-block").click()}});a._.register({rule:{host:/^(www\.)?similarsites\.com$/,path:/^\/goto\/([^?]+)/},async start(b){b=b.path[1];/^https?:\/\//.test(b)||(b="http://"+b);await a.$.openLink(b)}});
a._.register({rule:{host:/^spacetica\.com$/},async ready(){(0,a.$)(".btn.btn-primary.btn-xs").click()}});a._.register({rule:{host:/^www\.spaste\.com$/,path:/^\/site\//},async ready(){await a._.wait(15E3);(0,a.$)("#template-contactform-submit").click()}});a._.register({rule:{host:/^stfly\.(me|xyz)$/},async ready(){(0,a.$)(".btn-captcha.m-2.form-send").click()}});a._.register({rule:{host:/^blogbux\.net$/},async ready(){const b=(0,a.$)(".btn-captcha.m-2.form-send");await a._.wait(12E3);b.click()}});
a._.register({rule:{host:/^techtrendmakers\.com$/},async ready(){const b=(0,a.$)(".btn-captcha.m-2.form-send.step_btn");await a._.wait(6E3);b.click()}});a._.register({rule:{host:/^(www\.)?supercheats\.com$/,path:/^\/interstitial\.html$/,query:/(?:\?|&)oldurl=([^&]+)(?:$|&)/},async start(b){await a.$.openLink(b.query[1])}});a._.register({rule:{host:/^swzz\.xyz$/,path:/^\/link\//},async ready(){const b=(0,a.$)("a.btn.btn-primary");await a.$.openLink(b.href)}});a._.register({rule:{host:/^techgeek\.digital$/},
async ready(){var b=(0,a.$)('[class="btn-main get-link"]');b&&b.click();(b=(0,a.$)('a[class="btn-main get-link"]'))&&await a.$.openLink(b.href)}});a._.register({rule:{host:/^thinfi\.com$/},async ready(){const b=(0,a.$)("div p a");await a.$.openLink(b.href)}});a._.register({rule:{host:/^go\.tnshort\.net$/},async ready(){await a._.wait(3E3);const b=(0,a.$)('a[class="btn btn-success btn-lg get-link"]');await a.$.openLink(b.href)}});a._.register({rule:{host:/^tribuntekno\.com$/},async ready(){var b=a.$.$("#lite-human-verif-button");
b&&b.click();(b=a.$.$("#lite-start-sora-button"))&&b.click()}});a._.register({rule:{host:/^tutwuri\.id$/},async ready(){await a._.wait(1E3);(0,a.$)("#btn-1").click();await a._.wait(12E3);(0,a.$)("#btn-2").click();(0,a.$)("#btn-3").click()}});a._.register({rule:{host:/^urlbluemedia\.shop$/},async ready(){await a._.wait(7E3);(0,a.$)("input#nut").click()}});a._.register({rule:{host:[/(^|\.)urlcash\.(com|org)$/,/^(detonating|smilinglinks|pornyhost|urlgalleries)\.com$/,/^looble\.net$/,/^xxxs\.org$/]},
async ready(){if(a.$.window&&a.$.window.linkDestUrl)await a.$.openLink(a.$.window.linkDestUrl);else{var b=document.body.innerHTML.match(/linkDestUrl = '(.+)'/);b&&await a.$.openLink(b[1])}}});a._.register({rule:{host:/^(www\.)?vzturl\.com$/},async ready(){const b=(0,a.$)("frame[scrolling=yes]");await a.$.openLink(b.src)}});a._.register({rule:{host:/^xpshort\.com$/},async ready(){await a._.wait(8E3);(0,a.$)(".btn-success.btn-lg.get-link").click()}});a._.register({rule:{host:/^22pixx\.xyz$/,path:/^\/ia-[aio]\/(.+)\.jpeg\.html/},
async start(){const b=window.location.href.replace("/ia-","/").replace(".html","");await a.$.openLink(b)}});a._.register({rule:{host:/^22pixx\.xyz$/,path:/^\/ib-[aior]\/(.+)\.jpeg\.html/},async start(){const b=window.location.href.replace("/ib-","/").replace(".html","");await a.$.openLink(b)}});a._.register({rule:{host:/^22pixx\.xyz$/,path:/^\/i-[ai1]\/(.+)\.jpeg\.html/},async start(){const b=window.location.href.replace("/i-","/").replace(".html","");await a.$.openLink(b)}});a._.register({rule:{host:/^22pixx\.xyz$/,
path:/^\/x-[aor]\/(.+)\.jpeg\.html/},async start(){const b=window.location.href.replace("/x-","/").replace(".html","");await a.$.openLink(b)}});a._.register({rule:{host:/^22pixx\.xyz$/,path:/^\/y-[ao1]\/(.+)\.jpeg\.html/},async start(){const b=window.location.href.replace("/y-","/").replace(".html","");await a.$.openLink(b)}});a._.register({rule:{host:/^22pixx\.xyz$/,path:/^\/x-i\/(.+)\.jpeg\.html/},async start(){const b=window.location.href.replace("/x","/y");await a.$.openLink(b)}});a._.register({rule:{host:[/^abload\.de$/,
/^imageup\.ru$/]},async ready(){const b=(0,a.$)("#image");await a.$.openImage(b.src)}});a._.register({rule:{host:[/^acidimg\.cc$/,/^imx\.to$/]},async ready(){let b=a.$.$("#continuebutton, .button");b&&b.click();b=(0,a.$)(".centred");await a.$.openImage(b.src)}});a._.register({rule:{host:/^bayimg\.com$/},async ready(){const b=(0,a.$)("#mainImage");await a.$.openImage(b.src)}});a._.register({rule:{host:/^beeimg\.com$/},async ready(){const b=(0,a.$)("#beeimage");await a.$.openImage(b.src)}});a._.register({rule:{host:/^www\.casimages\.com$/},
async ready(){const b=(0,a.$)("div.logo a img");await a.$.openImage(b.src)}});a._.register({rule:{host:/^cubeupload\.com$/},async ready(){const b=(0,a.$)("img.galleryBigImg");await a.$.openImage(b.src)}});a._.register({rule:{host:/^(depic|dpic)\.me$/},async ready(){const b=(0,a.$)("#pic");await a.$.openImage(b.src)}});a._.register({rule:{host:/^www\.directupload\.net$/},async ready(){const b=(0,a.$)("#ImgFrame");await a.$.openImage(b.src)}});a._.register({rule:{host:/^fastpic\.org$/,path:/^\/view\//},
async ready(){const b=(0,a.$)("#picContainer img");await a.$.openImage(b.src)}});a._.register({rule:{host:[/^crownimg\.com$/,/^fotokiz\.com$/,/^imgbaron\.com$/,/^imgsen\.com$/,/^imgsto\.com$/,/^kropic\.com$/,/^kvador\.com$/,/^picbaron\.com$/,/^picdollar\.com$/,/^pics4upload\.com$/,/^silverpic\.com$/,/^barbit\.net$/,/^pics4you\.net$/,/^imgstar\.eu$/,/^www\.fappic\.com$/]},async ready(){const b=a.$.$("img.pic");b?await a.$.openImage(b.src):(0,a.$)("form").submit()}});a._.register({rule:{host:/^www\.fotosik\.pl$/},
async ready(){const b=(0,a.$)(".simple-photo img");await a.$.openImage(b.src)}});a._.register({rule:{host:/^www\.hostpic\.org$/},async ready(){const b=(0,a.$)("#photo");await a.$.openImage(b.src)}});a._.register({rule:{host:/^www\.imagebam\.com$/},async ready(){let b=a.$.$("#continue > a");b&&b.click();b=(0,a.$)(".main-image");await a.$.openImage(b.src)}});a._.register({rule:{host:/^imageban\.ru$/},async ready(){const b=(0,a.$)("#img_main");await a.$.openImage(b.src)}});a._.register({rule:{host:/^imagehaha\.com$/,
path:/\/*\/.*/},async ready(){const b=(0,a.$)("img.img-responsive");await a.$.openImage(b.src)}});a._.register({rule:"https://www.imagehost.at/image/*",async ready(){const b=(0,a.$)('meta[property="og:image"]');await a.$.openImage(b.content)}});a._.register({rule:{host:/^www\.imagenetz\.de$/},async ready(){const b=(0,a.$)(".img-rounded.img-responsive");await a.$.openImage(b.src)}});a._.register({rule:{host:/^imageshack\.com$/,path:/^\/i\//},async ready(){const b=(0,a.$)("#lp-image");await a.$.openImage(b.src)}});
a._.register({rule:{host:[/^imagetwist\.com$/,/^imagenpic\.com$/,/^imagexport\.com$/,/^imageshimage\.com$/,/^croea\.com$/,/^vipr\.im$/]},async ready(){const b=(0,a.$)("img.pic");await a.$.openImage(b.src)}});a._.register({rule:{host:/^imageupper\.com$/},async ready(){const b=(0,a.$)("#img");await a.$.openImage(b.src)}});a._.register({rule:{host:/^www\.imagevenue\.com$/},async ready(){const b=(0,a.$)("#main-image");await a.$.openImage(b.src)}});a._.register({rule:{host:[/^cloudgallery\.net$/,/^imgair\.net$/,
/^imgblaze\.net$/,/^imgfrost\.net$/,/^img[a-z]{2,10}\.(sbs|shop)$/,/^pic[a-z]{2,10}\.(sbs|shop)$/,/^pix[a-z]{2,10}\.sbs$/]},async ready(){const b=a.$.searchFromScripts(/imgbg\.src = "([^"]+)";/);await a.$.openImage(b[1])}});a._.register({rule:{host:[/^(imgbase|picforall)\.ru$/]},async ready(){let b=(0,a.$)("#pay_thumb_img img");b=b.getAttribute("onclick");b=b.match(/mshow\('(.+)'\)/);b=b[1];await a.$.openImage(b)}});a._.register({rule:{host:[/^imgbb\.com$/,/^ibb\.co$/]},async ready(){const b=(0,a.$)(".image-viewer-container img");
await a.$.openImage(b.src)}});a._.register({rule:{host:/^imgbox\.com$/},async ready(){const b=(0,a.$)("#img");await a.$.openImage(b.src)}});a._.register({rule:{host:[/^2i\.(cz|sk)$/,/^(picnew|rintor)\.space$/,/^[0-9]{1,3}xpics\.space$/,/^imgcloud\.pw$/,/^pilot007\.org$/,/^img\.javstore\.net$/,/^www\.imghit\.com$/,/^xxxaddicted\.top$/],path:/^\/(image|i)\/.*/},async ready(){const b=(0,a.$)('link[rel="image_src"]');await a.$.openImage(b.href)}});a._.register({rule:{host:/^imgdawgknuttz\.com$/},async ready(){await a._.wait(1E3);
let b=a.$.$(".button");b&&b.click();b=(0,a.$)(".centred");await a.$.openImage(b.src)}});a._.register({rule:{host:[/^(www\.)?imgdrive\.net$/,/^(www\.)?(imgtaxi|imgwallet|imgadult)\.com$/]},async ready(){let b=(0,a.$)('meta[property="og:image"]');b=b.content.replace("small","big");await a.$.openImage(b)}});a._.register({rule:{host:/^imgflip\.com$/},async ready(){const b=(0,a.$)("#im");await a.$.openImage(b.src)}});a._.register({rule:[{host:[/^imgking\.co$/,/^imgkings\.com$/],path:/^\/img*.*\.html/}],
async ready(){await a.$.openImage(a.$.window.linkid);const b=(0,a.$)("img[alt]");await a.$.openImage(b.src)}});a._.register({rule:{host:/^imgprime\.com$/},async ready(){let b=a.$.$("#continuetoimage a");b?await a.$.openLink(b.href):(b=(0,a.$)("center a img"),await a.$.openImage(b.src))}});a._.register({rule:{host:/^imgspice\.com$/},async ready(){const b=(0,a.$)("#imgpreview.pic");await a.$.openImage(b.src)}});a._.register({rule:{host:/^imgtraffic\.com$/,path:/^\/a-1\/(.+)\.jpeg\.html/},async start(){const b=
window.location.href.replace("/a-","/").replace(".html","");await a.$.openLink(b)}});a._.register({rule:{host:/^imgtraffic\.com$/,path:/^\/i-1\/(.+)\.jpeg\.html/},async start(){const b=window.location.href.replace("/i-","/").replace(".html","");await a.$.openLink(b)}});a._.register({rule:{host:/^imgtraffic\.com$/,path:/^\/n-1\/(.+)\.jpeg\.html/},async start(){const b=window.location.href.replace("/n-","/").replace(".html","");await a.$.openLink(b)}});a._.register({rule:{host:/^imgtraffic\.com$/,path:/^\/z-1\/(.+)\.jpeg\.html/},
async start(){const b=window.location.href.replace("/z-","/").replace(".html","");await a.$.openLink(b)}});a._.register({rule:"https://4fuk.me/upload/en/* https://555fap.com/upload/en/* https://ai18.pics/upload/en/* https://cnpics.org/upload/en/* https://cnxx.me/upload/en/* https://cosplay18.pics/upload/en/* https://idol69.net/upload/en/* https://javball.com/upload/en/* https://javsunday.com/upload/en/* https://kin8-av.com/upload/en/* https://ovabee.com/upload/en/* https://pig69.com/upload/en/* https://porn4f.com/upload/en/*".split(" "),
async ready(){const b=(0,a.$)('meta[property="og:image"]');await a.$.openImage(b.content)}});a._.register({rule:{host:/^keptarolo\.hu$/,path:/^(\/[^/]+\/[^/]+)$/},async start(b){await a.$.openImage("http://www.keptarolo.hu/kep"+b.path[1])}});(function(){a._.register({rule:{host:[/^miragepics\.com$/,/^foto-pic\.net$/],path:/^\/viewer\.php$/,query:/file=([^&]+)/},start:async function(b){await a.$.openImage("/images/"+b.query[1])}})})();a._.register({rule:{host:/^www\.mrjh\.org$/,path:/^\/gallery\.php$/,
query:/^\?entry=(.+)$/},async ready(b){await a.$.openImage("/"+b.query[1])}});a._.register({rule:{host:/^www\.noelshack\.com$/},async ready(){const b=(0,a.$)('meta[property="og:image"]');await a.$.openImage(b.content)}});a._.register({rule:{host:[/^dewimg\.com$/,/^outletpic\.com$/,/^pictwn\.com$/,/^picyield\.com$/,/^tezzpic\.com$/]},async ready(){const b=(0,a.$)("center > img.picview");await a.$.openImage(b.src)}});a._.register({rule:{host:/^www\.pic-upload\.de$/},async ready(){const b=(0,a.$)(".preview_picture_2b");
await a.$.openImage(b.src)}});a._.register({rule:{host:/^picstate\.com$/,path:/^\/view\/full\/.*/},async ready(){const b=(0,a.$)("#image_container a img");await a.$.openImage(b.src)}});a._.register({rule:{host:[/^picturedent\.org$/,/^everest\.picturedent\.org$/,/^pacific\.picturedent\.org$/],path:/^\/image\//},async ready(){const b=(0,a.$)("#full_img");await a.$.openImage(b.src)}});a._.register({rule:{host:/^(www\.)?pimpandhost\.com$/,path:/^\/image\/\d+/,query:/^\?size=original/},async ready(){const b=
(0,a.$)("#overflow-wrapper img.original");await a.$.openImage(b.src)}});a._.register({rule:{host:/^(www\.)?pimpandhost\.com$/,path:/^\/image\/\d+/},async start(b){await a.$.openLink(b.path+"?size=original")}});a._.register({rule:[{host:/^(www\.)?pixhost\.to$/,path:/^\/show\//},{host:[/^3xplanet\.(com|net)$/,/^javtenshi\.com$/,/^jav-load\.com$/,/^uncenav\.com$/],path:/^\/viewimage\//}],async ready(){a.$.remove("iframe, #ad");let b=a.$.$("#all");b&&(b.style.display="");b=(0,a.$)("#show_image, #image");
await a.$.openImage(b.src)}});a._.register({rule:{host:/^(www\.)?pixroute\.com$/},async ready(){const b=(0,a.$)("#download_box img#imgpreview.pic");await a.$.openImage(b.src)}});a._.register({rule:{host:[/^postimg\.cc$/,/^postlmg\.cc$/,/^pixxxels\.cc$/]},async ready(){const b=(0,a.$)("#main-image");await a.$.openImage(b.src)}});a._.register({rule:{host:[/^prnt\.sc$/],path:/\.html$/}});a._.register({rule:{host:[/^prnt\.sc$/]},async ready(){const b=(0,a.$)("#screenshot-image");await a.$.openImage(b.src)}});
a._.register({rule:{host:/^pronpic\.org$/},async ready(){var b=(0,a.$)("table.new_table2:nth-child(1) img.link").src.split("th_")[0];const t=(0,a.$)("table.new_table2:nth-child(2) img.link");b+=t.src.split("th_")[1];await a.$.openImage(b)}});a._.register({rule:{host:/^starimage\.club$/,path:/^\/image\/.+$/},async ready(){const b=(0,a.$)("input#embed-code-2.text-input").getAttribute("value");await a.$.openImage(b)}});a._.register({rule:{host:/^thotimg\.xyz$/},async ready(){const b=(0,a.$)("center > img");
await a.$.openImage(b.src)}});a._.register({rule:[{host:[/^img\.trafficimage\.club$/,/^trafficimage\.club$/],path:/^\/image\//},{host:/^im\.ge$/,path:/^\/i\//}],async ready(){const b=(0,a.$)('meta[property="og:image"]');await a.$.openImage(b.content)}});a._.register({rule:{host:/^www\.turboimagehost\.com$/,path:/^\/p\//},async ready(){const b=(0,a.$)("#imageid");await a.$.openImage(b.src)}});a._.register({rule:{host:/^xxxwebdlxxx\.(org|top)$/},async ready(){const b=(0,a.$)(".centred, .centred_resized");
await a.$.openImage(b.src)}})},(r,p,m)=>{function a(q,n){return(0,u.querySelector)(q,n)}m.r(p);m.d(p,{$:()=>a,_:()=>k});r=m(8);p=m(9);var b=m(1),t=m(2),u=m(10),w=m(11),h=m(12),f=m(5),g=m(13);m=m(3);const k={AdsBypasserError:b.AdsBypasserError,evil:g.evil,find:b.find,forEach:b.forEach,generateRandomIP:g.generateRandomIP,info:f.info,none:b.none,partial:b.partial,register:t.register,tryEvery:b.tryEvery,wait:b.wait,warn:f.warn};a.$=u.querySelectorOrNull;a.$$=u.querySelectorAll;a.block=u.block;a.get=r.get;
a.getCookie=p.getCookie;a.nuke=g.nuke;a.openImage=w.openImage;a.openLink=h.openLink;a.post=r.post;a.remove=u.remove;a.removeAllTimer=g.removeAllTimer;a.resetCookies=p.resetCookies;a.searchFromScripts=u.searchFromScripts;a.setCookie=p.setCookie;a.toDOM=u.toDOM;a.window=m.usw},(r,p,m)=>{function*a(e){if(e)for(const [c,d]of Object.entries(e))if(Array.isArray(d))for(const l of d)yield[[c,""],l];else if("object"===typeof d)for(const [l,v]of a(d))yield[[c,...l],v];else yield[[c],d]}function b(e){const [c,
...d]=e;return`${c}${d.map(l=>`[${l}]`)}`}function t(e,c){const d=Object.getOwnPropertyNames(c);return(0,k.map)(d,l=>{const v=c[l];l=`${e}[${l}]`;return"object"===typeof v?t(l,v):[l,v].map(encodeURIComponent).join("=")}).join("&")}function u(e){var c=typeof e;if(null===e||"string"!==c&&"object"!==c)return"";if("string"===c)return e;if(e instanceof String)return e.toString();c=Object.getOwnPropertyNames(e);return(0,k.map)(c,d=>{const l=e[d];return"object"===typeof l?t(d,l):[d,l].map(encodeURIComponent).join("=")}).join("&")}
function w(e){var c=typeof e;if(null===e||"string"!==c&&"object"!==c)return"";if("string"===c)return e;if(e instanceof String)return e.toString();c=new FormData;for(const [d,l]of a(e))c.append(b(d),l);return c}function h(e,c,d,l){(0,n.debug)("ajax",e,c,d,l);const v=document.createElement("a");v.href=c;(0,k.forEach)({Host:v.hostname||window.location.host,Origin:window.location.origin,Referer:window.location.href,"X-Requested-With":"XMLHttpRequest"},(y,C)=>{l[C]===k.none?delete l[C]:l[C]=y});d&&(d=
0<=l["Content-Type"].indexOf("json")?JSON.stringify(d):0<=l["Content-Type"].indexOf("multipart")?w(d):u(d),l["Content-Length"]=d.length);return new Promise((y,C)=>{q.GMAPI.xmlHttpRequest({method:e,url:c,data:d,headers:l,onload(A){A="undefined"!==typeof A.responseText?A:this;200!==A.status?C(new x(e,c,d,l,A.status,A.responseText)):y(A.responseText)},onerror(A){A="undefined"!==typeof A.responseText?A:this;C(new x(e,c,d,l,A.status,A.responseText))}})})}function f(e,c,d){c=u(c);d=d||{};return h("GET",
e+(c?"?"+c:""),"",d)}function g(e,c,d){const l={"Content-Type":"application/x-www-form-urlencoded; charset=UTF-8"};d&&(0,k.forEach)(d,(v,y)=>{l[y]=v});return h("POST",e,c,l)}m.r(p);m.d(p,{get:()=>f,post:()=>g});var k=m(1),q=m(3),n=m(5);class x extends k.AdsBypasserError{constructor(e,c,d,l,v,y){super(`${e} ${c} got ${v}`);this._method=e;this._url=c;this._data=d;this._headers=l;this._status=v;this._response=y}get name(){return"AjaxError"}get method(){return this._method}get url(){return this._url}get data(){return this._data}get headers(){return this._headers}get status(){return this._status}get response(){return this._response}}
},(r,p,m)=>{function a(w,h){document.cookie=`${w}=${h};path=${location.pathname};`}function b(w){let [,h]=(0,u.find)(document.cookie.split(";"),f=>{if(f.replace(/^\s*([a-zA-Z0-9-_]+)=.+$/,"$1")!==w)return u.none});return h===u.none?null:(h=h.replace(/^\s*[a-zA-Z0-9-_]+=([^;]+).?$/,"$1"))?h:null}function t(){const w=document.domain,h=document.domain.replace(/^www\./,""),f=document.domain.replace(/^(\w+\.)+?(\w+\.\w+)$/,"$2"),g=(new Date(1E3)).toUTCString();(0,u.forEach)(document.cookie.split(";"),
k=>{k=k.replace(/^\s*(\w+)=.+$/,"$1");document.cookie=`${k}=;expires=${g};`;document.cookie=`${k}=;path=/;expires=${g};`;document.cookie=`${k}=;path=/;domain=${w};expires=${g};`;document.cookie=`${k}=;path=/;domain=${h};expires=${g};`;document.cookie=`${k}=;path=/;domain=${f};expires=${g};`})}m.r(p);m.d(p,{getCookie:()=>b,resetCookies:()=>t,setCookie:()=>a});var u=m(1)},(r,p,m)=>{function a(e,c){c&&c.querySelector||(c=document);c=c.querySelector(e);if(!c)throw new x(e);return c}function b(e,c){try{return a(e,
c)}catch(d){return null}}function t(e,c){c&&c.querySelectorAll||(c=document);return c.querySelectorAll(e)}function u(e){try{return(new DOMParser).parseFromString(e,"text/html")}catch(c){throw new q.AdsBypasserError("could not parse HTML to DOM");}}function w(e,c){e=t(e,c);(0,q.forEach)(e,d=>{(0,n.debug)("removed",d);d.remove()})}function h(e,c=null){c||=document;let d=null;if((0,q.isString)(e))d=()=>{w(e,c)};else if("function"===typeof e)d=l=>{l.addedNodes.forEach(v=>{e(v)&&v.parentNode.removeChild(v)})};
else throw new TypeError("wrong selector");(new MutationObserver(l=>{l.forEach(v=>{d(v)})})).observe(c,{childList:!0,subtree:!0})}function f(e,c){c=t("script",c);[,,c]=(0,q.find)(c,d=>(d=d.textContent.match(e))?d:q.none);return c===q.none?null:c}function g(e,c){c=t("script",c);[,c]=(0,q.find)(c,d=>{d=d.textContent.indexOf(e);return 0>d?q.none:d});return c===q.none?null:c.textContent}function k(e,c){return e instanceof RegExp?f(e,c):(0,q.isString)(e)?g(e,c):null}m.r(p);m.d(p,{block:()=>h,querySelector:()=>
a,querySelectorAll:()=>t,querySelectorOrNull:()=>b,remove:()=>w,searchFromScripts:()=>k,toDOM:()=>u});var q=m(1),n=m(5);class x extends q.AdsBypasserError{constructor(e){super(`\`${e}\` not found`)}get name(){return"DomNotFoundError"}}},(r,p,m)=>{async function a(c,d){d=d||{};const l=!!d.referer;d.replace?await g(c):await e.GMAPI.getValue("redirect_image")&&await (0,k.openLink)(c,{referer:l})}function b(){this.classList.toggle("adsbypasser-shrinked")}function t(){const c=this.naturalWidth,d=this.naturalHeight,
l=document.documentElement.clientWidth,v=document.documentElement.clientHeight;(c>l||d>v)&&!this.classList.contains("adsbypasser-resizable")?(this.classList.add("adsbypasser-resizable"),this.classList.add("adsbypasser-shrinked"),this.addEventListener("click",b)):c<=l&&d<=v&&this.classList.contains("adsbypasser-resizable")&&(this.removeEventListener("click",b),this.classList.remove("adsbypasser-shrinked"),this.classList.remove("adsbypasser-resizable"))}async function u(c){const d=await e.GMAPI.getResourceUrl("scaleImage");
f(d);c.naturalWidth&&c.naturalHeight?t.call(c):c.addEventListener("load",t);let l=0;window.addEventListener("resize",()=>{window.clearTimeout(l);l=window.setTimeout(t.bind(c),100)})}async function w(){const c=await e.GMAPI.getResourceUrl("bgImage");document.body.style.backgroundColor="#222222";document.body.style.backgroundImage=`url('${c}')`}async function h(){const c=await e.GMAPI.getResourceUrl("alignCenter");f(c)}function f(c){const d=document.createElement("link");d.rel="stylesheet";d.type="text/css";
d.href=c;document.head.appendChild(d)}async function g(c){if(await e.GMAPI.getValue("redirect_image"))if(c){(0,n.info)(`replacing body with \`${c}\` ...`);(0,x.removeAllTimer)();("CSS1Compat"===document.compatMode?document.documentElement:document.body).style.overflow="";document.body=document.createElement("body");var d=document.createElement("div");document.body.appendChild(d);var l=document.createElement("img");l.src=c;d.appendChild(l);c=await e.GMAPI.getValue("align_center");var v=await e.GMAPI.getValue("scale_image");
if(c||v)(0,q.remove)("style, link[rel=stylesheet]"),d.id="adsbypasser-wrapper",l.id="adsbypasser-image";c&&await h();await e.GMAPI.getValue("change_background")&&await w();v&&await u(l)}else(0,n.warn)("false url")}m.r(p);m.d(p,{openImage:()=>a});var k=m(12),q=m(10),n=m(5),x=m(13),e=m(3)},(r,p,m)=>{function a(f){document.body||(document.body=document.createElement("body"));document.body.appendChild(f);return(0,w.wait)(0)}async function b(f){const g=document.createElement("a");g.href=f;let k=!1;g.addEventListener("click",
n=>{n.stopPropagation();k=!0},!0);await a(g);g.click();const q=setInterval(()=>{k?((0,h.info)("already clicked"),clearInterval(q)):((0,h.info)("try again"),g.click())},500)}async function t(f,g){g=g||{};const k=document.createElement("form");k.method="post";k.action=f;(0,w.forEach)(g,(q,n)=>{const x=document.createElement("input");x.type="hidden";x.name=n;x.value=q;k.appendChild(x)});await a(k);k.submit()}async function u(f,g){if((0,w.isString)(f)||f){g=g||{};var k="undefined"===typeof g.referer?
!0:g.referer;g=g.post;(0,h.info)(`${window.location.toString()} -> ${f}`);g?await t(f,g):k?await b(f):window.top.location.replace(f)}else(0,h.warn)("false URL")}m.r(p);m.d(p,{openLink:()=>u});var w=m(1),h=m(5)},(r,p,m)=>{function a(){let g=window.setInterval(w.nop,10);for(;0<g;)window.clearInterval(g--);for(g=window.setTimeout(w.nop,10);0<g;)window.clearTimeout(g--)}function b(g){try{h.usw.document.write("nuked by AdsBypasser, leading to ...<br/>")}catch(q){(0,f.warn)("nuke failed",q)}const k=document.createElement("a");
k.href=g;k.textContent=g;document.body.appendChild(k)}function t(){return[0,0,0,0].map(()=>Math.floor(256*Math.random())).join(".")}function u(g){return((k,q,n,x,e,c,d,l,v,y)=>eval(g))()}m.r(p);m.d(p,{evil:()=>u,generateRandomIP:()=>t,nuke:()=>b,removeAllTimer:()=>a});var w=m(1),h=m(3),f=m(5)}],E={};(()=>{z.d=(r,p)=>{for(var m in p)z.o(p,m)&&!z.o(r,m)&&Object.defineProperty(r,m,{enumerable:!0,get:p[m]})}})();(()=>{z.o=(r,p)=>Object.prototype.hasOwnProperty.call(r,p)})();(()=>{z.r=r=>{"undefined"!==
typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(r,Symbol.toStringTag,{value:"Module"});Object.defineProperty(r,"__esModule",{value:!0})}})();z.r({});var F=z(1),O=z(2),B=z(3),H=z(4),D=z(5);z(6);const K=0<Object.prototype.toString.call(window.HTMLElement).indexOf("Constructor");(async function(){if(B.rawUSW.top===B.rawUSW.self){B.GMAPI.registerMenuCommand("AdsBypasser - Configure",()=>{B.GMAPI.openInTab("https://adsbypasser.github.io/configure.html")});await (0,H.loadConfig)();var r=(0,O.findHandler)();
r&&(await L(r),await N(),await M(r))}})().catch(r=>{(0,D.warn)(r)})})();
