// ==UserScript==
// @name           AdsBypasser Lite
// @namespace      AdsBypasser
// @copyright      2012+, Wei-Cheng Pan, https://adsbypasser.github.io/
// @version        7.29.0
// @license        BSD
// @homepageURL    https://adsbypasser.github.io/
// @supportURL     https://github.com/adsbypasser/adsbypasser/issues
// @updateURL https://raw.githubusercontent.com/siritami/test1/release/release/adsbypasser.lite.es7.meta.js
// @downloadURL https://raw.githubusercontent.com/siritami/test1/release/release/adsbypasser.lite.es7.user.js
// @icon           https://raw.githubusercontent.com/adsbypasser/adsbypasser/v7.29.0/resources/img/logo.png
// @grant          GM_deleteValue
// @grant          GM_getValue
// @grant          GM_info
// @grant          GM_openInTab
// @grant          GM_registerMenuCommand
// @grant          GM_setValue
// @grant          GM_xmlhttpRequest
// @grant          GM.deleteValue
// @grant          GM.getValue
// @grant          GM.info
// @grant          GM.openInTab
// @grant          GM.setValue
// @grant          GM.xmlHttpRequest
// @grant          unsafeWindow
// @noframes
// @run-at         document-start
// @include        http://*
// @include        https://*
// @connect        *
// ==/UserScript==
(()=>{function z(q){var p=E[q];if(void 0!==p)return p.exports;p=E[q]={exports:{}};I[q](p,p.exports,z);return p.exports}function J(){try{B.usw.open=function(){return{closed:!1}}}catch(q){(0,D.warn)("cannot mock window.open")}B.usw.alert=F.nop;B.usw.confirm=F.nop}function G(q){if(q){var p=function(){(0,D.info)("blocked onbeforeunload")};q.onbeforeunload=void 0;K?q.__defineSetter__("onbeforeunload",p):B.usw.Object.defineProperty(q,"onbeforeunload",{configurable:!0,enumerable:!1,get:void 0,set:p});var m=
q.addEventListener;q.addEventListener=function(a){if("beforeunload"===a)(0,D.info)("blocked addEventListener onbeforeunload");else return m.apply(this,arguments)}}}async function L(q){const p=await (0,H.dumpConfig)();(0,D.info)("working on\n%s \nwith\n%s",window.location.toString(),JSON.stringify(p));G(B.usw);J();await q.start()}async function M(q){G(B.usw.document.body);document.title+=" - AdsBypasser";await q.ready()}function N(){return new Promise(q=>{"loading"!==document.readyState?q():document.addEventListener("DOMContentLoaded",
()=>{q()})})}var I=[,(q,p,m)=>{function a(c,g){return f(c)?Array.prototype.forEach.call(c,g):Object.keys(c).forEach(n=>g(c[n],n,c))}function b(c,g){return f(c)?Array.prototype.every.call(c,g):Object.keys(c).every(n=>g(c[n],n,c))}function v(c,g){if(f(c))return Array.prototype.map.call(c,g);const n=Object.assign({},c);Object.getOwnPropertyNames(n).forEach(w=>{n[w]=g(c[w],w,c)});return n}function t(c,g){for(const [n,w]of u(c)){const y=g(w,n,c);if(y!==e)return[n,w,y]}return[e,e,e]}function*u(c){if(f(c))yield*Array.prototype.entries.call(c);
else{var g=Object.getOwnPropertyNames(c);for(const n of g)yield[n,c[n]]}}function f(c){return Array.isArray(c)||"NodeList"===c.constructor.name}function d(c,...g){if("function"!==typeof c)throw new x("must give a function");return(...n)=>c(...g.concat(n))}function h(c){return"string"===typeof c||c instanceof String}function k(){}function r(c){return new Promise(g=>{setTimeout(g,c)})}function l(c,g){return new Promise(n=>{const w=setInterval(function(){const y=g();y!==e&&(clearInterval(w),n(y))},c)})}
m.r(p);m.d(p,{AdsBypasserError:()=>x,every:()=>b,find:()=>t,forEach:()=>a,isString:()=>h,map:()=>v,none:()=>e,nop:()=>k,partial:()=>d,tryEvery:()=>l,wait:()=>r});class x extends Error{constructor(c){super(c)}get name(){return"AdsBypasserError"}}const e=k},(q,p,m)=>{function a(k){h.push(k)}function b(k,r){k=(0,d.map)(k,(l,x)=>{if(l instanceof RegExp)return r[x].match(l);if(Array.isArray(l))return[,,l]=(0,d.find)(l,e=>r[x].match(e)||d.none),l!==d.none?l:null;throw new d.AdsBypasserError("invalid rule");
});return(0,d.every)(k,l=>!!l)?k:null}function v(k,r,l,x){[,,k]=(0,d.find)(k,e=>(e=u(e,r,l,x))?e:d.none);return k!==d.none?k:null}function t(k,r){var l=/\*|https?|file|ftp|chrome-extension/;let x=/\*|(\*\.)?([^/*]+)/;var e=/\/.*/;l=`^(${l.source})://(${x.source})?(${e.source})$`;l=new RegExp(l);e=k.match(l);if(!e)return null;l=e[1];x=e[2];const c=e[3];k=e[4];e=e[5];if("*"===l&&!/https?/.test(r.scheme)||l!==r.scheme)return null;if("file"!==l&&"*"!==x)if(c){if(l=r.host.indexOf(k),0>l||l+k.length!==
r.host.length)return null}else if(x!==r.host)return null;l=e.replace(/[*.[\]?+#]/g,g=>"*"===g?".*":"\\"+g);e=new RegExp(`^${l}$`);return e.test(r.path)?r:null}function u(k,r,l,x){return Array.isArray(k)?v(k,r,l,x):"function"===typeof k?k(r,l,x):k instanceof RegExp?r.match(k):(0,d.isString)(k)?t(k,l):b(k,x)}function f(){const k=window.location.toString(),r={scheme:window.location.protocol.slice(0,-1),host:window.location.host,path:window.location.pathname+window.location.search+window.location.hash},
l={scheme:window.location.protocol,host:window.location.hostname,port:window.location.port,path:window.location.pathname,query:window.location.search,hash:window.location.hash},[x,e,c]=(0,d.find)(h,g=>(g=u(g.rule,k,r,l))?g:d.none);return x===d.none||!e.start&&!e.ready?null:{start:e.start?(0,d.partial)(e.start,c):d.nop,ready:e.ready?(0,d.partial)(e.ready,c):d.nop}}m.r(p);m.d(p,{findHandler:()=>f,register:()=>a});var d=m(1);const h=[]},(q,p,m)=>{function a(f){if(null===f||!(f instanceof Object)||f===
unsafeWindow)return f;if(f instanceof String)return f.toString();if(f instanceof Function)return exportFunction(f,unsafeWindow,{allowCrossOriginArguments:!0});if(f instanceof Array){const h=new unsafeWindow.Array;for(let k=0;k<f.length;++k)h.push(a(f[k]));return h}const d=new unsafeWindow.Object;(0,b.forEach)(f,(h,k)=>{d[k]=a(h)});return d}m.r(p);m.d(p,{GMAPI:()=>u,rawUSW:()=>v,usw:()=>t});var b=m(1);const v=function(){let f=null;try{f=unsafeWindow}catch(d){try{f=(0,eval)("this").global}catch(h){}}return f?
f:(0,eval)("this").window}(),t=function(){if("Greasemonkey"!==("object"===typeof GM_info&&GM_info?GM_info:"object"===typeof GM&&GM&&GM.info?GM.info:{}).scriptHandler)return v;const f={set(d,h,k){if("__adsbypasser_reverse_proxy__"===h)return!1;d[h]=a(k);return!0},get(d,h){if("__adsbypasser_reverse_proxy__"===h)return d;d=d[h];h=typeof d;return null===d||"function"!==h&&"object"!==h?d:new Proxy(d,f)},apply(d,h,k){k=Array.prototype.slice.call(k);d===unsafeWindow.Object.defineProperty&&(k[0]=k[0].__adsbypasser_reverse_proxy__);
d===unsafeWindow.Function.apply&&(h=h.__adsbypasser_reverse_proxy__,k[1]=Array.prototype.slice.call(k[1]));d===unsafeWindow.document.querySelector&&(h=h.__adsbypasser_reverse_proxy__);d===unsafeWindow.document.write&&(h=h.__adsbypasser_reverse_proxy__);k=a(k);return d.apply(h,k)},construct(d,h){h=Array.prototype.slice.call(h);h.unshift(void 0);h=a(h);return new (unsafeWindow.Function.prototype.bind.apply(d,h))}};return new Proxy(unsafeWindow,f)}(),u=function(){if(v.global)return null;const f={};f.openInTab=
"function"===typeof GM_openInTab?GM_openInTab:GM.openInTab;f.getValue="function"===typeof GM_getValue?(d,h)=>Promise.resolve(GM_getValue(d,h)):GM.getValue;f.setValue="function"===typeof GM_setValue?(d,h)=>Promise.resolve(GM_setValue(d,h)):GM.setValue;f.deleteValue="function"===typeof GM_deleteValue?d=>Promise.resolve(GM_deleteValue(d)):GM.deleteValue;f.xmlHttpRequest="function"===typeof GM_xmlhttpRequest?GM_xmlhttpRequest:GM.xmlHttpRequest;f.registerMenuCommand="function"===typeof GM_registerMenuCommand?
GM_registerMenuCommand:b.nop;"function"===typeof GM_getResourceURL?f.getResourceUrl=d=>Promise.resolve(GM_getResourceURL(d)):"object"===typeof GM&&GM&&GM.getResourceUrl&&(f.getResourceUrl=GM.getResourceUrl);return f}()},(q,p,m)=>{function a(c){return"boolean"===typeof c}function b(c){return!!c}function v(c){return parseInt(c,10)}async function t(){let c=x.map(async g=>{const n=await l.GMAPI.getValue(g.key);return g.verify(n)});c=await Promise.all(c);(0,k.every)(c,g=>g)||await l.GMAPI.setValue("version",
0)}async function u(){let c=await l.GMAPI.getValue("version");if(0!==c&&!c)throw new k.AdsBypasserError("invalid version");for(;c<e.length;)e[c](),++c;await l.GMAPI.setValue("version",c)}async function f(){await t();await u();(0,r.register)({rule:{host:/^adsbypasser\.github\.io$/,path:/^\/configure\.html$/},async ready(){await d();l.usw.commit=async c=>{for(const [g,n]of Object.entries(c))await l.GMAPI.setValue(g,n)};l.usw.render({version:await l.GMAPI.getValue("version"),options:{align_center:{type:"checkbox",
value:await l.GMAPI.getValue("align_center"),label:"Align Center",help:"Align image to the center if possible. (default: enabled)"},change_background:{type:"checkbox",value:await l.GMAPI.getValue("change_background"),label:"Change Background",help:"Use Firefox-like image background if possible. (default: enabled)"},redirect_image:{type:"checkbox",value:await l.GMAPI.getValue("redirect_image"),label:"Redirect Image",help:"Directly open image link if possible. (default: enabled)<br/>\nIf disabled, redirection will only works on link shortener sites."},
scale_image:{type:"checkbox",value:await l.GMAPI.getValue("scale_image"),label:"Scale Image",help:"When image loaded, scale it to fit window if possible. (default: enabled)"},log_level:{type:"select",value:await l.GMAPI.getValue("log_level"),menu:[[0,"0 (quiet)"],[1,"1 (default)"],[2,"2 (verbose)"]],label:"Log Level",help:"Log level in developer console. (default: 1)<br/>\n0 will not print anything in console.<br/>\n1 will only print logs on affected sites.<br/>\n2 will print on any sites."}}})}})}
function d(){return new Promise(c=>{const g=setInterval(()=>{l.usw.render&&(clearInterval(g),c())},50)})}async function h(){let c=x.map(async n=>[n.key,await l.GMAPI.getValue(n.key)]);c=await Promise.all(c);const g={};for(const [n,w]of c)g[n]=w;return g}m.r(p);m.d(p,{dumpConfig:()=>h,loadConfig:()=>f});var k=m(1),r=m(2),l=m(3);const x=[{key:"version",default_:0,verify(c){return"number"===typeof c&&0<=c},normalize:v},{key:"align_center",default_:!0,verify:a,normalize:b},{key:"change_background",default_:!0,
verify:a,normalize:b},{key:"redirect_image",default_:!0,verify:a,normalize:b},{key:"scale_image",default_:!0,verify:a,normalize:b},{key:"log_level",default_:1,verify(c){return"number"===typeof c&&0<=c&&2>=c},normalize:v}],e=[async()=>{const c=await l.GMAPI.getValue("align_center"),g=await l.GMAPI.getValue("change_background"),n=await l.GMAPI.getValue("scale_image"),w=await l.GMAPI.getValue("redirect_image"),y="boolean"===typeof c;"boolean"!==typeof g&&await l.GMAPI.setValue("change_background",y?
c:!0);"boolean"!==typeof n&&await l.GMAPI.setValue("scale_image",y?c:!0);y||await l.GMAPI.setValue("align_center",!0);"boolean"!==typeof w&&await l.GMAPI.setValue("redirect_image",!0)},async()=>{"boolean"!==typeof await l.GMAPI.getValue("external_server_support")&&await l.GMAPI.setValue("external_server_support",!1)},async()=>{"number"!==typeof await l.GMAPI.getValue("log_level")&&await l.GMAPI.setValue("log_level",1)},async()=>{await l.GMAPI.deleteValue("external_server_support")}]},(q,p,m)=>{function a(f,
d){d=Array.prototype.slice.call(d);(0,u.isString)(d[0])?d[0]="AdsBypasser: "+d[0]:d.unshift("AdsBypasser:");f=console[f];"function"===typeof f&&f.apply(console,d)}function b(){a("debug",arguments)}function v(){a("info",arguments)}function t(){a("warn",arguments)}m.r(p);m.d(p,{debug:()=>b,info:()=>v,warn:()=>t});var u=m(1)},(q,p,m)=>{m.r(p);var a=m(7);a._.register({rule:{host:/^ak\.sv$/},async ready(){await a._.wait(1E3);(0,a.$)("html").click();await a._.wait(6E3);const b=(0,a.$)('a[class="download_button"]');
await a.$.openLink(b)}});a._.register({rule:{host:/^(www\.)?apunkasoftware\.net$/},async ready(){const b=(0,a.$)("div#proceed-now > a#dlink");await a.$.openLink(b.href)}});a._.register({rule:{host:/^thefileslocker\.net$/},async ready(){(0,a.$)("#downloadbtn").click()}});a._.register({rule:{host:[/^(www\.)?indishare\.org$/,/^uploadrar\.com$/]},async ready(){const b=(0,a.$)("button#downloadbtn.downloadbtn");b.removeAttribute("disabled");b.click()}});a._.register({rule:{host:/^infidrive\.net$/},async ready(){await a._.wait(4E4);
(0,a.$)("button.inline-flex:nth-child(2)").click()}});a._.register({rule:{host:/^k2s\.cc$/},async ready(){await a._.wait(35E3);const b=(0,a.$)("a.link-to-file");await a.$.openLink(b.href)}});a._.register({rule:{host:/^katfile\.com$/},async ready(){const b=(0,a.$)('a[id="dlink"]');await a.$.openLink(b.href)}});a._.register({rule:{host:/^(www\.)?keeplinks\.org$/},async ready(){(0,a.$)('[id="btnproceedsubmit"]').click()}});a._.register({rule:"https://www.mirrored.to/files/*",async ready(){const b=(0,a.$)(".col-sm.centered.extra-top a");
await a.$.openLink(b.href)}});a._.register({rule:{host:/^multiup\.io$/},async ready(){(0,a.$)(".btn-info.btn-lg.btn-block").click()}});a._.register({rule:{host:/^www\.onlinefreecourse\.net$/},async ready(){const b=(0,a.$)('a[class="btn btn-success"]');await a.$.openLink(b)}});a._.register({rule:{host:/^sfile\.mobi$/},async ready(){await a._.wait(8E3);(0,a.$)("#download").click()}});a._.register({rule:{host:/^uploadhaven\.com$/,path:/^\/download\//},async ready(){await a._.wait(18E3);(0,a.$)(".btn-submit-free.btn-download-free").click()}});
a._.register({rule:{host:/^usersdrive\.com$/},async ready(){const b=(0,a.$)(".btn-download");await a.$.openLink(b.href)}});a._.register({rule:{host:/^1ink\.cc$/},async ready(){const b=(0,a.$)("#countingbtn");await a.$.openLink(b.href)}});a._.register({rule:{host:/^1link\.club$/},async ready(){const b=(0,a.$)("#download.btn");await a.$.openLink(b.href)}});a._.register({rule:{host:/^1v\.to$/,path:/^\/t\/[a-zA-Z0-9/=]+/},async start(){const b=window.location.href.replace("/t/","/saliendo/");await a.$.openLink(b)}});
a._.register({rule:{host:/^a2zapk\.io$/},async ready(){const b=(0,a.$)("#dlbtn li a");await a.$.openLink(b.href)}});a._.register({rule:{host:/^adfoc\.us$/},async ready(){const b=(0,a.$)(".skip");await a.$.openLink(b.href)}});a._.register({rule:{host:/^adshnk\.com$/},async ready(){await a._.wait(16E3);(0,a.$)('button[class="ui right labeled icon button primary huge fluid"]').click();await a._.wait(18E3);const b=(0,a.$)('a[id="final_redirect"]');await a.$.openLink(b.href)}});a._.register({rule:{host:/^www\.adz7short\.space$/},
async ready(){const b=(0,a.$)("#continue");await a._.wait(1E4);b.click()}});a._.register({rule:{host:/^bcvc\.ink$/},async ready(){await a._.wait(5E3);(0,a.$)("#getLink").click()}});a._.register({rule:{host:/^(www\.)?biglistofwebsites\.com$/,path:/^\/go\/(\w+\.\w+)$/},async start(b){await a.$.openLink("http://"+b.path[1])}});a._.register({rule:[{host:/^(www\.)?([a-zA-Z0-9]+\.)?binbox\.io$/,path:/\/o\/([a-zA-Z0-9]+)/}],async start(b){b=window.atob(b.path[1]);await a.$.openLink(b)}});a._.register({rule:{host:/^bioskopkeren\.boo$/},
async ready(){await a._.wait(1E3);(0,a.$)(".reklamgec").click()}});a._.register({rule:{host:/^boost\.ink$/},async start(){const b=(0,a.$)("body").getAttribute("result");b&&await a.$.openLink(atob(b))}});a._.register({rule:{host:/^cocoleech\.com$/},async ready(){const b=(0,a.$)(".btn.btn-block.btn-success");await a.$.openLink(b.href)}});a._.register({rule:{host:/^cpmlink\.net$/},async ready(){const b=(0,a.$)("#btn-main");await a.$.openLink(b.href)}});a._.register({rule:{host:/^ctr\.sh$/},async ready(){await a._.wait(12E3);
(0,a.$)(".btn.btn-primary.btn-captcha").click()}});a._.register({rule:{host:/^cutpaid\.com$/},async ready(){let b=(0,a.$)(".btn-primary");b&&(await a._.wait(2E4),b.click());b=(0,a.$)(".btn-success.btn-lg.get-link");await a._.wait(9E3);await a.$.openLink(b.href)}});a._.register({rule:{host:/^www\.dlink3\.com$/},async ready(){await a._.wait(12E3);const b=(0,a.$)('[class="myButton"]');await a.$.openLink(b.href)}});a._.register({rule:{host:/^dlupload\.com$/},async ready(){await a._.wait(3500);(0,a.$)(".btn-block.btn-primary.text-white.shadow.m-1.position-relative.up-tooltip-container").click();
await a._.wait(6E3);(0,a.$)(".btn-block.continue-btn-bg").click()}});a._.register({rule:{host:/^earnlink\.io$/},async ready(){const b=a.$.searchFromScripts(/"([^"]+)"\)\.html\("Continue"\)/);await a.$.openLink(b[1])}});a._.register({rule:{host:/^forex-trnd\.com$/},async ready(){await a._.wait(1E4);(0,a.$)(".get-link").click()}});a._.register({rule:{host:/^exeo\.app$/},async ready(){(0,a.$)(".link-button.button").click();await a._.wait(2E3);(0,a.$)(".link-button").click();await a._.wait(6E3);(0,a.$)(".link-button.get-link").click()}});
a._.register({rule:{host:/^fc-lc\.(com|xyz)$/},async ready(){await a._.wait(2E3);(0,a.$)(".btn-primary.btn-captcha.mb-4").click()}});a._.register({rule:{host:/^loaninsurehub\.com$/},async ready(){var b=(0,a.$)("#glink");b&&b.click();await a._.wait(12E3);a.$.remove("#overlay");(b=(0,a.$)("#surl"))&&b.click()}});a._.register({rule:{host:/^fir3\.net$/},async ready(){await a._.wait(12E3);(0,a.$)(".btn.btn-success.btn-lg.get-link").click()}});a._.register({rule:{host:/^get-click2\.blogspot\.com$/},async ready(){const b=
(0,a.$)("button#gotolink");b.removeAttribute("disabled");await a._.wait(1);b.click()}});a._.register({rule:{host:/^getthot\.com$/},async ready(){await a._.wait(12E3);const b=(0,a.$)(".skip-btn");await a.$.openLink(b.href)}});a._.register({rule:{host:/^gplinks\.co$/},async ready(){await a._.wait(8E3);(0,a.$)(".get-link").click()}});a._.register({rule:{host:/^hen-tay\.net$/,path:/^\/go\//},async ready(){const b=(0,a.$)("#download_url div a");await a.$.openLink(b.href)}});a._.register({rule:{host:/^hotshorturl\.com$/},
async ready(){const b=(0,a.$)("frame[scrolling=yes]");await a.$.openLink(b.src)}});a._.register({rule:{host:/^icutlink\.com$/},async ready(){await a._.wait(1E4);const b=(0,a.$)(".btn-success.btn-lg.get-link");await a.$.openLink(b)}});a._.register({rule:{host:/^zegtrends\.com$/},async ready(){await a._.wait(12E3);(0,a.$)("div > button.bsub").click()}});a._.register({rule:{host:/^imagetwist\.netlify\.app$/},async ready(){const b=(0,a.$)(".btn.btn-dark");await a.$.openLink(b.href)}});a._.register({rule:{host:/^www\.javlibrary\.com$/,
query:/url=([^&]+)/},async start(b){await a.$.openLink(decodeURIComponent(b.query[1]))}});a._.register({rule:{host:/^kimochi\.info$/,path:/^\/inter$/},async ready(){const b=(0,a.$)("a#next");await a.$.openLink(b.href)}});a._.register({rule:{host:/^(www\.)?kingofshrink\.com$/},async ready(){const b=(0,a.$)("#textresult > a");await a.$.openLink(b.href)}});a._.register({rule:{host:/^linegee\.net$/},async ready(){(0,a.$)("p.kecil a").click()}});a._.register({rule:{host:/^link\.turkdown\.com$/},async ready(){await a._.wait(5E3);
const b=(0,a.$)(".btn-success.btn-lg.get-link");await a.$.openLink(b.href)}});a._.register({rule:{host:/^link1s\.com$/},async ready(){await a._.wait(1E4);(0,a.$)(".btn.btn-success.btn-lg.get-link").click()}});(function(){async function b(f){let d=a.$.window.$;for(;!d;)await a._.wait(50),d=a.$.window.$;f=d(f);return 0<f.length?f:null}function v(f){return new Promise((d,h)=>{f.is("a")&&f.attr("href")&&d(f.attr("href"));a.$.window.$.ajax({dataType:"json",type:"POST",url:f.attr("action"),data:f.serialize(),
success:k=>{k.url?d(k.url):h(new a._.AdsBypasserError(k.message))},error:(k,r,l)=>{a._.warn(k,r,l);h(new a._.AdsBypasserError("request error"))}})})}a._.register({rule:{host:[/^adsafelink\.com$/,/^birdurls\.com$/,/^dz4link\.com$/,/^(linkmoni|shrinkcash)\.com$/,/^shrt10\.com$/,/^tmearn\.net$/,/^vinaurl\.net$/,/^payskip\.org$/,/^clik\.pw$/,/^miniurl\.pw$/,/^aylink\.co$/,/^(clk|oko)\.sh$/,/^cpmlink\.pro$/,/^gitlink\.pro$/,/^megalink\.pro$/,/^met\.bz/,/^mitly\.us$/,/^oke\.io$/,/^pahe\.plus$/,/^pingit\.im$/,
/^thotpacks\.xyz$/]},async ready(){await (new u).call()}});class t{constructor(){this._overlaySelector='[class$="Overlay"], #__random_class_name__, #headlineatas, #myModal, .opacity_wrapper, #overlay';this._formSelector='#go-link, .go-link, #originalLink.get-link, form[action="/links/go"]'}removeOverlay(){a.$.remove(this._overlaySelector);a.$.block(this._overlaySelector,document.body);setInterval(()=>{document.body.style.overflow="initial"},500)}removeFrame(){a.$.remove("iframe")}async call(){if(await this.prepare()){var f=
await this.getMiddleware();f?(f=await this.getURL(f),await a.$.openLink(f)):this.withoutMiddleware()}}}class u extends t{async prepare(){this.removeOverlay();if(!a.$.$("#captchaShortlink, div.g-recaptcha"))return!0;a._.info("recaptcha detected, stop");a._.info("trying to listen submit button");if(!a.$.$("#invisibleCaptchaShortlink"))return!1}async submitListen(f){(new MutationObserver(()=>{f.disabled||f.click()})).observe(f,{attributes:!0})}async getMiddleware(){return await b(this._formSelector)}withoutMiddleware(){(0,a.$)("#link-view").submit()}async getURL(f){for(;;){await a._.wait(1E3);
try{const d=await v(f);if(d)return d}catch(d){a._.warn(d)}}}}})();a._.register({rule:{host:/^n\.fcd\.su$/},async ready(){const b=(0,a.$)("a.btn:nth-child(2)");await a.$.openLink(b.href)}});a._.register({rule:{host:/^linkpoi\.me$/},async ready(){await a._.wait(6E3);(0,a.$)(".btn.btn-primary.btn-block.redirect.get-link").click()}});a._.register({rule:{host:/^linkshrink\.net$/,path:/^\/[a-zA-Z0-9]+$/},async start(){a.$.window._impspcabe=0},async ready(){let b=a.$.searchFromScripts(/revC\("([^"]+)"\)/);
b=atob(b[1]);await a.$.openLink("/"+b)}});a._.register({rule:{host:/^linksly\.co$/},async ready(){(0,a.$)(".btn-primary").click()}});a._.register({rule:{host:[/^go\.linksly\.co$/,/^go\.bitcosite\.com$/]},async ready(){await a._.wait(8E3);const b=(0,a.$)(".btn-success.btn-lg.get-link");await a.$.openLink(b.href)}});a._.register({rule:{host:/^lnk2\.cc$/,path:/^\/go\//},async ready(){a.$.remove("iframe, .popupOverlay");await a._.wait(18E3);(0,a.$)("#getLink").click()}});a._.register({rule:{host:/^www\.lolinez\.com$/,
query:/\?(.+)/},async start(b){await a.$.openLink(b.query[1])}});a._.register({rule:{host:/^mangalist\.org$/},async ready(){await a._.wait(1E3);(0,a.$)(".btn-primary.url.text-center").click()}});a._.register({rule:{host:/^mylink\.us$/},async ready(){await a._.wait(8E3);(0,a.$)("div.skip_btn a").click()}});a._.register({rule:{host:/^nmac\.to$/,path:/^\/dl\/(.+)/},async ready(){const b=(0,a.$)(".btn-medium.btn-block");await a.$.openLink(b.href)}});a._.register({rule:{host:/^noriskdomain\.com$/},async ready(){await a._.wait(1E4);
(0,a.$)(".uk-button-primary.go-to-button").click();await a._.wait(1E3);(0,a.$)(".uk-button-primary.go-to-button").click()}});a._.register({rule:{host:/^noweconomy\.live$/},async ready(){const b=(0,a.$)('[class="btn-main get-link"]');await a.$.openLink(b.href)}});a._.register({rule:{host:/^www\.oni\.vn$/},async ready(){a.$.remove("iframe");var b=a.$.searchFromScripts(/data:"([^"]+)"/);if(!b)throw new a._.AdsBypasserError("pattern changed");b=b[1];b=await a.$.get("/click.html",b);await a.$.openLink(b)}});
a._.register({rule:{host:/^otomi-games\.com$/,path:/^\/go\//},async ready(){const b=(0,a.$)("#wpsafe-link a");await a.$.openLink(b.href)}});a._.register({rule:{host:/^(www\.)?ouo\.(io|press)$/,path:/(^\/\w+$|^\/go\/\w+$)/},async ready(){(0,a.$)("form").submit()}});a._.register({rule:{host:/^paylinnk\.com$/},async ready(){await a._.wait(2E3);(0,a.$)("div.banner.banner-captcha").click();(0,a.$)(".btn.btn-success.btn-lg.get-link").click()}});a._.register({rule:{host:/^icerik\.site$/,path:/^\/go/},async ready(){await a._.wait(500);
(0,a.$)("#get_link_btn").click()}});a._.register({rule:{host:[/^realsht\.mobi$/]},async ready(){(0,a.$)("#download_link").click()}});a._.register({rule:{host:/^preview\.rlu\.ru$/},async ready(){const b=(0,a.$)("#content > .long_url > a");await a.$.openLink(b.href)}});a._.register({rule:{host:/^segmentnext\.com$/,path:/^\/interstitial\.html$/,query:/return_url=([^&]+)/},async start(b){await a.$.openLink(decodeURIComponent(b.query[1]))}});a._.register({rule:{host:[/^shink\.me$/,/^shon\.xyz$/]},async ready(){(0,a.$)("#skip").submit()}});
a._.register({rule:{host:/^(short|srt)\.am$/},async ready(){await a._.wait(5E3);await a.$.openLink("",{post:{_image:"Continue"}})}});(function(){function b(v){const t=a.$.searchFromScripts(/xpid:"([^"]+)"/),u={adSessionId:v},f={Accept:"application/json, text/javascript"};t&&(f["X-NewRelic-ID"]=t);const d=setInterval(function(){a.$.get("/shortest-url/end-adsession",u,f).then(function(h){h=JSON.parse(h);if("ok"==h.status&&h.destinationUrl)return clearInterval(d),a.$.removeAllTimer(),h=decodeURIComponent(h.destinationUrl),
a.$.openLink(h)})},1E3)}a._.register({rule:{host:[/^(cllkme|clkmein|corneey|ceesty)\.com$/,/^(destyy|festyy|gestyy)\.com$/,/^sh\.st$/],path:/^\/[\d\w]+/},async ready(){a.$.remove("iframe");a.$.removeAllTimer();const v=a.$.searchFromScripts(/sessionId: "([\d\w]+)",/);if(v)b(v[1]);else{var t=new MutationObserver(u=>{u.forEach(()=>{const f=a.$.searchFromScripts(/sessionId: "([\d\w]+)",/);f&&(t.disconnect(),b(f[1]))})});t.observe(document.body,{childList:!0})}}})})();a._.register({rule:{host:[/^shortlinkto\.biz$/,
/^uplinkto\.hair$/]},async ready(){const b=(0,a.$)(".view-well a");await a.$.openLink(b.href)}});a._.register({rule:{host:/^(www\.)?shortly\.xyz$/},async ready(){await a._.wait(8E3);(0,a.$)(".btn-success.btn-lg.get-link").click()}});a._.register({rule:{host:/^shortmoz\.link$/},async ready(){(0,a.$)(".btn.btn-primary.btn-block").click()}});a._.register({rule:{host:/^(www\.)?similarsites\.com$/,path:/^\/goto\/([^?]+)/},async start(b){b=b.path[1];/^https?:\/\//.test(b)||(b="http://"+b);await a.$.openLink(b)}});
a._.register({rule:{host:/^spacetica\.com$/},async ready(){(0,a.$)(".btn.btn-primary.btn-xs").click()}});a._.register({rule:{host:/^www\.spaste\.com$/,path:/^\/site\//},async ready(){await a._.wait(15E3);(0,a.$)("#template-contactform-submit").click()}});a._.register({rule:{host:/^stfly\.(me|xyz)$/},async ready(){(0,a.$)(".btn-captcha.m-2.form-send").click()}});a._.register({rule:{host:/^blogbux\.net$/},async ready(){const b=(0,a.$)(".btn-captcha.m-2.form-send");await a._.wait(12E3);b.click()}});
a._.register({rule:{host:/^techtrendmakers\.com$/},async ready(){const b=(0,a.$)(".btn-captcha.m-2.form-send.step_btn");await a._.wait(6E3);b.click()}});a._.register({rule:{host:/^(www\.)?supercheats\.com$/,path:/^\/interstitial\.html$/,query:/(?:\?|&)oldurl=([^&]+)(?:$|&)/},async start(b){await a.$.openLink(b.query[1])}});a._.register({rule:{host:/^swzz\.xyz$/,path:/^\/link\//},async ready(){const b=(0,a.$)("a.btn.btn-primary");await a.$.openLink(b.href)}});a._.register({rule:{host:/^techgeek\.digital$/},
async ready(){var b=(0,a.$)('[class="btn-main get-link"]');b&&b.click();(b=(0,a.$)('a[class="btn-main get-link"]'))&&await a.$.openLink(b.href)}});a._.register({rule:{host:/^thinfi\.com$/},async ready(){const b=(0,a.$)("div p a");await a.$.openLink(b.href)}});a._.register({rule:{host:/^go\.tnshort\.net$/},async ready(){await a._.wait(3E3);const b=(0,a.$)('a[class="btn btn-success btn-lg get-link"]');await a.$.openLink(b.href)}});a._.register({rule:{host:/^tribuntekno\.com$/},async ready(){var b=a.$.$("#lite-human-verif-button");
b&&b.click();(b=a.$.$("#lite-start-sora-button"))&&b.click()}});a._.register({rule:{host:/^tutwuri\.id$/},async ready(){await a._.wait(1E3);(0,a.$)("#btn-1").click();await a._.wait(12E3);(0,a.$)("#btn-2").click();(0,a.$)("#btn-3").click()}});a._.register({rule:{host:/^urlbluemedia\.shop$/},async ready(){await a._.wait(7E3);(0,a.$)("input#nut").click()}});a._.register({rule:{host:[/(^|\.)urlcash\.(com|org)$/,/^(detonating|smilinglinks|pornyhost|urlgalleries)\.com$/,/^looble\.net$/,/^xxxs\.org$/]},
async ready(){if(a.$.window&&a.$.window.linkDestUrl)await a.$.openLink(a.$.window.linkDestUrl);else{var b=document.body.innerHTML.match(/linkDestUrl = '(.+)'/);b&&await a.$.openLink(b[1])}}});a._.register({rule:{host:/^(www\.)?vzturl\.com$/},async ready(){const b=(0,a.$)("frame[scrolling=yes]");await a.$.openLink(b.src)}});a._.register({rule:{host:/^xpshort\.com$/},async ready(){await a._.wait(8E3);(0,a.$)(".btn-success.btn-lg.get-link").click()}})},(q,p,m)=>{function a(k,r){return(0,t.querySelector)(k,
r)}m.r(p);m.d(p,{$:()=>a,_:()=>h});q=m(8);p=m(9);var b=m(1),v=m(2),t=m(10),u=m(11),f=m(5),d=m(12);m=m(3);const h={AdsBypasserError:b.AdsBypasserError,evil:d.evil,find:b.find,forEach:b.forEach,generateRandomIP:d.generateRandomIP,info:f.info,none:b.none,partial:b.partial,register:v.register,tryEvery:b.tryEvery,wait:b.wait,warn:f.warn};a.$=t.querySelectorOrNull;a.$$=t.querySelectorAll;a.block=t.block;a.get=q.get;a.getCookie=p.getCookie;a.nuke=d.nuke;a.openLink=u.openLink;a.post=q.post;a.remove=t.remove;
a.removeAllTimer=d.removeAllTimer;a.resetCookies=p.resetCookies;a.searchFromScripts=t.searchFromScripts;a.setCookie=p.setCookie;a.toDOM=t.toDOM;a.window=m.usw},(q,p,m)=>{function*a(e){if(e)for(const [c,g]of Object.entries(e))if(Array.isArray(g))for(const n of g)yield[[c,""],n];else if("object"===typeof g)for(const [n,w]of a(g))yield[[c,...n],w];else yield[[c],g]}function b(e){const [c,...g]=e;return`${c}${g.map(n=>`[${n}]`)}`}function v(e,c){const g=Object.getOwnPropertyNames(c);return(0,k.map)(g,
n=>{const w=c[n];n=`${e}[${n}]`;return"object"===typeof w?v(n,w):[n,w].map(encodeURIComponent).join("=")}).join("&")}function t(e){var c=typeof e;if(null===e||"string"!==c&&"object"!==c)return"";if("string"===c)return e;if(e instanceof String)return e.toString();c=Object.getOwnPropertyNames(e);return(0,k.map)(c,g=>{const n=e[g];return"object"===typeof n?v(g,n):[g,n].map(encodeURIComponent).join("=")}).join("&")}function u(e){var c=typeof e;if(null===e||"string"!==c&&"object"!==c)return"";if("string"===
c)return e;if(e instanceof String)return e.toString();c=new FormData;for(const [g,n]of a(e))c.append(b(g),n);return c}function f(e,c,g,n){(0,l.debug)("ajax",e,c,g,n);const w=document.createElement("a");w.href=c;(0,k.forEach)({Host:w.hostname||window.location.host,Origin:window.location.origin,Referer:window.location.href,"X-Requested-With":"XMLHttpRequest"},(y,C)=>{n[C]===k.none?delete n[C]:n[C]=y});g&&(g=0<=n["Content-Type"].indexOf("json")?JSON.stringify(g):0<=n["Content-Type"].indexOf("multipart")?
u(g):t(g),n["Content-Length"]=g.length);return new Promise((y,C)=>{r.GMAPI.xmlHttpRequest({method:e,url:c,data:g,headers:n,onload(A){A="undefined"!==typeof A.responseText?A:this;200!==A.status?C(new x(e,c,g,n,A.status,A.responseText)):y(A.responseText)},onerror(A){A="undefined"!==typeof A.responseText?A:this;C(new x(e,c,g,n,A.status,A.responseText))}})})}function d(e,c,g){c=t(c);g=g||{};return f("GET",e+(c?"?"+c:""),"",g)}function h(e,c,g){const n={"Content-Type":"application/x-www-form-urlencoded; charset=UTF-8"};
g&&(0,k.forEach)(g,(w,y)=>{n[y]=w});return f("POST",e,c,n)}m.r(p);m.d(p,{get:()=>d,post:()=>h});var k=m(1),r=m(3),l=m(5);class x extends k.AdsBypasserError{constructor(e,c,g,n,w,y){super(`${e} ${c} got ${w}`);this._method=e;this._url=c;this._data=g;this._headers=n;this._status=w;this._response=y}get name(){return"AjaxError"}get method(){return this._method}get url(){return this._url}get data(){return this._data}get headers(){return this._headers}get status(){return this._status}get response(){return this._response}}
},(q,p,m)=>{function a(u,f){document.cookie=`${u}=${f};path=${location.pathname};`}function b(u){let [,f]=(0,t.find)(document.cookie.split(";"),d=>{if(d.replace(/^\s*([a-zA-Z0-9-_]+)=.+$/,"$1")!==u)return t.none});return f===t.none?null:(f=f.replace(/^\s*[a-zA-Z0-9-_]+=([^;]+).?$/,"$1"))?f:null}function v(){const u=document.domain,f=document.domain.replace(/^www\./,""),d=document.domain.replace(/^(\w+\.)+?(\w+\.\w+)$/,"$2"),h=(new Date(1E3)).toUTCString();(0,t.forEach)(document.cookie.split(";"),
k=>{k=k.replace(/^\s*(\w+)=.+$/,"$1");document.cookie=`${k}=;expires=${h};`;document.cookie=`${k}=;path=/;expires=${h};`;document.cookie=`${k}=;path=/;domain=${u};expires=${h};`;document.cookie=`${k}=;path=/;domain=${f};expires=${h};`;document.cookie=`${k}=;path=/;domain=${d};expires=${h};`})}m.r(p);m.d(p,{getCookie:()=>b,resetCookies:()=>v,setCookie:()=>a});var t=m(1)},(q,p,m)=>{function a(e,c){c&&c.querySelector||(c=document);c=c.querySelector(e);if(!c)throw new x(e);return c}function b(e,c){try{return a(e,
c)}catch(g){return null}}function v(e,c){c&&c.querySelectorAll||(c=document);return c.querySelectorAll(e)}function t(e){try{return(new DOMParser).parseFromString(e,"text/html")}catch(c){throw new r.AdsBypasserError("could not parse HTML to DOM");}}function u(e,c){e=v(e,c);(0,r.forEach)(e,g=>{(0,l.debug)("removed",g);g.remove()})}function f(e,c=null){c||=document;let g=null;if((0,r.isString)(e))g=()=>{u(e,c)};else if("function"===typeof e)g=n=>{n.addedNodes.forEach(w=>{e(w)&&w.parentNode.removeChild(w)})};
else throw new TypeError("wrong selector");(new MutationObserver(n=>{n.forEach(w=>{g(w)})})).observe(c,{childList:!0,subtree:!0})}function d(e,c){c=v("script",c);[,,c]=(0,r.find)(c,g=>(g=g.textContent.match(e))?g:r.none);return c===r.none?null:c}function h(e,c){c=v("script",c);[,c]=(0,r.find)(c,g=>{g=g.textContent.indexOf(e);return 0>g?r.none:g});return c===r.none?null:c.textContent}function k(e,c){return e instanceof RegExp?d(e,c):(0,r.isString)(e)?h(e,c):null}m.r(p);m.d(p,{block:()=>f,querySelector:()=>
a,querySelectorAll:()=>v,querySelectorOrNull:()=>b,remove:()=>u,searchFromScripts:()=>k,toDOM:()=>t});var r=m(1),l=m(5);class x extends r.AdsBypasserError{constructor(e){super(`\`${e}\` not found`)}get name(){return"DomNotFoundError"}}},(q,p,m)=>{function a(d){document.body||(document.body=document.createElement("body"));document.body.appendChild(d);return(0,u.wait)(0)}async function b(d){const h=document.createElement("a");h.href=d;let k=!1;h.addEventListener("click",l=>{l.stopPropagation();k=!0},
!0);await a(h);h.click();const r=setInterval(()=>{k?((0,f.info)("already clicked"),clearInterval(r)):((0,f.info)("try again"),h.click())},500)}async function v(d,h){h=h||{};const k=document.createElement("form");k.method="post";k.action=d;(0,u.forEach)(h,(r,l)=>{const x=document.createElement("input");x.type="hidden";x.name=l;x.value=r;k.appendChild(x)});await a(k);k.submit()}async function t(d,h){if((0,u.isString)(d)||d){h=h||{};var k="undefined"===typeof h.referer?!0:h.referer;h=h.post;(0,f.info)(`${window.location.toString()} -> ${d}`);
h?await v(d,h):k?await b(d):window.top.location.replace(d)}else(0,f.warn)("false URL")}m.r(p);m.d(p,{openLink:()=>t});var u=m(1),f=m(5)},(q,p,m)=>{function a(){let h=window.setInterval(u.nop,10);for(;0<h;)window.clearInterval(h--);for(h=window.setTimeout(u.nop,10);0<h;)window.clearTimeout(h--)}function b(h){try{f.usw.document.write("nuked by AdsBypasser, leading to ...<br/>")}catch(r){(0,d.warn)("nuke failed",r)}const k=document.createElement("a");k.href=h;k.textContent=h;document.body.appendChild(k)}
function v(){return[0,0,0,0].map(()=>Math.floor(256*Math.random())).join(".")}function t(h){return((k,r,l,x,e,c,g,n,w,y)=>eval(h))()}m.r(p);m.d(p,{evil:()=>t,generateRandomIP:()=>v,nuke:()=>b,removeAllTimer:()=>a});var u=m(1),f=m(3),d=m(5)}],E={};(()=>{z.d=(q,p)=>{for(var m in p)z.o(p,m)&&!z.o(q,m)&&Object.defineProperty(q,m,{enumerable:!0,get:p[m]})}})();(()=>{z.o=(q,p)=>Object.prototype.hasOwnProperty.call(q,p)})();(()=>{z.r=q=>{"undefined"!==typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(q,
Symbol.toStringTag,{value:"Module"});Object.defineProperty(q,"__esModule",{value:!0})}})();z.r({});var F=z(1),O=z(2),B=z(3),H=z(4),D=z(5);z(6);const K=0<Object.prototype.toString.call(window.HTMLElement).indexOf("Constructor");(async function(){if(B.rawUSW.top===B.rawUSW.self){B.GMAPI.registerMenuCommand("AdsBypasser - Configure",()=>{B.GMAPI.openInTab("https://adsbypasser.github.io/configure.html")});await (0,H.loadConfig)();var q=(0,O.findHandler)();q&&(await L(q),await N(),await M(q))}})().catch(q=>
{(0,D.warn)(q)})})();
