// ==UserScript==
// @name                ChatGPT Infinity ∞
// @author              Adam Lui
// @namespace           https://github.com/adamlui
// @version             2025.3.8.1
// @license             MIT
// @icon                https://assets.chatgptinfinity.com/images/icons/infinity-symbol/circled/with-robot/icon48.png?v=69e434b
// @icon64              https://assets.chatgptinfinity.com/images/icons/infinity-symbol/circled/with-robot/icon64.png?v=69e434b
// @compatible          chrome
// @compatible          firefox
// @compatible          edge
// @compatible          opera
// @compatible          brave
// @compatible          vivaldi
// @compatible          waterfox
// @compatible          librewolf
// @compatible          ghost
// @compatible          qq
// @compatible          whale
// @compatible          kiwi
// @match               *://chatgpt.com/*
// @connect             cdn.jsdelivr.net
// @connect             gm.chatgptinfinity.com
// @connect             raw.githubusercontent.com
// @require             https://cdn.jsdelivr.net/npm/@kudoai/chatgpt.js@3.7.1/dist/chatgpt.min.js#sha256-uv1k2VxGy+ri3+2C+D/kTYSBCom5JzvrNCLxzItgD6M=
// @require             https://cdn.jsdelivr.net/gh/adamlui/chatgpt-infinity@4ec0a82/chromium/extension/components/modals.js#sha256-/WTJT4ykm9m003gIIZnvYnZNXSwsrc7FsqeEFIozRQ8=
// @require             https://cdn.jsdelivr.net/gh/adamlui/chatgpt-infinity@4ec0a82/chromium/extension/components/toggles.js#sha256-9Oc1cL75YDDVpJP9qt8htiYRz0uM8SUMH2uJrsm8DUw=
// @require             https://cdn.jsdelivr.net/gh/adamlui/chatgpt-infinity@1ae4e33/chromium/extension/lib/dom.js#sha256-U+SUWAkqLIY6krdR2WPhVy5/f+cTV03n3F8b+Y+/Py0=
// @require             https://cdn.jsdelivr.net/gh/adamlui/chatgpt-infinity@2ec25ce/chromium/extension/lib/settings.js#sha256-cyRP9w9Di8RjzNZSJeah3ILK7dx57598Rn4BZL/eiv0=
// @require             https://cdn.jsdelivr.net/gh/adamlui/chatgpt-infinity@6089211/chromium/extension/lib/ui.js#sha256-/szI0bDpLL1aVTrc29iyToff58VMfeM/lSyjHWTipt0=
// @resource rpgCSS     https://assets.aiwebextensions.com/styles/rising-particles/dist/gray.min.css?v=727feff#sha256-48sEWzNUGUOP04ur52G5VOfGZPSnZQfrF3szUr4VaRs=
// @resource rpwCSS     https://assets.aiwebextensions.com/styles/rising-particles/dist/white.min.css?v=727feff#sha256-6xBXczm7yM1MZ/v0o1KVFfJGehHk47KJjq8oTktH4KE=
// @grant               GM_setValue
// @grant               GM_getValue
// @grant               GM_registerMenuCommand
// @grant               GM_unregisterMenuCommand
// @grant               GM_getResourceText
// @grant               GM_xmlhttpRequest
// @grant               GM.xmlHttpRequest
// @noframes
// @downloadURL https://raw.githubusercontent.com/siritami/test1/release/release/chatgptinfinity.user.js
// @updateURL https://raw.githubusercontent.com/siritami/test1/release/release/chatgptinfinity.meta.js
// @homepageURL         https://www.chatgptinfinity.com
// @supportURL          https://support.chatgptinfinity.com
// @contributionURL     https://github.com/sponsors/adamlui
// ==/UserScript==
(async()=>{function t(a){if(!a)return"";a=a.toLowerCase().split(" ");for(let c=0;c<a.length;c++)a[c]=a[c][0].toUpperCase()+a[c].slice(1);return a.join(" ")}function u(a,c="",g="",h=""){const d=n.state.words.find(l=>a.includes(l));d&&(a=a.replace(d,""));chatgpt.notify(`${b.symbol} ${a}`,c,g,h||"dark"==e.ui.scheme?"":"shadow");c=document.querySelector(".chatgpt-notif:last-child");d&&(g=dom.create.elem("span"),g.style.cssText={on:{light:"color: #5cef48 ; text-shadow: rgba(255,250,169,0.38) 2px 1px 5px",
dark:"color: #5cef48 ; text-shadow: rgb(55,255,0) 3px 0 10px"},off:{light:"color: #ef4848 ; text-shadow: rgba(255,169,225,0.44) 2px 1px 5px",dark:"color: #ef4848 ; text-shadow: rgba(255, 116, 116, 0.87) 3px 0 9px"}}[d==n.state.words[0]?"off":"on"][e.ui.scheme],g.append(d),c.append(g))}function p(a){if("infinityMode"==a?.updatedKey)f[config.infinityMode?"activate":"deactivate"]();else"prompt"==settings.controls[a?.updatedKey].type&&config.infinityMode&&f.restart({target:"replyInterval"==a?.updatedKey?
"self":"new"});/infinityMode|toggleHidden/.test(a?.updatedKey)&&toggles.sidebar.update.state();n.refresh()}function x(a){a.origin==location.origin&&(a=a.data.source,e.extensionActive=a.includes(b.slug)&&/extension/i.test(a))}function y(){const a=ui.getScheme();e.ui.scheme!=a&&(e.ui.scheme=a,toggles.sidebar.update.scheme(),modals.stylize())}var k={language:chatgpt.getUserLanguage(),isFF:chatgpt.browser.isFirefox(),isMobile:chatgpt.browser.isMobile()};try{var z=GM_info.scriptHandler}catch(a){z="unknown"}try{var A=
GM_info.version}catch(a){A="unknown"}const e={browser:k,scriptManager:{name:z,version:A},ui:{scheme:ui.getScheme()}};e.browser.isPortrait=e.browser.isMobile&&innerWidth<innerHeight;e.scriptManager.supportsTooltips="Tampermonkey"==e.scriptManager.name&&5<=parseInt(e.scriptManager.version.split(".")[0]);const v="undefined"!=typeof GM&&GM.xmlHttpRequest||GM_xmlhttpRequest,b={version:GM_info.script.version,configKeyPrefix:"chatGPTinfinity",chatgptJSver:/chatgpt\.js@([\d.]+)/.exec(GM_info.scriptMetaStr)[1],
urls:{update:"https://gm.chatgptinfinity.com"},latestResourceCommitHash:"d57d034"};b.urls.resourceHost=`https://cdn.jsdelivr.net/gh/adamlui/chatgpt-infinity@${b.latestResourceCommitHash}`;k=await new Promise(a=>v({method:"GET",url:`${b.urls.resourceHost}/assets/data/app.json`,onload:c=>a(JSON.parse(c.responseText))}));Object.assign(b,{...k,urls:{...b.urls,...k.urls}});b.msgs={appName:b.name,appAuthor:b.author.name,appDesc:"Generate endless answers from all-knowing ChatGPT (in any language!)",menuLabel_infinityMode:"Infinity Mode",
menuLabel_autoStart:"Auto-Start",menuLabel_toggleVis:"Toggle Visibility",menuLabel_autoScroll:"Auto-Scroll",menuLabel_replyLang:"Reply Language",menuLabel_replyTopic:"Reply Topic",menuLabel_all:"ALL",menuLabel_replyInt:"Reply Interval",menuLabel_about:"About",menuLabel_donate:"Please send a donation",menuLabel_extensionActive:"extension active",about_author:"Author",about_and:"&",about_contributors:"contributors",about_version:"Version",about_poweredBy:"Powered by",about_openSourceCode:"Open source code",
prompt_updateReplyLang:"Update reply language",prompt_updateReplyTopic:"Update reply topic",prompt_orEnter:"or enter",prompt_updateReplyInt:"Update reply interval (minimum 5 secs)",helptip_autoStart:"Automatically start Infinity Mode when visiting chatgpt.com",helptip_toggleVis:"Show Infinity Mode toggle in sidebar",helptip_autoScroll:"Automatically scroll to bottom as replies are generating",alert_replyLangUpdated:"Language updated",alert_willReplyIn:"will reply in",alert_yourSysLang:"your system language",
alert_replyTopicUpdated:"Topic updated",alert_willAnswer:"will answer questions",alert_onTopicOf:"on the topic of",alert_onAllTopics:"on ALL topics",alert_replyIntUpdated:"Interval updated",alert_willReplyEvery:"will reply every",alert_choosePlatform:"Choose a platform",alert_updateAvail:"Update available",alert_newerVer:"An update to",alert_isAvail:"is available",alert_upToDate:"Up-to-date",alert_isUpToDate:"is up-to-date",alert_showYourSupport:"Show your support",alert_isOSS:"is open-source software built & maintained for free through 100% volunteer efforts",
alert_despiteAffliction:"Despite being severely afflicted by",alert_longCOVID:"long COVID",alert_since2020:"since 2020",alert_byDonatingResults:"by donating, you help me to continue improving, fixing bugs, adding new features, and making the software even better",alert_yourContrib:"Your contribution",alert_noMatterSize:"no matter the size",alert_directlySupports:"directly supports my unpaid efforts to ensure this project remains free and open for all to use",alert_tyForSupport:"Thank you for your support",
btnLabel_moreAIextensions:"More AI Extensions",btnLabel_rateUs:"Rate Us",btnLabel_discuss:"Discuss",btnLabel_getSupport:"Get Support",btnLabel_checkForUpdates:"Check for Updates",btnLabel_update:"Update",btnLabel_dismiss:"Dismiss",link_viewChanges:"View changes",unit_seconds:"seconds",state_enabled:"enabled",state_disabled:"disabled",state_on:"on",state_off:"off"};e.browser.language.startsWith("en")||(k=await new Promise(a=>{function c(){v({method:"GET",url:l,onload:g})}function g(q){try{const m=
JSON.parse(q.responseText);q={};for(const r in m)"object"==typeof m[r]&&"message"in m[r]&&(q[r]=m[r].message);a(q)}catch(m){w++;if(3==w)return a({});l=e.browser.language.includes("-")&&1==w?l.replace(/([^_]+_[^_]+)_[^/]*(\/.*)/,"$1$2"):h+"en/messages.json";c()}}const h=b.urls.resourceHost+"/chromium/extension/_locales/",d=(e.browser.language?e.browser.language.replace("-","_"):"en")+"/";let l=h+d+"messages.json",w=0;c()}),Object.assign(b.msgs,k));dom.import({scheme:e.ui.scheme});modals.import({app:b,
env:e,updateCheck:function(){v({method:"GET",url:b.urls.update+"?t="+Date.now(),headers:{"Cache-Control":"no-cache"},onload:a=>{b.latestVer=/@version +(.*)/.exec(a.responseText)?.[1];if(b.latestVer)for(a=0;4>a;a++){const c=parseInt(b.version.split(".")[a],10)||0,g=parseInt(b.latestVer.split(".")[a],10)||0;if(c>g)break;else if(g>c)return modals.open("update","available")}modals.open("update","unavailable")}})}});settings.import({app:b});settings.load(Object.keys(settings.controls).filter(a=>"infinityMode"!=
a));settings.save("infinityMode",!1);config.replyLanguage||settings.save("replyLanguage",e.browser.language);config.replyTopic||settings.save("replyTopic",b.msgs.menuLabel_all);config.replyInterval||settings.save("replyInterval",7);const n={ids:[],state:{symbols:["\u274c","\u2714\ufe0f"],separator:"Tampermonkey"==e.scriptManager.name?" \u2014 ":": ",words:[b.msgs.state_off.toUpperCase(),b.msgs.state_on.toUpperCase()]},refresh(){if("undefined"!=typeof GM_unregisterMenuCommand){for(const a of this.ids)GM_unregisterMenuCommand(a);
this.register()}},register(){if(e.extensionActive)GM_registerMenuCommand(`${this.state.symbols[0]} ${t(b.msgs.state_disabled)} (${b.msgs.menuLabel_extensionActive})`,()=>modals.open("about"),e.scriptManager.supportsTooltips?{title:" "}:void 0);else{const a=new RegExp(`^(${b.msgs.menuLabel_all}|all|any|every)$`,"i");Object.keys(settings.controls).forEach(c=>{const g=settings.controls[c].type,h=`${settings.controls[c].symbol||this.state.symbols[+settings.isEnabled(c)]} `+settings.controls[c].label+
("toggle"==g?this.state.separator+this.state.words[+settings.isEnabled(c)]:`\u2014 ${settings.controls[c].status}`);this.ids.push(GM_registerMenuCommand(h,()=>{if("toggle"==g)settings.save(c,!config[c]),u(`${settings.controls[c].label}: ${this.state.words[+(/disabled/i.test(c)^config[c])]}`);else if("replyLanguage"==c)for(;;){var d=prompt(`${b.msgs.prompt_updateReplyLang}:`,config.replyLanguage);if(null==d)break;else if(!/\d/.test(d)){d=4>d.length||d.includes("-")?d.toUpperCase():t(d);settings.save("replyLanguage",
d||e.browser.language);modals.alert(b.msgs.alert_replyLangUpdated+"!",b.msgs.appName+" "+b.msgs.alert_willReplyIn+" "+(d||b.msgs.alert_yourSysLang)+".");break}}else if("replyTopic"==c)d=prompt(b.msgs.prompt_updateReplyTopic+" ("+b.msgs.prompt_orEnter+" 'ALL'):",config.replyTopic),null!=d&&(d=t(d.toString()),settings.save("replyTopic",!d||a.test(d)?b.msgs.menuLabel_all:d),modals.alert(`${b.msgs.alert_replyTopicUpdated}!`,`${b.msgs.appName} ${b.msgs.alert_willAnswer} `+(!d||a.test(d)?b.msgs.alert_onAllTopics:
`${b.msgs.alert_onTopicOf} ${d}`)+"!"));else if("replyInterval"==c)for(;d=prompt(`${b.msgs.prompt_updateReplyInt}:`,config.replyInterval),null!=d;)if(!isNaN(parseInt(d,10))&&4<parseInt(d,10)){settings.save("replyInterval",parseInt(d,10));modals.alert(b.msgs.alert_replyIntUpdated+"!",b.msgs.appName+" "+b.msgs.alert_willReplyEvery+" "+d+" "+b.msgs.unit_seconds+".");break}p({updatedKey:c})},e.scriptManager.supportsTooltips?{title:settings.controls[c].helptip||" "}:void 0))})}["about","donate"].forEach(a=>
{"donate"===a&&e.extensionActive||this.ids.push(GM_registerMenuCommand(`${"about"==a?"\ud83d\udca1":"\ud83d\udc96"}`+` ${b.msgs[`menuLabel_${a}`]} ${"about"==a?b.msgs.appName:""}`,()=>modals.open(a),e.scriptManager.supportsTooltips?{title:" "}:void 0))})}};chatgpt.isIdle=function(){return new Promise(a=>{(new MutationObserver((c,g)=>{chatgpt.getStopBtn()||(g.disconnect(),a())})).observe(document.body,{childList:!0,subtree:!0})})};const f={async activate(){const a="Generate a single random question"+
(config.replyLanguage?" in "+config.replyLanguage:"")+(" on "+("ALL"==config.replyTopic?"ALL topics":"the topic of "+config.replyTopic))+" then answer it. Don't type anything else.";e.browser.isMobile&&chatgpt.sidebar.isOn()&&chatgpt.sidebar.hide();if(!(new URL(location)).pathname.startsWith("/g/"))try{chatgpt.startNewChat()}catch(c){return}await new Promise(c=>setTimeout(c,500));chatgpt.send(a);await new Promise(c=>setTimeout(c,3E3));!document.querySelector("[data-message-author-role]")&&config.infinityMode&&
chatgpt.send(a);await chatgpt.isIdle();config.infinityMode&&!f.isActive&&(f.isActive=setTimeout(f.continue,1E3*parseInt(config.replyInterval,10)))},async continue(){if(!config.autoScrollDisabled)try{chatgpt.scrollToBottom()}catch(a){}chatgpt.send("Do it again.");await chatgpt.isIdle();f.isActive&&(f.isActive=setTimeout(f.continue,1E3*parseInt(config.replyInterval,10)))},deactivate(){chatgpt.getStopBtn()&&chatgpt.stop();clearTimeout(f.isActive);f.isActive=null},async restart(a={target:"new"}){"new"==
a.target?(f.deactivate(),setTimeout(()=>f.activate(),750)):(clearTimeout(f.isActive),f.isActive=null,await chatgpt.isIdle(),config.infinityMode&&!f.isActive&&(f.isActive=setTimeout(f.continue,1E3*parseInt(config.replyInterval,10))))}};toggles.import({app:b,env:e,notify:u,syncConfigToUI:p});toggles.sidebar.update.navicon({preload:!0});postMessage({action:"getExtensionInfo",source:`${b.slug}.user.js`},location.origin);addEventListener("message",x);await new Promise(a=>setTimeout(a,100));removeEventListener("message",
x);n.register();e.extensionActive||(await Promise.race([chatgpt.isLoaded(),new Promise(a=>setTimeout(a,5E3))]),await chatgpt.sidebar.isLoaded(),e.ui.firstLink=chatgpt.getNewChatLink(),"hidden"in document&&(document.onvisibilitychange=()=>{config.infinityMode&&(settings.save("infinityMode",!1),p({updatedKey:"infinityMode"}))}),["rpg","rpw"].forEach(a=>document.head.append(dom.create.style(GM_getResourceText(`${a}CSS`)))),toggles.sidebar.insert(),config.autoStart&&(settings.save("infinityMode",!0),
p({updatedKey:"infinityMode"}),u(`${b.msgs.menuLabel_autoStart}: ${b.msgs.state_on.toUpperCase()}`)),(new MutationObserver(()=>{config.toggleHidden||document.querySelector(`.${toggles.sidebar.class}`)||"inserting"==toggles.sidebar.status||(toggles.sidebar.status="missing",toggles.sidebar.insert())})).observe(document.body,{attributes:!0,subtree:!0}),(new MutationObserver(y)).observe(document.documentElement,{attributes:!0,attributeFilter:["class"]}),window.matchMedia("(prefers-color-scheme: dark)").addEventListener("change",
()=>requestAnimationFrame(y)),document.documentElement.hasAttribute("sidebar-click-zoom-observed")||((new MutationObserver(a=>a.forEach(({target:c})=>{c.closest("[class*=sidebar]")&&!c.closest("[class*=sidebar-toggle]")&&"none"!=c.style.transform&&(c.style.transform="none")}))).observe(document.body,{attributes:!0,subtree:!0,attributeFilter:["style"]}),document.documentElement.setAttribute("sidebar-click-zoom-observed",!0)))})();
