// ==UserScript==
// @name         Direct download from Google Play
// @namespace    StephenP
// @version      3.6.0
// @author       StephenP
// @icon      data:image/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAAM1BMVEV2ZXLgIkzxMUf6OkN9f5v7ZTAOpP8OxP4myPsU1LkU1P4k4oAr3vwk7H1U41v+ziz92jIMI6b6AAAAAXRSTlMAQObYZgAAAKtJREFUOMul0ssSgyAMQNGAtCgv/f+vLcVCSCLiTLPL3MPAAoAn4/0EbP6eWDsRaxEx3gG7xe+MAIo4ABPhiIjXoBeCOCEiB0IkDphI+3EwQETaM+iIYyL3AhpxVKT3OSgCEeaFACgowiyLBE241WgE7ZEBhdFaVwA9CNi1vgQB+wCE1kcg1A4DQO6n5uxKleMgO/x6nrKKDrXX/eINpstV9D+G9SLIruCP+QAbnhEp2bGFogAAAABJRU5ErkJggg==
// @match        https://play.google.com/*
// @match        http://play.google.com/*
// @match        http://apkfind.com/store/captcha?app=*
// @grant        GM.xmlHttpRequest
// @grant        GM.getValue
// @grant        GM.setValue
// @require      https://greasemonkey.github.io/gm4-polyfill/gm4-polyfill.js
// @connect      self
// @connect      apkpure.com
// @connect      apkfind.com
// @connect      apk-cloud.com
// @connect      winudf.com
// @connect      apkcombo.com
// @connect      down-apk.com
// @connect      play.googleapis.com
// @connect      gvt1.com
// @connect      apkpremier.com
// @connect      web-api.aptoide.com
// @connect      apk.support
// @contributionURL https://buymeacoffee.com/stephenp_greasyfork
// @downloadURL https://raw.githubusercontent.com/siritami/test1/release/release/Direct20download20from20Google20Play.user.js
// @updateURL https://raw.githubusercontent.com/siritami/test1/release/release/Direct20download20from20Google20Play.meta.js
// ==/UserScript==
var ui,wlButton,pageURL,title,appCwiz,done=[0],useGS;(async function(){useGS=await GM.getValue("useGS",!1);starter()})();
function starter(){if(!0===document.location.href.includes("apkfind"))setInterval(unredirect,100);else try{"use strict";ui=checkUI();pageURL=location.href;if(0<ui){title=document.getElementById("main-title").innerHTML;var a=document.createElement("style");a.textContent='.ddlButton: visited {\n                          color: white;\n                      }\n                      .ddlButton: hover {\n                          opacity: 0.8;\n                      }\n                      .ddlButton: active {\n                          opacity: 0.6;\n                      }\n                      .ddlButton {\n                          font-family: "Google Sans",Roboto,Arial,sans-serif;\n                          font-size: 1rem;\n                          font-weight: 500;\n                          padding: 0 10px;\n                          color: white;\n                          position: relative;\n                          z-index: 0;\n                          width: 100px;\n                          cursor: pointer;\n                      }\n                      .ddlButton>a {\n                          color: white;\n                      }\n                      .dropdown {\n                          background-color:  #fff;\n                          width: min-content;\n                          border-radius: 8px;\n                          box-shadow: 0 5px 20px rgba(0, 0, 0, 0.7);\n                          padding: 8px;\n                          z-index: 1000;\n                      }\n                      #buttonDropdown > .ddlButton:first-child{\n                          border-radius: 8px 8px 0 0;\n                      }\n                      #buttonDropdown > .ddlButton:last-child{\n                          border-radius: 0 0 8px 8px;\n                      }';document.body.appendChild(a)}(pageURL.includes("details?id=")||
pageURL.includes("/store/search?q="))&&addButtons();setInterval(checkReload,2E3)}catch(c){console.log("main(): "+c)}}function unredirect(){var a=document.body.children.length-1;2<parseInt(document.body.children[a].style.zIndex,10)&&(""==document.body.children[a].id?(document.body.children[a].style.zIndex="1",document.body.children[a-1].style.zIndex="-1000"):document.body.children[a].style.zIndex="-1000")}
function waitForRemovingButtons(){if(pageURL!=location.href||!1===isButtonVisible()){if(title=document.getElementById("main-title").innerHTML,pageURL=location.href,wlButton=null,location.href.includes("details?id=")||location.href.includes("/store/search?q=")){if(0<ui&&0<document.getElementsByClassName("ddlButton").length)try{removePreviousCwiz()}catch(a){console.log(a+"; I was probably just trying to remove buttons that weren't there...")}addButtons()}}else setTimeout(waitForRemovingButtons,1E3)}
function checkReload(){pageURL==location.href&&!1!==isButtonVisible()||waitForRemovingButtons()}function isButtonVisible(){var a=document.getElementsByClassName("ddlButton");if(0<a.length){for(var c=0;c<a.length;c++)if(null!=a[c].offsetParent)return!0;return!1}return document.location.href.includes("play.google.com/store/apps/details")?(console.log("apppage//false"),!1):!0}
function addButtons(){var a=-1,c=null;if(0<ui){for(c=get2022UIButtons();"C-WIZ"!=c.tagName;)c=c.parentNode;try{a=c.querySelector("meta[itemprop=price]").content}catch(k){console.error("Price not found. Maybe the app is already installed or not officially available?"),a=0}var g=c.parentNode;do"C-WIZ"==g.tagName&&(appCwiz=g),g=g.parentNode;while("BODY"!=g.tagName)}else{document.getElementById("search-section").lastChild.remove();g=document.getElementById("search-section");var e=document.createElement("SPAN");
e.style="margin-top: 32px; float: left";e.textContent="or ";g.appendChild(e);e=document.createElement("SPAN");let k=document.createElement("A");k.style="background-color: #FF8B14; font-weight: bold; text-decoration: none; padding: 1em; margin: 17px; float: left; color: white; cursor: pointer;";k.textContent="Search on APKMirror";k.className="rounded";k.id="apkMirrorBtn";let d="https://www.apkmirror.com/?post_type=app_release&searchtype=apk&s="+location.search.match(/id=(.*)/)[1].split("&",1);k.addEventListener("click",
function(){window.open(d)});e.appendChild(k);g.appendChild(e);e=document.createElement("DIV");e.style="clear:both";g.appendChild(e);GM.xmlHttpRequest({method:"GET",url:"https://www.apkmirror.com/?post_type=app_release&searchtype=apk&s="+location.search.match(/id=(.*)/)[1].split("&",1),timeout:5E3,onload:function(l){0<(new DOMParser).parseFromString(l.responseText,"text/html").getElementById("content").getElementsByClassName("appRow").length?k.textContent="Available on APKMirror":(l=k.cloneNode(!0),
l.textContent="Not available on APKMirror",l.style.backgroundColor="#CCCCCC",l.style.cursor="not-allowed",k.parentNode.replaceChild(l,k))}})}if(0==a){var b;location.href.includes("details?id=")?b=location.search.match(/id=(.*)/)[1].split("&",1):location.href.includes("/store/search?q=")&&(b=c.querySelector('[data-item-id^="%.@."]').getAttribute("data-item-id").match(/%\.@\.".+"/)[0].replace('%.@."',"").replace('"',""));a="https://d.apkpure.com/b/APK/"+b+"?version=latest";g="https://apps.evozi.com/apk-downloader/?id="+
b;e="http://apkfind.com/store/download?id="+b;var h="https://www.apkmirror.com/?post_type=app_release&searchtype=apk&s="+b,f="https://apkcombo.com/genericApp/"+b+"/download/apk",m="https://apkpremier.com/download/"+b.toString().replace(/[.]/g,"-"),n="https://web-api.aptoide.com/search?query="+b,p="https://apk.support/download-app/"+b;wlButton=document.createDocumentFragment();var q="";c=c.parentNode;q="ddlButton";let k=document.createElement("button");k.className=q;k.innerHTML="Download \u25bc";k.style.backgroundColor=
"#F55";k.style.borderRadius="8px";let d=document.createElement("div");d.id="buttonDropdown";d.style.position="absolute";d.style.display="none";d.style.marginTop="5px";d.className="dropdown";d.appendChild(createOptionButton("APK-DL",e,"#009688",b,!0,!1));d.appendChild(createOptionButton("APKPure",a,"#24cd77",b,!0,!1));d.appendChild(createOptionButton("APKCombo",f,"#00875f",b,!0,!0));d.appendChild(createOptionButton("APKPremier",m,"#3740ff",b,!0,!1));d.appendChild(createOptionButton("Evozi",g,"#286090",
b,!1,!1));d.appendChild(createOptionButton("APKMirror",h,"#FF8B14",b,!1,!1));d.appendChild(createOptionButton("Aptoide",n,"#fe6446",b,!0,!1));d.appendChild(createOptionButton("APKSupport",p,"#3740ff",b,!0,!0));k.onclick=function(){d.style.display="block"===d.style.display?"none":"block"};document.body.addEventListener("click",function(l){console.log(l.target.closest("#buttonDropdown"));l.target.closest("#buttonDropdown")||l.target===k||(d.style.display="none")});c.appendChild(k);c.appendChild(d)}}
function createOptionButton(a,c,g,e,b,h){let f=document.createElement("button");f.className="ddlButton";f.style.backgroundColor=g;f.innerHTML=!b||h?'<a href="'+c+'">'+a+"</a>":"<span>"+a+"</span>";f.onclick=b?function(){ddl(this,c,e);return!1}:function(){window.open(c);return!1};return f}function openLink(a){window.open(a.replace("http://","https://"),"_self")}
function ddlFinalApk(a,c,g){if(""!=a)return done[g]=0,GM.xmlHttpRequest({method:"GET",url:a,timeout:5E3,ontimeout:function(e){0==done[g]?c.firstChild.textContent="Retry":done[g]=0},onprogress:function(e){(e.finalUrl.includes("winudf.com")||e.finalUrl.includes("down-apk.com")||e.finalUrl.includes("/play-apps-download-default/"))&&0==done[g]&&(console.log("downloading file n."+g),done[g]=1,a.includes("apkpure")?(window.open(e.finalUrl,"_self"),c.onclick=function(){openLink(e.finalUrl)},c.firstChild.textContent=
"Ready!"):a.includes("apkpremier")?(window.open(e.finalUrl,"_self"),c.onclick=function(){openLink(e.finalUrl)},c.firstChild.textContent="Ready!"):(window.open(e.finalUrl,g),c.firstChild.textContent="APKCombo"))},onload:function(e){0==done[g]?c.firstChild.textContent="Retry":done[g]=0},onerror:function(){buttonError(c,"Offline!")}}),0;buttonError(c,"Failed!");return-1}
function ddl(a,c,g){a.firstChild.textContent="Loading...";if(c.includes("apkfind"))try{GM.xmlHttpRequest({method:"GET",url:c,onload:function(b){console.log(b);if(b.finalUrl.includes("/captcha?"))a.addEventListener("click",function(){window.open(b.finalUrl)}),a.firstChild.textContent="CAPTCHA",a.onclick=null;else if(b.finalUrl.includes("app/removed"))buttonError(a,"Removed!");else try{var h="http:"+(new DOMParser).parseFromString(b.response,"text/html").getElementsByClassName("mdl-button")[0].getAttribute("href");
a.firstChild.textContent="Ready!";openLink(h);a.onclick=function(){openLink(h)}}catch(f){buttonError(a,"Failed!"),console.log(f)}},onerror:function(){buttonError(a,"Offline!")}})}catch(b){buttonError(a,"Failed!"),console.log(b)}else if(c.includes("apkpure")){if(-1==ddlFinalApk(c,a,0))try{GM.xmlHttpRequest({method:"GET",url:c,onload:function(b){switch(b.status){case 410:buttonError(a,"Removed!");break;case 404:buttonError(a,"Not found!");break;default:b=b.responseText.substr(b.responseText.indexOf("https://download.apkpure.com/b/"),
b.responseText.length-1),b=b.substr(0,b.indexOf('"')),console.log(c),a.firstChild.textContent="Wait...",ddlFinalApk(b,a,0)}},onerror:function(){buttonError(a,"Offline!")}})}catch(b){buttonError(a,"Failed!"),console.log(b)}}else if(c.includes("apkcombo"))try{var e;GM.xmlHttpRequest({method:"POST",url:"https://apkcombo.com/checkin",headers:{Referer:c,Origin:"https://apkcombo.com"},onload:function(b){e=b.responseText;GM.xmlHttpRequest({method:"GET",url:c,onload:function(h){switch(h.status){case 410:buttonError(a,
"Removed!");break;case 404:buttonError(a,"Not found!");break;default:try{var f,m=(new DOMParser).parseFromString(h.responseText,"text/html").getElementsByClassName("file-list")[0];if(void 0!==m){var n=m.getElementsByTagName("a");for(f=0;f<n.length;f++){let d=n[f].getAttribute("href");if(d.startsWith("/r2?u="))try{window.open(decodeURIComponent(d).split("?u=")[1])}catch(l){console.log(l),buttonError(a,"Error!")}else window.open(d+"&"+e)}a.firstChild.textContent="APKCombo"}else{var p=h.responseText.indexOf("/dl?token=")+
4,q=h.responseText.indexOf('"',p),k=h.responseText.substring(p,q);c=h.finalUrl;GM.xmlHttpRequest({method:"POST",url:c.replace("/download/apk","/dl")+"?"+k,onload:function(d){m=(new DOMParser).parseFromString(d.responseText,"text/html").getElementsByClassName("file-list")[0];if(null!==m){d=m.getElementsByTagName("a");for(f=0;f<d.length;f++)window.open(d[f].getAttribute("href")+"&"+e);a.firstChild.textContent="APKCombo"}else a.addEventListener("click",function(){window.open(c)}),a.firstChild.textContent=
"New tab >",a.onclick=null},onerror:function(d){buttonError(a,"Error!")}})}}catch(d){console.log(d)}}},onerror:function(){buttonError(a,"Offline!")}})}})}catch(b){buttonError(a,"Failed!"),console.log(b)}else if(c.includes("apkpremier"))try{GM.xmlHttpRequest({method:"POST",url:c,data:"cmd=apk&gc=0",headers:{"Content-Type":"application/x-www-form-urlencoded"},onload:function(b){switch(b.status){case 410:buttonError(a,"Removed!");break;case 404:buttonError(a,"Not found!");break;default:let h=(new DOMParser).parseFromString(b.responseText,
"text/html").getElementsByClassName("bdlinks");if("error capchar"==b.responseText)a.addEventListener("click",function(){window.open(c)}),a.firstChild.textContent="CAPTCHA",a.onclick=null;else if(0<h.length){for(let f of h)window.open(f.firstElementChild.getAttribute("href"),"_self");a.firstChild.textContent="Ready!"}else a.firstChild.textContent="Failed!"}},onerror:function(){buttonError(a,"Offline!")}})}catch(b){buttonError(a,"Failed!"),console.log(b)}else if(c.includes("aptoide"))try{GM.xmlHttpRequest({method:"GET",
url:c,headers:{"Content-Type":"application/x-www-form-urlencoded"},onload:function(b){switch(b.status){case 410:buttonError(a,"Removed!");break;case 404:buttonError(a,"Not found!");break;default:if(b=JSON.parse(b.responseXML),0<b.datalist.total){let h=c.split("?query=")[1];for(let f of b.datalist.list)if(f.package===h){if(f.aab)for(let m of f.aab.splits)window.open(m.path);f.obb&&window.open(f.obb.main.path);openLink(b.datalist.list[0].file.path);a.firstChild.textContent="Ready!"}"Ready!"!=a.firstChild.textContent&&
buttonError(a,"Not found!")}else a.firstChild.textContent="Failed!"}},onerror:function(){buttonError(a,"Offline!")}})}catch(b){buttonError(a,"Failed!"),console.log(b)}else if(c.includes("apk.support"))try{GM.xmlHttpRequest({method:"POST",url:c,data:"cmd=csapk&pkg="+g+"&arch=default&tbi=default&device_id=&model=default&language=en&dpi=480&av=default",headers:{Referer:c,Origin:"https://apk.support","Content-Type":"application/x-www-form-urlencoded"},onload:function(b){if(b.responseXML){let h=b.responseXML.querySelectorAll("[href*='.androidcontents.com/']");
0==h.length&&(h=b.responseXML.querySelectorAll("[href*='.googleapis.com/download/']"));if(0<h.length){a.firstChild.textContent="Ready!";for(let f of h)window.open(f)}else buttonError(a,"Not found!")}},onerror:function(b){buttonError(a,"Error!")}})}catch(b){console.log(b)}}
function get2022UIButtons(){var a=document.querySelectorAll('[data-item-id^="%.@."]');if(0==a.length){a=document.querySelectorAll('[data-p^="%.@.["]');for(let c of a)if(c.querySelector("[fill-rule=evenodd]")&&c.getAttribute("data-p").includes('",7]]'))return c}console.log("Install buttons:");console.log(a);return a[0]}
function checkUI(){var a=0;try{a=0<document.getElementsByTagName("header").length?5:0}catch(c){console.error('The user interface of Google Play Store was not recognized by "Direct Download from Google Play" script. This might result in unexpected behaviour of the page. Please report the error to the author on Greasyfork. Error: '+c)}console.log("PLAY STORE INTERFACE: "+a);return a}function removePreviousCwiz(){appCwiz.parentNode.removeChild(appCwiz)}
function buttonError(a,c){a.firstChild.textContent=c;a.style.backgroundColor="#CCCCCC";a.onclick=null}async function setUseGS(a){useGS=a;GM.setValue("useGS",a)};
