// ==UserScript==
// @name         Bilibili international subtitle downloader
// @version      0.7.5
// @author       AdvMaple
// @match        /\:\/\/.*.bilibili.*\/(\w\/|)(play|video)\/.*$/
// @include      /\:\/\/.*.bilibili.*\/(\w\/|)(play|video)\/.*$/
// @icon         https://www.google.com/s2/favicons?domain=biliintl.com
// @updateURL https://raw.githubusercontent.com/siritami/test1/release/release/download.meta.js
// @grant        GM_addStyle

// ==/UserScript==
(function(){function H(a){const c=b=>(I.find(e=>e.id===b)||{}).label||"Unknown Codec",f=(b="")=>(e,g)=>e[b]<g[b]?1:e[b]>g[b]?-1:0;let d="";(a||J).sort(f("codec_id")).sort(f("id")).forEach(b=>{d+=`<option value="${b.id};${b.codec_id}" ${r===`${b.id}`&&t===`${b.codec_id}`?"selected":""}>[${c(b.codec_id)}] ${b.label} </option>`});return d}function z({ep_url:a,ep_title:c}){const f=document.createElement("a");f.textContent=c;f.href=a;f.download=`${c}.mp4`;f.type="video/mp4";document.getElementById("videoList").appendChild(f)}
function A({file_name:a,blob:c,file_format:f=l}){const d=document.createElement("a");d.download=`${a}.${p}.${f}`;d.textContent=`${a}`;d.href=URL.createObjectURL(c);document.getElementById("jsonSubtitleList").appendChild(d)}async function K({ep_id:a,video_id:c,ep_title:f}){a=await (await fetch(`https://api.bilibili.tv/intl/gateway/web/v2/subtitle?s_locale=${p}&platform=web&${0<a?`episode_id=${a}`:`aid=${c}`}`,{credentials:"include"})).text();if(B(a)){({data:a}=JSON.parse(a));null!==a.subtitles&&null!==
a.video_subtitle||alert("There is no suitable subtitle data");c=a.subtitles||a.video_subtitle||[];for(let b=0;b<c.length;b++)if(c[b].lang_key===p&&!d){var d=a.subtitles[b].url;const e=a.video_subtitle[b].srt?.url||d;d=["srt","ass"].includes(l)?a.video_subtitle[b][l]?.url||d||e:e}d?L({ep_title:f,ep_sub_url:d}):w("The language you selected, does not have subtitle files!")}else alert("Can't get subtitles data, please contact DEV")}function C({ep_id:a,season_id:c,video_id:f}){const d=0<f,b=0<a;fetch(`https://api.bilibili.tv/intl/gateway/web/playurl?${b||
0<c?b?`ep_id=${a}`:`season_id=${c}`:`aid=${f}`}&platform=web&device=wap&qn=64&tf=0&type=0`,{credentials:"include"}).then(e=>e.json()).then(({data:e})=>{b||d?(e=e.playurl.video.filter(g=>!!g.video_resource.url).map(g=>({codec_id:g.video_resource.codec_id,id:g.video_resource.quality,label:g.stream_info.desc_words})),e=H(e),document.getElementById("changeQuality").innerHTML=e):0<e?.sections?.length&&(e=e?.sections[0].episodes,0<e.length&&C(e[0].episode_id))})}function M({ep_id:a,video_id:c,ep_title:f}){fetch(`https://api.bilibili.tv/intl/gateway/web/playurl?${0<
a?`ep_id=${a}`:`aid=${c}`}&device=wap&platform=web&qn=64&tf=0&type=0`,{credentials:"include"}).then(d=>d.json()).then(({data:d})=>{var b=0,e=0;d=d.playurl;const g=Number(r),m=Number(t);var h=d.video.findIndex(u=>u.video_resource.quality===g&&u.video_resource.codec_id===m),k=!1;-1<h?(h=d.video[h].video_resource.url)?z({ep_url:h,ep_title:f}):k=!0:k=!0;if(k)for(k=0;k<d.video.length;k++)h=d.video[k].video_resource.url,""!==h&&b<d.video[k].video_resource.quality&&(b=d.video[k].video_resource.quality,z({ep_url:h,
ep_title:f}));for(b=0;b<d.audio_resource.length;b++)k=d.audio_resource[b].url,""!==k&&e<d.audio_resource[b].quality&&(e=d.audio_resource[b].quality,h=document.createElement("a"),h.textContent=`${f} `,h.href=k,h.download="audio_url",h.type="video/mp4",document.getElementById("audioList").appendChild(h))})}function D(){var a=(h=[],k="")=>{if(0<h.length)return h.findIndex(u=>u===k)},c=location.pathname.split("/");const f=location.pathname.includes("play"),d=location.pathname.includes("video"),b=a(c,
f?"play":"video");let e,g,m;f?(e=c[b+2],m=c[b+1],e=Number.parseInt(e)||void 0,m=Number.parseInt(m)||void 0):d&&(g=c[b+1],g=Number.parseInt(g)||void 0);if(!(0<e||0<g))if(f){if(c=document.body.querySelector(".video-play .ep-section .ep-list .ep-item--active")?.href?.split("?")?.shift()?.split("/")||[],0<c.length)a=a(c,"play"),e=c[a+2],e=Number.parseInt(e)||void 0;0<e||alert("Can't identify episode ID, please contact dev")}else alert("Can't identify video ID, please contact dev");return{ep_id:e,video_id:g,
season_id:m}}function v(){document.getElementById("jsonSubtitleList").innerHTML=`${q[n].subtitle}\&nbsp;:\&nbsp;`;document.getElementById("videoList").innerHTML=`${q[n].video}\&nbsp;:\&nbsp;`;document.getElementById("audioList").innerHTML=`${q[n].audio}\&nbsp;:\&nbsp;`;w("");var a=document.head.querySelector("[property='og:title'][content]")?.content?.replace(" HD | bilibili","");var c=document.body.querySelector(".video-play .video-play__meta .bstar-meta .bstar-meta__title")?.innerText,f=document.body.querySelector(".video-play .video-play__meta .bstar-meta .bstar-meta__extra .bstar-meta__origin-name .bstar-meta__origin-name-content")?.innerText,
d=document.body.querySelector(".video-play .video-play__meta .bstar-meta .bstar-meta__extra .bstar-meta__alias .bstar-meta__alias-content")?.innerText;a=a||c||d||f;c=document.title?.replace(" - BiliBili","")?.replace(`${a} `,"");c=document.body.querySelector(".video-play__breadcrumb .breadcrumb__item:last-child > .breadcrumb__item-text")?.innerText||c;f=c.split(" - ")[0];d=c.split(" - ")[1];let b=f?.replace(/[^0-9]/g,"");"string"===typeof b&&(b=Number.parseInt(b));a=0<=b?`E${`${b}`}${d?` - ${d}`:
""}`:`${f||a} - ${d||c}`;const {ep_id:e,video_id:g}=D();if(0<e||0<g)K({ep_id:e,video_id:g,ep_title:`${a} [${e||g}]`}),M({ep_id:e,video_id:g,ep_title:`${a} [${e||g}]`})}function N(a){const c=document.getElementById("snackbar");c.className="show";c.innerText=a;x&&=clearTimeout(x);x=setTimeout(function(){c.className=c.className.replace("show","")},3E3)}function w(a){document.getElementById("plugin_notice").innerText=a}const O=[{id:"en",label:"English"},{id:"th",label:"\u0e20\u0e32\u0e29\u0e32\u0e44\u0e17\u0e22"},
{id:"vi",label:"Ti\u1ebfng Vi\u1ec7t"},{id:"id",label:"Bahasa Indonesia"},{id:"ms",label:"Bahasa Melayu"},{id:"zh-Hans",label:"\u4e2d\u6587\uff08\u7b80\u4f53\uff09"},{id:"zh-Hant",label:"\u4e2d\u6587\uff08\u7e41\u4f53\uff09"}],P=["ass","srt","vtt","json"],I=[{id:7,label:"AVC"},{id:12,label:"HEVC"}],J=[{id:120,label:"4K"},{id:112,label:"1080P(HD)"},{id:80,label:"1080P"},{id:64,label:"720P"},{id:32,label:"480P"},{id:16,label:"320P"},{id:6,label:"240P"},{id:5,label:"144P"}],q={en:{gen_this_link:"Generate Links for this EP",
gen_links:"Generate Links",subtitle:"Subtitle",video:"Video",audio:"Audio"},th:{gen_this_link:"\u0e2a\u0e23\u0e49\u0e32\u0e07\u0e01\u0e32\u0e23\u0e14\u0e32\u0e27\u0e19\u0e4c\u0e42\u0e2b\u0e25\u0e14\u0e2a\u0e33\u0e2b\u0e23\u0e31\u0e1a EP \u0e19\u0e35\u0e49",gen_links:"\u0e2a\u0e23\u0e49\u0e32\u0e07\u0e01\u0e32\u0e23\u0e14\u0e32\u0e27\u0e19\u0e4c\u0e42\u0e2b\u0e25\u0e14",subtitle:"\u0e04\u0e33\u0e1a\u0e23\u0e23\u0e22\u0e32\u0e22",video:"\u0e27\u0e34\u0e14\u0e35\u0e42\u0e2d",audio:"\u0e40\u0e2a\u0e35\u0e22\u0e07"}};
let p=localStorage.getItem("SUB_LANGUAGE");p||(localStorage.setItem("SUB_LANGUAGE","en"),p="en");let l=localStorage.getItem("SUB_FORMAT");l||(localStorage.setItem("SUB_FORMAT","srt"),l="srt");let r=localStorage.getItem("VIDEO_QUALITY");r||(localStorage.setItem("VIDEO_QUALITY",112),r=112);let t=localStorage.getItem("VIDEO_CODEC");t||(localStorage.setItem("VIDEO_CODEC",12),t=12);let n=location.pathname.split("/")[1];Object.keys(q).includes(n)||(n="en");const {ep_id:E,video_id:F,season_id:G}=D();(0<
E||0<G||0<F)&&C({ep_id:E,season_id:G,video_id:F});let y=document.createElement("div");y.innerHTML=`
    <button id="down-this" class="btn" type="button"> ${q[n].gen_this_link} </button>

    <select id="changeLanguage" class="subtitleSelect" name="lang">
      ${(function(){return`${O.map(a=>`<option value="${a.id}" ${p===a.id?"selected":""}> ${a.label} </option>`)}`})()}
    </select>

    <select id="changeSubFormat" class="subtitleSelect" name="lang-format">
      ${(function(){return`${P.map(a=>`<option value="${a}" ${l===a?"selected":""}> ${a.toUpperCase()} </option>`)}`})()}
    </select>

    <select id="changeQuality" class="subtitleSelect" name="quality">

    </select>

    <div class="linkContainer" id="jsonSubtitleList">${q[n].subtitle}\&nbsp;:\&nbsp;</div>

    <div class="linkContainer" id="videoList" >${q[n].video}\&nbsp;:\&nbsp;</div>

    <div class="linkContainer" id="audioList" >${q[n].audio}\&nbsp;:\&nbsp;</div>

    <div id="plugin_notice"></div>

    <div id="snackbar"></div>
  `;y.setAttribute("id","downloadBiliintScript");document.body.appendChild(y);document.getElementById("down-this").addEventListener("click",v,!1);document.getElementById("changeLanguage").addEventListener("change",function(a){localStorage.setItem("SUB_LANGUAGE",a.target.value);p=a.target.value;v()},!1);document.getElementById("changeSubFormat").addEventListener("change",function(a){localStorage.setItem("SUB_FORMAT",a.target.value);l=a.target.value;v()},!1);document.getElementById("changeQuality").addEventListener("change",
function(a){const c=a.target.value.split(";");localStorage.setItem("VIDEO_QUALITY",c[0]);r=a.target.value;localStorage.setItem("VIDEO_CODEC",c[1]);t=a.target.value;v()},!1);const B=a=>{try{JSON.parse(a)}catch(c){return!1}return!0},L=async({ep_title:a,ep_sub_url:c})=>{var f=await (await fetch(c)).text();c="unknown format";let d=l;if(B(f)){c="json";f=JSON.parse(f);let b="";if("vtt"===l||"srt"===l||"ass"===l){const e=g=>{let m=new Date(0);return(new Date((new Date(1E3*g)).getTime()-m.getTime())).toISOString().split("T")[1].split("Z")[0]};
"vtt"===l&&(b+=`WEBVTT\nKind: captions\nLanguage: ${p}\n\n`);f.body.forEach((g,m)=>{const h=e(void 0!==g.from?g.from:0),k=e(g.to);b+=m+1+"\n";b+=`${h.replace(".",",")} --> ${k.replace(".",",")}\n`;b+=g.content+"\n\n"});f=new Blob([b],{type:`text/${"vtt"===l?"vtt":"plain"}`})}else f=new Blob([JSON.stringify(f)],{type:"application/json"});"ass"===l&&(d="srt",w(".ass format subtitles are not available, the plugin will automatically create subtitle links in .srt format!"));A({file_name:a,blob:f,file_format:d})}else f.includes("[V4+ Styles]")?
(c="ass",f=new Blob([f],{type:"text/plain"}),A({file_name:a,blob:f,file_format:d})):alert("Format subtitles .ass problematic, please contact DEV");N(`The server is returning ${c} file. The generated link is .${d} file`)};let x;GM_addStyle("\n\n    #downloadBiliintScript {\n      position: fixed;\n      bottom: 2.2vw;\n      left: 2.2vw;\n      z-index: 9999;\n      opacity: 0.97;\n      background: black;\n      padding: 16px;\n    }\n\n    #down-this {\n      background: #4c93ff;\n      margin-bottom: 16px;\n\n      color: white;\n      font-weight: 700;\n    }\n\n    .linkContainer {\n      margin-top: 16px;\n\n      color: black;\n      background: white;\n      opacity: 0.97;\n      border-radius: 20px;\n      padding: 8px;\n      font-size: 15px\n    }\n\n    .btn {\n      cursor: pointer;\n      padding: 3px;\n      opacity:0.97;\n      border-radius: 20px;\n      padding: 8px;\n    }\n\n    .btn:hover {\n      background-color: #6b9f25;\n      color: white;\n    }\n\n    #BtnContainer{\n      margin-top: 3px;\n      margin-bottom: 6px;\n      opacity: 0.97;\n    }\n\n    #mySortBtn {\n      cursor: pointer;\n      padding: 3px;\n      border-radius:20px;\n      width: 100%;\n      background-color: #23427f;\n      color: white;\n      opacity: 0.99;\n    }\n    #mySortBtn:hover {\n      background-color: #38548b;\n      color: #d3d9e5;\n    }\n\n    #downloadBiliintScript a {\n      color: #4c93ff;\n      background: white;\n      opacity: 0.97;\n    }\n\n    #downloadBiliintScript a:hover {\n      color: #4078cb;\n      background: white;\n      opacity: 0.97;\n    }\n\n    .subtitleSelect {\n      margin-right: 8px;\n\n      border-radius: 20px;\n      padding: 8px;\n      background: white;\n      opacity: 0.97;\n    }\n\n    #plugin_notice {\n      margin-top: 16px;\n\n      color: red;\n      font-size: 13px;\n      font-style: italic;\n    }\n    #plugin_notice:empty {\n      display: none;\n    }\n\n    #snackbar {\n      visibility: hidden;\n      min-width: 250px;\n      margin-left: -125px;\n      background-color: #333;\n      color: #fff;\n      text-align: center;\n      border-radius: 2px;\n      padding: 16px;\n      position: fixed;\n      z-index: 1;\n      left: 50%;\n      bottom: 30px;\n      font-size: 17px;\n    }\n\n    #snackbar.show {\n      visibility: visible;\n      -webkit-animation: fadein 0.5s, fadeout 0.5s 2.5s;\n      animation: fadein 0.5s, fadeout 0.5s 2.5s;\n    }\n\n    @-webkit-keyframes fadein {\n      from {bottom: 0; opacity: 0;}\n      to {bottom: 30px; opacity: 1;}\n    }\n\n    @keyframes fadein {\n      from {bottom: 0; opacity: 0;}\n      to {bottom: 30px; opacity: 1;}\n    }\n\n    @-webkit-keyframes fadeout {\n      from {bottom: 30px; opacity: 1;}\n      to {bottom: 0; opacity: 0;}\n    }\n\n    @keyframes fadeout {\n      from {bottom: 30px; opacity: 1;}\n      to {bottom: 0; opacity: 0;}\n    }\n")})();
