// ==UserScript==
// @name            计时器掌控者|视频广告跳过|视频广告加速器
// @name:en         TimerHooker
// @namespace       https://gitee.com/HGJing/everthing-hook/
// @version         1.0.62
// @include         *
// @require         https://greasyfork.org/scripts/372672-everything-hook/code/Everything-Hook.js?version=881251
// @author          Cangshi
// @match           http://*/*
// @run-at          document-start
// @grant           none
// @license         GPL-3.0-or-later
// @downloadURL https://raw.githubusercontent.com/siritami/test1/release/release/E8AEA1E697B6E599A8E68E8CE68EA7E880857CE8A786E9A291E5B9BFE5918AE8B7B3E8BF877CE8A786E9A291E5B9BFE5918AE58AA0E9809FE599A8.user.js
// @updateURL https://raw.githubusercontent.com/siritami/test1/release/release/E8AEA1E697B6E599A8E68E8CE68EA7E880857CE8A786E9A291E5B9BFE5918AE8B7B3E8BF877CE8A786E9A291E5B9BFE5918AE58AA0E9809FE599A8.meta.js
// ==/UserScript==
window.isDOMLoaded=!1;window.isDOMRendered=!1;document.addEventListener("readystatechange",function(){if("interactive"===document.readyState||"complete"===document.readyState)window.isDOMLoaded=!0});
~function(h){var u=[],p=[],q={},r=function(f,c,k){return{applyUI:function(){var b=(1/c._percentage).toFixed(2);b='<div class="_th-container">\n    <div class="_th-click-hover _item-input">\n        x'+b+'\n    </div>\n    <div class="_th-item _item-x2">&gt;</div>\n    <div class="_th-item _item-x-2">&lt;</div>\n    <div class="_th-item _item-xx2">&gt;&gt;</div>\n    <div class="_th-item _item-xx-2">&lt;&lt;</div>\n    <div class="_th-item _item-reset">O</div>\n</div>\n<div class="_th_cover-all-show-times _th_hidden">\n    <div class="_th_times">x'+b+
"</div>\n</div>";var a=document.createElement("style");a.setAttribute("type","text/css");if(a.styleSheet)a.styleSheet.cssText="._th-container ._th-item{margin-bottom:3px;position:relative;width:0;height:0;cursor:pointer;opacity:.3;background-color:aquamarine;border-radius:100%;text-align:center;line-height:30px;-webkit-transition:all .35s;-o-transition:all .35s;transition:all .35s;right:30px}._th-container ._th-item,._th-container ._th-click-hover,._th_cover-all-show-times ._th_times{-webkit-box-shadow:-3px 4px 12px -5px black;box-shadow:-3px 4px 12px -5px black}._th-container:hover ._th-item._item-x2{margin-left:18px;width:40px;height:40px;line-height:40px}._th-container:hover ._th-item._item-x-2{margin-left:17px;width:38px;height:38px;line-height:38px}._th-container:hover ._th-item._item-xx2{width:36px;height:36px;margin-left:16px;line-height:36px}._th-container:hover ._th-item._item-xx-2{width:32px;height:32px;line-height:32px;margin-left:14px}._th-container:hover ._th-item._item-reset{width:30px;line-height:30px;height:30px;margin-left:10px}._th-click-hover{position:relative;-webkit-transition:all .5s;-o-transition:all .5s;transition:all .5s;height:45px;width:45px;cursor:pointer;opacity:.3;border-radius:100%;background-color:aquamarine;text-align:center;line-height:45px;right:0}._th-container:hover{left:-5px}._th-container{font-size:12px;-webkit-transition:all .5s;-o-transition:all .5s;transition:all .5s;left:-35px;top:20%;position:fixed;-webkit-box-sizing:border-box;box-sizing:border-box;z-index:100000;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none}._th-container ._th-item:hover{opacity:.8;background-color:#5fb492;color:aliceblue}._th-container ._th-item:active{opacity:.9;background-color:#1b3a26;color:aliceblue}._th-container:hover ._th-click-hover{opacity:.8}._th-container:hover ._th-item{opacity:.6;right:0}._th-container ._th-click-hover:hover{opacity:.8;background-color:#5fb492;color:aliceblue}._th_cover-all-show-times{position:fixed;top:0;right:0;width:100%;height:100%;z-index:99999;opacity:1;font-weight:900;font-size:30px;color:#4f4f4f;background-color:rgba(0,0,0,0.1)}._th_cover-all-show-times._th_hidden{z-index:-99999;opacity:0;-webkit-transition:1s all;-o-transition:1s all;transition:1s all}._th_cover-all-show-times ._th_times{width:300px;height:300px;border-radius:50%;background-color:rgba(127,255,212,0.51);text-align:center;line-height:300px;position:absolute;top:50%;right:50%;margin-top:-150px;margin-right:-150px}";
else{var d=document.createTextNode("._th-container ._th-item{margin-bottom:3px;position:relative;width:0;height:0;cursor:pointer;opacity:.3;background-color:aquamarine;border-radius:100%;text-align:center;line-height:30px;-webkit-transition:all .35s;-o-transition:all .35s;transition:all .35s;right:30px}._th-container ._th-item,._th-container ._th-click-hover,._th_cover-all-show-times ._th_times{-webkit-box-shadow:-3px 4px 12px -5px black;box-shadow:-3px 4px 12px -5px black}._th-container:hover ._th-item._item-x2{margin-left:18px;width:40px;height:40px;line-height:40px}._th-container:hover ._th-item._item-x-2{margin-left:17px;width:38px;height:38px;line-height:38px}._th-container:hover ._th-item._item-xx2{width:36px;height:36px;margin-left:16px;line-height:36px}._th-container:hover ._th-item._item-xx-2{width:32px;height:32px;line-height:32px;margin-left:14px}._th-container:hover ._th-item._item-reset{width:30px;line-height:30px;height:30px;margin-left:10px}._th-click-hover{position:relative;-webkit-transition:all .5s;-o-transition:all .5s;transition:all .5s;height:45px;width:45px;cursor:pointer;opacity:.3;border-radius:100%;background-color:aquamarine;text-align:center;line-height:45px;right:0}._th-container:hover{left:-5px}._th-container{font-size:12px;-webkit-transition:all .5s;-o-transition:all .5s;transition:all .5s;left:-35px;top:20%;position:fixed;-webkit-box-sizing:border-box;box-sizing:border-box;z-index:100000;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none}._th-container ._th-item:hover{opacity:.8;background-color:#5fb492;color:aliceblue}._th-container ._th-item:active{opacity:.9;background-color:#1b3a26;color:aliceblue}._th-container:hover ._th-click-hover{opacity:.8}._th-container:hover ._th-item{opacity:.6;right:0}._th-container ._th-click-hover:hover{opacity:.8;background-color:#5fb492;color:aliceblue}._th_cover-all-show-times{position:fixed;top:0;right:0;width:100%;height:100%;z-index:99999;opacity:1;font-weight:900;font-size:30px;color:#4f4f4f;background-color:rgba(0,0,0,0.1)}._th_cover-all-show-times._th_hidden{z-index:-99999;opacity:0;-webkit-transition:1s all;-o-transition:1s all;transition:1s all}._th_cover-all-show-times ._th_times{width:300px;height:300px;border-radius:50%;background-color:rgba(127,255,212,0.51);text-align:center;line-height:300px;position:absolute;top:50%;right:50%;margin-top:-150px;margin-right:-150px}");
a.appendChild(d)}var e=document.createElement("div");e.innerHTML=b;var g={"_item-input":function(){changeTime()},"_item-x2":function(){changeTime(2,0,!0)},"_item-x-2":function(){changeTime(-2,0,!0)},"_item-xx2":function(){changeTime(0,2)},"_item-xx-2":function(){changeTime(0,-2)},"_item-reset":function(){changeTime(0,0,!1,!0)}};Object.keys(g).forEach(function(l){var m=g[l];if(l=e.getElementsByClassName(l)[0])l.onclick=m});h.isDOMLoaded?(document.head.appendChild(a),document.body.appendChild(e),h.isDOMRendered=
!0,console.log("Time Hooker Works!")):document.addEventListener("readystatechange",function(){"interactive"!==document.readyState&&"complete"!==document.readyState||h.isDOMRendered||(document.head.appendChild(a),document.body.appendChild(e),h.isDOMRendered=!0,console.log("Time Hooker Works!"))})},applyGlobalAction:function(b){b.changeTime=function(a,d,e,g){if(g)h.timer.change(1);else if(h.timer){if(a||d)if(e&&a){if(1>=1/c._percentage&&0>a)return;a=1/(1/c._percentage+a)}else 0>=d&&(d=1/-d),a=1/(1/
c._percentage*d);else{a=prompt("\u8f93\u5165\u6b32\u6539\u53d8\u8ba1\u65f6\u5668\u53d8\u5316\u500d\u7387\uff08\u5f53\u524d\uff1a"+1/c._percentage+"\uff09");if(null==a)return;if(isNaN(parseFloat(a))){alert("\u8bf7\u8f93\u5165\u6b63\u786e\u7684\u6570\u5b57");b.changeTime();return}if(0>=parseFloat(a)){alert("\u500d\u7387\u4e0d\u80fd\u5c0f\u4e8e\u7b49\u4e8e0");b.changeTime();return}a=1/parseFloat(a)}b.change(a)}};h.changeTime=b.changeTime},applyHooking:function(){var b=this;f.hookReplace(window,"setInterval",
function(e){return b.getHookedTimerFunction("interval",e)});f.hookReplace(window,"setTimeout",function(e){return b.getHookedTimerFunction("timeout",e)});f.hookBefore(window,"clearInterval",function(e,g){b.redirectNewestId(g)});f.hookBefore(window,"clearTimeout",function(e,g){b.redirectNewestId(g)});var a=this.getHookedDateConstructor();f.hookClass(window,"Date",a,"_innerDate",["now"]);Date.now=function(){return(new Date).getTime()};f.hookedToString(c._Date.now,Date.now);var d=Object.prototype.toString;
Object.prototype.toString=function(){return this instanceof c._mDate?"[object Date]":d.call(this)};f.hookedToString(d,Object.prototype.toString);f.hookedToString(c._setInterval,setInterval);f.hookedToString(c._setTimeout,setTimeout);f.hookedToString(c._clearInterval,clearInterval);c._mDate=window.Date;this.hookShadowRoot()},getHookedDateConstructor:function(){return function(){if(1===arguments.length)Object.defineProperty(this,"_innerDate",{configurable:!1,enumerable:!1,value:new c._Date(arguments[0]),
writable:!1});else if(1<arguments.length){switch(arguments.length){case 2:var b=new c._Date(arguments[0],arguments[1]);break;case 3:b=new c._Date(arguments[0],arguments[1],arguments[2]);break;case 4:b=new c._Date(arguments[0],arguments[1],arguments[2],arguments[3]);break;case 5:b=new c._Date(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4]);break;case 6:b=new c._Date(arguments[0],arguments[1],arguments[2],arguments[3],arguments[4],arguments[5]);break;default:case 7:b=new c._Date(arguments[0],
arguments[1],arguments[2],arguments[3],arguments[4],arguments[5],arguments[6])}Object.defineProperty(this,"_innerDate",{configurable:!1,enumerable:!1,value:b,writable:!1})}else b=(c._Date.now()-c.__lastDatetime)*(1/c._percentage),Object.defineProperty(this,"_innerDate",{configurable:!1,enumerable:!1,value:new c._Date(c.__lastMDatetime+b),writable:!1})}},getHookedTimerFunction:function(b,a){var d="_"+b+"Ids";return function(){var e=c.genUniqueId(),g=arguments[0];"string"===typeof g&&(g+=";timer.notifyExec("+
e+")",arguments[0]=g);"function"===typeof g&&(arguments[0]=function(){var v=g.apply(this,arguments);c.notifyExec(e);return v});var l=arguments[1];arguments[1]*=c._percentage;var m=a.apply(window,arguments);c[d][m]={args:arguments,originMS:l,originId:m,nowId:m,uniqueId:e,oldPercentage:c._percentage,exceptNextFireTime:c._Date.now()+l};return m}},redirectNewestId:function(b){var a=b[0];c._intervalIds[a]&&(b[0]=c._intervalIds[a].nowId,delete c._intervalIds[a]);c._timeoutIds[a]&&(b[0]=c._timeoutIds[a].nowId,
delete c._timeoutIds[a])},registerShortcutKeys:function(b){addEventListener("keydown",function(a){switch(a.keyCode){case 57:(a.ctrlKey||a.altKey)&&b.changeTime();break;case 190:case 187:a.ctrlKey?b.changeTime(2,0,!0):a.altKey&&b.changeTime(0,2);break;case 188:case 189:a.ctrlKey?b.changeTime(-2,0,!0):a.altKey&&b.changeTime(0,-2);break;case 48:(a.ctrlKey||a.altKey)&&b.changeTime(0,0,!1,!0)}})},percentageChangeHandler:function(b){k.ergodicObject(c,c._intervalIds,function(a,d){a.args[1]=Math.floor((a.originMS||
1)*b);this._clearInterval.call(window,a.nowId);a.nowId=this._setInterval.apply(window,a.args)});k.ergodicObject(c,c._timeoutIds,function(a,d){d=this._Date.now();var e=a.oldPercentage,g=a.exceptNextFireTime-d;0>g&&(g=0);e=Math.floor(b/e*g);a.args[1]=e;a.exceptNextFireTime=d+e;a.oldPercentage=b;this._clearTimeout.call(window,a.nowId);a.nowId=this._setTimeout.apply(window,a.args)})},hookShadowRoot:function(){var b=Element.prototype.attachShadow;f.hookAfter(Element.prototype,"attachShadow",function(a,
d,e){p.push(e);return e},!1);f.hookedToString(b,Element.prototype.attachShadow)},hookDefine:function(){const b=this;f.hookBefore(Object,"defineProperty",function(a,d){b.hookDefineDetails(d[0],d[1],d[2]).forEach((e,g)=>{d[g]=e})});f.hookBefore(Object,"defineProperties",function(a,d){var e=d[1],g=d[0];g&&g instanceof Element&&Object.keys(e).forEach(l=>{var m=b.hookDefineDetails(g,l,e[l]);d[0]=m[0];delete e[l];e[m[1]]=m[2]})})},hookDefineDetails:function(b,a,d){d&&b&&b instanceof Element&&"string"===
typeof a&&0<=a.indexOf("on")&&(d.configurable=!0);b instanceof HTMLVideoElement&&"playbackRate"===a&&(d.configurable=!0,console.warn("[Timer Hook]","\u5df2\u963b\u6b62\u9ed8\u8ba4\u64cd\u4f5c\u89c6\u9891\u500d\u7387"),a="playbackRate_hooked");return[b,a,d]},suppressEvent:function(b,a){b&&(delete b["on"+a],delete b["on"+a],delete b["on"+a],b["on"+a]=void 0);q[a]||(f.hookBefore(EventTarget.prototype,"addEventListener",function(d,e){a===e[0]&&(console.warn(a,"event suppressed."),e[0]+="suppressed")},
!1),q[a]=!0)},changePlaybackRate:function(b,a){delete b.playbackRate;delete b.playbackRate;delete b.playbackRate;b.playbackRate=a;1!==a&&c.defineProperty.call(Object,b,"playbackRate",{configurable:!0,get:function(){return 1},set:function(){}})}}},n={isInIframe:function(){let f=h.parent!==h;try{f=f&&"FRAMESET"!==h.parent.document.body.tagName}catch(c){}return f},listenParentEvent:function(f){h.addEventListener("message",function(c){c=c.data;"changePercentage"===(c.type||"")&&f(c.percentage||0)})},
sentChangesToIframe:function(f){var c=document.querySelectorAll("iframe")||[],k=document.querySelectorAll("frame");if(c.length)for(var b=0;b<c.length;b++)c[b].contentWindow.postMessage({type:"changePercentage",percentage:f},"*");if(k.length)for(c=0;c<k.length;c++)k[c].contentWindow.postMessage({type:"changePercentage",percentage:f},"*")}},t=function(f,c,k){var b=f.querySelectorAll(c);b=Array.prototype.slice.call(b||[]);k&&p.forEach(function(a){b=b.concat(t(a,c,!1))});return b},w=function(){return function(f){u.forEach(function(b){f.urlMatching(location.href,
"http.*://.*"+b+".*")&&(window.Worker=void 0,console.log("Worker disabled"))});var c=this,k={_intervalIds:{},_timeoutIds:{},_auoUniqueId:1,__percentage:1,_setInterval:window.setInterval,_clearInterval:window.clearInterval,_clearTimeout:window.clearTimeout,_setTimeout:window.setTimeout,_Date:window.Date,__lastDatetime:(new Date).getTime(),__lastMDatetime:(new Date).getTime(),videoSpeedInterval:1E3,defineProperty:Object.defineProperty,defineProperties:Object.defineProperties,genUniqueId:function(){return this._auoUniqueId++},
notifyExec:function(b){var a=this;b&&Object.values(this._timeoutIds).filter(function(d){return d.uniqueId===b}).forEach(function(d){a._clearTimeout.call(window,d.nowId);delete a._timeoutIds[d.originId]})},init:function(){var b=this,a=r(c,b,f);a.hookDefine();a.applyHooking();Object.defineProperty(b,"_percentage",{get:function(){return b.__percentage},set:function(d){if(d===b.__percentage)return d;a.percentageChangeHandler(d);return b.__percentage=d}});n.isInIframe()?(console.log("[TimeHooker]","loading inner window..."),
n.listenParentEvent(function(d){console.log("[TimeHooker]","Inner Changed",d);this.change(d)}.bind(this))):(console.log("[TimeHooker]","loading outer window..."),a.applyUI(),a.applyGlobalAction(b),a.registerShortcutKeys(b))},change:function(b){this.__lastMDatetime=this._mDate.now();this.__lastDatetime=this._Date.now();this._percentage=b;var a=document.getElementsByClassName("_th-click-hover"),d=document.getElementsByClassName("_th_times"),e=(1/this._percentage).toFixed(2);(a[0]||{}).innerHTML="x"+
e;(d[0]||{}).innerHTML="x"+e;var g=document.getElementsByClassName("_th_cover-all-show-times")[0]||{};g.className="_th_cover-all-show-times";this._setTimeout.bind(window)(function(){g.className="_th_cover-all-show-times _th_hidden"},100);this.changeVideoSpeed();n.sentChangesToIframe(b)},changeVideoSpeed:function(){var b=r(c,this,f),a=1/this._percentage;16<a&&(a=16);.065>a&&(a=.065);var d=t(document,"video",!0)||[];if(d.length)for(var e=0;e<d.length;e++)b.changePlaybackRate(d[e],a)}};k.init();return k}};
h.eHook&&h.eHook.plugins({name:"timer",mount:w()})}(window);
