// ==UserScript==
// @name        Flickr Original Link
// @namespace   https://greasyfork.org/scripts/1190-flickr-original-link
// @include 	/flickr\.com/
// @version	6.0
// @grant       GM_getValue
// @grant       GM_setValue
// @grant 	GM_addStyle
// @require 	https://code.jquery.com/jquery-3.3.1.min.js
// @downloadURL https://raw.githubusercontent.com/siritami/test1/release/release/Flickr20Original20Link.user.js
// @updateURL https://raw.githubusercontent.com/siritami/test1/release/release/Flickr20Original20Link.meta.js
// ==/UserScript==
var postfix="_d.jpg",prefix="DOWNLOAD ",isChecked_openLink="",isChecked_alwaysShow="",key_openLink="flickr_openLink",key_alwaysShow="flickr_alwaysShow",value_openLink=!1,value_alwaysShow=!1,imageSizeOrder="9k 8k 7k 6k 5k 4k 3k 2k o k h l b c z".split(" "),globalObserver=null;function log(a){console.log(a)}log("Begin flickr script");
function getSetting(){log("Begin get settings");value_openLink=GM_getValue(key_openLink,!1);value_alwaysShow=GM_getValue(key_alwaysShow,!1);value_openLink?(postfix=".",isChecked_openLink=' checked="checked" ',prefix="OPEN "):(postfix="_d.",isChecked_openLink="",prefix="DOWNLOAD ");isChecked_alwaysShow=value_alwaysShow?' checked="checked" ':""}function checkAlwaysShow(){value_alwaysShow&&$("div.interaction-view").css("opacity","1");$("div.interaction-bar").css("bottom","1.1em")}
function action_single_page(){if(0<$(".commonButton").length)return!1;$.get(document.URL,function(a){var c=a.match(/modelExport: {.+?"sizes":{.+?}}/i);a=c[0].match(/"width":"?\d+"?,"height":"?\d+"?,/ig);c=c[0].match(/"displayUrl":"[^"]+"/ig);for(var d=c.length,b=0;b<d;b++)a[b]=a[b].replace(/"width":(\d+),"height":(\d+),/i,"$1 x $2"),c[b]=c[b].replace(/"displayUrl":"([^"]+)"/i,"$1").replace(/\\/g,"").replace(/(_[0-9a-z]+)\.([a-z]{3,4})/i,"$1"+postfix+"$2");var e=$(".sub-photo-right-row1").filter(":first"),
g='<div><a class="commonButton bigButton" href="'+c[d-1]+'">'+prefix+a[d-1]+" px</a>";for(b=d-2;b>=d-7&&0<=b;--b)g+='<a class="commonButton smallButton" href="'+c[b]+'">'+a[b]+" px</a>";e.prop("outerHTML",g+"</div>"+e.prop("outerHTML"))})}
function getLinkFromSource(a){if(null!==a){var c=a.match(/"sizes":.+?}}/ig);if(null===c)return!1;a=a.match(/"datePosted":"\d+"/ig);null==a&&log("cannot find any dates");var d=$("div.photo-list-photo-view");"album"==type&&(d=$("div.photo-card-view div.foot"));log("Number of photo in this page: "+d.length);for(var b=0;b<d.length;b++){var e=$(d[b]);if(!(0<e.find(".myFuckingLink").filter(":first").length)){e.html(e.html()+'<a class="myFuckingLink"></a>');for(var g=0;g<imageSizeOrder.length;++g){var f=
c[b].match(new RegExp('"'+imageSizeOrder[g]+'".*?:{"displayUrl":"([^"]+)","width":(\\d+),"height":(\\d+)',"i"));if(null!==f){e=e.find(".myFuckingLink");e.attr("href",f[1].replace(/\\/g,"").replace(/(_[0-9a-z]+)\.([a-z]{3,4})/i,"$1"+postfix+"$2"));g=a[b].match(/\d+/i);g=new Date(1E3*new Number(g));e.attr("title",prefix+f[2]+" x "+f[3]+" | Upload: "+g.toLocaleDateString());e.html(prefix+f[2]+" x "+f[3]);break}}}}}}
function action_normal_page(a){var c=$("#content")[0],d="none",b=0,e=null,g=function(f){var h=$("div.photo-list-photo-view");"album"==f&&(h=$("div.photo-card-view"));if(document.URL==d){if(h.length==b)return!1;checkAlwaysShow();b=h.length;log("Number of thumb: "+b);getLinkFromSource(e)}else{f=h.find("a").filter(":first");if(1>f.length)return!1;checkAlwaysShow();e=null;d=document.URL;f=f.attr("href");console.time("GetSource");$("#content").append('<div id="loadingIndicator" style="position:fixed;left:5px;bottom:2em;display:block;background-color:pink;border:solid;padding:3px">Getting original link<br>Please wait...</div>');
log("Begin get source 1: "+f);$.get(f,function(l){var k=l.match(/<a\s+class=.+?entry-type.+?href='([^']+)/i)[1];k=k.replace("/albums/","/sets/");log("Begin get source 2: "+k);$.get(k,function(m){log("Got final source: "+k);console.timeEnd("GetSource");$("#loadingIndicator").remove();e=m;getLinkFromSource(e)})})}};g(a);globalObserver=new MutationObserver(function(f,h){g(a)});globalObserver.observe(c,{childList:!0,subtree:!0})}
function flickr_mouseenter(){var a=$(this);if(0<a.find(".myFuckingLink").filter(":first").length)return a.off("mouseenter"),!1;var c=a.find("a").filter(":first").attr("href");if("undefined"==typeof c||null===c)return!1;a.append('<a class="myFuckingLink">(Link loading...)</a>');$.get(c,function(d){var b=d.match(/"displayUrl":"([^"]+)","width":(\d+),"height":(\d+)[^}]+}}/i);d=b[1].replace(/\\/g,"").replace(/(_[0-9a-z]+)\.([a-z]{3,4})/i,"$1"+postfix+"$2");b=prefix+b[2]+" x "+b[3]+" Upload: ";var e=a.find(".myFuckingLink");
e.attr("href",d);e.attr("title",b);e.html(b)})}function action_hover_page(){var a=$("body")[0],c=0;globalObserver=new MutationObserver(function(d,b){d=$("div.photo-list-photo-view");if(d.length==c)return!1;log("Number of thumb: "+d.length);c=d.length;checkAlwaysShow();d.mouseenter(flickr_mouseenter)});globalObserver.observe(a,{childList:!0,subtree:!0})}
function pageType(){var a="none",c=$("html").attr("class");console.log("HTML class: "+c);null!==c.match(/html-photo-page.+scrappy-view/i)?a="single":null!==c.match(/html-(search-photos-unified|group-pool)-page-view/i)?a="hover":0<$("div.photo-list-photo-view").filter(":first").length?a="normal":0<$("div.photo-list-view").filter(":first").length&&(a="album");console.log("Page type: "+a);return a}var prevType="none",type="none",oldUrl="none",count=0;
function kickStart(){oldUrl=document.URL;type=pageType();getSetting();checkAlwaysShow();var a=".myFuckingLink{position:absolute;z-index:999999;left:3px;bottom:0px;width:100%;display:block;color:white!important;} .myFuckingLink:hover{background-color:rgba(100, 100, 255,0.65)!important} .commonButton{display: inline-block;border-radius: 0.5em;margin: 0.2em;padding: 0.5em;font-size: 90%;height: fit-content;} .bigButton{background-color: lightgreen} .smallButton{background-color:pink}";"album"==type&&
(a=".myFuckingLink{position:absolute;z-index:999999;left:5px;bottom:0px;width:100%;display:block;} .myFuckingLink:hover{background-color:rgba(100, 100, 255,0.65)!important} .commonButton{display: inline-block;border-radius: 0.5em;margin: 0.2em;padding: 0.5em;font-size: 90%;height: fit-content;} .bigButton{background-color: lightgreen} .smallButton{background-color:pink}");GM_addStyle(a);$(".myOptionBox").remove();$("ul.nav-menu:first").append('<li class="myOptionBox"><div style="color:pink;padding:1px"><input id="optionbox_openLink" type="checkbox"'+
isChecked_openLink+'style="margin:2px"/>Open image link in browser<br><input id="optionbox_alwaysShow" type="checkbox"'+isChecked_alwaysShow+'style="margin:2px"/>Always show image information in Photostream</div></li>');$("#optionbox_openLink").change(function(){GM_setValue(key_openLink,$(this).prop("checked"))});$("#optionbox_alwaysShow").change(function(){GM_setValue(key_alwaysShow,$(this).prop("checked"))});"single"==type?action_single_page():"normal"==type||"album"==type?action_normal_page(type):
"hover"==type&&action_hover_page()}log("Kickstart");var timestamp="1469473824",number=new Number(timestamp),t=new Date(1E3*number);log("Time number: "+t.toLocaleDateString("vi-VN"));kickStart();var target=$("html")[0],config={childList:!1,attributes:!0},observer=new MutationObserver(function(a,c){oldUrl!=document.URL&&(null!==globalObserver&&globalObserver.disconnect(),kickStart())});observer.observe(target,config);
