// ==UserScript==
// @name       HTML5视频播放工具
// @name:en	   HTML5 Video Playing Tools
// @homepage https://bbs.kafan.cn/thread-2093014-1-1.html
// @match    https://*.qq.com/*
// @exclude  https://user.qzone.qq.com/*
// @match    https://www.weiyun.com/video_*
// @match    https://v.youku.com/v*
// @match    https://m.youku.com/*
// @match    https://vku.youku.com/live/*
// @match    https://video.tudou.com/v/*
// @match    https://www.iqiyi.com/*
// @match    https://live.bilibili.com/*
// @match    https://www.bilibili.com/*
// @match    https://www.ixigua.com/*
// @match    https://www.toutiao.com/video/*
// @match    https://www.acfun.cn/*
// @match    https://live.acfun.cn/live/*
// @match    http://v.pptv.com/show/*
// @match    https://v.pptv.com/show/*
// @match    https://www.miguvideo.com/*
// @match    https://tv.sohu.com/*
// @match    https://film.sohu.com/album/*
// @match    https://www.mgtv.com/*
// @match    https://movie.douban.com/subject/*
// @version    2.0.1
// @match    https://pan.baidu.com/*
// @match    https://yun.baidu.com/*
// @match    https://*.163.com/*
// @match    https://*.icourse163.org/*
// @match    http://video.sina.*/*
// @match    https://video.sina.*/*
// @match    http://k.sina.*/*
// @match    https://k.sina.*/*
// @match    https://weibo.com/*
// @match    https://*.weibo.com/*
// @match    https://pan.baidu.com/*
// @match    https://yun.baidu.com/*
// @match    http://v.ifeng.com/*
// @match    https://v.ifeng.com/*
// @match    http://news.mtime.com/*
// @match    http://video.mtime.com/*
// @GM_info
// @match    https://www.youtube.com/*
// @match    https://www.ted.com/talks/*
// @match    https://www.twitch.tv/*
// @inject-into content
// @match    https://www.yy.com/*
// @match    https://www.huya.com/*
// @match    https://v.douyu.com/*
// @match    https://www.douyu.com/*
// @match    https://live.douyin.com/*
// @match    https://www.douyin.com/*

// @match    https://www.longzhu.com/*
// @match    https://www.zhanqi.tv/*
// @run-at     document-start
// @require    https://cdn.jsdelivr.net/npm/vue@2.7.16/dist/vue.min.js
// @require    https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.min.js
// @grant      GM_addStyle
// @include    */play*
// @include    *play/*
// @exclude    https://www.dj92cc.net/dance/play/id/*
// @grant      window.onurlchange
// @grant      unsafeWindow
// @grant      GM_registerMenuCommand
// @grant      GM_setValue
// @grant      GM_getValue
// @namespace  https://greasyfork.org/users/7036
// @license    MIT
// @downloadURL https://raw.githubusercontent.com/siritami/test1/release/release/HTML5E8A786E9A291E692ADE694BEE5B7A5E585B7.user.js
// @updateURL https://raw.githubusercontent.com/siritami/test1/release/release/HTML5E8A786E9A291E692ADE694BEE5B7A5E585B7.meta.js
// ==/UserScript==
const curLang=navigator.language.slice(0,2),i18n={zh:{console:"%c\u811a\u672c[%s] \u53cd\u9988\uff1a%s\n%s",cacheStoringError:"\u76f4\u63a5\u5a92\u4f53\u7c7b\u578b\uff08\u5982MP4\u683c\u5f0f\uff09\u7f13\u5b58\u65e0\u6548\u679c\uff01",cacheStoringConfirm:"\u89c6\u9891\u5207\u7247\u6570\u636e\u80fd\u5426\u7f13\u5b58\uff1f\u68c0\u6d4b\u65b9\u6cd5\uff1a\u5237\u65b0\u9875\u9762\uff0c\u5df2\u89c2\u770b\u89c6\u9891\u7247\u6bb5\u4e0d\u4ea7\u751f\u7f51\u7edc\u6d41\u91cf\u5219\u53ef\u7f13\u5b58\u3002\u5982\u679c\u80fd\u7f13\u5b58\u89c6\u9891\u5207\u7247\uff0c\u9009\u62e9\u786e\u8ba4\u76f4\u63a5\u7f13\u5b58\u5168\u90e8\u89c6\u9891\u65f6\u6bb5\uff1b\u70b9\u53d6\u6d88\u5219\u6309\u9ed8\u8ba4\u7f13\u51b2\u533a\u5927\u5c0f\u8fdb\u884c\u7f13\u51b2\u3002",
cantOpenPIP:"\u65e0\u6cd5\u8fdb\u5165\u753b\u4e2d\u753b\u6a21\u5f0f!\u9519\u8bef:\n",cantExitPIP:"\u65e0\u6cd5\u9000\u51fa\u753b\u4e2d\u753b\u6a21\u5f0f!\u9519\u8bef\uff1a\n",rememberRateMenuOption:"\u8bb0\u5fc6\u64ad\u653e\u901f\u5ea6",speedRate:"\u64ad\u653e\u901f\u5ea6 ",ready:"\u51c6\u5907\u5c31\u7eea\uff01 \u5f85\u547d\u4e2d.",mainPageOnly:"\u53ea\u5904\u7406\u4e3b\u9875\u9762",download:"\u4e0b\u8f7d: ",videoLag:"\u89c6\u9891\u5361\u987f",fullScreen:"\u5168\u5c4f",helpMenuOption:"\u811a\u672c\u529f\u80fd\u5feb\u6377\u952e\u8868",
helpBody:"\u53cc\u51fb\uff1a\u5207\u6362\uff08\u7f51\u9875\uff09\u5168\u5c4f         \u9f20\u6807\u4e2d\u952e\uff1a\u5feb\u8fdb5\u79d2\n\nP\uff1a\u89c6\u9891\u622a\u56fe    i\uff1a\u5207\u6362\u753b\u4e2d\u753b   M\uff1a(\u505c\u6b62)\u7f13\u5b58\u89c6\u9891(hls.js)\n\u2190 \u2192\u65b9\u5411\u952e\uff1a\u5feb\u9000\u3001\u5feb\u8fdb5\u79d2;   \u65b9\u5411\u952e + shift: 20\u79d2\n\u2191 \u2193\u65b9\u5411\u952e\uff1a\u97f3\u91cf\u8c03\u8282   ESC\uff1a\u9000\u51fa\uff08\u7f51\u9875\uff09\u5168\u5c4f\n\u7a7a\u683c\u952e\uff1a\u6682\u505c/\u64ad\u653e      N\uff1a\u64ad\u653e\u4e0b\u4e00\u96c6\n\u56de\u8f66\u952e\uff1a\u5207\u6362\u5168\u5c4f;      \u56de\u8f66\u952e + shift: \u5207\u6362\u7f51\u9875\u5168\u5c4f\nC(\u6296\u97f3\u3001youtube\u7528V\u952e)\uff1a\u52a0\u901f0.1\u500d  X(\u6296\u97f3S)\uff1a\u51cf\u901f0.1\u500d  Z(\u6296\u97f3A)\uff1a\u5207\u6362\u52a0\u901f\u72b6\u6001\nD\uff1a\u4e0a\u4e00\u5e27     F\uff1a\u4e0b\u4e00\u5e27(youtube.com\u7528E\u952e)"},
en:{console:"%cScript[%s] Feedback\uff1a%s\n%s",cacheStoringError:"Trying to cache direct media types (such as MP4 format) has no effect!",cacheStoringConfirm:"Do you want all segments of the video to be cached? The detection method used is as follows: when the page is refreshed, the watched video clips will be cached so that no additional network traffic is generated. If you want all segments of the videos to be cached, select OK; or select Cancel to buffer a portion of the video based on the default buffer size (which is the default browser behavior).",
cantOpenPIP:"Unable to access picture-in-picture mode! Error\uff1a\n",cantExitPIP:"Unable to exit picture-in-picture mode! Error\uff1a\n",rememberRateMenuOption:"Remember video playback speed",speedRate:"Speed rate ",ready:" ready\uff01 Waiting for you commands.",mainPageOnly:"Process the main page only",download:"Download: ",videoLag:"Video lag",fullScreen:"Full screen",helpMenuOption:"Hotkeys list:",helpBody:"Double-click: activate full screen.\nMiddle mouse button: fast forward 5 seconds\n\nP key\uff1a Take a screenshot\nI key\uff1a Enter/Exit picture-in-picture mode\nM key\uff1a Enable/disable caching of video(hls.js)\n\nArrow keys \u2190 and \u2192\uff1a Fast forward or rewind by 5 seconds\nShift + Arrow keys \u2190 and \u2192\uff1a Fast forward or rewind 20 seconds\nArrow keys \u2191 and \u2193\uff1a Raise or lower the volume\n\nESC\uff1a Exit full screen (or exit video enlarged to window size)\nSpacebar\uff1a Stop/Play\nEnter\uff1a Enable/disable full screen video\nShift + Enter: Set/unset video enlarged to window size\n\nN key\uff1a Play the next video (if any)\nC key(YouTube:V key)\uff1a Speed up video playback by 0.1\nX key: Slow down video playback by 0.1\nZ key, Set video playback speed: 1.0 \u2190\u2192 X\nD key: Previous frame\nF key: Next frame (except on YouTube)\nE key: Next frame (YouTube only)"},
it:{console:"%cScript[%s] Feedback\uff1a%s\n%s",cacheStoringError:"Cercare di memorizzazione nella cache tipi di media diretti (come ad esempio il formato MP4) non ha alcuna efficacia!",cacheStoringConfirm:"Vuoi che tutti i segmenti del video siano memorizzati nella cache? Il metodo di rilevamento utilizzato \u00e8 il seguente: all'aggiornamento della pagina, i video clip guardati saranno memorizzati nella cache in modo da non generare ulteriore traffico di rete. Se vuoi che tutti i segmenti dei video siano memorizzati nella cache, seleziona OK; seleziona invece Annulla per bufferizzare una parte del video in base alla dimensione predefinita del buffer (come da comportamento predefinito del browser).",
cantOpenPIP:"Impossibile accedere alla modalit\u00e0 picture-in-picture! Errore\uff1a\n",cantExitPIP:"Impossibile uscire dalla modalit\u00e0 picture-in-picture! Errore\uff1a\n",rememberRateMenuOption:"Memorizza la velocit\u00e0 di riproduzione dei video",speedRate:"Velocit\u00e0 di riproduzione ",ready:"Pronto\uff01 In attesa dei comandi dell'utente.",mainPageOnly:"Elaborazione della sola pagina principale",download:"Scarica: ",videoLag:"Ritardo del video",fullScreen:"Schermo intero",helpMenuOption:"Elenco dei tasti di scelta rapida",
helpBody:"Doppio clic: attiva lo schermo intero\nPulsante centrale del mouse: avanzamento rapido di 5 secondi\n\nTasto P: Esegui uno screenshot\nTasto I\uff1a Attiva modalit\u00e0 picture-in-picture\nTasto M\uff1a Attiva/disattiva memorizzazione del video nella cache(hls.js)\n\nTasti freccia \u2190 e \u2192\uff1a Avanza o riavvolgi di 5 secondi\nShift + Tasti freccia \u2190 e \u2192: Avanza o riavvolgi di 20 secondi\nTasti freccia \u2191 e \u2193\uff1a Alza o abbassa il volume\nESC\uff1a Esci da schermo intero\nBarra spaziatrice: Ferma/Riproduci\nInvio\uff1a Attiva/disattiva ingrandimento del video a schermo intero\nShift + Invio: Attiva/disattiva ingrandimento del video a dimensione della finestra\n\nTasto N\uff1a Riproduzione del video successivo (se presente)\nTasto C(YouTube: Tasto V): Velocizza riproduzione video di 0,1\nTasto X: Rallenta riproduzione video di 0,1\nTasto Z, Impostare la velocit\u00e0 di riproduzione video: 1,0 \u2190\u2192 X\nTasto D: Vai al frame precedente\nTasto F: Vai al frame successivo (escluso YouTube)\nTasto E: Vai al frame successivo (solo su YouTube)"}},
MSG=i18n[curLang]||i18n.en,w=unsafeWindow||window,{host,pathname:path}=location,d=document,find=[].find;let $msg,v,_fp,_fs,by;
const observeOpt={childList:!0,subtree:!0},noopFn=function(){},validEl=a=>a&&1<a.offsetWidth,q=(a,b=d)=>b.querySelector(a),r1=(a,b)=>a.test(b)&&RegExp.$1,log=console.log.bind(console,MSG.console,"color:#c3c;font-size:1.2em",GM_info.script.name,GM_info.script.homepage),gmFuncOfCheckMenu=(a,b,c=!0)=>{const e=GM_getValue(b,c);e&&(a="\u221a  "+a);GM_registerMenuCommand(a,()=>{GM_setValue(b,!e);location.reload()});return e},sleep=a=>new Promise(b=>{setTimeout(b,a)}),hookAttachShadow=a=>{try{const b=Element.prototype.attachShadow;
Element.prototype.attachShadow=function(c){c.mode="open";c=b.call(this,c);a(c);return c}}catch(b){console.error("Hack attachShadow error",b)}},getStyle=(a,b)=>{if(a.style[b])return a.style[b];if(getComputedStyle)return a=getComputedStyle(a,""),b=b.replace(/([A-Z])/g,"-$1").toLowerCase(),a&&a.getPropertyValue(b)},doClick=a=>{"string"===typeof a&&(a=q(a));a&&(a.click?a.click():a.dispatchEvent(new MouseEvent("click")))},clickDualButton=a=>{a.nextElementSibling&&"none"===getStyle(a,"display")?doClick(a.nextElementSibling):
doClick(a)},polling=(a,b,c=!0)=>{const e="string"===typeof b?q.bind(null,b):b,f=setInterval(()=>{e()&&(c&&clearInterval(f),a())},300);return f},goNextMV=()=>{const a=location.pathname,b=a.match(/(\d+)(\D*)$/),c=+b[1]+1;location.assign(a.slice(0,b.index)+c+b[2])},firefoxVer=r1(/Firefox\/(\d+)/,navigator.userAgent),isEdge=/ Edge?\//.test(navigator.userAgent),fakeUA=a=>Object.defineProperty(navigator,"userAgent",{value:a,writable:!1,configurable:!1,enumerable:!0}),getMainDomain=a=>{a=a.split(".");let b=
a.length-2;/^(com?|cc|tv|net|org|gov|edu)$/.test(a[b])&&b--;return a[b]},inRange=(a,b,c)=>Math.max(b,a)==Math.min(a,c),adjustRate=a=>{a+=v.playbackRate;v.playbackRate=.1>a?.1:16<a?16:+a.toFixed(2)},adjustVolume=a=>{a+=v.volume;inRange(a,0,1)&&(v.volume=+a.toFixed(2))},tip=a=>{$msg?.get(0)?.offsetHeight||($msg=$('<div style="max-width:455px;min-width:333px;background:#EEE;color:#111;height:22px;top:-30px;left:50%;transform:translate(-50%, 0); border-radius:8px;border:1px solid orange;text-align:center;font-size:15px;position:fixed;z-index:2147483647"></div>').appendTo(by));
if(a?.length){var b=15*a.length;$msg.stop(!0,!0).text(a).css({width:`${b}px`}).animate({top:"190px"}).animate({top:"+=9px"},1900).animate({top:"-30px"})}},u=getMainDomain(host),cfg={isLive:!1,disableDBLClick:!1,isClickOnVideo:!1,multipleV:!1,isNumURL:!1},bus=new Vue;
void 0===window.onurlchange&&(history.pushState=(a=>function(){const b=a.apply(this,arguments);window.dispatchEvent(new Event("pushstate"));window.dispatchEvent(new Event("urlchange"));return b})(history.pushState),history.replaceState=(a=>function(){const b=a.apply(this,arguments);window.dispatchEvent(new Event("replacestate"));window.dispatchEvent(new Event("urlchange"));return b})(history.replaceState),window.addEventListener("popstate",()=>{window.dispatchEvent(new Event("urlchange"))}));
class FullScreen{constructor(a){let b=d.exitFullscreen||d.webkitExitFullscreen||d.mozCancelFullScreen||d.msExitFullscreen||noopFn;this.exit=b.bind(d);b=a.requestFullscreen||a.webkitRequestFullScreen||a.mozRequestFullScreen||a.msRequestFullScreen||noopFn;this.enter=b.bind(a)}static isFull(){return!!(d.fullscreen||d.webkitIsFullScreen||d.mozFullScreen||d.fullscreenElement||d.webkitFullscreenElement||d.mozFullScreenElement)}toggle(){FullScreen.isFull()?this.exit():this.enter()}}
class FullPage{constructor(a){this._isFull=!1;this.container=a||FullPage.getPlayerContainer(v);GM_addStyle(".gm-fp-body .gm-fp-zTop {\n\t\t\t\tposition: relative !important;\n\t\t\t\tz-index: 2147483646 !important;\n\t\t\t}\n\t\t\t.gm-fp-wrapper, .gm-fp-body{ overflow:hidden !important; }\n\t\t\t.gm-fp-wrapper .gm-fp-innerBox {\n\t\t\t\twidth: 100% !important;\n\t\t\t\theight: 100% !important;\n\t\t\t}\n\t\t\t.gm-fp-wrapper {\n\t\t\t\tdisplay: block !important;\n\t\t\t\tposition: fixed !important;\n\t\t\t\twidth: 100% !important;\n\t\t\t\theight: 100% !important;\n\t\t\t\tpadding: 0 !important;\n\t\t\t\tmargin: 0 !important;\n\t\t\t\ttop: 0 !important;\n\t\t\t\tleft: 0 !important;\n\t\t\t\tbackground: #000 !important;\n\t\t\t\tz-index: 2147483646 !important;\n\t\t\t}")}static getPlayerContainer(a){let b=
a.parentNode;const {clientWidth:c,clientHeight:e}=a;do a=b,b=a.parentNode;while(b&&b!==by&&5>b.clientWidth-c&&5>b.clientHeight-e);return a}static isFull(a){return 5>w.innerWidth-a.clientWidth&&5>w.innerHeight-a.clientHeight}toggle(){this.container.contains(v)||(this.container=FullPage.getPlayerContainer(v));bus.$emit("switchFP",!this._isFull);by.classList.toggle("gm-fp-body");let a=v;for(;a!=this.container;)a.classList.toggle("gm-fp-innerBox"),a=a.parentNode;a.classList.toggle("gm-fp-wrapper");for(a=
a.parentNode;a!=by;)a.classList.toggle("gm-fp-zTop"),a=a.parentNode;this._isFull=!this._isFull}}
const cacheMV={check(){const a=v.buffered;this.iEnd=a.end(a.length-1);return this.mode?this.iEnd>v.duration-55:a.start(0)>=this.playPos||this.iEnd>v.duration-55},finish(){v.removeEventListener("canplaythrough",this.onChache);v.currentTime=this.playPos;this.chached=!1;setTimeout(a=>v.pause(),99);HTMLMediaElement.prototype.play=this.rawPlay},onChache(){this.check()?this.finish():v.currentTime=this.iEnd},exec(){!cfg.isLive&&v&&(v.src.startsWith("http")?alert(MSG.cacheStoringError):(this.mode=confirm(MSG.cacheStoringConfirm),
this.chached=!0,v.pause(),this.rawPlay=HTMLMediaElement.prototype.play,HTMLMediaElement.prototype.play=()=>new Promise(noopFn),this.playPos=v.currentTime,v.addEventListener("canplaythrough",this.onChache),this.check(),v.currentTime=this.iEnd))}};cacheMV.onChache=cacheMV.onChache.bind(cacheMV);const actList=new Map;
actList.set(90,a=>{v.playbackRate=1==v.playbackRate||0==v.playbackRate?+localStorage.mvPlayRate||1.3:1}).set(88,adjustRate.bind(null,-.1)).set(67,adjustRate.bind(null,.1)).set(40,adjustVolume.bind(null,-.1)).set(38,adjustVolume.bind(null,.1)).set(37,a=>{v.currentTime-=5}).set(1061,a=>{v.currentTime-=20}).set(39,a=>{v.currentTime+=5}).set(1063,a=>{v.currentTime+=20}).set(68,a=>{v.currentTime-=.03;v.pause()}).set(70,a=>{v.currentTime+=.03;v.pause()}).set(32,a=>{cfg.btnPlay?clickDualButton(cfg.btnPlay):
v.paused?v.play():v.pause()}).set(13,a=>{_fs?_fs.toggle():clickDualButton(cfg.btnFS)}).set(1037,a=>{self!=top?top.postMessage({id:"gm-h5-toggle-iframeWebFull"},"*"):_fp?_fp.toggle():clickDualButton(cfg.btnFP)}).set(1051,noopFn).set(27,a=>{FullScreen.isFull()?_fs?_fs.exit():clickDualButton(cfg.btnFS):self!=top?top.postMessage({id:"gm-h5-is-iframeWebFull"},"*"):FullPage.isFull(v)&&(_fp?_fp.toggle():clickDualButton(cfg.btnFP))}).set(73,a=>{d.pictureInPictureElement?d.exitPictureInPicture().catch(b=>
{alert(MSG.cantExitPIP+b)}):v.requestPictureInPicture().catch(b=>{alert(MSG.cantOpenPIP+b)})}).set(80,a=>{a=d.createElement("canvas");a.width=v.videoWidth;a.height=v.videoHeight;a.getContext("2d").drawImage(v,0,0,a.width,a.height);a.toBlob(async b=>{b=URL.createObjectURL(b);const c=d.createElement("a");c.onclick=e=>{e.stopPropagation()};c.href=b;c.download=Date.now().toString(36)+".png";c.style.display="none";d.body.appendChild(c);c.click();c.remove();await sleep(500);URL.revokeObjectURL(b)})}).set(77,
a=>{cacheMV.chached?cacheMV.finish():cacheMV.exec()}).set(78,a=>{self!=top?top.postMessage({id:"gm-h5-play-next"},"*"):cfg.btnNext?doClick(cfg.btnNext):cfg.isNumURL&&goNextMV()});
const app={rawProps:new Map,shellEvent(){const a=c=>{c.target.closest("svg,img,button")||(c.stopPropagation(),c.stopImmediatePropagation(),this.checkUI(),actList.get(1037)())},b=cfg.isClickOnVideo?v:cfg.mvShell;b.addEventListener("mousedown",c=>{1==c.button&&(c.preventDefault(),c.stopPropagation(),c.stopImmediatePropagation(),cfg.isLive||(actList.has(39)?actList.get(39)():v.currentTime+=5))});!cfg.disableDBLClick&&b.addEventListener("dblclick",a)},setShell(){const a=this.getDPlayer()||this.getArtplayer()||
this.getVjsPlayer()||cfg.shellCSS&&q(cfg.shellCSS)||(top!=self?by:FullPage.getPlayerContainer(v));a&&cfg.mvShell!==a&&(cfg.mvShell=a,this.shellEvent())},checkMV(){if(this.vList){const a=this.findMV();a&&a!=v&&(v=a,cfg.btnPlay=cfg.btnNext=cfg.btnFP=cfg.btnFS=_fs=_fp=null,!cfg.isLive&&GM_getValue("remberRate",!0)&&(v.playbackRate=+localStorage.mvPlayRate||1,v.addEventListener("ratechange",b=>{v.playbackRate&&1!=v.playbackRate&&(localStorage.mvPlayRate=v.playbackRate)})),this.setShell())}validEl(cfg.mvShell)||
(cfg.mvShell=null,this.setShell());this.checkUI();return v},getArtplayer(){const a=v.parentNode;if(!v.matches(".art-video")||!a.matches(".art-video-player"))return!1;cfg.btnFP=q(".art-control-fullscreenWeb",a);cfg.btnFS=q(".art-control-fullscreen",a);a.closest("body > *")?.classList.add("gm-dp-zTop");return a},getDPlayer(){if(!v.matches(".dplayer-video"))return!1;const a=v.closest(".dplayer");a&&(cfg.btnFP=q(".dplayer-full-in-icon > span",a),cfg.btnFS=q(".dplayer-full-icon",a),a.closest("body > *").classList.add("gm-dp-zTop"));
return a},getVjsPlayer(){const a=v.closest(".video-js");a&&(cfg.btnFS=q(".vjs-control-bar > button.vjs-button:nth-last-of-type(1)"),cfg.webfullCSS='.vjs-control-bar > button.vjs-button[title$="\u5168\u5c4f"]:nth-last-of-type(2)');return a},hotKey(a){var b=a.target;a.ctrlKey||a.metaKey||a.altKey||"true"==b.contentEditable||/INPUT|TEXTAREA|SELECT/.test(b.nodeName)||a.shiftKey&&![13,37,39].includes(a.keyCode)||a.shiftKey&&27==a.keyCode||!this.checkMV()||!a.shiftKey&&cfg.mvShell&&cfg.mvShell.contains(b)&&
[32,37,39].includes(a.keyCode)||(b=a.shiftKey?a.keyCode+1024:a.keyCode,actList.has(b)&&(a.stopImmediatePropagation(),a.stopPropagation(),a.preventDefault(),actList.get(b)(a),[67,88,90].includes(a.keyCode)&&tip(MSG.speedRate+v.playbackRate)))},checkUI(){cfg.webfullCSS&&!validEl(cfg.btnFP)&&(cfg.btnFP=q(cfg.webfullCSS));cfg.btnFP?_fp=null:_fp||self!=top||(_fp=new FullPage(cfg.mvShell));cfg.fullCSS&&!validEl(cfg.btnFS)&&(cfg.btnFS=q(cfg.fullCSS));cfg.btnFS?_fs=null:_fs||=new FullScreen(v);!cfg.nextCSS||
validEl(cfg.btnNext)&&cfg.btnNext.matches(cfg.nextCSS)||(cfg.btnNext=q(cfg.nextCSS));cfg.playCSS&&!validEl(cfg.btnPlay)&&(cfg.btnPlay=q(cfg.playCSS))},onGrowVList(){if(this.vList.length!=this.vCount){if(this.viewObserver)for(let a of this.vList)this.vSet.has(a)||this.viewObserver.observe(a);else{this.viewObserver=new IntersectionObserver(this.onIntersection.bind(this),{rootMargin:"0px",threshold:.9});for(let a of this.vList)this.viewObserver.observe(a)}this.vSet=new Set(this.vList);this.vCount=this.vList.length}},
onIntersection(a){2>this.vList.length||(a=find.call(a,b=>b.isIntersecting))&&v!=a.target&&(v=a.target,_fs=new FullScreen(v),_fp=new FullPage(v),bus.$on("switchFP",async b=>{sleep(200);b||v.scrollIntoView()}),bus.$emit("switchMV"))},bindEvent(){clearInterval(this.timer);for(const [b,c]of this.rawProps)Reflect.defineProperty(HTMLVideoElement.prototype,b,c);this.rawProps.clear();this.rawProps=void 0;by=d.body;v=v||this.findMV();log("bind event\n",v);bus.$emit("foundMV");const a=gmFuncOfCheckMenu(MSG.rememberRateMenuOption,
"remberRate");window.addEventListener("urlchange",async b=>{await sleep(1990);this.checkMV();a&&(v.playbackRate=+localStorage.mvPlayRate||1);bus.$emit("urlchange")});top!=self&&(top.postMessage({id:"gm-h5-init-MVframe"},"*"),window.addEventListener("message",b=>{if(b.source&&b.data&&b.data.id)switch(b.data.id){case "gm-h5-toggle-fullScreen":_fs?_fs.toggle():clickDualButton(cfg.btnFS)}},!1));$(v).one("canplay",b=>{cfg.isLive=cfg.isLive||Infinity==v.duration;if(cfg.isLive)for(const c of[37,1061,39,
1063,78,77,88,67,90])actList.delete(c);else a&&(v.playbackRate=+localStorage.mvPlayRate||1),v.addEventListener("ratechange",c=>{a&&v.playbackRate&&1!=v.playbackRate&&(localStorage.mvPlayRate=v.playbackRate)});this.checkMV();bus.$emit("canplay")});$(by).keydown(this.hotKey.bind(this));cfg.mvShell?this.shellEvent():this.setShell();this.checkUI();cfg.multipleV&&((new MutationObserver(this.onGrowVList.bind(this))).observe(by,observeOpt),this.vCount=0,this.onGrowVList())},init(){const a=EventTarget.prototype.addEventListener;
EventTarget.prototype.addEventListener=function(...c){if(!(this instanceof HTMLMediaElement&&"dblclick"==c[0]&&!c[1].toString().includes("actList.get(1037)")||"ratechange"==c[0]&&"baidu"==u&&!c[1].toString().includes("localStorage.mvPlayRate")))return a.apply(this,c)};for(const c of this.rawProps.keys())this.rawProps.set(c,Reflect.getOwnPropertyDescriptor(HTMLMediaElement.prototype,c));this.vList=d.getElementsByTagName("video");const b=c=>cfg.cssMV?c.matches(cfg.cssMV):9<c.offsetWidth;this.findMV=
find.bind(this.vList,b);this.timer=polling(c=>{v=c;this.bindEvent()},this.findMV);hookAttachShadow(async c=>{bus.$emit("addShadowRoot",c);await sleep(600);!v&&(v=q("video",c))&&(log("Found MV in ShadowRoot\n",v,c),cfg.shellCSS||(cfg.mvShell=c.host),this.bindEvent(),this.vList=c.getElementsByTagName("video"),this.findMV=find.bind(this.vList,b))})}},router={ted(){cfg.fullCSS="button[title=Fullscreen]"},youtube(){GM_addStyle(".gm-fp-body #player-container-inner{padding-top:0!important}\n\t\t\t.gm-fp-body #player-container-outer{\n\t\t\t\tmax-width:100%!important;\n\t\t\t\tmargin:0!important;\n\t\t\t}");
cfg.shellCSS="#player";cfg.playCSS="button.ytp-play-button";cfg.nextCSS="a.ytp-next-button";cfg.fullCSS="button.ytp-fullscreen-button";cfg.isClickOnVideo=!0;actList.delete(32);actList.set(69,actList.get(70)).delete(70);actList.set(86,actList.get(67)).delete(67)},douyin(){cfg.isLive=host.startsWith("live.");cfg.fullCSS=".xgplayer-fullscreen";cfg.isLive||(GM_addStyle(".xgplayer-progress-cache{background-color:green!important}"),actList.set(65,actList.get(90)).delete(90),actList.set(83,actList.get(88)).delete(88),
actList.set(86,actList.get(67)).delete(67))},qq(){if(self!=top&&("v.qq.com"==host||"video.qq.com"==host))throw MSG.mainPageOnly;actList.delete(32);cfg.shellCSS="#player";cfg.nextCSS=".txp_btn_next_u";cfg.webfullCSS=".txp_btn_fake";cfg.fullCSS=".txp_btn_fullscreen";app.rawProps.set("playbackRate",1);for(let a=37;40>=a;a++)actList.delete(a)},youku(){actList.delete(37);actList.delete(39);host.startsWith("vku.")?(bus.$on("canplay",()=>{cfg.isLive=!q(".spv_progress")}),cfg.fullCSS=".live_icon_full"):(bus.$on("foundMV",
()=>{$(document).unbind("keyup")}),cfg.shellCSS="#ykPlayer",cfg.webfullCSS=".kui-webfullscreen-icon-0",cfg.fullCSS=".kui-fullscreen-icon-0",cfg.nextCSS=".kui-next-icon-0")},bilibili(){cfg.isLive=host.startsWith("live.");cfg.isLive||(actList.delete(32),bus.$on("addShadowRoot",a=>{"BWP-VIDEO"===a.host.nodeName&&(app.vList=d.getElementsByTagName("bwp-video"),app.findMV=find.bind(app.vList,b=>9<b.offsetWidth),v=a.host,app.bindEvent())}),cfg.shellCSS="#bilibili-player",cfg.nextCSS=".bpx-player-ctrl-next",
cfg.webfullCSS=".bpx-player-ctrl-web",cfg.fullCSS=".bpx-player-ctrl-full")},iqiyi(){cfg.fullCSS=".iqp-btn-fullscreen:not(.fake__click)";cfg.nextCSS=".iqp-btn-next"},pptv(){cfg.fullCSS=".w-zoom-container > div";cfg.webfullCSS=".w-expand-container > div";cfg.nextCSS=".w-next"},mgtv(){cfg.fullCSS="mango-screen";cfg.webfullCSS="mango-webscreen > a";cfg.nextCSS="mango-control-playnext-btn"},ixigua(){cfg.fullCSS='div[aria-label="\u5168\u5c4f"]';cfg.nextCSS=".xgplayer-control-item.control_playnext";GM_addStyle(".gm-fp-body .xgplayer{padding-top:0!important} .gm-fp-wrapper #player_default{max-height: 100%!important} h1.title~a, .videoTitle h1~a{ padding-left:12px; color:blue; }")},
miguvideo(){cfg.nextCSS=".next-btn";cfg.fullCSS=".zoom-btn";cfg.shellCSS=".mod-player"},baidu(){app.rawProps.set("playbackRate",1)},weibo(){cfg.multipleV=path.startsWith("/u/")},acfun(){cfg.nextCSS=".btn-next-part .control-btn";cfg.webfullCSS=".fullscreen-web";cfg.fullCSS=".fullscreen-screen"},["163"](){cfg.multipleV=host.startsWith("news.");GM_addStyle("div.video,video{max-height: 100% !important;}");return 3<host.split(".").length},sohu(){cfg.nextCSS="li.on[data-vid]+li a";cfg.fullCSS=".x-fullscreen-btn";
cfg.webfullCSS=".x-pagefs-btn"},fun(){cfg.nextCSS=".btn-item.btn-next"},le(){GM_addStyle(".gm-fp-body .le_head{display:none!important}");cfg.cssMV="#video video";cfg.shellCSS="#video";cfg.nextCSS=".hv_ico_next";const a=b=>{v.offsetWidth||Object.values(v.attributes).reverse().some(c=>{if(""==v.getAttribute(c.name))return v.removeAttribute(c.name),!0})};bus.$on("urlchange",a);bus.$once("canplay",a)},agedm(){actList.set(78,a=>{location.href=location.href.replace(/\d+$/,b=>++b)})},nnyy(){GM_registerMenuCommand(MSG.videoLag,
()=>{v.pause();const a=v.currentTime,b=v.buffered;v.currentTime=b.end(b.length-1)+1;$(v).one("progress",c=>{v.currentTime=a;v.play()})});cfg.nextCSS=".playlist .on + li a"},douban(){cfg.nextCSS="a.next-series"},douyu(){cfg.isLive=!host.startsWith("v.");cfg.isLive?(cfg.cssMV=".layout-Player video",cfg.shellCSS="#js-player-video",cfg.webfullCSS=".wfs-2a8e83",cfg.fullCSS=".fs-781153",cfg.playCSS="div[class|=play]","/"!=path&&$(a=>{q(".u-specialStateInput").checked=!0})):bus.$on("addShadowRoot",async function(a){a.host.matches("#demandcontroller-bar")&&
(await sleep(600),cfg.shellCSS="div[fullscreen].video",cfg.btnFP=q(".ControllerBar-PageFull",a),cfg.btnFS=q(".ControllerBar-WindowFull",a))})},yy(){cfg.isLive=!path.startsWith("/x/");cfg.isLive&&(cfg.fullCSS=".yc__fullscreen-btn",cfg.webfullCSS=".yc__cinema-mode-btn",cfg.playCSS=".yc__play-btn")},huya(){if(firefoxVer&&57>firefoxVer)return!0;cfg.disableDBLClick=!0;cfg.webfullCSS=".player-fullpage-btn";cfg.fullCSS=".player-fullscreen-btn";cfg.playCSS="#player-btn";polling(doClick,".login-tips-close");
localStorage["sidebar/ads"]="{}";localStorage["sidebar/state"]=0},twitch(){cfg.isLive=!path.startsWith("/videos/");cfg.fullCSS="button[data-a-target=player-fullscreen-button]";cfg.webfullCSS=".player-controls__right-control-group > div:nth-child(4) > button";cfg.playCSS="button[data-a-target=player-play-pause-button]"},longzhu(){cfg.fullCSS="a.ya-screen-btn"},zhanqi(){localStorage.lastPlayer="h5";cfg.fullCSS=".video-fullscreen"}};Reflect.defineProperty(navigator,"plugins",{get(){return{length:0}}});
GM_registerMenuCommand(MSG.helpMenuOption,alert.bind(w,MSG.helpBody));router[u]&&router[u]()||app.init();router[u]||cfg.isNumURL||(cfg.isNumURL=/[_\W]\d+(\/|\.[a-z]{3,8})?$/.test(path));
