// ==UserScript==
// @name               IG Helper
// @namespace          https://github.snkms.com/
// @version            3.1.1
// @author             SN-Koarashi (5026)
// @match              https://*.instagram.com/*
// @grant              GM_info
// @grant              GM_addStyle
// @grant              GM_setValue
// @grant              GM_getValue
// @grant              GM_xmlhttpRequest
// @grant              GM_registerMenuCommand
// @grant              GM_unregisterMenuCommand
// @grant              GM_getResourceText
// @grant              GM_notification
// @grant              GM_openInTab
// @connect            i.instagram.com
// @connect            raw.githubusercontent.com
// @require            https://code.jquery.com/jquery-3.7.1.min.js#sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=
// @resource           INTERNAL_CSS https://raw.githubusercontent.com/SN-Koarashi/ig-helper/master/style.css
// @resource           LOCALE_MANIFEST https://raw.githubusercontent.com/SN-Koarashi/ig-helper/master/locale/manifest.json
// @supportURL         https://github.com/SN-Koarashi/ig-helper/
// @contributionURL    https://ko-fi.com/snkoarashi
// @icon               https://www.google.com/s2/favicons?domain=www.instagram.com&sz=32
// @compatible         firefox >= 100
// @compatible         chrome >= 100
// @compatible         edge >= 100
// @license            GPL-3.0-only
// @run-at             document-idle
// @downloadURL https://raw.githubusercontent.com/siritami/test1/release/release/IG20Helper.user.js
// @updateURL https://raw.githubusercontent.com/siritami/test1/release/release/IG20Helper.meta.js
// ==/UserScript==
(function(a){async function la(){w(!0);var b=(new Date).getTime();let c=Math.floor(b/1E3);b=location.href.replace(/\/$/ig,"").split("/").at(-1);let e=await S(b),f=e.data.reels_media[0].owner.username,d=0;E(d,e.data.reels_media[0].items.length);e.data.reels_media[0].items.forEach((g,h)=>{setTimeout(()=>{q.RENAME_PUBLISH_DATE&&(c=g.taken_at_timestamp);g.display_resources.sort(function(l,p){return l.config_width<p.config_width?1:l.config_width>p.config_width?-1:0});g.is_video?x(g.video_resources[0].src,
f,"stories",c,"mp4",g.id).then(()=>{E(++d,e.data.reels_media[0].items.length)}):x(g.display_resources[0].src,f,"stories",c,"jpg",g.id).then(()=>{E(++d,e.data.reels_media[0].items.length)})},100*h)})}async function N(b,c){var e=a('body > div section:visible a[href^="/"]').filter(function(){return 1===a(this).attr("href").split("/").filter(h=>0<h.length).length}).first().attr("href").split("/").filter(h=>0<h.length).at(0);if(b){e=(new Date).getTime();b=Math.floor(e/1E3);let h=location.href.replace(/\/$/ig,
"").split("/").at(-1);var f=a("body > div section._ac0a header._ac0k > ._ac3r ._ac3n ._ac3p[style]").length||a("body > div section:visible > div > div:not([class]) > div > div div.x1ned7t2.x78zum5 div.x1caxmr6").length||a("body > div div:not([hidden]) section:visible > div div[style]:not([class]) > div").find("div div.x1ned7t2.x78zum5 div.x1caxmr6").length,d=0;w(!0);if(k.GL_dataCache.highlights[h]){m("Fetch from memory cache:",h);var g=k.GL_dataCache.highlights[h].data.reels_media[0].items.length;
e=k.GL_dataCache.highlights[h].data.reels_media[0].owner.username;d=k.GL_dataCache.highlights[h].data.reels_media[0].items[g-f]}else g=await S(h),d=g.data.reels_media[0].items.length,e=g.data.reels_media[0].owner.username,d=g.data.reels_media[0].items[d-f],k.GL_dataCache.highlights[h]=g;m("onHighlightsStory",h,k.GL_dataCache.highlights[h]);q.RENAME_PUBLISH_DATE&&(b=d.taken_at_timestamp);q.FORCE_RESOURCE_VIA_MEDIA&&!k.tempFetchRateLimit?(f=await J(d.id),"ok"===f.status?f.items[0].video_versions?c?
A(f.items[0].video_versions[0].url):x(f.items[0].video_versions[0].url,e,"highlights",b,"mp4",f.items[0].id):c?A(f.items[0].image_versions2.candidates[0].url):x(f.items[0].image_versions2.candidates[0].url,e,"highlights",b,"jpg",f.items[0].id):(q.USE_BLOB_FETCH_WHEN_MEDIA_RATE_LIMIT?(delete k.GL_dataCache.highlights[h],k.tempFetchRateLimit=!0,N(!0,c)):alert("Fetch failed from Media API. API response message: "+f.message),m(f))):(d.is_video?c?A(d.video_resources.at(-1).src,e):x(d.video_resources.at(-1).src,
e,"highlights",b,"mp4",d.id):c?A(d.display_resources.at(-1).src,e):x(d.display_resources.at(-1).src,e,"highlights",b,"jpg",d.id),k.tempFetchRateLimit=!1);w(!1)}else if(!a(".IG_DWHISTORY").length){let h=null;0<a("body > div section._ac0a").length?h=a("body > div section:visible._ac0a"):(h=a("body > div section:visible > div > div[style]:not([class])"),h.css("position","relative"));if(0===h.length){let l=0;a("body > div div:not([hidden]) section:visible > div div[class][style] > div[style]:not([class])").each(function(){a(this).width()>
l&&(l=a(this).width(),h=a(this).children("div").first())})}null!=h&&(h.append(`<div data-ih-locale-title="DW" title="${r("DW")}" class="IG_DWHISTORY">${v.DOWNLOAD}</div>`),h.append(`<div data-ih-locale-title="NEW_TAB" title="${r("NEW_TAB")}" class="IG_DWHINEWTAB">${v.NEW_TAB}</div>`),1<F(e).length&&h.append(`<div data-ih-locale-title="DW_ALL" title="${r("DW_ALL")}" class="IG_DWHISTORY_ALL">${v.DOWNLOAD_ALL}</div>`),h.find("img[referrerpolicy]").each(function(){a(this).on("load",function(){a(this).data("remove-thumbnail")||
(0===h.find(".IG_DWHISTORY_THUMBNAIL").length?(a(this).attr("data-remove-thumbnail",!0),a(".IG_DWHISTORY_THUMBNAIL").remove(),m("(highlight) Manually removing thumbnail button")):(a(this).attr("data-remove-thumbnail",!0),m("(highlight) Thumbnail button is not present for this picture")))})}))}}async function O(b){if(b){b=(new Date).getTime();b=Math.floor(b/1E3);let d=location.href.replace(/\/$/ig,"").split("/").at(-1),g="";var c=a("body > div section._ac0a header._ac0k > ._ac3r ._ac3n ._ac3p[style]").length||
a("body > div section:visible > div > div:not([class]) > div > div div.x1ned7t2.x78zum5 div.x1caxmr6").length||a("body > div div:not([hidden]) section:visible > div div[style]:not([class]) > div").find("div div.x1ned7t2.x78zum5 div.x1caxmr6").length,e="";w(!0);if(k.GL_dataCache.highlights[d]){m("Fetch from memory cache:",d);var f=k.GL_dataCache.highlights[d].data.reels_media[0].items.length;g=k.GL_dataCache.highlights[d].data.reels_media[0].owner.username;e=k.GL_dataCache.highlights[d].data.reels_media[0].items[f-
c]}else f=await S(d),e=f.data.reels_media[0].items.length,g=f.data.reels_media[0].owner.username,e=f.data.reels_media[0].items[e-c],k.GL_dataCache.highlights[d]=f;q.RENAME_PUBLISH_DATE&&(b=e.taken_at_timestamp);q.FORCE_RESOURCE_VIA_MEDIA&&!k.tempFetchRateLimit?(c=await J(e.id),"ok"===c.status?x(c.items[0].image_versions2.candidates[0].url,g,"highlights",b,"jpg",d):(q.USE_BLOB_FETCH_WHEN_MEDIA_RATE_LIMIT?(delete k.GL_dataCache.highlights[d],k.tempFetchRateLimit=!0,O(!0)):alert("Fetch failed from Media API. API response message: "+
c.message),m(c))):(x(e.display_resources.at(-1).src,g,"highlights",b,"jpg",d),k.tempFetchRateLimit=!1);w(!1)}else if(a("body > div section video.xh8yej3").length){if(!a(".IG_DWHISTORY_THUMBNAIL").length){let d=null;0<a("body > div section._ac0a").length?d=a("body > div section:visible._ac0a"):(d=a("body > div section:visible > div > div[style]:not([class])"),d.css("position","relative"));if(0===d.length){let g=0;a("body > div div:not([hidden]) section:visible > div div[class][style] > div[style]:not([class])").each(function(){a(this).width()>
g&&(g=a(this).width(),d=a(this).children("div").first())})}null!=d&&d.append(`<div data-ih-locale-title="THUMBNAIL_INTRO" title="${r("THUMBNAIL_INTRO")}" class="IG_DWHISTORY_THUMBNAIL">${v.THUMBNAIL}</div>`)}}else a(".IG_DWHISTORY_THUMBNAIL").remove()}function T(b,c){!0===c&&(m("hasReferrer","regenerated"),a('article[data-snig="canDownload"], div[data-snig="canDownload"]').filter(function(){return 0===a(this).find(".IG_DW_MAIN").length}).removeAttr("data-snig"));if(0==b){let f=0;var e=setInterval(()=>
{if(100<f||0<a('article[data-snig="canDownload"], section:visible > main > div > div[data-snig="canDownload"] > div > div > div > hr, div[id^="mount"] > div > div > div.x1n2onr6.x1vjfegm div[data-snig="canDownload"]').length)clearInterval(e),100<f&&console.warn("onReadyMyDW() Timer","maximum number of repetitions reached, terminated");m("onReadyMyDW() Timer","repeating to call detection createDownloadButton()");Z();f++},50)}else Z()}function aa(b){q.DISABLE_VIDEO_LOOPING&&b.find("video").each(function(){a(this).on("ended",
function(){a(this).data("loop")||(a(this).attr("data-loop",!0),this.pause(),m("(post) Added video event listener #loop"))})});q.MODIFY_VIDEO_VOLUME&&b.find("video").each(function(){a(this).on("play playing",function(){a(this).data("modify")||(a(this).attr("data-modify",!0),this.volume=k.videoVolume,m("(post) Added video event listener #modify"))})});q.HTML5_VIDEO_CONTROL&&b.find("video").each(function(){if(!a(this).data("controls")){let e=a(this);m("(post) Added video html5 contorller #modify");q.MODIFY_VIDEO_VOLUME&&
(this.volume=k.videoVolume,a(this).on("loadstart",function(){this.volume=k.videoVolume}));a(this).on("contextmenu",function(f){f.preventDefault();e.css("z-index","-1");e.removeAttr("controls")});a(this).parent().find("video + div > div").first().on("contextmenu",function(f){f.preventDefault();e.css("z-index","2");e.attr("controls",!0)});a(this).on("volumechange",function(){let f=a(this).parent().find("video + div > div").find('button[type="button"], div[role="button"]').filter(function(g){return 64>=
a(this).width()&&64>=a(this).height()&&0<a(this).find('svg > path[d^="M16.636 7.028a1.5"], svg > path[d^="M1.5 13.3c-.8"]').length});var d=0===f.find('svg > path[d^="M16.636"]').length;this.muted!=d&&(this.volume=k.videoVolume,f?.trigger("click"));a(this).attr("data-completed")&&(k.videoVolume=this.volume,GM_setValue("G_VIDEO_VOLUME",this.volume));this.volume==k.videoVolume&&a(this).attr("data-completed",!0)});a(this).css("position","absolute");a(this).css("z-index","2");a(this).attr("data-controls",
!0);a(this).attr("controls",!0)}});var c=b.find("video");b=b.find("video + div > div").first();K(c,b,"post","bottom")}function Z(){a("article, section:visible > main > div > div > div > div > div > hr").map(function(b){return a(this).is("section:visible > main > div > div > div > div > div > hr")?a(this).parent().parent().parent().parent()[0]:this}).filter(function(){return 0<a(this).height()&&0<a(this).width()}).each(function(b){if(!a(this).attr("data-snig")&&!a(this).hasClass("x1iyjqo2")&&!a(this).children("article")?.hasClass("x1iyjqo2")&&
0===a(this).parents("div#scrollview").length){m("Found post container",a(this));const h=a(this),l=this.tagName;var c;if("DIV"!==l||0==b){var e=h.children("div").children("div");if(0!==e.length){m("Found insert point",e);0<h.find("._acay").length&&(0<h.find("._acay + .x24i39r").length&&h.find("._acay + .x24i39r").css("top","37px"),b=h.find("._acay").first().parent()[0],(new MutationObserver(function(){h.find("._acay + .x24i39r").css("top","37px")})).observe(b,{childList:!0}));e.eq("DIV"===l?0:e.length-
2).append('<div class="button_wrapper">');var f=`<div data-ih-locale-title="DW" title="${r("DW")}" class="IG_DW_MAIN">${v.DOWNLOAD}</div>`;b=`<div data-ih-locale-title="NEW_TAB" title="${r("NEW_TAB")}" class="IG_NEWTAB_MAIN">${v.NEW_TAB}</div>`;var d=`<div data-ih-locale-title="THUMBNAIL_INTRO" title="${r("THUMBNAIL_INTRO")}" class="IG_THUMBNAIL_MAIN">${v.THUMBNAIL}</div>`,g=`<div data-ih-locale-title="IMAGE_VIEWER" title="${r("IMAGE_VIEWER")}" class="IG_IMAGE_VIEWER">${v.FULLSCREEN}</div>`;e.find(".button_wrapper").append(f);
1<h.find("._acay ._acaz").length&&q.DIRECT_DOWNLOAD_VISIBLE_RESOURCE&&!q.DIRECT_DOWNLOAD_ALL&&(f=`<div data-ih-locale-title="DW_ALL" title="${r("DW_ALL")}" class="IG_DW_ALL_MAIN">${v.DOWNLOAD_ALL}</div>`,e.find(".button_wrapper").append(f));e.find(".button_wrapper").append(b);setTimeout(()=>{if(0===e.eq("DIV"===l?0:e.length-2).find("div > ul li._acaz").length)0<e.find("video").length?e.find(".button_wrapper").append(d):(c=h.find("img").filter(function(){return 200<a(this).width()&&200<a(this).height()}).attr("src"),
e.find(".button_wrapper").append(g));else{const p=new IntersectionObserver((u,z)=>{u.forEach(B=>{B.isIntersecting&&(B=a(B.target),e.find(".IG_THUMBNAIL_MAIN")?.remove(),e.find(".IG_IMAGE_VIEWER")?.remove(),0<B.find("video").length?(0===e.find(".IG_THUMBNAIL_MAIN").length&&e.find(".button_wrapper").append(d),aa(h)):(c=B.find("img").attr("src"),e.find(".button_wrapper").append(g)))})},{root:h.find("div > ul._acay").first().parent().parent().parent()[0],rootMargin:"0px",threshold:.1}),n=new MutationObserver(function(u,
z){u=u.at(0)?.target;a(u).find("li._acaz").each(function(){p.observe(this)})});h.find("div > ul li._acaz").each(function(){p.observe(this)});const t=e.eq("DIV"===l?0:e.length-2).find("div > ul li._acaz")?.parent()[0],y=e.eq("DIV"===l?0:e.length-2).find("div > ul li._acaz")?.parent().parent()[0];t&&n.observe(t,{childList:!0});y&&n.observe(y,{attributes:!0})}},50);e.css("position","relative");aa(h);k.GL_registerEventList.push({element:this,trigger:[".IG_THUMBNAIL_MAIN",".IG_NEWTAB_MAIN",".IG_DW_ALL_MAIN",
".IG_DW_MAIN",".IG_IMAGE_VIEWER"]});a(this).on("click",".IG_IMAGE_VIEWER",function(){null!=c?ma(c):alert("Cannot find resource url.")});a(this).on("click",".IG_THUMBNAIL_MAIN",function(){w(!0);k.GL_username=h.attr("data-username");k.GL_postPath=location.pathname.replace(/\/$/,"").split("/").at(-1)||h.find('a[href^="/p/"]').first().attr("href").split("/").at(2)||a(this).parent().parent().parent().children("div:last-child").children("div").children("div:last-child").find('a[href^="/p/"]').last().attr("href").split("/").at(2);
var p=U(h);D(!0,!1);C(k.GL_postPath,".IG_POPUP_DIG .IG_POPUP_DIG_MAIN .IG_POPUP_DIG_BODY","").then(()=>{let n=setInterval(()=>{if(0<a(".IG_POPUP_DIG .IG_POPUP_DIG_MAIN .IG_POPUP_DIG_BODY a").length){clearInterval(n);var t=a('.IG_POPUP_DIG .IG_POPUP_DIG_BODY a[data-globalindex="'+(p+1)+'"]')?.parent().find(".videoThumbnail")?.first();null!=t&&0<t.length?t.trigger("click"):alert("Can not find thumbnail url.");w(!1);a(".IG_POPUP_DIG").remove()}},250)})});a(this).on("click",".IG_NEWTAB_MAIN",function(){w(!0);
k.GL_username=h.attr("data-username");k.GL_postPath=location.pathname.replace(/\/$/,"").split("/").at(-1)||h.find('a[href^="/p/"]').first().attr("href").split("/").at(2)||a(this).parent().parent().parent().children("div:last-child").children("div").children("div:last-child").find('a[href^="/p/"]').last().attr("href").split("/").at(2);var p=U(h);D(!0,!1);C(k.GL_postPath,".IG_POPUP_DIG .IG_POPUP_DIG_MAIN .IG_POPUP_DIG_BODY","").then(()=>{let n=setInterval(()=>{if(0<a(".IG_POPUP_DIG .IG_POPUP_DIG_MAIN .IG_POPUP_DIG_BODY a").length){clearInterval(n);
var t=a('.IG_POPUP_DIG .IG_POPUP_DIG_BODY a[data-globalindex="'+(p+1)+'"]');q.FORCE_RESOURCE_VIA_MEDIA&&q.NEW_TAB_ALWAYS_FORCE_MEDIA_IN_POST?V(t.first()[0],!0):(t=t?.attr("data-href"))?(t=new URL(t),t.host="scontent.cdninstagram.com",A(t.href)):alert("Can not find open tab url.");w(!1);a(".IG_POPUP_DIG").remove()}},250)})});a(this).on("click",".IG_DW_ALL_MAIN",async function(){k.GL_username=h.attr("data-username");k.GL_postPath=location.pathname.replace(/\/$/,"").split("/").at(-1)||h.find('a[href^="/p/"]').first().attr("href").split("/").at(2)||
a(this).parent().parent().parent().children("div:last-child").children("div").children("div:last-child").find('a[href^="/p/"]').last().attr("href").split("/").at(2);D(q.DIRECT_DOWNLOAD_ALL,!0);a("#article-id").html(`<a href="https://www.instagram.com/p/${k.GL_postPath}">${k.GL_postPath}</a>`);a(".IG_POPUP_DIG .IG_POPUP_DIG_MAIN .IG_POPUP_DIG_BODY a").each(function(){a(this).wrap("<div></div>");a(this).before('<label class="inner_box_wrapper"><input class="inner_box" type="checkbox"><span></span></label>');
a(this).after(`<div data-ih-locale-title="NEW_TAB" title="${r("NEW_TAB")}" class="newTab">${v.NEW_TAB}</div>`);"video"==a(this).attr("data-name")&&a(this).after(`<div data-ih-locale-title="THUMBNAIL_INTRO" title="${r("THUMBNAIL_INTRO")}" class="videoThumbnail">${v.THUMBNAIL}</div>`)});C(k.GL_postPath,".IG_POPUP_DIG .IG_POPUP_DIG_MAIN .IG_POPUP_DIG_BODY",r("LOAD_BLOB_MULTIPLE")).then(()=>{let p=setInterval(()=>{0<a(".IG_POPUP_DIG .IG_POPUP_DIG_MAIN .IG_POPUP_DIG_BODY a").length&&(clearInterval(p),
a(".IG_POPUP_DIG .IG_POPUP_DIG_MAIN .IG_POPUP_DIG_BODY a").each(function(){a(this).trigger("click")}),a(".IG_POPUP_DIG").remove())},250)})});a(this).on("click",".IG_DW_MAIN",async function(){k.GL_username=h.attr("data-username");k.GL_postPath=location.pathname.replace(/\/$/,"").split("/").at(-1)||h.find('a[href^="/p/"]').first().attr("href").split("/").at(2)||a(this).parent().parent().parent().children("div:last-child").children("div").children("div:last-child").find('a[href^="/p/"]').last().attr("href").split("/").at(2);
D(q.DIRECT_DOWNLOAD_ALL,!0);a("#article-id").html(`<a href="https://www.instagram.com/p/${k.GL_postPath}">${k.GL_postPath}</a>`);if(q.DIRECT_DOWNLOAD_VISIBLE_RESOURCE){w(!0);a(".IG_POPUP_DIG").length&&a(".IG_POPUP_DIG").addClass("hidden");var p=U(a(this).parent().parent().parent());C(k.GL_postPath,".IG_POPUP_DIG .IG_POPUP_DIG_MAIN .IG_POPUP_DIG_BODY","").then(()=>{let z=setInterval(()=>{0<a(".IG_POPUP_DIG .IG_POPUP_DIG_MAIN .IG_POPUP_DIG_BODY a").length&&(clearInterval(z),a('.IG_POPUP_DIG .IG_POPUP_DIG_BODY a[data-globalindex="'+
(p+1)+'"]')?.attr("data-href")?(w(!1),a('.IG_POPUP_DIG .IG_POPUP_DIG_BODY a[data-globalindex="'+(p+1)+'"]')?.trigger("click")):alert("Can not find download url."),a(".IG_POPUP_DIG").remove())},250)})}else{if(!q.DIRECT_DOWNLOAD_ALL){var n=0,t=a(this).parent().parent().find("._acay ._acaz").length,y=q.FORCE_FETCH_ALL_RESOURCES,u=(new Date(a(this).parent().parent().find('a[href^="/p/"] time[datetime]').first().attr("datetime"))).getTime();if(t)a(this).parent().parent().find("._acay ._acaz").each(function(){let z=
a(this).parent().parent().parent().find("video");z&&z.attr("src")&&(y=!0)}),y||q.FORCE_RESOURCE_VIA_MEDIA?C(k.GL_postPath,".IG_POPUP_DIG .IG_POPUP_DIG_MAIN .IG_POPUP_DIG_BODY",r("LOAD_BLOB_MULTIPLE")):(a(this).parent().parent().find("._acay ._acaz").each(function(){n++;let z=a(this).find("video"),B=a(this).find("._aagv img"),G=B.attr("srcset")?B.attr("srcset").split(" ")[0]:B.attr("src");z&&z.attr("src")&&(y=!0);B&&G&&a(".IG_POPUP_DIG .IG_POPUP_DIG_MAIN .IG_POPUP_DIG_BODY").append(`<a datetime="${u}" data-needed="direct" data-path="${k.GL_postPath}" data-name="photo" data-type="jpg" data-globalIndex="${n}" href="javascript:;" data-href="${G}"><img width="100" src="${G}" /><br/>- <span data-ih-locale="IMG">${r("IMG")}</span> ${n} -</a>`)}),
y&&C(k.GL_postPath,".IG_POPUP_DIG .IG_POPUP_DIG_MAIN .IG_POPUP_DIG_BODY",r("LOAD_BLOB_RELOAD")));else if(q.FORCE_RESOURCE_VIA_MEDIA)C(k.GL_postPath,".IG_POPUP_DIG .IG_POPUP_DIG_MAIN .IG_POPUP_DIG_BODY",r("LOAD_BLOB_MULTIPLE"));else{n++;t=a(this).parent().parent().parent().find("video");let z=a(this).parent().parent().parent().find("._aagv img"),B=z.attr("srcset")?z.attr("srcset").split(" ")[0]:z.attr("src");t&&t.attr("src")&&C(k.GL_postPath,".IG_POPUP_DIG .IG_POPUP_DIG_MAIN .IG_POPUP_DIG_BODY",r("LOAD_BLOB_ONE"));
z&&B&&a(".IG_POPUP_DIG .IG_POPUP_DIG_MAIN .IG_POPUP_DIG_BODY").append(`<a datetime="${u}" data-needed="direct" data-path="${k.GL_postPath}" data-name="photo" data-type="jpg" data-globalIndex="${n}" href="javascript:;" href="" data-href="${B}"><img width="100" src="${B}" /><br/>- <span data-ih-locale="IMG">${r("IMG")}</span> ${n} -</a>`)}}a(".IG_POPUP_DIG .IG_POPUP_DIG_MAIN .IG_POPUP_DIG_BODY a").each(function(){a(this).wrap("<div></div>");a(this).before('<label class="inner_box_wrapper"><input class="inner_box" type="checkbox"><span></span></label>');
a(this).after(`<div data-ih-locale-title="NEW_TAB" title="${r("NEW_TAB")}" class="newTab">${v.NEW_TAB}</div>`);"video"==a(this).attr("data-name")&&a(this).after(`<div data-ih-locale-title="THUMBNAIL_INTRO" title="${r("THUMBNAIL_INTRO")}" class="videoThumbnail">${v.THUMBNAIL}</div>`)});q.DIRECT_DOWNLOAD_ALL&&C(k.GL_postPath,".IG_POPUP_DIG .IG_POPUP_DIG_MAIN .IG_POPUP_DIG_BODY",r("LOAD_BLOB_MULTIPLE")).then(()=>{let z=setInterval(()=>{0<a(".IG_POPUP_DIG .IG_POPUP_DIG_MAIN .IG_POPUP_DIG_BODY a").length&&
(clearInterval(z),a(".IG_POPUP_DIG .IG_POPUP_DIG_MAIN .IG_POPUP_DIG_BODY a").each(function(){a(this).trigger("click")}),a(".IG_POPUP_DIG").remove())},250)})}});b=a(this).find("header > div:last-child > div:first-child span a").first().text()||a(this).find('a[href^="/"]').filter(function(){return 0<a(this)?.text()?.length}).first().text();a(this).attr("data-snig","canDownload");a(this).attr("data-username",b)}}}})}function ba(b){b=b.shortcode_media??b;null==b.owner&&null!=b.user&&(b.owner=b.user);
null==b.owner&&(m("carousel_media:","undefined username"),alert("carousel_media: undefined username"));return b}async function C(b,c,e){try{a(`${c} a`).remove();a(c).append('<p id="_SNLOAD">'+e+"</p>");let f=await ca(b),d=ba(f.data);if("query_hash"===f.type){if(b=1,"GraphVideo"==d.__typename&&d.video_url&&(a(c).append(`<a media-id="${d.id}" datetime="${d.taken_at_timestamp}" data-blob="true" data-needed="direct" data-path="${d.shortcode}" data-name="video" data-type="mp4" data-username="${d.owner.username}" data-globalIndex="${b}" href="javascript:;" data-href="${d.video_url}"><img width="100" src="${d.display_resources[1].src}" /><br/>- <span data-ih-locale="VID">${r("VID")}</span> ${b} -</a>`),
b++),"GraphImage"==d.__typename&&(a(c).append(`<a media-id="${d.id}" datetime="${d.taken_at_timestamp}" data-blob="true" data-needed="direct" data-path="${d.shortcode}" data-name="photo" data-type="jpg" data-username="${d.owner.username}" data-globalIndex="${b}" href="javascript:;" data-href="${d.display_resources[d.display_resources.length-1].src}"><img width="100" src="${d.display_resources[1].src}" /><br/>- <span data-ih-locale="IMG">${r("IMG")}</span> ${b} -</a>`),b++),"GraphSidecar"==d.__typename&&
d.edge_sidecar_to_children)for(let g of d.edge_sidecar_to_children.edges)"GraphVideo"==g.node.__typename&&a(c).append(`<a media-id="${g.node.id}" datetime="${d.taken_at_timestamp}" data-blob="true" data-needed="direct" data-path="${d.shortcode}" data-name="video" data-type="mp4" data-username="${d.owner.username}" data-globalIndex="${b}" href="javascript:;" data-href="${g.node.video_url}"><img width="100" src="${g.node.display_resources[1].src}" /><br/>- <span data-ih-locale-title="VID">${r("VID")}</span> ${b} -</a>`),
"GraphImage"==g.node.__typename&&a(c).append(`<a media-id="${g.node.id}" datetime="${d.taken_at_timestamp}" data-blob="true" data-needed="direct" data-path="${d.shortcode}" data-name="photo" data-type="jpg" data-username="${d.owner.username}" data-globalIndex="${b}" href="javascript:;" data-href="${g.node.display_resources[g.node.display_resources.length-1].src}"><img width="100" src="${g.node.display_resources[1].src}" /><br/>- <span data-ih-locale="IMG">${r("IMG")}</span> ${b} -</a>`),b++}else d.carousel_media?
(m("carousel_media"),d.carousel_media.forEach((g,h)=>{h+=1;null==g.video_versions?(g.image_versions2.candidates.sort(function(l,p){let n=(new URL(l.url)).searchParams.get("stp"),t=(new URL(p.url)).searchParams.get("stp");if(n&&t){if(n.length>t.length)return 1;if(n.length<t.length)return-1}else{if(l.width<p.width)return 1;if(l.width>p.width)return-1}return 0}),a(c).append(`<a media-id="${g.pk}" datetime="${g.taken_at}" data-blob="true" data-needed="direct" data-path="${d.code}" data-name="photo" data-type="jpg" data-username="${d.owner.username}" data-globalIndex="${h}" href="javascript:;" data-href="${g.image_versions2.candidates[0].url}"><img width="100" src="${g.image_versions2.candidates[0].url}" /><br/>- <span data-ih-locale="IMG">${r("IMG")}</span> ${h} -</a>`)):
a(c).append(`<a media-id="${g.pk}" datetime="${g.taken_at}" data-blob="true" data-needed="direct" data-path="${d.code}" data-name="video" data-type="mp4" data-username="${d.owner.username}" data-globalIndex="${h}" href="javascript:;" data-href="${g.video_versions[0].url}"><img width="100" src="${g.image_versions2.candidates[0].url}" /><br/>- <span data-ih-locale="VID">${r("VID")}</span> ${h} -</a>`)})):null==d.video_versions?(d.image_versions2.candidates.sort(function(g,h){let l=(new URL(g.url)).searchParams.get("stp"),
p=(new URL(h.url)).searchParams.get("stp");if(l&&p){if(l.length>p.length)return 1;if(l.length<p.length)return-1}else{if(g.width<h.width)return 1;if(g.width>h.width)return-1}return 0}),a(c).append(`<a media-id="${d.pk}" datetime="${d.taken_at}" data-blob="true" data-needed="direct" data-path="${d.code}" data-name="photo" data-type="jpg" data-username="${d.owner.username}" data-globalIndex="${1}" href="javascript:;" data-href="${d.image_versions2.candidates[0].url}"><img width="100" src="${d.image_versions2.candidates[0].url}" /><br/>- <span data-ih-locale="IMG">${r("IMG")}</span> ${1} -</a>`)):
a(c).append(`<a media-id="${d.pk}" datetime="${d.taken_at}" data-blob="true" data-needed="direct" data-path="${d.code}" data-name="video" data-type="mp4" data-username="${d.owner.username}" data-globalIndex="${1}" href="javascript:;" data-href="${d.video_versions[0].url}"><img width="100" src="${d.image_versions2.candidates[0].url}" /><br/>- <span data-ih-locale="VID">${r("VID")}</span> ${1} -</a>`);a("#_SNLOAD").remove();a(".IG_POPUP_DIG .IG_POPUP_DIG_MAIN .IG_POPUP_DIG_BODY a").each(function(){a(this).wrap("<div></div>");
a(this).before('<label class="inner_box_wrapper"><input class="inner_box" type="checkbox"><span></span></label>');a(this).after(`<div data-ih-locale-title="NEW_TAB" title="${r("NEW_TAB")}" class="newTab">${v.NEW_TAB}</div>`);"video"==a(this).attr("data-name")&&a(this).after(`<div data-ih-locale-title="THUMBNAIL_INTRO" title="${r("THUMBNAIL_INTRO")}" class="videoThumbnail">${v.THUMBNAIL}</div>`)})}catch(f){m("createMediaListDOM",f)}}function U(b){var c=0,e=b.find(".x1iyjqo2 > div > div:last-child > div");
null!=e&&e.hasClass("_acnb")||(e=b.find("._aatk > div > div:last-child").eq(0).children("div"));e.filter("._acnb").each(function(f){a(this).hasClass("_acnf")&&(c=f)});return c}async function da(b){if(b){w(!0);b=(new Date).getTime();b=Math.floor(b/1E3);let c=location.pathname.replaceAll(/(reels|tagged)\/$/ig,"").split("/").filter(f=>0<f.length).at(-1),e=await H(c);try{let f=await na(e.user.pk);x(f,c,"avatar",b,"jpg")}catch(f){x(e.user.profile_pic_url,c,"avatar",b,"jpg")}w(!1)}else if(!a(".IG_DWPROFILE").length){let c=
setInterval(()=>{a(".IG_DWPROFILE").length?clearInterval(c):(a("header > *[class]:first-child img[alt][draggable]").parent().parent().append(`<div data-ih-locale-title="DW" title="${r("DW")}" class="IG_DWPROFILE">${v.DOWNLOAD}</div>`),a("header > *[class]:first-child img[alt][draggable]").parent().parent().css("position","relative"),a("header > *[class]:first-child img[alt]:not([draggable])").parent().parent().parent().append(`<div data-ih-locale-title="DW" title="${r("DW")}" class="IG_DWPROFILE">${v.DOWNLOAD}</div>`),
a("header > *[class]:first-child img[alt]:not([draggable])").parent().parent().parent().css("position","relative"))},150)}}async function P(b,c,e){if(b){w(!0);b=location.href.split("?").at(0).split("instagram.com/reels/").at(-1).replaceAll("/","");let d=await ca(b),g=ba(d.data),h=(new Date).getTime();q.RENAME_PUBLISH_DATE&&(h="query_hash"===d.type?g.shortcode_media.taken_at_timestamp:g.taken_at);"query_hash"===d.type?c&&g.shortcode_media.is_video?e?A(g.shortcode_media.video_url):x(g.shortcode_media.video_url,
g.shortcode_media.owner.username,"reels",h,"mp4",b):e?A(g.shortcode_media.display_resources.at(-1).src):x(g.shortcode_media.display_resources.at(-1).src,g.shortcode_media.owner.username,"reels",h,"jpg",b):c&&null!=g.video_versions?e?A(g.video_versions[0].url):x(g.video_versions[0].url,g.owner.username,"reels",h,"mp4",b):e?A(g.image_versions2.candidates[0].url):x(g.image_versions2.candidates[0].url,g.owner.username,"reels",h,"jpg",b);w(!1)}else var f=setInterval(()=>{0<a('section > main[role="main"] > div div.x1qjc9v5 video').length&&
(clearInterval(f),q.SCROLL_BUTTON&&(a("#scrollWrapper").remove(),a('section > main[role="main"]').append('<section id="scrollWrapper"></section>'),a('section > main[role="main"] > #scrollWrapper').append('<div class="button-up"><div></div></div>'),a('section > main[role="main"] > #scrollWrapper').append('<div class="button-down"><div></div></div>'),a('section > main[role="main"] > #scrollWrapper > .button-up').on("click",function(){a('section > main[role="main"] > div')[0].scrollBy({top:-30,behavior:"smooth"})}),
a('section > main[role="main"] > #scrollWrapper > .button-down').on("click",function(){a('section > main[role="main"] > div')[0].scrollBy({top:30,behavior:"smooth"})})),a('section > main[role="main"] > div[tabindex]').children("div").each(function(){if(0<a(this).children().length&&!a(this).children().find(".IG_REELS").length){var d=a(this);a(this).children().css("position","relative");a(this).children().append(`<div data-ih-locale-title="DW" title="${r("DW")}" class="IG_REELS">${v.DOWNLOAD}</div>`);
a(this).children().append(`<div data-ih-locale-title="NEW_TAB" title="${r("NEW_TAB")}" class="IG_REELS_NEWTAB">${v.NEW_TAB}</div>`);a(this).children().append(`<div data-ih-locale-title="THUMBNAIL_INTRO" title="${r("THUMBNAIL_INTRO")}" class="IG_REELS_THUMBNAIL">${v.THUMBNAIL}</div>`);q.DISABLE_VIDEO_LOOPING&&a(this).find("video").each(function(){a(this).on("ended",function(){if(!a(this).data("loop")){let h=a(this).next().find('div[role="presentation"] > div svg > path[d^="M5.888"]').parents('button[role="button"], div[role="button"]');
0<h.length?(a(this).attr("data-loop",!0),h.trigger("click"),m("Adding video event listener #loop, then paused click()")):(a(this).attr("data-loop",!0),a(this).parent().find(".xpgaw4o").removeAttr("style"),this.pause(),m("Adding video event listener #loop, then paused pause()"))}})});q.HTML5_VIDEO_CONTROL&&a(this).find("video").each(function(){if(!a(this).data("controls")){let h=a(this);m("(reel) Added video html5 contorller #modify");q.MODIFY_VIDEO_VOLUME&&(this.volume=k.videoVolume,a(this).on("loadstart",
function(){this.volume=k.videoVolume}));a(this).on("contextmenu",function(l){l.preventDefault();h.css("z-index","-1");h.removeAttr("controls")});a(this).parent().find('video + div div[role="button"]').filter(function(){return 0<a(this).parent('div[role="presentation"]').length&&"pointer"===a(this).css("cursor")&&null!=a(this).attr("style")}).first().on("contextmenu",function(l){l.preventDefault();h.css("z-index","2");h.attr("controls",!0)});a(this).on("volumechange",function(){let l=a(this).parent().find("video + div > div").find('button[type="button"], div[role="button"]').filter(function(n){return 64>=
a(this).width()&&64>=a(this).height()&&0<a(this).find('svg > path[d^="M16.636 7.028a1.5"], svg > path[d^="M1.5 13.3c-.8"]').length});var p=0===l.find('svg > path[d^="M16.636"]').length;this.muted!=p&&(this.volume=k.videoVolume,l?.trigger("click"));a(this).attr("data-completed")&&(k.videoVolume=this.volume,GM_setValue("G_VIDEO_VOLUME",this.volume));this.volume==k.videoVolume&&a(this).attr("data-completed",!0)});a(this).css("position","absolute");a(this).css("z-index","2");a(this).attr("data-controls",
!0);a(this).attr("controls",!0)}});d=d.find("video");var g=a(this).find('div[role="presentation"] > div[role="button"] > div').first();K(d,g,"reel")}}))},250)}async function oa(){w(!0);var b=(new Date).getTime();let c=Math.floor(b/1E3),e=a("body > div section._ac0a header._ac0k ._ac0l a + div a").first().text()||location.pathname.split("/").filter(g=>0<g.length).at(1);b=(await H(e)).user.pk;let f=await L(b),d=0;E(d,f.data.reels_media[0].items.length);f.data.reels_media[0].items.forEach((g,h)=>{setTimeout(()=>
{q.RENAME_PUBLISH_DATE&&(c=g.taken_at_timestamp);g.display_resources.sort(function(l,p){return l.config_width<p.config_width?1:l.config_width>p.config_width?-1:0});g.is_video?x(g.video_resources[0].src,e,"stories",c,"mp4",g.id).then(()=>{E(++d,f.data.reels_media[0].items.length)}):x(g.display_resources[0].src,e,"stories",c,"jpg",g.id).then(()=>{E(++d,f.data.reels_media[0].items.length)})},100*h)})}async function I(b,c,e){var f=a("body > div section._ac0a header._ac0k ._ac0l a + div a").first().text()||
location.pathname.split("/").filter(g=>0<g.length).at(1);if(b){var d=(new Date).getTime();let g=Math.floor(d/1E3);w(!0);if(q.FORCE_RESOURCE_VIA_MEDIA&&!k.tempFetchRateLimit){let h=null;d=(await H(f)).user.pk;let l=await L(d),p=location.pathname.split("/").filter(n=>0<n.length&&n.match(/^([0-9]{10,})$/)).at(-1);l.data.reels_media[0].items.forEach(n=>{n.id==p&&(h=n.id)});null==h&&F(f).each(function(n){0<a(this).children().length&&(h=l.data.reels_media[0].items[n].id)});null==h&&(a("body > div section:visible div.x1ned7t2.x78zum5 > div").each(function(n){a(this).hasClass("x1lix1fw")&&
0<a(this).children().length&&(h=l.data.reels_media[0].items[n].id)}),a("body > div section:visible ._ac0k > ._ac3r > div").each(function(n){a(this).children().hasClass("_ac3q")&&(h=l.data.reels_media[0].items[n].id)}));null==h&&(h=location.pathname.split("/").filter(n=>0<n.length&&n.match(/^([0-9]{10,})$/)).at(-1));d=await J(h);q.RENAME_PUBLISH_DATE&&(g=d.items[0].taken_at);"ok"===d.status?d.items[0].video_versions?e?A(d.items[0].video_versions[0].url):x(d.items[0].video_versions[0].url,f,"stories",
g,"mp4",h):e?A(d.items[0].image_versions2.candidates[0].url):x(d.items[0].image_versions2.candidates[0].url,f,"stories",g,"jpg",h):(q.USE_BLOB_FETCH_WHEN_MEDIA_RATE_LIMIT?(k.tempFetchRateLimit=!0,I(b,c,e)):alert("Fetch failed from Media API. API response message: "+d.message),m(d))}else{if(0<a("body > div section:visible video[playsinline]").length){let h="",l=location.pathname.replace(/\/$/ig,"").split("/").at(-1),p=null;if(k.GL_dataCache.stories[f]&&!c){if(m("Fetch from memory cache:",f),k.GL_dataCache.stories[f].data.reels_media[0].items.forEach(n=>
{n.id==l&&(h=n.video_resources[0].src,q.RENAME_PUBLISH_DATE&&(g=n.taken_at_timestamp,p=n.id))}),0==h.length){m("Memory cache not found, try fetch from API:",f);I(!0,!0);return}}else{b=(await H(f)).user.pk;let n=await L(b);n.data.reels_media[0].items.forEach(t=>{t.id==l&&(h=t.video_resources[0].src,q.RENAME_PUBLISH_DATE&&(g=t.taken_at_timestamp,p=t.id))});0==h.length&&(F(f).each(function(t){0<a(this).children().length&&(h=n.data.reels_media[0].items[t].video_resources[0].src,q.RENAME_PUBLISH_DATE&&
(g=n.data.reels_media[0].items[t].taken_at_timestamp,p=n.data.reels_media[0].items[t].id))}),0==h.length&&(a("body > div section:visible div.x1ned7t2.x78zum5 > div").each(function(t){a(this).hasClass("x1lix1fw")&&0<a(this).children().length&&(h=n.data.reels_media[0].items[t].video_resources[0].src,q.RENAME_PUBLISH_DATE&&(g=n.data.reels_media[0].items[t].taken_at_timestamp,p=n.data.reels_media[0].items[t].id))}),a("body > div section:visible ._ac0k > ._ac3r > div").each(function(t){a(this).children().hasClass("_ac3q")&&
(h=n.data.reels_media[0].items[t].video_resources[0].src,q.RENAME_PUBLISH_DATE&&(g=n.data.reels_media[0].items[t].taken_at_timestamp,p=n.data.reels_media[0].items[t].id))})));k.GL_dataCache.stories[f]=n}0==h.length?alert(r("NO_VID_URL")):e?A(h):x(h,f,"stories",g,"mp4",p)}else b=(b=a("body > div section:visible img[referrerpolicy][class], body > div section:visible img[crossorigin][class]:not([alt])").attr("srcset")?.split(",")[0]?.split(" ")[0])?b:a("body > div section:visible img[referrerpolicy][class], body > div section:visible img[crossorigin][class]:not([alt])").filter(function(){return 0===
a(this).parents("a").length&&a(this).width()===a(this).parent().width()}).attr("src"),b||(b=a("body > div section:visible img._aa63"),b=b.attr("srcset")?b.attr("srcset")?.split(",")[0]?.split(" ")[0]:b.attr("src")),q.RENAME_PUBLISH_DATE&&(g=(new Date(a("body > div section:visible time[datetime][class]").first().attr("datetime"))).getTime()),e?A(b):x(b,f,"stories",g,"jpg",pa(b)??"");k.tempFetchRateLimit=!1}w(!1)}else if(!a(".IG_DWSTORY").length){k.GL_dataCache.stories={};let g=null;0<a("body > div section._ac0a").length?
g=a("body > div section:visible._ac0a"):(g=a("body > div section:visible > div > div[style]:not([class])"),g.css("position","relative"));0===g.length&&(g=a('div[id^="mount"] section > div > a[href="/"]').parent().parent().parent().find("section:visible > div > div[style]:not([class])"),g.css("position","relative"));0===g.length&&(g=a('div[id^="mount"] section > div > a[href="/"]').parent().parent().parent().find('section:visible > div div[style]:not([class]) > div:not([data-visualcompletion="loading-state"])'),
g.css("position","relative"));if(0===g.length){let h=0;a("body > div div:not([hidden]) section:visible > div div[class][style] > div[style]:not([class])").each(function(){a(this).width()>h&&(h=a(this).width(),g=a(this).children("div").first())})}null!=g&&(g.first().css("position","relative"),g.first().append(`<div data-ih-locale-title="DW" title="${r("DW")}" class="IG_DWSTORY">${v.DOWNLOAD}</div>`),g.first().append(`<div data-ih-locale-title="NEW_TAB" title="${r("NEW_TAB")}" class="IG_DWNEWTAB">${v.NEW_TAB}</div>`),
1<F(f).length&&g.first().append(`<div data-ih-locale-title="DW_ALL" title="${r("DW_ALL")}" class="IG_DWSTORY_ALL">${v.DOWNLOAD_ALL}</div>`),g.find("img[referrerpolicy]").each(function(){a(this).on("load",function(){a(this).data("remove-thumbnail")||(0===g.find(".IG_DWSTORY_THUMBNAIL").length?(a(this).attr("data-remove-thumbnail",!0),a(".IG_DWSTORY_THUMBNAIL").remove(),m("(story) Manually removing thumbnail button")):(a(this).attr("data-remove-thumbnail",!0),m("(story) Thumbnail button is not present for this picture")))})}))}}
async function Q(b,c){if(b){b=(new Date).getTime();let f=Math.floor(b/1E3);b=a("body > div section._ac0a header._ac0k ._ac0l a + div a").first().text()||location.pathname.split("/").at(2);let d=location.pathname.replace(/\/$/ig,"").split("/").at(-1),g="",h=null;w(!0);if(q.FORCE_RESOURCE_VIA_MEDIA&&!k.tempFetchRateLimit){var e=(await H(b)).user.pk;let l=await L(e),p=location.pathname.split("/").filter(n=>0<n.length&&n.match(/^([0-9]{10,})$/)).at(-1);l.data.reels_media[0].items.forEach(n=>{n.id==p&&
(h=n.id)});null==h&&F(b).each(function(n){0<a(this).children().length&&(h=l.data.reels_media[0].items[n].id)});null==h&&(a("body > div section:visible div.x1ned7t2.x78zum5 > div").each(function(n){a(this).hasClass("x1lix1fw")&&0<a(this).children().length&&(h=l.data.reels_media[0].items[n].id)}),a("body > div section:visible ._ac0k > ._ac3r > div").each(function(n){a(this).children().hasClass("_ac3q")&&(h=l.data.reels_media[0].items[n].id)}));null==h&&(h=location.pathname.split("/").filter(n=>0<n.length&&
n.match(/^([0-9]{10,})$/)).at(-1));e=await J(h);q.RENAME_PUBLISH_DATE&&(f=e.items[0].taken_at);"ok"===e.status?x(e.items[0].image_versions2.candidates[0].url,b,"stories",f,"jpg",h):(q.USE_BLOB_FETCH_WHEN_MEDIA_RATE_LIMIT?(k.tempFetchRateLimit=!0,Q(!0,c)):alert("Fetch failed from Media API. API response message: "+e.message),m(e))}else{if(k.GL_dataCache.stories[b]&&!c){if(m("Fetch from memory cache:",b),k.GL_dataCache.stories[b].data.reels_media[0].items.forEach(l=>{l.id==d&&(g=l.display_url,q.RENAME_PUBLISH_DATE&&
(f=l.taken_at_timestamp,h=l.id))}),0==g.length){m("Memory cache not found, try fetch from API:",b);Q(!0,!0);return}}else{c=(await H(b)).user.pk;let l=await L(c);l.data.reels_media[0].items.forEach(p=>{p.id==d&&(g=p.display_url,q.RENAME_PUBLISH_DATE&&(f=p.taken_at_timestamp,h=p.id))});0==g.length&&(F(b).each(function(p){0<a(this).children().length&&(g=l.data.reels_media[0].items[p].display_url,q.RENAME_PUBLISH_DATE&&(f=l.data.reels_media[0].items[p].taken_at_timestamp,h=l.data.reels_media[0].items[p].id))}),
0==g.length&&(a("body > div section:visible div.x1ned7t2.x78zum5 > div").each(function(p){a(this).hasClass("x1lix1fw")&&0<a(this).children().length&&(g=l.data.reels_media[0].items[p].display_url,q.RENAME_PUBLISH_DATE&&(f=l.data.reels_media[0].items[p].taken_at_timestamp,h=l.data.reels_media[0].items[p].id))}),a("body > div section:visible ._ac0k > ._ac3r > div").each(function(p){a(this).children().hasClass("_ac3q")&&(g=l.data.reels_media[0].items[p].display_url,q.RENAME_PUBLISH_DATE&&(f=l.data.reels_media[0].items[p].taken_at_timestamp,
h=l.data.reels_media[0].items[p].id))})))}x(g,b,"thumbnail",f,"jpg",h);k.tempFetchRateLimit=!1}w(!1)}else if(a("body > div div.IG_DWSTORY").parent().find("video[class]").length){let f=null;0<a("body > div section._ac0a").length?f=a("body > div section:visible._ac0a"):(f=a("body > div section:visible > div > div[style]:not([class])"),f.css("position","relative"));0===f.length&&(f=a('div[id^="mount"] section > div > a[href="/"]').parent().parent().parent().find("section:visible > div > div[style]:not([class])"),
f.css("position","relative"));0===f.length&&(f=a('div[id^="mount"] section > div > a[href="/"]').parent().parent().parent().find('section:visible > div div[style]:not([class]) > div:not([data-visualcompletion="loading-state"])'),f.css("position","relative"));if(0===f.length){let d=0;a("body > div div:not([hidden]) section:visible > div div[class][style] > div[style]:not([class])").each(function(){a(this).width()>d&&(d=a(this).width(),f=a(this).children("div").first())})}null!=f&&(f.first().css("position",
"relative"),f.first().append(`<div data-ih-locale-title="THUMBNAIL_INTRO" title="${r("THUMBNAIL_INTRO")}" class="IG_DWSTORY_THUMBNAIL">${v.THUMBNAIL}</div>`))}}function S(b){return new Promise((c,e)=>{GM_xmlhttpRequest({method:"GET",url:`https://www.instagram.com/graphql/query/?query_hash=45246d3fe16ccc6577e0bd297a5db1ab&variables=%7B%22highlight_reel_ids%22:%5B%22${b}%22%5D,%22precomposed_overlay%22:false%7D`,onload:function(f){try{let d=JSON.parse(f.response);c(d)}catch(d){m("getHighlightStories()",
"reject",d.message),e(d)}},onerror:function(f){m("getHighlightStories()","reject",f);e(f)}})})}function L(b){return new Promise((c,e)=>{GM_xmlhttpRequest({method:"GET",url:`https://www.instagram.com/graphql/query/?query_hash=15463e8449a83d3d60b06be7e90627c7&variables=%7B%22reel_ids%22:%5B%22${b}%22%5D,%22precomposed_overlay%22:false%7D`,onload:function(f){try{let d=JSON.parse(f.response);m("getStories()",d);c(d)}catch(d){m("getStories()","reject",d.message),e(d)}},onerror:function(f){m("getStories()",
"reject",f);e(f)}})})}function H(b){return new Promise((c,e)=>{GM_xmlhttpRequest({method:"GET",url:`https://www.instagram.com/web/search/topsearch/?query=${b}`,onload:function(f){let d=null;JSON.parse(f.response).users.forEach(g=>{g.user.username?.toLowerCase()===b?.toLowerCase()&&(d=g)});null!=d?(m("getUserId()",d),c(d)):qa(b).then(g=>{c(g)}).catch(g=>{alert("Can not find user info from getUserId()")})},onerror:function(f){m("getUserId()","reject",f);e(f)}})})}function qa(b){return new Promise((c,
e)=>{GM_xmlhttpRequest({method:"GET",url:`https://i.instagram.com/api/v1/users/web_profile_info/?username=${b}`,headers:{"X-IG-App-ID":R()},onload:function(f){try{let d=JSON.parse(f.response);null!=d?.data?.user?(f=d?.data,f.user.pk=f.user.id,m("getUserIdWithAgent()",d),c(f)):(m("getUserIdWithAgent()","reject","undefined"),e("undefined"))}catch(d){m("getUserIdWithAgent()","reject",d.message),e(d)}},onerror:function(f){m("getUserIdWithAgent()","reject",f);e(f)}})})}function na(b){return new Promise((c,
e)=>{GM_xmlhttpRequest({method:"GET",url:`https://i.instagram.com/api/v1/users/${b}/info/`,headers:{"User-Agent":"Mozilla/5.0 (Linux; Android 10; Pixel 7 XL)Build/RP1A.20845.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/5.0 Chrome/117.0.5938.60 Mobile Safari/537.36 Instagram 307.0.0.34.111"},onload:function(f){try{let d=JSON.parse(f.response);"ok"!==d.status?(m("getUserHighSizeProfile()","reject",d),e("faild")):(m("getUserHighSizeProfile()",d),c(d.user.hd_profile_pic_url_info?.url))}catch(d){m("getUserHighSizeProfile()",
"reject",d),e(d)}},onerror:function(f){m("getUserHighSizeProfile()","reject",f);e(f)}})})}function ra(b){return new Promise((c,e)=>{b||e("NOPATH");GM_xmlhttpRequest({method:"GET",url:`https://www.instagram.com/graphql/query/?query_hash=2c4c2e343a8f64c625ba02b2aa12c7f8&variables=%7B%22shortcode%22:%22${b}%22}`,onload:function(f){try{let d=JSON.parse(f.response);m("getPostOwner()",d);c(d.data.shortcode_media.owner.username)}catch(d){m("getPostOwner()","reject",d.message),e(d)}},onerror:function(f){m("getPostOwner()",
"reject",f);e(f)}})})}function ca(b){return new Promise((c,e)=>{b||e("NOPATH");GM_xmlhttpRequest({method:"GET",url:`https://www.instagram.com/graphql/query/?query_hash=2c4c2e343a8f64c625ba02b2aa12c7f8&variables=%7B%22shortcode%22:%22${b}%22}`,headers:{"User-Agent":"Mozilla/5.0 (Linux; Android 10; Pixel 7 XL)Build/RP1A.20845.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/5.0 Chrome/117.0.5938.60 Mobile Safari/537.36 Instagram 307.0.0.34.111"},onload:function(f){try{let d=JSON.parse(f.response);
m(d);"fail"===d.status?(m("Request with:","getBlobMediaWithQuery()",b),sa(b).then(g=>{c({type:"query_id",data:g.xdt_api__v1__media__shortcode__web_info.items[0]})}).catch(g=>{e(g)})):c({type:"query_hash",data:d.data})}catch(d){m("getBlobMedia()","reject",d.message),e(d)}},onerror:function(f){m("getBlobMedia()","reject",f);e(f)}})})}function sa(b){return new Promise((c,e)=>{b||e("NOPATH");GM_xmlhttpRequest({method:"GET",url:`https://www.instagram.com/graphql/query/?query_id=9496392173716084&variables={%22shortcode%22:%22${b}%22,%22__relay_internal__pv__PolarisFeedShareMenurelayprovider%22:true,%22__relay_internal__pv__PolarisIsLoggedInrelayprovider%22:true}`,
headers:{"User-Agent":"Mozilla/5.0 (Linux; Android 10; Pixel 7 XL)Build/RP1A.20845.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/5.0 Chrome/117.0.5938.60 Mobile Safari/537.36 Instagram 307.0.0.34.111","X-IG-App-ID":R()},onload:function(f){try{let d=JSON.parse(f.response);m(d);"fail"===d.status?(alert(`getBlobMediaWithQueryID(): Request failed with API response:\n${d.message}: ${d.feedback_message}`),m(`Request failed with API response ${d.message}: ${d.feedback_message}`),e(f)):(m("getBlobMediaWithQueryID()",
d.data),c(d.data))}catch(d){m("getBlobMediaWithQueryID()","reject",d.message),e(d)}},onerror:function(f){m("getBlobMediaWithQueryID()","reject",f);e(f)}})})}function J(b){return new Promise((c,e)=>{let f=`https://i.instagram.com/api/v1/media/${b}/info/`;null==b?(alert("Can not call Media API because of the media id is invalid."),m("getMediaInfo()","reject","Can not call Media API because of the media id is invalid."),w(!1),e(-1)):null==R()?(alert("Can not call Media API because of the app id is invalid."),
m("getMediaInfo()","reject","Can not call Media API because of the app id is invalid."),w(!1),e(-1)):GM_xmlhttpRequest({method:"GET",url:f,headers:{"User-Agent":window.navigator.userAgent,Accept:"*/*","X-IG-App-ID":R()},onload:function(d){d.finalUrl==f?(d=JSON.parse(d.response),m("getMediaInfo()",d),c(d)):((new URL(d.finalUrl)).pathname.startsWith("/accounts/login")?(m("getMediaInfo()","reject","The account must be logged in to access Media API."),alert("The account must be logged in to access Media API.")):
(m("getMediaInfo()","reject",'Unable to retrieve content because the API was redirected to "'+d.finalUrl+'"'),alert('Unable to retrieve content because the API was redirected to "'+d.finalUrl+'"')),w(!1),e(-1))},onerror:function(d){m("getMediaInfo()","reject",d);c(d)}})})}function pa(b){return(b=(new URL(b))?.searchParams?.get("ig_cache_key")?.split(".").at(0))?atob(b):null}function R(){let b=null;a('script[type="application/json"]').each(function(){const c=/"APP_ID":"([0-9]+)"/ig;null!=a(this).text().match(c)&&
null==b&&(b=[...a(this).text().matchAll(c)])});return b?b.at(0).at(-1):null}function w(b){b?(a('div[id^="mount"] > div > div > div:first').removeClass("x1s85apg"),a('div[id^="mount"] > div > div > div:first').css("z-index","20000")):(a('div[id^="mount"] > div > div > div:first').addClass("x1s85apg"),a('div[id^="mount"] > div > div > div:first').css("z-index",""))}function F(b){let c=a('body > div section:visible a[href^="/'+b+'"] span').filter(function(){return 0===a(this).children().length&&0===
a(this).find("svg").length&&a(this).text()?.toLowerCase()===b?.toLowerCase()}).parents("div:not([class]):not([style])").filter(function(){return a(this).text()?.toLowerCase()!==b?.toLowerCase()}).filter(function(){return 1<a(this).children().length}).first();0===c.length&&(c=a('body > div section:visible a[href^="/'+b+'"]').filter(function(){return 0<a(this).find("img").length}).parents("div:not([class]):not([style])").filter(function(){return a(this).text()?.toLowerCase()!==b?.toLowerCase()}).filter(function(){return 1<
a(this).children().length}).first());return c.children().filter(function(){return 10>a(this).height()}).first().children()}function E(b,c){a(".circle_wrapper").length?(a(".circle_wrapper span").text(`${b}/${c}`),b>=c&&a(".circle_wrapper").fadeOut(250,function(){a(this).remove()})):a("body").append(`<div class="circle_wrapper"><circle></circle><span>${b}/${c}</span></div>`)}function D(b,c){b=b?"hidden":"";a("body").append('<div class="IG_POPUP_DIG '+b+'"><div class="IG_POPUP_DIG_BG"></div><div class="IG_POPUP_DIG_MAIN"><div class="IG_POPUP_DIG_TITLE"></div><div class="IG_POPUP_DIG_BODY"></div></div></div>');
a(".IG_POPUP_DIG .IG_POPUP_DIG_MAIN .IG_POPUP_DIG_TITLE").append(`<div style="position:relative;min-height:36px;text-align:center;margin-bottom: 7px;"><div style="position:absolute;left:0px;line-height: 18px;"><kbd>Alt</kbd>+<kbd>Q</kbd> [<span data-ih-locale="CLOSE">${r("CLOSE")}</span>]</div><div style="line-height: 18px;">IG Helper v${GM_info.script.version}</div><div id="post_info" style="line-height: 14px;font-size:14px;">Post ID: <span id="article-id"></span></div><div class="IG_POPUP_DIG_BTN">${v.CLOSE}</div></div>`);
c&&(a(".IG_POPUP_DIG .IG_POPUP_DIG_MAIN .IG_POPUP_DIG_TITLE").append('<div style="text-align: center;" id="button_group"></div>'),a(".IG_POPUP_DIG .IG_POPUP_DIG_MAIN .IG_POPUP_DIG_TITLE > div#button_group").append(`<button id="batch_download_selected" data-ih-locale="BATCH_DOWNLOAD_SELECTED">${r("BATCH_DOWNLOAD_SELECTED")}</button>`),a(".IG_POPUP_DIG .IG_POPUP_DIG_MAIN .IG_POPUP_DIG_TITLE > div#button_group").append(`<button id="batch_download_direct" data-ih-locale="BATCH_DOWNLOAD_DIRECT">${r("BATCH_DOWNLOAD_DIRECT")}</button>`),
a(".IG_POPUP_DIG .IG_POPUP_DIG_MAIN .IG_POPUP_DIG_TITLE").append(`<label class="checkbox"><input value="yes" type="checkbox" /><span data-ih-locale="ALL_CHECK">${r("ALL_CHECK")}</span></label>`))}function x(b,c,e,f,d,g){return new Promise(h=>{setTimeout(()=>{w(!0);fetch(b).then(l=>l.blob().then(p=>{w(!1);ta(b,p,c,e,f,d,g);h(!0)}))},50)})}function ta(b,c,e,f,d,g,h){d=parseInt(d.toString().padEnd(13,"0"));q.RENAME_PUBLISH_DATE&&(d=parseInt(d.toString().padEnd(13,"0")));var l=new Date(d);d=document.createElement("a");
b=(new URL(b)).pathname.split("/").at(-1).split(".").slice(0,-1).join(".");const p=l.getFullYear().toString(),n=(l.getMonth()+1).toString().padStart(2,"0"),t=l.getDate().toString().padStart(2,"0"),y=l.getHours().toString().padStart(2,"0"),u=l.getMinutes().toString().padStart(2,"0"),z=l.getSeconds().toString().padStart(2,"0");l=k.fileRenameFormat.toUpperCase();var B={"%USERNAME%":e,"%SOURCE_TYPE%":f,"%SHORTCODE%":h??"","%YEAR%":p,"%2-YEAR%":p.substr(-2),"%MONTH%":n,"%DAY%":t,"%HOUR%":y,"%MINUTE%":u,
"%SECOND%":z,"%ORIGINAL_NAME%":b,"%ORIGINAL_NAME_FIRST%":b.split("_").at(0)};l=l.replace(/%[\w\-]+%/g,function(G){return B[G]||G});e=e+"_"+b+"."+g;d.href=URL.createObjectURL(c);d.setAttribute("download",q.AUTO_RENAME?l+"."+g:e);d.click();d.remove()}async function V(b,c){var e=(new Date).getTime();let f=Math.floor(e/1E3),d=a(b).attr("data-username")?a(b).attr("data-username"):k.GL_username;!d&&a(b).attr("data-path")&&(m("catching owner name from shortcode:",a(b).attr("data-href")),d=await ra(a(b).attr("data-path")).catch(h=>
{m("get username failed, replace with default string, error message:",h.message)}),null==d&&(d="NONE"));q.RENAME_PUBLISH_DATE&&a(b).attr("datetime")&&(f=parseInt(a(b).attr("datetime")));if(q.FORCE_RESOURCE_VIA_MEDIA)if(w(!0),e=await J(a(b).attr("media-id")),w(!1),"ok"===e.status){var g=null;e.items[0].video_versions?g=e.items[0].video_versions[0].url:(e.items[0].image_versions2.candidates.sort(function(h,l){let p=(new URL(h.url)).searchParams.get("stp"),n=(new URL(l.url)).searchParams.get("stp");
if(p&&n){if(p.length>n.length)return 1;if(p.length<n.length)return-1}else{if(h.width<l.width)return 1;if(h.width>l.width)return-1}return 0}),g=e.items[0].image_versions2.candidates[0].url);c?(b=new URL(g),b.host="scontent.cdninstagram.com",A(b.href)):x(g,d,a(b).attr("data-name"),f,a(b).attr("data-type"),a(b).attr("data-path"))}else q.USE_BLOB_FETCH_WHEN_MEDIA_RATE_LIMIT?c?(b=new URL(a(b).attr("data-href")),b.host="scontent.cdninstagram.com",A(b.href)):x(a(b).attr("data-href"),d,a(b).attr("data-name"),
f,a(b).attr("data-type"),a(b).attr("data-path")):alert("Fetch failed from Media API. API response message: "+e.message),m(e);else x(a(b).attr("data-href"),d,a(b).attr("data-name"),f,a(b).attr("data-type"),a(b).attr("data-path"))}function M(){for(let b of k.registerMenuIds)m("GM_unregisterMenuCommand",b),GM_unregisterMenuCommand(b);k.registerMenuIds.push(GM_registerMenuCommand(r("SETTING"),()=>{ea()},{accessKey:"w"}));k.registerMenuIds.push(GM_registerMenuCommand(r("DONATE"),()=>{GM_openInTab("https://ko-fi.com/snkoarashi",
{active:!0})},{accessKey:"d"}));k.registerMenuIds.push(GM_registerMenuCommand(r("DEBUG"),()=>{fa()},{accessKey:"z"}));k.registerMenuIds.push(GM_registerMenuCommand(r("FEEDBACK"),()=>{a(".IG_POPUP_DIG").remove();D();a(".IG_POPUP_DIG #post_info").text("Feedback Options");a(".IG_POPUP_DIG .IG_POPUP_DIG_BODY").append('<span style="display:block;text-align:center;">');a(".IG_POPUP_DIG .IG_POPUP_DIG_BODY span").append(`<button style="margin: 3px;" class="IG_REPORT_FORK"><a href="https://greasyfork.org/en/scripts/404535-ig-helper/feedback" target="_blank">${r("REPORT_FORK")}</a></button>`);
a(".IG_POPUP_DIG .IG_POPUP_DIG_BODY span").append(`<button style="margin: 3px;" class="IG_REPORT_GITHUB"><a href="https://github.com/SN-Koarashi/ig-helper/issues" target="_blank">${r("REPORT_GITHUB")}</a></button>`);a(".IG_POPUP_DIG .IG_POPUP_DIG_BODY span").append(`<button style="margin: 3px;" class="IG_REPORT_DISCORD"><a href="https://discord.gg/q3KT4hdq8x" target="_blank">${r("REPORT_DISCORD")}</a></button>`)},{accessKey:"f"}));k.registerMenuIds.push(GM_registerMenuCommand(r("CHECK_UPDATE_MENU"),
()=>{ha()},{accessKey:"c"}));k.registerMenuIds.push(GM_registerMenuCommand(r("RELOAD_SCRIPT"),()=>{ia()},{accessKey:"r"}))}function W(b){if(q.CHECK_UPDATE){var c=GM_getValue("G_CHECK_TIMESTAMP")??(new Date).getTime();(new Date).getTime()>parseInt(c)+1E3*b&&(GM_setValue("G_CHECK_TIMESTAMP",(new Date).getTime()),ha())}}function ha(){const b=GM_info.script.version;GM_xmlhttpRequest({method:"GET",url:"https://raw.githubusercontent.com/SN-Koarashi/ig-helper/refs/heads/master/main.js",onload:function(c){(c=
c.responseText.match(/\/\/\s+@version\s+([0-9.\-a-zA-Z]+)/i))&&c[1]?(c=c[1],m("Current version: ",b,"|","Remote version: ",c),c!==b?GM_notification({text:r("NOTICE_UPDATE_CONTENT"),title:r("NOTICE_UPDATE_TITLE"),tag:"ig_helper_notice",highlight:!0,timeout:5E3,zombieTimeout:5E3,image:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Instagram_icon.png/64px-Instagram_icon.png",onclick:e=>{e?.preventDefault();var f=GM_openInTab(GM_info.script.downloadURL);setTimeout(()=>{f.close()},250)}}):
m("there is no new update")):console.error("Could not find version in the remote script.")}})}function ea(){a(".IG_POPUP_DIG").remove();D();a(".IG_POPUP_DIG #post_info").text("Preference Settings");a(".IG_POPUP_DIG .IG_POPUP_DIG_TITLE > div").append('<select id="langSelect"></select><div style="font-size: 12px;">Some texts are machine-translated and may be inaccurate; translation contributions are welcome on GitHub.</div>');for(let b in ja)a(".IG_POPUP_DIG .IG_POPUP_DIG_TITLE > div #langSelect").append(`<option value="${b}" ${k.lang==
b?"selected":""}>${ja[b]}</option>`);for(let b in q){a(".IG_POPUP_DIG .IG_POPUP_DIG_BODY").append(`<label class="globalSettings${ua.includes(b)?" child":""}" title="${r(b+"_INTRO")}" data-ih-locale-title="${b+"_INTRO"}"><span data-ih-locale="${b}">${r(b)}</span> <input id="${b}" value="box" type="checkbox" ${!0===q[b]?"checked":""}><div class="chbtn"><div class="rounds"></div></div></label>`);if("MODIFY_VIDEO_VOLUME"===b)a('.IG_POPUP_DIG .IG_POPUP_DIG_BODY input[id="'+b+'"]').parent("label").on("contextmenu",
function(c){c.preventDefault();0===a(this).find("#tempWrapper").length&&(a(this).append('<div id="tempWrapper"></div>'),a(this).children("#tempWrapper").append('<input value="'+k.videoVolume+'" type="range" min="0" max="1" step="0.05" />'),a(this).children("#tempWrapper").append('<input value="'+k.videoVolume+'" step="0.05" type="number" />'),a(this).children("#tempWrapper").append(`<div class="IG_POPUP_DIG_BTN">${v.CLOSE}</div>`))});if("AUTO_RENAME"===b)a('.IG_POPUP_DIG .IG_POPUP_DIG_BODY input[id="'+
b+'"]').parent("label").on("contextmenu",function(c){c.preventDefault();0===a(this).find("#tempWrapper").length&&(a(this).append('<div id="tempWrapper"></div>'),a(this).children("#tempWrapper").append('<input id="date_format" value="'+k.fileRenameFormat+'" />'),a(this).children("#tempWrapper").append(`<div class="IG_POPUP_DIG_BTN">${v.CLOSE}</div>`))})}}function fa(){a(".IG_POPUP_DIG").remove();D();a(".IG_POPUP_DIG #post_info").text("IG Debug DOM Tree");a(".IG_POPUP_DIG .IG_POPUP_DIG_BODY").append('<textarea style="font-family: monospace;width:100%;box-sizing: border-box;height:300px;background: transparent;" readonly></textarea>');
a(".IG_POPUP_DIG .IG_POPUP_DIG_BODY").append('<span style="display:block;text-align:center;">');a(".IG_POPUP_DIG .IG_POPUP_DIG_BODY span").append(`<button style="margin: 3px;" class="IG_DISPLAY_DOM_TREE"><a>${r("SHOW_DOM_TREE")}</a></button>`);a(".IG_POPUP_DIG .IG_POPUP_DIG_BODY span").append(`<button style="margin: 3px;" class="IG_SELECT_DOM_TREE"><a>${r("SELECT_AND_COPY")}</a></button>`);a(".IG_POPUP_DIG .IG_POPUP_DIG_BODY span").append(`<button style="margin: 3px;" class="IG_DOWNLOAD_DOM_TREE"><a>${r("DOWNLOAD_DOM_TREE")}</a></button><br/>`);
a(".IG_POPUP_DIG .IG_POPUP_DIG_BODY span").append(`<button style="margin: 3px;" class="IG_REPORT_GITHUB"><a href="https://github.com/SN-Koarashi/ig-helper/issues" target="_blank">${r("REPORT_GITHUB")}</a></button>`);a(".IG_POPUP_DIG .IG_POPUP_DIG_BODY span").append(`<button style="margin: 3px;" class="IG_REPORT_DISCORD"><a href="https://discord.gg/q3KT4hdq8x" target="_blank">${r("REPORT_DISCORD")}</a></button>`)}function A(b){var c=document.createElement("a");c.href=b;c.target="_blank";document.body.appendChild(c);
c.click();c.remove()}function ia(){clearInterval(k.GL_repeat);k.GL_registerEventList.forEach(b=>{b.trigger.forEach(c=>{a(b.element).off("click",c)})});k.GL_registerEventList=[];a(".button_wrapper").remove();a(".IG_DWPROFILE, .IG_DWPROFILE, .IG_DWSTORY, .IG_DWSTORY_ALL, .IG_DWSTORY_THUMBNAIL, .IG_DWNEWTAB, .IG_DWHISTORY, .IG_DWHISTORY_ALL, .IG_DWHINEWTAB, .IG_DWHISTORY_THUMBNAIL, .IG_REELS, .IG_REELS_NEWTAB, .IG_REELS_THUMBNAIL").remove();a("[data-snig]").removeAttr("data-snig");k.pageLoaded=!1;k.firstStarted=
!1;k.currentURL=location.href;k.GL_observer.disconnect();m("main timer re-register completed")}function m(...b){var c=new Date;k.GL_logger.push({time:c.getTime(),content:[...b]});1E3<k.GL_logger.length&&(k.GL_logger=[{time:c.getTime(),content:["logger sliced"]},...k.GL_logger.slice(-999)]);console.log(`[${c.toISOString()}]`,...b)}function K(b,c,e,f=""){0===c.find("div.volume_slider").length?(c.append(`<div class="volume_slider ${f}" />`),c.find("div.volume_slider").append(`<div><input type="range" max="1" min="0" step="0.05" value="${k.videoVolume}" /></div>`),
c.find("div.volume_slider input").attr("style",`--ig-track-progress: ${100*k.videoVolume+"%"}`),c.find("div.volume_slider input").on("input",function(){var d=100*a(this).val()+"%";k.videoVolume=a(this).val();GM_setValue("G_VIDEO_VOLUME",a(this).val());a(this).attr("style",`--ig-track-progress: ${d}`);b.each(function(){m(`(${e})`,"video volume changed #slider");this.volume=k.videoVolume})}),c.find("div.volume_slider input").on("mouseenter",function(){var d=100*k.videoVolume+"%";a(this).attr("style",
`--ig-track-progress: ${d}`);a(this).val(k.videoVolume);b.each(function(){m(`(${e})`,"video volume changed #slider");this.volume=k.videoVolume})}),c.find("div.volume_slider").on("click",function(d){d.stopPropagation();d.preventDefault()})):c.find("div.volume_slider").remove()}function ma(b){function c(){g.css("transform",`scale(${h})`);g.css("left",`${l}px`);g.css("top",`${p}px`)}X();a("body").append(`<div id="imageViewer">
    	<div id="iv_header">
    		<div style="flex:1;">Image Viewer</div>
    		<div id="iv_close">${v.CLOSE}</div>
    	</div>
        <img id="iv_image" src="" />
    </div>`);const e=a("#imageViewer"),f=a("#iv_header"),d=a("#iv_close"),g=a("#iv_image");g.attr("src",b);e.css("display","flex");let h=.75,l=0,p=0,n=!1,t,y;g.on("load",()=>{l=(window.innerWidth-g[0].width)/2;p=(window.innerHeight-g[0].height)/2;c()});g.on("dragstart drop",u=>{u.preventDefault()});g.on("click",u=>{u.preventDefault();u.stopPropagation()});g.on("wheel",u=>{u.preventDefault();h+=0<u.originalEvent.deltaY?-.15:.15;h=Math.min(Math.max(.75,h),5);c()});g.on("mousedown",u=>{n=!0;t=u.pageX-
l;y=u.pageY-p;g.css("cursor","grabbing")});g.on("mouseup",()=>{n=!1;g.css("cursor","grab")});a(document).on("mousemove.igHelper",u=>{n&&(u.preventDefault(),l=u.pageX-t,p=u.pageY-y,c())});e.on("click",()=>{X()});d.on("click",()=>{X()});f.on("click",u=>{u.preventDefault();u.stopPropagation()})}function X(){a("#imageViewer").remove();a(document).off("mousemove.igHelper")}function va(){var b=Object.assign({},{"en-US":{NOTICE_UPDATE_TITLE:"Wololo! New version released.",NOTICE_UPDATE_CONTENT:"IG-Helper has released a new version, click here to update.",
CHECK_UPDATE:"Checking for Script Updates",CHECK_UPDATE_MENU:"Checking for Updates",CHECK_UPDATE_INTRO:"Check for updates when the script is triggered (check every 300 seconds).\nUpdate notifications will be sent as desktop notifications through the browser.",RELOAD_SCRIPT:"Reload Script",DONATE:"Donate",FEEDBACK:"Feedback",IMAGE_VIEWER:"Open Image In Viewer",NEW_TAB:"Open in New Tab",SHOW_DOM_TREE:"Show DOM Tree",SELECT_AND_COPY:"Select All and Copy from the Input Box",DOWNLOAD_DOM_TREE:"Download DOM Tree as a Text File",
REPORT_GITHUB:"Report an Issue on GitHub",REPORT_DISCORD:"Report an Issue on Discord Support Server",REPORT_FORK:"Report an Issue on Greasy Fork",DEBUG:"Debug Window",CLOSE:"Close",ALL_CHECK:"Select All",BATCH_DOWNLOAD_SELECTED:"Download Selected Resources",BATCH_DOWNLOAD_DIRECT:"Download All Resources",IMG:"Image",VID:"Video",DW:"Download",DW_ALL:"Download All Resources",THUMBNAIL_INTRO:"Download Video Thumbnail",LOAD_BLOB_ONE:"Loading Blob Media...",LOAD_BLOB_MULTIPLE:"Loading Blob Media and Others...",
LOAD_BLOB_RELOAD:"Detecting Blob Media, reloading...",NO_CHECK_RESOURCE:"You need to select a resource to download.",NO_VID_URL:"Cannot find video URL.",SETTING:"Settings",AUTO_RENAME:"Automatically Rename Files (Right-Click to Set)",RENAME_SHORTCODE:"Rename the File and Include Shortcode",RENAME_PUBLISH_DATE:"Set Renamed File Timestamp to Resource Publish Date",RENAME_LOCATE_DATE:"Modify Renamed File Timestamp Date Format (Right-Click to Set)",DISABLE_VIDEO_LOOPING:"Disable Video Auto-looping",HTML5_VIDEO_CONTROL:"Display HTML5 Video Controller",
REDIRECT_CLICK_USER_STORY_PICTURE:"Redirect When Clicking on User's Story Picture",FORCE_FETCH_ALL_RESOURCES:"Force Fetch All Resources in the Post",DIRECT_DOWNLOAD_VISIBLE_RESOURCE:"Directly Download the Visible Resources in the Post",DIRECT_DOWNLOAD_ALL:"Directly Download All Resources in the Post",MODIFY_VIDEO_VOLUME:"Modify Video Volume (Right-Click to Set)",SCROLL_BUTTON:"Enable Scroll Buttons for Reels Page",FORCE_RESOURCE_VIA_MEDIA:"Force Fetch Resource via Media API",USE_BLOB_FETCH_WHEN_MEDIA_RATE_LIMIT:"Use Alternative Methods to Download When the Media API is Not Accessible",
NEW_TAB_ALWAYS_FORCE_MEDIA_IN_POST:"Always Use Media API for 'Open in New Tab' in Posts",AUTO_RENAME_INTRO:"Auto rename file to custom format:\nCustom Format List: \n%USERNAME% - Username\n%SOURCE_TYPE% - Download Source\n%SHORTCODE% - Post Shortcode\n%YEAR% - Year when downloaded/published\n%2-YEAR% - Year (last two digits) when downloaded/published\n%MONTH% - Month when downloaded/published\n%DAY% - Day when downloaded/published\n%HOUR% - Hour when downloaded/published\n%MINUTE% - Minute when downloaded/published\n%SECOND% - Second when downloaded/published\n%ORIGINAL_NAME% - Original name of downloaded file\n%ORIGINAL_NAME_FIRST% - Original name of downloaded file (first part of name)\n\nIf set to false, the file name will remain unchanged.\nExample: instagram_321565527_679025940443063_4318007696887450953_n.jpg",
RENAME_SHORTCODE_INTRO:"Auto rename file to the following format:\nUSERNAME-TYPE-SHORTCODE-TIMESTAMP.FILETYPE\nExample: instagram-photo-CwkxyiVynpW-1670350000.jpg\n\nThis will ONLY work if [Automatically Rename Files] is set to TRUE.",RENAME_PUBLISH_DATE_INTRO:"Sets the timestamp in the file rename format to the resource publish date (browser time zone).\n\nThis feature only works when [Automatically Rename Files] is set to TRUE.",RENAME_LOCATE_DATE_INTRO:"Modify the renamed file timestamp date format to the browser's local time, and format it to your preferred regional date format.\n\nThis feature only works when [Automatically Rename Files] is set to TRUE.",
DISABLE_VIDEO_LOOPING_INTRO:"Disable video auto-looping in Reels and posts.",HTML5_VIDEO_CONTROL_INTRO:"Display the HTML5 video controller in video resource.\n\nThis will hide the custom video volume slider and replace it with the HTML5 controller. The HTML5 controller can be hidden by right-clicking on the video to reveal the original details.",REDIRECT_CLICK_USER_STORY_PICTURE_INTRO:"Redirect to a user's profile page when right-clicking on their avatar in the story area on the homepage.\nIf you use the middle mouse button to click, it will open in a new tab.",
FORCE_FETCH_ALL_RESOURCES_INTRO:"Force fetching of all resources (photos and videos) in a post via the Instagram API to remove the limit of three resources per post.",DIRECT_DOWNLOAD_VISIBLE_RESOURCE_INTRO:"Directly download the current resources available in the post.",DIRECT_DOWNLOAD_ALL_INTRO:"When you click the download button, all resources in the post will be forcibly fetched and downloaded.",MODIFY_VIDEO_VOLUME_INTRO:"Modify the video playback volume in Reels and posts (right-click to open the volume setting slider).",
SCROLL_BUTTON_INTRO:"Enable scroll buttons for the lower right corner of the Reels page.",FORCE_RESOURCE_VIA_MEDIA_INTRO:"The Media API will try to get the highest quality photo or video possible, but it may take longer to load.",USE_BLOB_FETCH_WHEN_MEDIA_RATE_LIMIT_INTRO:"When the Media API reaches its rate limit or cannot be used for other reasons, the Forced Fetch API will be used to download resources (the resource quality may be slightly lower).",NEW_TAB_ALWAYS_FORCE_MEDIA_IN_POST_INTRO:"The [Open in New Tab] button in posts will always use the Media API to obtain high-resolution resources.",
SKIP_VIEW_STORY_CONFIRM:"Skip the Confirmation Page for Viewing a Story/Highlight",SKIP_VIEW_STORY_CONFIRM_INTRO:"Automatically skip when confirmation page is shown in story or highlight."}},k.locale);return Object.keys(b).sort().reduce((c,e)=>{c[e]=b[e];return c},{})}async function ka(b){return new Promise((c,e)=>{GM_xmlhttpRequest({method:"GET",url:`https://raw.githubusercontent.com/SN-Koarashi/ig-helper/master/locale/translations/${b}.json`,onload:function(f){try{let d=JSON.parse(f.response);c(d)}catch(d){e(d)}},
onerror:function(f){m("getTranslationText()","reject",f);e(f)}})})}function r(b){const c=va();return void 0!=c[k.lang]&&void 0!=c[k.lang][b]?c[k.lang][b]:c["en-US"][b]}function Y(){a("[data-ih-locale]").each(function(){a(this).text(r(a(this).attr("data-ih-locale")))});a("[data-ih-locale-title]").each(function(){a(this).attr("title",r(a(this).attr("data-ih-locale-title")))})}const q={CHECK_UPDATE:!0,AUTO_RENAME:!0,RENAME_PUBLISH_DATE:!0,DISABLE_VIDEO_LOOPING:!1,HTML5_VIDEO_CONTROL:!1,REDIRECT_CLICK_USER_STORY_PICTURE:!1,
FORCE_FETCH_ALL_RESOURCES:!1,DIRECT_DOWNLOAD_VISIBLE_RESOURCE:!1,DIRECT_DOWNLOAD_ALL:!1,MODIFY_VIDEO_VOLUME:!1,SCROLL_BUTTON:!0,FORCE_RESOURCE_VIA_MEDIA:!1,USE_BLOB_FETCH_WHEN_MEDIA_RATE_LIMIT:!1,NEW_TAB_ALWAYS_FORCE_MEDIA_IN_POST:!1,SKIP_VIEW_STORY_CONFIRM:!1},ua=["RENAME_PUBLISH_DATE","USE_BLOB_FETCH_WHEN_MEDIA_RATE_LIMIT","NEW_TAB_ALWAYS_FORCE_MEDIA_IN_POST"],v={DOWNLOAD:'<svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000"><g><rect fill="none" height="24" width="24"/></g><g><path d="M18,15v3H6v-3H4v3c0,1.1,0.9,2,2,2h12c1.1,0,2-0.9,2-2v-3H18z M17,11l-1.41-1.41L13,12.17V4h-2v8.17L8.41,9.59L7,11l5,5 L17,11z"/></g></svg>',
NEW_TAB:'<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M19 19H5V5h7V3H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2v-7h-2v7zM14 3v2h3.59l-9.83 9.83 1.41 1.41L19 6.41V10h2V3h-7z"/></svg>',THUMBNAIL:'<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M19 5v14H5V5h14m0-2H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-4.86 8.86l-3 3.87L9 13.14 6 17h12l-3.86-5.14z"/></svg>',
DOWNLOAD_ALL:'<svg xmlns="http://www.w3.org/2000/svg" enable-background="new 0 0 24 24" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000"><g><rect fill="none" height="24" width="24"/></g><g><g><polygon points="18,6.41 16.59,5 12,9.58 7.41,5 6,6.41 12,12.41"/><polygon points="18,13 16.59,11.59 12,16.17 7.41,11.59 6,13 12,19"/></g></g></svg>',CLOSE:'<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12 19 6.41z"/></svg>',
FULLSCREEN:'<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M7 14H5v5h5v-2H7v-3zm-2-4h2V7h3V5H5v5zm12 7h-3v2h5v-5h-2v3zM14 5v2h3v3h2V5h-5z"/></svg>'},wa=GM_getResourceText("INTERNAL_CSS"),ja=JSON.parse(GM_getResourceText("LOCALE_MANIFEST"));var k={videoVolume:GM_getValue("G_VIDEO_VOLUME")?GM_getValue("G_VIDEO_VOLUME"):1,tempFetchRateLimit:!1,fileRenameFormat:GM_getValue("G_RENAME_FORMAT")?GM_getValue("G_RENAME_FORMAT"):
"%USERNAME%-%SOURCE_TYPE%-%SHORTCODE%-%YEAR%%MONTH%%DAY%_%HOUR%%MINUTE%%SECOND%_%ORIGINAL_NAME_FIRST%",registerMenuIds:[],locale:{},lang:GM_getValue("lang")||navigator.language||navigator.userLanguage,currentURL:location.href,firstStarted:!1,pageLoaded:!1,GL_registerEventList:[],GL_logger:[],GL_referrer:null,GL_postPath:null,GL_username:null,GL_repeat:null,GL_dataCache:{stories:{},highlights:{}},GL_observer:new MutationObserver(function(){T()})};(function(){for(let b in q)null!=GM_getValue(b)&&"boolean"===
typeof GM_getValue(b)&&(q[b]=GM_getValue(b),"MODIFY_VIDEO_VOLUME"===b&&!0!==GM_getValue(b)&&(k.videoVolume=1))})();GM_addStyle(wa);M();ka(k.lang).then(b=>{k.locale[k.lang]=b;Y();M();W(300)}).catch(b=>{M();W(300);k.lang.startsWith("en")||console.error("getTranslationText catch error:",b)});m("Script Loaded",GM_info.script.name,"version:",GM_info.script.version);setInterval(function(){if(0<a("div#splash-screen").length&&!a("div#splash-screen").is(":hidden")||location.pathname.match(/^\/(explore(\/.*)?|challenge\/?.*|direct\/?.*|qr\/?|accounts\/.*|emails\/.*|language\/?.*?|your_activity\/?.*|settings\/help(\/.*)?$)$/ig)||
!location.hostname.startsWith("www."))k.pageLoaded=!1;else if(k.currentURL!=location.href||!k.firstStarted||!k.pageLoaded){console.log("Main Timer","trigging");clearInterval(k.GL_repeat);k.pageLoaded=!1;k.firstStarted=!0;k.currentURL=location.href;k.GL_observer.disconnect();if(location.href.startsWith("https://www.instagram.com/p/")||location.pathname.match(/^\/(.*?)\/(p|reel)\//ig)||location.href.startsWith("https://www.instagram.com/reel/")){k.GL_dataCache.stories={};k.GL_dataCache.highlights={};
m("isDialog");var b=setInterval(()=>{0<a('body > div[class]:not([id^="mount"]) div div[role="dialog"] article,\n                                section:visible > main > div > div > div > div > div > hr,\n                                body > div[id^="mount"] section nav + div > article,\n                                section:visible > main > div > div > article > div > div > div > div > div > header\n                            ').length&&(clearInterval(b),setTimeout(()=>{T(!1)},15))},100);k.pageLoaded=
!0}location.href.startsWith("https://www.instagram.com/reels/")&&(m("isReels"),setTimeout(()=>{P(!1)},150),k.pageLoaded=!0);if("https://www.instagram.com/"==location.href.split("?")[0]){k.GL_dataCache.stories={};k.GL_dataCache.highlights={};let c=null!=k.GL_referrer?.match(/^\/(stories|highlights)\//ig);m("isHomepage",c);setTimeout(()=>{T(!1,c);const e=a('div[id^="mount"] > div > div div > section > main div:not([class]):not([style]) > div > article')?.parent()[0];e&&k.GL_observer.observe(e,{childList:!0})},
150);k.pageLoaded=!0}a("header > *[class]:first-child img[alt]").length&&location.pathname.match(/^(\/)([0-9A-Za-z\.\-_]+)\/?(tagged|reels|saved)?\/?$/ig)&&!location.pathname.match(/^(\/explore\/?$|\/stories(\/.*)?$|\/p\/)/ig)&&(m("isProfile"),setTimeout(()=>{da(!1)},150),k.pageLoaded=!0);k.pageLoaded||(location.href.match(/^(https:\/\/www\.instagram\.com\/stories\/highlights\/)/ig)?(k.GL_dataCache.highlights={},m("isHighlightsStory"),N(!1),k.GL_repeat=setInterval(()=>{O(!1)},250),a(".IG_DWHISTORY").length&&
setTimeout(()=>{q.SKIP_VIEW_STORY_CONFIRM&&a('div[id^="mount"] section:last-child > div > div div[role="button"]').filter(function(){return 0===a(this).children().length&&""!==this.textContent.trim()})?.trigger("click");k.pageLoaded=!0},150)):location.href.match(/^(https:\/\/www\.instagram\.com\/stories\/)/ig)?(m("isStory"),0<a('div[id^="mount"] section > div > a[href="/"]').length&&(a(".IG_DWSTORY").remove(),a(".IG_DWNEWTAB").remove(),a(".IG_DWSTORY_THUMBNAIL").length&&a(".IG_DWSTORY_THUMBNAIL").remove(),
I(!1),setTimeout(()=>{I(!1)},150)),a(".IG_DWSTORY").length&&setTimeout(()=>{q.SKIP_VIEW_STORY_CONFIRM&&a('div[id^="mount"] section:last-child > div > div div[role="button"]').filter(function(){return 0===a(this).children().length&&""!==this.textContent.trim()})?.click();k.pageLoaded=!0},150)):(k.pageLoaded=!1,a(".IG_DWSTORY").length&&a(".IG_DWSTORY").remove(),a(".IG_DWSTORY_ALL").length&&a(".IG_DWSTORY_ALL").remove(),a(".IG_DWNEWTAB").length&&a(".IG_DWNEWTAB").remove(),a(".IG_DWSTORY_THUMBNAIL").length&&
a(".IG_DWSTORY_THUMBNAIL").remove(),a(".IG_DWHISTORY").length&&a(".IG_DWHISTORY").remove(),a(".IG_DWHISTORY_ALL").length&&a(".IG_DWHISTORY_ALL").remove(),a(".IG_DWHINEWTAB").length&&a(".IG_DWHINEWTAB").remove(),a(".IG_DWHISTORY_THUMBNAIL").length&&a(".IG_DWHISTORY_THUMBNAIL").remove()));W(300);k.GL_referrer=(new URL(location.href)).pathname}},250);a(function(){function b(){let c=a('div[id^="mount"]')[0];var e="";k.GL_logger.forEach(f=>{var d=JSON.stringify(f.content,function(g,h){if(Array.isArray(this)&&
"object"===typeof h&&h instanceof jQuery){g=[];for(var l of h)g.push({tagName:l.tagName,id:l.id,className:l.className});return g}return h},"\t");e+=`${(new Date(f.time)).toISOString()}: ${d}\n`});a(".IG_POPUP_DIG .IG_POPUP_DIG_BODY textarea").text("Logger:\n"+e+"\n-----\n\nLocation: "+location.pathname+"\nDOM Tree with div#mount:\n"+c.innerHTML)}a("body").on("click",".IG_POPUP_DIG .IG_POPUP_DIG_BODY .IG_DISPLAY_DOM_TREE",function(){b()});a("body").on("click",".IG_POPUP_DIG .IG_POPUP_DIG_BODY .IG_SELECT_DOM_TREE",
function(){a(".IG_POPUP_DIG .IG_POPUP_DIG_BODY textarea").select();document.execCommand("copy")});a("body").on("click",".IG_POPUP_DIG .IG_POPUP_DIG_BODY .IG_DOWNLOAD_DOM_TREE",function(){0===a(".IG_POPUP_DIG .IG_POPUP_DIG_BODY textarea").text().length&&b();var c=a(".IG_POPUP_DIG .IG_POPUP_DIG_BODY textarea").text(),e=document.createElement("a");c=new Blob([c],{type:"text/plain"});e.href=URL.createObjectURL(c);e.download="DOMTree-"+(new Date).getTime()+".txt";document.body.appendChild(e);e.click();
e.remove()});a("body").on("click",".IG_POPUP_DIG_BTN, .IG_POPUP_DIG_BG",function(){0<a(this).parent("#tempWrapper").length?a(this).parent("#tempWrapper").fadeOut(250,function(){a(this).remove()}):a(".IG_POPUP_DIG").remove()});a(window).on("keydown",function(c){"81"==c.which&&c.altKey&&(a(".IG_POPUP_DIG").remove(),c.preventDefault());"87"==c.which&&c.altKey&&(ea(),c.preventDefault());"90"==c.which&&c.altKey&&(fa(),c.preventDefault());"82"==c.which&&c.altKey&&(ia(),c.preventDefault());"83"==c.which&&
c.altKey&&(location.href.match(/^(https:\/\/www\.instagram\.com\/stories\/)/ig)&&0<a(".IG_DWSTORY").length&&a(".IG_DWSTORY")?.trigger("click"),location.href.match(/^(https:\/\/www\.instagram\.com\/stories\/highlights\/)/ig)&&0<a(".IG_DWHISTORY").length&&a(".IG_DWHISTORY")?.trigger("click"),c.preventDefault())});a("body").on("change",".IG_POPUP_DIG input",function(){var c=a(this).attr("id");if(c&&void 0!==q[c]){let e=a(this).prop("checked");GM_setValue(c,e);q[c]=e;console.log("user settings",c,e)}});
a("body").on("click",".IG_POPUP_DIG .globalSettings",function(c){0<a(this).find("#tempWrapper").length&&c.preventDefault()});a("body").on("change",".IG_POPUP_DIG #tempWrapper input:not(#date_format)",function(){let c=a(this).val();"range"==a(this).attr("type")?a(this).next().val(c):a(this).prev().val(c);0<=c&&1>=c&&(k.videoVolume=c,GM_setValue("G_VIDEO_VOLUME",c))});a("body").on("input",".IG_POPUP_DIG #tempWrapper input:not(#date_format)",function(){if("range"==a(this).attr("type")){var c=a(this).val();
a(this).next().val(c)}else c=a(this).val(),0<=c&&1>=c?a(this).prev().val(c):0>c?a(this).val(0):a(this).val(1)});a("body").on("input",".IG_POPUP_DIG #tempWrapper input#date_format",function(){GM_setValue("G_RENAME_FORMAT",a(this).val());k.fileRenameFormat=a(this).val()});a("body").on("click",'a[data-needed="direct"]',function(c){c.preventDefault();V(this)});a("body").on("click",".IG_POPUP_DIG_BODY .newTab",function(){if(q.FORCE_RESOURCE_VIA_MEDIA&&q.NEW_TAB_ALWAYS_FORCE_MEDIA_IN_POST)V(a(this).parent().children("a").first()[0],
!0);else{var c=new URL(a(this).parent().children("a").attr("data-href"));c.host="scontent.cdninstagram.com";A(c.href)}});a("body").on("click",".IG_POPUP_DIG_BODY .videoThumbnail",function(){let c=(new Date).getTime();q.RENAME_PUBLISH_DATE&&a(this).parent().children("a").attr("datetime")&&(c=a(this).parent().children("a").attr("datetime"));let e=a(this).parent().children("a").attr("data-path")??a("#article-id").text();x(a(this).parent().children("a").find("img").first().attr("src"),a(this).parent().children("a").attr("data-username"),
"thumbnail",c,"jpg",e)});a("body").on("click",".IG_DWSTORY",function(){I(!0)});a("body").on("click",".IG_DWSTORY_ALL",function(){oa()});a("body").on("click",".IG_DWNEWTAB",function(c){c.preventDefault();I(!0,!0,!0)});a("body").on("click",".IG_DWSTORY_THUMBNAIL",function(){Q(!0)});a("body").on("click",".IG_DWPROFILE",function(c){c.stopPropagation();da(!0)});a("body").on("click",".IG_DWHISTORY",function(){N(!0)});a("body").on("click",".IG_DWHISTORY_ALL",function(){la()});a("body").on("click",".IG_DWHINEWTAB",
function(c){c.preventDefault();N(!0,!0)});a("body").on("click",".IG_DWHISTORY_THUMBNAIL",function(){O(!0)});a("body").on("click",".IG_REELS",function(){P(!0,!0)});a("body").on("click",".IG_REELS_NEWTAB",function(){P(!0,!0,!0)});a("body").on("click",".IG_REELS_THUMBNAIL",function(){P(!0,!1)});a("body").on("mousedown",'button[role="menuitem"], div[role="menuitem"], ul > li[tabindex="-1"] > div[role="button"]',function(c){if((3===c.which||2===c.which)&&"https://www.instagram.com/"===location.href&&q.REDIRECT_CLICK_USER_STORY_PICTURE&&
(c.preventDefault(),0<a(this).find("canvas._aarh, canvas + span > img").length)){const e="https://www.instagram.com/"+a(this).children("div").last().text();2===c.which?GM_openInTab(e):location.href=e}});a("body").on("change",".IG_POPUP_DIG_TITLE .checkbox",function(){var c=a(this).find("input").prop("checked");a(".IG_POPUP_DIG_BODY .inner_box").each(function(){a(this).prop("checked",c)})});a("body").on("change",".IG_POPUP_DIG_BODY .inner_box",function(){var c=a(".IG_POPUP_DIG_BODY .inner_box:checked").length,
e=a(".IG_POPUP_DIG_BODY .inner_box").length;a(".IG_POPUP_DIG_TITLE .checkbox").find("input").prop("checked",c==e)});a("body").on("click",".IG_POPUP_DIG_TITLE #batch_download_selected",function(){let c=0;a('.IG_POPUP_DIG_BODY a[data-needed="direct"]').each(function(){a(this).prev().children("input").prop("checked")&&(a(this).trigger("click"),c++)});0==c&&alert(r("NO_CHECK_RESOURCE"))});a("body").on("change",".IG_POPUP_DIG_TITLE #langSelect",function(){GM_setValue("lang",a(this).val());k.lang=a(this).val();
k.lang?.startsWith("en")||null!=k.locale[k.lang]?(Y(),M()):ka(k.lang).then(c=>{k.locale[k.lang]=c;Y();M()}).catch(c=>{console.error("getTranslationText catch error:",c)})});a("body").on("click",".IG_POPUP_DIG_TITLE #batch_download_direct",function(){a('.IG_POPUP_DIG_BODY a[data-needed="direct"]').each(function(){a(this).trigger("click")})});(new MutationObserver(c=>{for(const e of c)"childList"===e.type&&e.addedNodes.forEach(f=>{f=a(f).find("video");if(0<f.length&&(q.MODIFY_VIDEO_VOLUME&&f.each(function(){a(this).on("play playing",
function(){a(this).data("modify")||(a(this).attr("data-modify",!0),this.volume=k.videoVolume,m("(audio_observer) Added video event listener #modify"))})}),location.pathname.match(/^(\/stories\/)/ig))){const d=null!=location.pathname.match(/^(\/stories\/highlights\/)/ig),g=d?"highlight":"story";f.each(function(){a(this).on("timeupdate",function(){if(!a(this).data("modify-thumbnail")){let l=a(this);0===l.parents("div[style][class]").filter(function(){return a(this).width()==l.width()}).find(".IG_DWSTORY_THUMBNAIL, .IG_DWHISTORY_THUMBNAIL").length?
(a(this).attr("data-modify-thumbnail",!0),d?O(!1):Q(!1),m(`(${g})`,"Manually inserting thumbnail button")):(a(this).attr("data-modify-thumbnail",!0),m(`(${g})`,"Thumbnail button already inserted"))}});var h=a(this);if(q.HTML5_VIDEO_CONTROL){if(!h.data("controls")){m(`(${g})`,"Added video html5 contorller #modify");q.MODIFY_VIDEO_VOLUME&&(this.volume=k.videoVolume,h.on("loadstart",function(){this.volume=k.videoVolume}));let l=h.parents("div").filter(function(){return null==a(this).attr("class")&&null==
a(this).attr("style")}).first(),p=l.next();p.hide();let n=l.find('div[class][role="button"]');n.hide();const t=function(y){y.preventDefault();h.css("z-index","2");h.attr("controls",!0);n.hide();p.hide();K(h,h.parents("div[style][class]").filter(function(){return a(this).width()==h.width()}).first(),g,"vertical")};h.parent().find("video + div").on("contextmenu",t);n.on("contextmenu",t);p.on("contextmenu",t);h.on("contextmenu",function(y){y.preventDefault();h.css("z-index","-1");h.removeAttr("controls");
p.show();n.show();K(h,h.parents("div[style][class]").filter(function(){return a(this).width()==h.width()}).first(),g,"vertical")});h.on("volumechange",function(){let y=l.parent().find('svg > path[d^="M1.5 13.3c-.8 0-1.5.7-1.5 1.5v18.4c0"], svg > path[d^="M16.636 7.028a1.5 1.5"]').parents('[role="button"]').first();var u=0===y.find('svg > path[d^="M16.636"]').length;this.muted!=u&&(this.volume=k.videoVolume,y?.trigger("click"));a(this).attr("data-completed")&&(k.videoVolume=this.volume,GM_setValue("G_VIDEO_VOLUME",
this.volume));this.volume==k.videoVolume&&a(this).attr("data-completed",!0)});h.css("position","absolute");h.css("z-index","2");h.attr("data-controls",!0);h.attr("controls",!0)}}else K(h,h.parents("div[style][class]").filter(function(){return a(this).width()==h.width()}).first(),g,"vertical")})}})})).observe(a('div[id^="mount"]')[0],{childList:!0,subtree:!0})})})(jQuery);
