// ==UserScript==
// @name                Instagram Download Button
// @namespace           https://github.com/y252328/Instagram_Download_Button
// @version             1.17.18
// @compatible          chrome
// @author              ZhiYu
// @match               https://www.instagram.com/*
// @icon                https://www.google.com/s2/favicons?sz=64&domain=instagram.com
// @grant               none
// @license             MIT
// @downloadURL https://raw.githubusercontent.com/siritami/test1/release/release/Instagram20Download20Button.user.js
// @updateURL https://raw.githubusercontent.com/siritami/test1/release/release/Instagram20Download20Button.meta.js
// ==/UserScript==
(function(){function t(a,b,c){a=a.querySelectorAll(b);for(b=0;b<a.length;++b){let d=a[b];if(d.querySelector(c))return d}return null}function M(a,b){a.append(b)}function N(a,b){a.parentNode.parentNode.append(b)}function O(a,b){a.parentNode.parentNode.parentNode.appendChild(b,a.parentNode.parentNode)}function P(a,b){a.parentNode.parentNode.parentNode.append(b)}function u(a,b,c){let d=C('<svg id="Capa_1" style="fill:%color;" viewBox="0 0 482.239 482.239" xmlns="http://www.w3.org/2000/svg" height="24" width="24">\n    <path d="m465.016 0h-344.456c-9.52 0-17.223 7.703-17.223 17.223v86.114h-86.114c-9.52 0-17.223 7.703-17.223 17.223v344.456c0 9.52 7.703 17.223 17.223 17.223h344.456c9.52 0 17.223-7.703 17.223-17.223v-86.114h86.114c9.52 0 17.223-7.703 17.223-17.223v-344.456c0-9.52-7.703-17.223-17.223-17.223zm-120.56 447.793h-310.01v-310.01h310.011v310.01zm103.337-103.337h-68.891v-223.896c0-9.52-7.703-17.223-17.223-17.223h-223.896v-68.891h310.011v310.01z"/>\n</svg>',
b,"newtab-btn","16px");c(a,d);b=C('<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" height="24" width="24"\n     viewBox="0 0 477.867 477.867" style="fill:%color;" xml:space="preserve">\n    <g>\n        <path d="M443.733,307.2c-9.426,0-17.067,7.641-17.067,17.067v102.4c0,9.426-7.641,17.067-17.067,17.067H68.267\n            c-9.426,0-17.067-7.641-17.067-17.067v-102.4c0-9.426-7.641-17.067-17.067-17.067s-17.067,7.641-17.067,17.067v102.4\n            c0,28.277,22.923,51.2,51.2,51.2H409.6c28.277,0,51.2-22.923,51.2-51.2v-102.4C460.8,314.841,453.159,307.2,443.733,307.2z"/>\n    </g>\n    <g>\n        <path d="M335.947,295.134c-6.614-6.387-17.099-6.387-23.712,0L256,351.334V17.067C256,7.641,248.359,0,238.933,0\n            s-17.067,7.641-17.067,17.067v334.268l-56.201-56.201c-6.78-6.548-17.584-6.36-24.132,0.419c-6.388,6.614-6.388,17.099,0,23.713\n            l85.333,85.333c6.657,6.673,17.463,6.687,24.136,0.031c0.01-0.01,0.02-0.02,0.031-0.031l85.333-85.333\n            C342.915,312.486,342.727,301.682,335.947,295.134z"/>\n    </g>\n</svg>',
b,"download-btn","14px");c(a,b)}function C(a,b,c,d){let e=document.createElement("a");e.innerHTML=a.replace("%color",b);e.setAttribute("class","custom-btn "+c);e.setAttribute("target","_blank");e.setAttribute("style","cursor: pointer;margin-left: "+d+";margin-top: 8px;z-index: 999;");e.onclick=v;e.onmouseenter=w;c.includes("newtab")?e.setAttribute("title","Open in new tab"):e.setAttribute("title","Download");return e}function v(a){var b=a.currentTarget;a.stopPropagation();a.preventDefault();window.location.pathname.includes("stories")?
Q(b):document.querySelector("header")&&document.querySelector("header").contains(b)?(a=document.querySelector("header img").getAttribute("src"),0<a.length&&(b.getAttribute("class").includes("download-btn")?(b=document.querySelector("header h2").textContent,x(a,b)):y(a))):R(b)}function w(a){a=a.currentTarget;if(window.location.pathname.includes("stories"))S(a);else if(document.querySelector("header")&&document.querySelector("header").contains(a)){let b=document.querySelector("header img").getAttribute("src");
a.setAttribute("href",b)}else T(a)}async function T(a){var b=D(a);({url:b}=await E(a,b));a.setAttribute("href",b)}async function R(a){try{let e=D(a),{url:g,mediaIndex:f}=await E(a,e);if(0<g.length)if(a.getAttribute("class").includes("download-btn")){let m=g.split("?")[0].split("\\").pop().split("/").pop();m=m.substring(0,m.lastIndexOf("."));let l=new Date(e.querySelector("time").getAttribute("datetime"));var b;if(!(b=e.querySelector("header a")))a:{a=e;var c=a.querySelector('article section + * a[href^="/"][href$="/"]');
if(c)b=c;else{var d=a.querySelector("canvas ~ * img");if(d){d=d.getAttribute("alt");let h=a.querySelectorAll("a");for(c=0;c<h.length;c++){const n=h[c].getAttribute("href").replace(/\//g,"");if(d.includes(n)){b=h[c];break a}}b=void 0}else b=document.querySelector("h2[dir]").innerText}}b=b.getAttribute("href").replace(/\//g,"");let p=F(e),k=G("%id%-%datetime%-%medianame%",b,l,m,p,f);x(g,k)}else y(g)}catch(e){return console.log(`Uncatched in postOnClicked(): ${e}\n${e.stack}`),null}}function D(a){for(;a&&
"ARTICLE"!==a.tagName&&"MAIN"!==a.tagName;)a=a.parentNode;return a}async function E(a,b){a=null;let c=0;if(0===b.querySelectorAll("li[style][class]").length){if(a=await z(b),null===a){var d=b.querySelector("video");if(d)if(a=d.getAttribute("src"),d.hasAttribute("videoURL"))a=d.getAttribute("videoURL");else{if(null===a||a.includes("blob"))a=await H(b,d)}else b.querySelector("article  div[role] div > img")?a=b.querySelector("article  div[role] div > img").getAttribute("src"):console.log("Err: not find media at handle post single")}}else{d=
location.pathname.startsWith("/p/");c=[...b.querySelectorAll("div._acnb")].reduce((e,g,f)=>2===g.classList.length?f:e,null);if(null===c)throw"Cannot find the media index";a=await z(b,c);if(null===a){d=[...b.querySelectorAll(`:scope > div > div:nth-child(${d?1:2}) > div > div:nth-child(1) ul li[style*="translateX"]`)];const e=Math.max(...d.map(g=>g.clientWidth));d=d.reduce((g,f)=>{const m=Math.round(Number(f.style.transform.match(/-?(\d+)/)[1])/e);return{...g,[m]:f}},{})[c];if(d.querySelector("video"))if(d=
d.querySelector("video"),a=d.getAttribute("src"),d.hasAttribute("videoURL"))a=d.getAttribute("videoURL");else{if(null===a||a.includes("blob"))a=await H(b,d)}else d.querySelector("img")&&(a=d.querySelector("img").getAttribute("src"))}}return{url:a,mediaIndex:c}}function U(){let a=document.querySelector('div[style^="transform"]').parentElement;return Array.from(a.parentElement.children).indexOf(a)}async function z(a,b=0){try{const d=/"X-IG-App-ID":"([\d]+)"/,e=/instagram:\/\/media\?id=(\d+)|["' ]media_id["' ]:["' ](\d+)["' ]/;
function g(l){return"video_versions"in l?l.video_versions[0].url:l.image_versions2.candidates[0].url}var c=function(){let l=document.querySelectorAll("body > script");for(let p=0;p<l.length;++p){let k=l[p].text.match(d);if(k)return k[1]}console.log("Cannot find app id");return null}();if(!c)return null;c={method:"GET",headers:{Accept:"*/*","X-IG-App-ID":c},credentials:"include",mode:"cors"};let f=await async function(){async function l(){let k=await F(a);if(!k)return null;if(!(k in A)){var h=await (await fetch(`https://www.instagram.com/p/${k}/`)).text();
h=h?h.match(e):[];let n=null;for(let q=0;q<h.length;++q)h[q]&&(n=h[q]);if(!n)return null;A[k]=n}return A[k]}function p(){let k=document.querySelectorAll('script[type="application/json"]');for(let n=0;n<k.length;n++){var h=k[n].text.match(/"pk":"(\d+)","id":"[\d_]+"/);if(h){if(!window.location.href.includes("highlights"))return h[1];h=Array.from(k[n].text.matchAll(/"pk":"(\d+)","id":"[\d_]+"/g),V=>V[1]);const q=U();if(h.length>q)return h[q]}}}return function(){let k=window.location.href,h=k.match(/www.instagram.com\/stories\/[^\/]+\/(\d+)/);
if(!k.includes("highlights")&&h)return h[1]}()||await l()||p()}();if(!f)return console.log("Cannot find media id"),null;if(!(f in B)){let l=await fetch("https://i.instagram.com/api/v1/media/"+f+"/info/",c);if(200!==l.status)return console.log(`Fetch info API failed with status code: ${l.status}`),null;let p=await l.json();B[f]=p}let m=B[f];return"carousel_media"in m.items[0]?g(m.items[0].carousel_media[b]):g(m.items[0])}catch(d){return console.log(`Uncatched in getUrlFromInfoApi(): ${d}\n${d.stack}`),
null}}function F(a){a=a.querySelectorAll("a");for(let c=0;c<a.length;++c){var b=a[c].getAttribute("href");if(b&&(b=b.match(W)))return b[1]}return null}async function H(a,b){var c=b.getAttribute("poster");a=a.querySelectorAll("time");a=a[a.length-1].parentNode.parentNode.href;c=c.match(/\/([^\/?]*)\?/)[1];c=(await (await fetch(a)).text()).match(new RegExp(`${c}.*?video_versions.*?url":("[^"]*")`,"s"));c=JSON.parse(c[1]);c=c.replace(/^(?:https?:\/\/)?(?:[^@\/\n]+@)?(?:www\.)?([^:\/?\n]+)/g,"https://scontent.cdninstagram.com");
b.setAttribute("videoURL",c);return c}async function S(a){var b=I(a);b=await J(a,b);a.setAttribute("href",b)}async function Q(a){var b=I(a);let c=await J(a,b);var d=/\/stories\/(.*)\/.*\//;if(a.getAttribute("class").includes("download-btn")){a=c.split("?")[0].split("\\").pop().split("/").pop();a=a.substring(0,a.lastIndexOf("."));let e=new Date(b.querySelector("time").getAttribute("datetime")),g="unkown";(b=b.querySelector("header a"))&&(g=b.getAttribute("href").replace(/\//g,""));"unkown"===g&&(d=
window.location.pathname.match(d))&&(g=d[1]);d=G("%id%-%datetime%-%medianame%",g,e,a);x(c,d)}else y(c)}function I(a){for(;a&&"SECTION"!==a.tagName;)a=a.parentNode;return a}async function J(a,b){a=await z(a);if(!a)if(b.querySelector("video > source"))a=b.querySelector("video > source").getAttribute("src");else if(b.querySelector('img[decoding="sync"]')){a=b.querySelector('img[decoding="sync"]').srcset.split(/ \d+w/g)[0].trim();if(0<a.length)return a;a=b.querySelector('img[decoding="sync"]').getAttribute("src")}else b.querySelector("video")&&
(a=b.querySelector("video").getAttribute("src"));return a}function G(a,b,c,d,e=+new Date,g="0"){a=a.replace(/%id%/g,b);b=a.replace;let f;f="%y%%m%%d%_%H%%M%%S%".replace(/%y%/g,c.getFullYear());f=f.replace(/%m%/g,r((c.getMonth()+1).toString()));f=f.replace(/%d%/g,r(c.getDate().toString()));f=f.replace(/%H%/g,r(c.getHours().toString()));f=f.replace(/%M%/g,r(c.getMinutes().toString()));f=f.replace(/%S%/g,r(c.getSeconds().toString()));a=b.call(a,/%datetime%/g,f);a=a.replace(/%medianame%/g,d);a=a.replace(/%postId%/g,
e);return a=a.replace(/%mediaIndex%/g,g)}function r(a){return 1===a.length?"0"+a:a}function y(a){var b=document.createElement("a");b.href=a;b.setAttribute("target","_blank");document.body.appendChild(b);b.click();b.remove()}function K(a,b,c){var d=document.createElement("a");d.download=b+"."+c;d.href=a;document.body.appendChild(d);d.click();d.remove()}function x(a,b){a.startsWith("blob:")?K(a,b,"mp4"):(console.log(`Dowloading ${a}`),b||=a.split("\\").pop().split("/").pop(),fetch(a,{headers:new Headers({"User-Agent":window.navigator.userAgent,
Origin:location.origin}),mode:"cors"}).then(c=>c.blob()).then(c=>{const d=c.type.split("/").pop();c=window.URL.createObjectURL(c);K(c,b,d)}).catch(c=>console.error(c)))}const W=/^\/p\/([^/]+)\//,X=/instagram\.com\/p\/[\w-]+\//;var L="";document.addEventListener("keydown",function(a){if("https://www.instagram.com/"!==window.location.href){var b={stopPropagation:function(){},preventDefault:function(){}};if(a.altKey&&("KeyK"===a.code||"k"==a.key)){var c=document.getElementsByClassName("download-btn");
if(0<c.length){let d={...b};d.currentTarget=c[c.length-1];w(d);v(d)}}!a.altKey||"KeyI"!==a.code&&"i"!=a.key||(c=document.getElementsByClassName("newtab-btn"),0<c.length&&(b={...b},b.currentTarget=c[c.length-1],w(b),v(b)));!a.altKey||"KeyL"!==a.code&&"l"!=a.key||(b=document.getElementsByClassName("_9zm2"),0<b.length&&b[0].click());!a.altKey||"KeyJ"!==a.code&&"j"!=a.key||(a=document.getElementsByClassName("_9zm0"),0<a.length&&a[0].click())}});setInterval(function(){const a=window.location.href;var b=
getComputedStyle(document.body).backgroundColor.match(/[.?\d]+/g);b=150>=.299*b[0]+.587*b[1]+.114*b[2]?"white":"black";if(L!==a)for(;0!==document.getElementsByClassName("custom-btn").length;)document.getElementsByClassName("custom-btn")[0].remove();var c=document.querySelectorAll("article");for(let d=0;d<c.length;d++){let e=Array.from(c[d].querySelectorAll('article *:not(li)>*>*>*>div:not([class])>div[role="button"]:not([style]):not([tabindex="-1"])')).pop();e&&0===c[d].getElementsByClassName("custom-btn").length&&
u(e,b,M)}window.location.href.match(X)&&(c=t(document,'div[role="button"] > div[role="button"]:not([style])','polygon[points="20 21 12 13.44 4 21 4 3 20 3 20 21"]')||t(document,'div[role="button"] > div[role="button"]:not([style])','path[d="M20 22a.999.999 0 0 1-.687-.273L12 14.815l-7.313 6.912A1 1 0 0 1 3 21V3a1 1 0 0 1 1-1h16a1 1 0 0 1 1 1v18a1 1 0 0 1-1 1Z"]'),0===document.getElementsByClassName("custom-btn").length&&c.parentNode.querySelector("svg")&&u(c.parentNode.querySelector("svg"),b,N));
0!==document.getElementsByClassName("custom-btn").length||a.includes("stor")||document.querySelector("header section svg circle")&&u(document.querySelector("header section svg circle"),b,O);0===document.getElementsByClassName("custom-btn").length&&(b=t(document,"svg",'path[d="M5.888 22.5a3.46 3.46 0 0 1-1.721-.46l-.003-.002a3.451 3.451 0 0 1-1.72-2.982V4.943a3.445 3.445 0 0 1 5.163-2.987l12.226 7.059a3.444 3.444 0 0 1-.001 5.967l-12.22 7.056a3.462 3.462 0 0 1-1.724.462Z"]')||t(document,"svg",'path[d="M15 1c-3.3 0-6 1.3-6 3v40c0 1.7 2.7 3 6 3s6-1.3 6-3V4c0-1.7-2.7-3-6-3zm18 0c-3.3 0-6 1.3-6 3v40c0 1.7 2.7 3 6 3s6-1.3 6-3V4c0-1.7-2.7-3-6-3z"]'))&&
u(b.parentNode,"white",P);L=a},500);let B={},A={}})();
