// ==UserScript==
// @name                Maximize Video
// @namespace           http://www.icycat.com
// @author              冻猫
// @include             *
// @exclude             *www.w3school.com.cn*
// @version             12.0
// @run-at              document-end
// @downloadURL https://raw.githubusercontent.com/siritami/test1/release/release/Maximize20Video.user.js
// @updateURL https://raw.githubusercontent.com/siritami/test1/release/release/Maximize20Video.meta.js
// ==/UserScript==
(()=>{const a={isFull:!1,isIframe:!1,autoCheckCount:0},p={"www.acfun.cn":[".player-container .player"],"www.bilibili.com":["#bilibiliPlayer"],"www.douyu.com":["#js-player-video-case"],"www.huya.com":["#videoContainer"],"www.twitch.tv":[".player"],"www.youtube.com":["#movie_player"],"www.yy.com":["#player"],"*weibo.com":['[aria-label="Video Player"]',".html5-video-live .html5-video"],"v.huya.com":["#video_embed_flash>div"]},r=[".dplayer",".video-js",".jwplayer","[data-player]"];window.top!==window.self&&
(a.isIframe=!0);"zh-cn"==navigator.language.toLocaleLowerCase()?a.btnText={max:"\u7f51\u9875\u5168\u5c4f",pip:"\u753b\u4e2d\u753b",tip:"Iframe\u5185\u89c6\u9891\uff0c\u8bf7\u7528\u9f20\u6807\u70b9\u51fb\u89c6\u9891\u540e\u91cd\u8bd5"}:a.btnText={max:"Maximize",pip:"PicInPic",tip:"Iframe video. Please click on the video and try again"};const e={print(b){var c=new Date;const d=c.getFullYear(),k=(10>c.getMonth()+1?"0":"")+(c.getMonth()+1),g=(10>c.getDate()?"0":"")+c.getDate(),l=(10>c.getHours()?"0":
"")+c.getHours(),n=(10>c.getMinutes()?"0":"")+c.getMinutes();c=(10>c.getSeconds()?"0":"")+c.getSeconds();console.log("["+d+"-"+k+"-"+g+" "+l+":"+n+":"+c+"][Maximize Video] > "+b)},getRect(b){b=b.getBoundingClientRect();const c=e.getScroll();return{pageX:b.left+c.left,pageY:b.top+c.top,screenX:b.left,screenY:b.top}},isHalfFullClient(b){const c=e.getClient(),d=e.getRect(b);return 21>Math.abs(c.width-b.offsetWidth)&&20>d.screenX||21>Math.abs(c.height-b.offsetHeight)&&10>d.screenY?21>Math.abs(b.offsetWidth/
2+d.screenX-c.width/2)&&21>Math.abs(b.offsetHeight/2+d.screenY-c.height/2)?!0:!1:!1},isAllFullClient(b){const c=e.getClient(),d=e.getRect(b);return 21>Math.abs(c.width-b.offsetWidth)&&20>d.screenX&&21>Math.abs(c.height-b.offsetHeight)&&10>d.screenY?!0:!1},getScroll(){return{left:document.documentElement.scrollLeft||document.body.scrollLeft,top:document.documentElement.scrollTop||document.body.scrollTop}},getClient(){return{width:"CSS1Compat"==document.compatMode?document.documentElement.clientWidth:
document.body.clientWidth,height:"CSS1Compat"==document.compatMode?document.documentElement.clientHeight:document.body.clientHeight}},addStyle(b){const c=document.createElement("style");c.type="text/css";b=document.createTextNode(b);c.appendChild(b);document.head.appendChild(c);return c},matchRule(b,c){return(new RegExp("^"+c.split("*").join(".*")+"$")).test(b)},createButton(b){const c=document.createElement("tbdiv");c.id=b;c.onclick=()=>{h.playerControl()};document.body.appendChild(c);return c},
async addTip(b){if(!document.getElementById("catTip")){const c=document.createElement("tbdiv");c.id="catTip";c.innerHTML=b;c.style.cssText='transition: all 0.8s ease-out;background: none repeat scroll 0 0 #27a9d8;color: #FFFFFF;font: 1.1em "\u5fae\u8f6f\u96c5\u9ed1";margin-left: -250px;overflow: hidden;padding: 10px;position: fixed;text-align: center;bottom: 100px;z-index: 300;';document.body.appendChild(c);c.style.right=-c.offsetWidth-5+"px";await new Promise(d=>{c.style.display="block";setTimeout(()=>
{c.style.right="25px";d("OK")},300)});await new Promise(d=>{setTimeout(()=>{c.style.right=-c.offsetWidth-5+"px";d("OK")},3500)});await new Promise(d=>{setTimeout(()=>{document.body.removeChild(c);d("OK")},1E3)})}}},m={init(){document.getElementById("playerControlBtn")||q();a.isIframe&&e.isHalfFullClient(a.player)?window.parent.postMessage("iframeVideo","*"):this.show()},show(){a.player.removeEventListener("mouseleave",f.leavePlayer,!1);a.player.addEventListener("mouseleave",f.leavePlayer,!1);a.isFull||
(document.removeEventListener("scroll",f.scrollFix,!1),document.addEventListener("scroll",f.scrollFix,!1));a.controlBtn.style.display="block";a.controlBtn.style.visibility="visible";document.pictureInPictureEnabled&&"OBJECT"!=a.player.nodeName&&"EMBED"!=a.player.nodeName&&(a.picinpicBtn.style.display="block",a.picinpicBtn.style.visibility="visible");this.locate()},locate(){const b=e.getRect(a.player);a.controlBtn.style.opacity="0.5";a.controlBtn.innerHTML=a.btnText.max;a.controlBtn.style.top=b.screenY-
20+"px";a.controlBtn.style.left=b.screenX-64+a.player.offsetWidth+"px";a.picinpicBtn.style.opacity="0.5";a.picinpicBtn.innerHTML=a.btnText.pip;a.picinpicBtn.style.top=a.controlBtn.style.top;a.picinpicBtn.style.left=b.screenX-64+a.player.offsetWidth-54+"px"}},f={getPlayer(b){if(!a.isFull){a.mouseoverEl=b.target;var c=document.location.hostname,d=[];for(let g in p)if(e.matchRule(c,g)){for(let l of p[g])if(0<document.querySelectorAll(l).length)for(let n of document.querySelectorAll(l))d.push(n);break}if(0==
d.length)for(let g of r)if(0<document.querySelectorAll(g).length)for(let l of document.querySelectorAll(g))d.push(l);if(0==d.length&&"VIDEO"!=b.target.nodeName&&0<document.querySelectorAll("video").length){c=document.querySelectorAll("video");for(var k of c)if(c=k.getBoundingClientRect(),b.clientX>=c.x-2&&b.clientX<=c.x+c.width+2&&b.clientY>=c.y-2&&b.clientY<=c.y+c.height+2&&399<k.offsetWidth&&220<k.offsetHeight){d=[];d[0]=f.autoCheck(k);a.autoCheckCount=1;break}}if(0<d.length){k=b.path||b.composedPath();
for(let g of d)if(-1<k.indexOf(g)){a.player=g;m.init();return}}switch(b.target.nodeName){case "VIDEO":case "OBJECT":case "EMBED":399<b.target.offsetWidth&&220<b.target.offsetHeight&&(a.player=b.target,m.init());break;default:f.leavePlayer()}}},autoCheck(b){let c,d=b;a.playerChilds=[];for(a.playerChilds.push(b);d=d.parentNode;)if(15>Math.abs(b.offsetWidth-d.offsetWidth)&&15>Math.abs(b.offsetHeight-d.offsetHeight))c=d,a.playerChilds.push(d);else break;return c},leavePlayer(){"visible"==a.controlBtn.style.visibility&&
(a.controlBtn.style.opacity="",a.controlBtn.style.visibility="",a.picinpicBtn.style.opacity="",a.picinpicBtn.style.visibility="",a.player.removeEventListener("mouseleave",f.leavePlayer,!1),document.removeEventListener("scroll",f.scrollFix,!1))},scrollFix(b){clearTimeout(a.scrollFixTimer);a.scrollFixTimer=setTimeout(()=>{m.locate()},20)},hotKey(b){27==b.keyCode&&h.playerControl();113==b.keyCode&&f.pictureInPicture()},async receiveMessage(b){switch(b.data){case "iframePicInPic":e.print("messege:iframePicInPic");
document.pictureInPictureElement?await document.exitPictureInPicture():await document.querySelector("video").requestPictureInPicture().catch(c=>{e.addTip(a.btnText.tip)});break;case "iframeVideo":e.print("messege:iframeVideo");a.isFull||(a.player=a.mouseoverEl,m.init());break;case "parentFull":e.print("messege:parentFull");a.player=a.mouseoverEl;a.isIframe&&window.parent.postMessage("parentFull","*");h.checkParent();h.fullWin();"0px"!=getComputedStyle(a.player).left&&e.addStyle("#htmlToothbrush #bodyToothbrush .playerToothbrush {left:0px !important;width:100vw !important;}");
a.isFull=!0;break;case "parentSmall":e.print("messege:parentSmall");a.isIframe&&window.parent.postMessage("parentSmall","*");h.smallWin();break;case "innerFull":e.print("messege:innerFull");"IFRAME"==a.player.nodeName&&a.player.contentWindow.postMessage("innerFull","*");h.checkParent();h.fullWin();break;case "innerSmall":e.print("messege:innerSmall"),"IFRAME"==a.player.nodeName&&a.player.contentWindow.postMessage("innerSmall","*"),h.smallWin()}},pictureInPicture(){document.pictureInPictureElement?
document.exitPictureInPicture():a.player?"IFRAME"==a.player.nodeName?a.player.contentWindow.postMessage("iframePicInPic","*"):a.player.parentNode.querySelector("video").requestPictureInPicture():document.querySelector("video").requestPictureInPicture()}},h={playerControl(){if(a.player)if(this.checkParent(),a.isFull)a.isIframe&&window.parent.postMessage("parentSmall","*"),"IFRAME"==a.player.nodeName&&a.player.contentWindow.postMessage("innerSmall","*"),this.smallWin();else if(a.isIframe&&window.parent.postMessage("parentFull",
"*"),"IFRAME"==a.player.nodeName&&a.player.contentWindow.postMessage("innerFull","*"),this.fullWin(),0<a.autoCheckCount&&!e.isHalfFullClient(a.playerChilds[0]))if(10<a.autoCheckCount)for(var b of a.playerChilds)b.classList.add("videoToothbrush");else b=f.autoCheck(a.playerChilds[0]),a.autoCheckCount++,h.playerControl(),a.player=b,h.playerControl();else a.autoCheckCount=0},checkParent(){if(!a.isFull){a.playerParents=[];for(var b=a.player;(b=b.parentNode)&&"BODY"!=b.nodeName;)b.getAttribute&&a.playerParents.push(b)}},
fullWin(){a.isFull||(document.removeEventListener("mouseover",f.getPlayer,!1),a.backHtmlId=document.body.parentNode.id,a.backBodyId=document.body.id,"www.youtube.com"!=document.location.hostname||document.querySelector("#player-theater-container #movie_player")||(document.querySelector("#movie_player .ytp-size-button").click(),a.ytbStageChange=!0),a.leftBtn.style.display="block",a.rightBtn.style.display="block",a.picinpicBtn.style.display="",a.controlBtn.style.display="",this.addClass());a.isFull=
!0},addClass(){document.body.parentNode.id="htmlToothbrush";document.body.id="bodyToothbrush";for(let b of a.playerParents)b.classList.add("parentToothbrush"),"fixed"==getComputedStyle(b).position&&b.classList.add("absoluteToothbrush");a.player.classList.add("playerToothbrush");"VIDEO"==a.player.nodeName&&(a.backControls=a.player.controls,a.player.controls=!0);window.dispatchEvent(new Event("resize"))},smallWin(){document.body.parentNode.id=a.backHtmlId;document.body.id=a.backBodyId;for(let b of a.playerParents)b.classList.remove("parentToothbrush"),
b.classList.remove("absoluteToothbrush");a.player.classList.remove("playerToothbrush");"www.youtube.com"==document.location.hostname&&a.ytbStageChange&&document.querySelector("#player-theater-container #movie_player")&&(document.querySelector("#movie_player .ytp-size-button").click(),a.ytbStageChange=!1);"VIDEO"==a.player.nodeName&&(a.player.controls=a.backControls);a.leftBtn.style.display="";a.rightBtn.style.display="";a.controlBtn.style.display="";document.addEventListener("mouseover",f.getPlayer,
!1);window.dispatchEvent(new Event("resize"));a.isFull=!1}},q=()=>{a.picinpicBtn=document.createElement("tbdiv");a.picinpicBtn.id="picinpicBtn";a.picinpicBtn.onclick=()=>{f.pictureInPicture()};document.body.appendChild(a.picinpicBtn);a.controlBtn=e.createButton("playerControlBtn");a.leftBtn=e.createButton("leftFullStackButton");a.rightBtn=e.createButton("rightFullStackButton");"fixed"!=getComputedStyle(a.controlBtn).position&&e.addStyle('#htmlToothbrush #bodyToothbrush .parentToothbrush .bilibili-player-video {margin:0 !important;}\n#htmlToothbrush, #bodyToothbrush {overflow:hidden !important;zoom:100% !important;}\n#htmlToothbrush #bodyToothbrush .parentToothbrush {overflow:visible !important;z-index:auto !important;transform:none !important;-webkit-transform-style:flat !important;transition:none !important;contain:none !important;}\n#htmlToothbrush #bodyToothbrush .absoluteToothbrush {position:absolute !important;}\n#htmlToothbrush #bodyToothbrush .playerToothbrush {position:fixed !important;top:0px !important;left:0px !important;width:100vw !important;height:100vh !important;max-width:none !important;max-height:none !important;min-width:0 !important;min-height:0 !important;margin:0 !important;padding:0 !important;z-index:2147483646 !important;border:none !important;background-color:#000 !important;transform:none !important;}\n#htmlToothbrush #bodyToothbrush .parentToothbrush video {object-fit:contain !important;}\n#htmlToothbrush #bodyToothbrush .parentToothbrush .videoToothbrush {width:100vw !important;height:100vh !important;}\n#playerControlBtn {text-shadow: none;visibility:hidden;opacity:0;display:none;transition: all 0.5s ease;cursor: pointer;font: 12px "\u5fae\u8f6f\u96c5\u9ed1";margin:0;width:64px;height:20px;line-height:20px;border:none;text-align: center;position: fixed;z-index:2147483647;background-color: #27A9D8;color: #FFF;} #playerControlBtn:hover {visibility:visible;opacity:1;background-color:#2774D8;}\n#picinpicBtn {text-shadow: none;visibility:hidden;opacity:0;display:none;transition: all 0.5s ease;cursor: pointer;font: 12px "\u5fae\u8f6f\u96c5\u9ed1";margin:0;width:53px;height:20px;line-height:20px;border:none;text-align: center;position: fixed;z-index:2147483647;background-color: #27A9D8;color: #FFF;} #picinpicBtn:hover {visibility:visible;opacity:1;background-color:#2774D8;}\n#leftFullStackButton{display:none;position:fixed;width:1px;height:100vh;top:0;left:0;z-index:2147483647;background:#000;}\n#rightFullStackButton{display:none;position:fixed;width:1px;height:100vh;top:0;right:0;z-index:2147483647;background:#000;}');
document.addEventListener("mouseover",f.getPlayer,!1);document.addEventListener("keydown",f.hotKey,!1);window.addEventListener("message",f.receiveMessage,!1);e.print("Ready")};q()})();
