// ==UserScript==
// @name                 Netflix UHD
// @namespace            http://tampermonkey.net/
// @version              1.23
// @author               TGSAN
// @match                https://www.netflix.com/*
// @icon                 https://www.google.com/s2/favicons?sz=64&domain=netflix.com
// @run-at               document-start
// @grant                unsafeWindow
// @grant                GM_registerMenuCommand
// @downloadURL https://raw.githubusercontent.com/siritami/test1/release/release/Netflix20UHD.user.js
// @updateURL https://raw.githubusercontent.com/siritami/test1/release/release/Netflix20UHD.meta.js
// ==/UserScript==
(function(){let a;self.unsafeWindow?(console.log("use unsafeWindow mode"),a=self.unsafeWindow):(console.log("use window mode"),a=self.window);delete a.screen;a.__defineGetter__("screen",function(){let b=[];b.width=7680;b.height=4320;b.availWidth=7680;b.availHeight=4320;b.availLeft=0;b.availTop=0;b.colorDepth=32;b.isExtended=!1;b.pixelDepth=32;return b});delete a.devicePixelRatio;a.devicePixelRatio=4;a.MSMediaKeys&&(a.MSMediaKeys.isTypeSupportedWithFeaturesOriginal=a.MSMediaKeys.isTypeSupportedWithFeatures,
a.MSMediaKeys.isTypeSupportedWithFeatures=function(b,c){c=c.replace(/,display-res-[x|y]=\d+,display-res-[x|y]=\d+/,"");return this.isTypeSupportedWithFeaturesOriginal(b,c)});a.WebKitMediaKeys&&(a.WebKitMediaKeys.isTypeSupportedOriginal=a.WebKitMediaKeys.isTypeSupported,a.WebKitMediaKeys.isTypeSupported=function(b,c){let e=this.isTypeSupportedOriginal(b,c);console.log("Hook WebKitMediaKeys",b,c,e);return e});a.navigator.requestMediaKeySystemAccess&&(a.navigator.requestMediaKeySystemAccessOriginal=
a.navigator.requestMediaKeySystemAccess,a.navigator.requestMediaKeySystemAccess=async function(b,c){b.indexOf("playready");for(let e=0;c.length>e;e++)if(void 0!=c[e].videoCapabilities)for(let h=0;c[e].videoCapabilities.length>h;h++);return await a.navigator.requestMediaKeySystemAccessOriginal(b,c)});a.MediaCapabilities.prototype&&(a.MediaCapabilities.prototype.decodingInfoOriginal=a.MediaCapabilities.prototype.decodingInfo,a.MediaCapabilities.prototype.decodingInfo=function(b){let c=this.decodingInfoOriginal(b);
return new Promise((e,h)=>{c.then(f=>{f.powerEfficient=f.supported;f.smooth=f.supported;e(f)}).catch(f=>{h(f)})})});(async function(){if(self.GM_registerMenuCommand&&window.MSMediaKeys){let b=""!=window.MSMediaKeys.isTypeSupportedWithFeaturesOriginal("com.microsoft.playready.hardware",'video/mp4; features="hdcp=0"'),c=""!=window.MSMediaKeys.isTypeSupportedWithFeaturesOriginal("com.microsoft.playready.hardware",'video/mp4; features="hdcp=1"'),e=""!=window.MSMediaKeys.isTypeSupportedWithFeaturesOriginal("com.microsoft.playready.hardware",
'video/mp4; features="hdcp=2"'),h=""!=window.MSMediaKeys.isTypeSupportedWithFeaturesOriginal("com.microsoft.playready.hardware",'video/mp4; codecs="hev1,mp4a"; features="hdcp=2"'),f=""!=window.MSMediaKeys.isTypeSupportedWithFeaturesOriginal("com.microsoft.playready.hardware",'video/mp4; codecs="hev1,mp4a"; features="decode-res-x=3840,decode-res-y=2160,decode-bpc=10,hdcp=2"'),k=""!=window.MSMediaKeys.isTypeSupportedWithFeaturesOriginal("com.microsoft.playready.software",'video/mp4; features="hdcp=0"'),
l=""!=window.MSMediaKeys.isTypeSupportedWithFeaturesOriginal("com.microsoft.playready.software",'video/mp4; features="hdcp=1"'),m=""!=window.MSMediaKeys.isTypeSupportedWithFeaturesOriginal("com.microsoft.playready.software",'video/mp4; features="hdcp=2"'),n=""!=window.MSMediaKeys.isTypeSupportedWithFeaturesOriginal("com.microsoft.playready.software",'video/mp4; codecs="hev1,mp4a"; features="hdcp=2"'),p=""!=window.MSMediaKeys.isTypeSupportedWithFeaturesOriginal("com.microsoft.playready.software",'video/mp4; codecs="hev1,mp4a"; features="decode-res-x=3840,decode-res-y=2160,decode-bpc=10,hdcp=2"'),
g=function(d){return d?"\u2713":"\u2715"};GM_registerMenuCommand("PlayReady DRM Info ("+(f?"UHD Ready":"Restricted")+")",function(){let d;d="PlayReady DRM (without HDCP 2.2):\nHardware: "+(g(b)+"    Software: "+g(k)+"\n\n");d=d+"PlayReady DRM (HDCP 2.2):\nHardware: "+(g(c)+"    Software: "+g(l)+"\n\n");d=d+"PlayReady DRM (HDCP 2.2 Type 1):\nHardware: "+(g(e)+"    Software: "+g(m)+"\n\n");d=d+"PlayReady DRM (HDCP 2.2 Type 1) with HEVC:\nHardware: "+(g(h)+"    Software: "+g(n)+"\n\n");d=d+"PlayReady DRM (HDCP 2.2 Type 1) with HEVC UHD:\nHardware: "+
(g(f)+"    Software: "+g(p)+"\n\n");alert(d)})}})();GM_registerMenuCommand("Player Info",function(){console.log("switch player info");a.dispatchEvent(new KeyboardEvent("keydown",{keyCode:68,ctrlKey:!0,altKey:!0,shiftKey:!0}))});GM_registerMenuCommand("Stream Selector",function(){console.log("switch player info");a.dispatchEvent(new KeyboardEvent("keydown",{keyCode:83,ctrlKey:!0,altKey:!0,shiftKey:!0}));a.dispatchEvent(new KeyboardEvent("keydown",{keyCode:66,ctrlKey:!0,altKey:!0,shiftKey:!0}))});GM_registerMenuCommand("Player Log",
function(){console.log("switch player log");a.dispatchEvent(new KeyboardEvent("keydown",{keyCode:76,ctrlKey:!0,altKey:!0,shiftKey:!0}))});GM_registerMenuCommand("Load Local Subtitle (.DFXP)",function(){console.log("load local subtitle");a.dispatchEvent(new KeyboardEvent("keydown",{keyCode:84,ctrlKey:!0,altKey:!0,shiftKey:!0}))})})();
