// ==UserScript==
// @name                 Netflix Plus
// @namespace            http://tampermonkey.net/
// @version              3.4
// @author               TGSAN
// @match                https://www.netflix.com/*
// @icon                 https://www.google.com/s2/favicons?sz=64&domain=netflix.com
// @run-at               document-start
// @sandbox              raw
// @grant                unsafeWindow
// @grant                GM_setValue
// @grant                GM_getValue
// @grant                GM_registerMenuCommand
// @grant                GM_unregisterMenuCommand
// @downloadURL https://raw.githubusercontent.com/siritami/test1/release/release/Netflix20Plus.user.js
// @updateURL https://raw.githubusercontent.com/siritami/test1/release/release/Netflix20Plus.meta.js
// ==/UserScript==
(async()=>{function w(){let a=document.createElement("div");a.style.position="fixed";a.style.top="20px";a.style.left="50%";a.style.transform="translateX(-50%)";a.style.padding="10px 20px";a.style.backgroundColor="rgba(250, 250, 250, 1.0)";a.style.color="rgba(32, 32, 32, 1.0)";a.style.fontSize="12px";a.style.textAlign="center";a.style.fontWeight="600";a.style.zIndex="9999";a.style.boxShadow="0 0 10px rgba(0, 0, 0, 0.25)";a.style.borderRadius="30px";a.style.opacity="0.0";a.style.transition="opacity 0.5s";
document.body.appendChild(a);return a}function x(a,d=1500){let e=w();e.innerText=a;setTimeout(function(){e.style.opacity="1.0";setTimeout(function(){e.style.opacity="0.0";setTimeout(function(){document.body.removeChild(e)},500)},d)},1)}function p(){q=!1;if(void 0==k)for(var a of b.document.getElementsByTagName("script"))if(a.src&&-1<a.src.indexOf("cadmium-playercore")){k=a;break}a=document.createElement("script");a.src="https://www.cloudmoe.com/static/userscript/netflix-plus/cadmium-playercore.js";
a.async=k.async;a.id=k.id;k.replaceWith(a)}async function r(a){let d=await GM_getValue("NETFLIX_PLUS_"+a);return"boolean"==typeof d?d:b.globalOptions[a]}async function y(a,d){let e=await r(d);b.globalOptions[d]=e;return await GM_registerMenuCommand((await r(d)?"\u2705":"\ud83d\udd32")+" "+a,async function(){await GM_setValue("NETFLIX_PLUS_"+d,!e);b.globalOptions[d]=!e;t()})}async function t(){for(let a of m)await GM_unregisterMenuCommand(a);m=[];for(let a of z)m.push(await y(a[1],a[0]))}let b=self.window;
self.unsafeWindow?(console.log("[Netflix Plus] use unsafeWindow mode"),b=self.unsafeWindow):console.log("[Netflix Plus] use window mode (your userscript extensions not support unsafeWindow)");var f=document.createElement("meta");f.httpEquiv="Cache-Control";f.content="no-cache";b.document.head.appendChild(f);f=document.createElement("meta");f.httpEquiv="Pragma";f.content="no-cache";b.document.head.appendChild(f);f=document.createElement("meta");f.httpEquiv="Expires";f.content="-1";b.document.head.appendChild(f);
let k=void 0,q=!0;b.Function.prototype.callNetflixPlusOriginal=b.Function.prototype.call;b.Function.prototype.call=function(...a){if(q){let d=this.toString();if(1E6<d.length&&-1<d.indexOf("h264mpl")&&0>d.indexOf("videoElementNetflixPlus")){console.log("PlayerCore found len: "+d.length);p();return}}return this.callNetflixPlusOriginal(...a)};void 0!==b.netflix&&void 0!==b.netflix.player&&(x('Netflix Plus is executing too late and is being forced to run, which may cause issues.\n\nRefresh the page while holding down the "Shift" key to resolve the issue.',
1E4),console.warn("The user script is executing too late and is being forced to run, which may cause issues."),p());b._videoElementNetflixPlus;Object.defineProperty(b,"videoElementNetflixPlus",{get:function(){return b._videoElementNetflixPlus},set:function(a){let d=b._videoElementNetflixPlus;b._videoElementNetflixPlus=a;a.addEventListener("playing",function(){if(d!==a&&b.globalOptions.setMaxBitrateOld){var e=function(c){return document.evaluate(c,document,null,XPathResult.FIRST_ORDERED_NODE_TYPE,
null).singleNodeValue},h=function(){b.dispatchEvent(new KeyboardEvent("keydown",{keyCode:83,ctrlKey:!0,altKey:!0,shiftKey:!0}));b.dispatchEvent(new KeyboardEvent("keydown",{keyCode:66,ctrlKey:!0,altKey:!0,shiftKey:!0}));const c=e("//div[text()='Video Bitrate / VMAF']"),u=e("//div[text()='Audio Bitrate']"),v=e("//button[text()='Override']");c&&u&&v?([c,u].forEach(function(g){g=g.parentElement;g.querySelectorAll("select").forEach(function(A){A.removeAttribute("disabled")});g=g.querySelectorAll("select > option");
for(var n=0;n<g.length-1;n++)g[n].removeAttribute("selected");g[g.length-1].setAttribute("selected","selected")}),setTimeout(function(){v.click()},100),d=a):setTimeout(h,100)};h()}})}});b.modifyFilterNetflixPlus=function(a,d,e){let h="playready"===e?30:0;b.globalOptions.useprk&&(a.push("h264mpl30-dash-playready-prk-qc"),a.push("h264mpl31-dash-playready-prk-qc"),a.push("h264mpl40-dash-playready-prk-qc"));30==h?(b.globalOptions.useddplus&&(a.push("ddplus-2.0-dash"),a.push("ddplus-5.1-dash"),a.push("ddplus-5.1hq-dash"),
a.push("ddplus-atmos-dash")),b.globalOptions.usehevc&&(a=a.filter(c=>{if(!(new RegExp(/main10-L5/g)).test(JSON.stringify(c)))return c})),b.globalOptions.usef12k&&(a=a.filter(c=>{if(!(new RegExp(/hevc-main10-L.*-dash-cenc-prk-do/g)).test(JSON.stringify(c)))return c})),b.globalOptions.usef4k&&(a.push("hevc-main10-L30-dash-cenc"),a.push("hevc-main10-L31-dash-cenc"),a.push("hevc-main10-L40-dash-cenc"),a.push("hevc-main10-L41-dash-cenc"))):(b.globalOptions.useFHD&&(a.push("playready-h264mpl40-dash"),a.push("playready-h264hpl40-dash"),
a.push("vp9-profile0-L40-dash-cenc"),a.push("av1-main-L50-dash-cbcs-prk"),a.push("av1-main-L51-dash-cbcs-prk"),a.push("av1-hdr10plus-main-L40-dash-cbcs-prk"),a.push("av1-hdr10plus-main-L41-dash-cbcs-prk"),a.push("av1-hdr10plus-main-L50-dash-cbcs-prk"),a.push("av1-hdr10plus-main-L51-dash-cbcs-prk")),b.globalOptions.useHA&&a.push("heaac-5.1-dash"),b.globalOptions.usedef||(b.globalOptions.useav1&&(a.push("av1-main-L20-dash-cbcs-prk"),a.push("av1-main-L21-dash-cbcs-prk"),a=a.filter(c=>{if(!(new RegExp(/h264/g)).test(JSON.stringify(c)))return c}),
a=a.filter(c=>{if(!(new RegExp(/vp9-profile/g)).test(JSON.stringify(c)))return c})),b.globalOptions.usevp9&&(a.push("vp9-profile0-L21-dash-cenc"),a=a.filter(c=>{if(!(new RegExp(/h264/g)).test(JSON.stringify(c)))return c}),a=a.filter(c=>{if(!(new RegExp(/av1-main/g)).test(JSON.stringify(c)))return c})),b.globalOptions.useAVCH&&(a=a.filter(c=>{if(!(new RegExp(/vp9-profile/g)).test(JSON.stringify(c)))return c}),a=a.filter(c=>{if(!(new RegExp(/av1-main/g)).test(JSON.stringify(c)))return c})),b.globalOptions.useAVC&&
(a=a.filter(c=>{if(!(new RegExp(/vp9-profile/g)).test(JSON.stringify(c)))return c}),a=a.filter(c=>{if(!(new RegExp(/h264hp/g)).test(JSON.stringify(c)))return c}),a=a.filter(c=>{if(!(new RegExp(/av1-main/g)).test(JSON.stringify(c)))return c}))));b.globalOptions.useallSub&&(d.showAllSubDubTracks=1);b.globalOptions.closeimsc&&(a=a.filter(c=>{if(!(new RegExp(/imsc1.1/g)).test(JSON.stringify(c)))return c}));return[a,d,e]};const B=class{constructor(a,d){this.script=a;this.target=d;this._cancel=!1;this._replace=
null;this._stop=!1}preventDefault(){this._cancel=!0}stopPropagation(){this._stop=!0}replacePayload(a){this._replace=a}};let l=[];b.addBeforeScriptExecuteListener=a=>{if("function"!==typeof a)throw Error("Event handler must be a function.");l.push(a)};b.removeBeforeScriptExecuteListener=a=>{let d=l.length;for(;d--;)l[d]===a&&l.splice(d,1)};(new MutationObserver(a=>{for(const d of a)for(const e of d.addedNodes)if("SCRIPT"===e.tagName){a=new B(e,d.target);if("function"===typeof b.onbeforescriptexecute)try{b.onbeforescriptexecute(a)}catch(h){console.error(h)}for(const h of l){if(a._stop)break;
try{h(a)}catch(c){console.error(c)}}a._cancel?(e.textContent="",e.remove()):"string"===typeof a._replace&&(e.textContent=a._replace)}})).observe(document,{childList:!0,subtree:!0});const z=[["onlyMaxBitrate","Only use best bitrate available"],["useallSub","Show all audio-tracks and subs"],["closeimsc","Use SUP subtitle replace IMSC subtitle"],["useDDPandHA","Enable Dolby and HE-AAC 5.1 Audio"],["alwaysUseHDR","Always use HDR or Dolby Vision when available"],["useFHD","Focus 1080P"]];let m=[];b.globalOptions=
{useDDPandHA:!0,useXHA:!1,alwaysUseHDR:!1,onlyMaxBitrate:!0,get onlyVideoMaxBitrate(){return b.globalOptions.onlyMaxBitrate},get onlyAudioMaxBitrate(){return b.globalOptions.onlyMaxBitrate},setMaxBitrateOld:!1,useallSub:!0,get useddplus(){return b.globalOptions.useDDPandHA},useAVC:!1,usedef:!1,get useHA(){return b.globalOptions.useDDPandHA},useAVCH:!0,usevp9:!1,useav1:!1,useprk:!0,usehevc:!1,usef4k:!0,usef12k:!1,closeimsc:!0};b.globalOptions.useFHD=!await async function(){let a=!1;b.MSMediaKeys&&
(a=!0);b.WebKitMediaKeys&&(a=!0);let d=[{videoCapabilities:[{contentType:"video/mp4;codecs=avc1.42E01E",robustness:"HW_SECURE_ALL"}]}];try{await navigator.requestMediaKeySystemAccess("com.widevine.alpha.experiment",d),a=!0}catch{}console.log("Supported advanced DRM: "+a);return a}();b.onbeforescriptexecute=function(a){a=document.getElementsByTagName("script");if(0!==a.length)for(let d=0;a.length>d;d++){let e=a[d];if(e.src.includes("cadmium-playercore")){k=e;console.warn("parsing playercore dom");
b.onbeforescriptexecute=null;break}}};t()})();
