// ==UserScript==
// @name         Pixeldrain Download Bypass
// @namespace    http://tampermonkey.net/
// @version      1.6.3
// @author       MegaLime0, honey, Nurarihyon
// @match        https://pixeldrain.com/*
// @match        https://cdn.pd8.workers.dev/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=pixeldrain.com
// @grant        GM_openInTab
// @downloadURL https://raw.githubusercontent.com/siritami/test1/release/release/Pixeldrain20Download20Bypass.user.js
// @updateURL https://raw.githubusercontent.com/siritami/test1/release/release/Pixeldrain20Download20Bypass.meta.js
// ==/UserScript==
(function(){function n(c){const a=window.location.href;if("file"==c)return"https://pd.cybar.xyz/"+a.replace("https://pixeldrain.com/u/","");if("gallery"==c){const d=[],h=[];document.querySelectorAll("a.file").forEach(k=>{const g=k.querySelector("div").style.backgroundImage.match(r);g&&1<g.length&&(d.push("https://pd.cybar.xyz/"+g[1]),h.push(k.textContent))});return{bypassUrlList:d,bypassUrlNames:h}}}function t(){const c=window.location.href;if(c.includes("https://pixeldrain.com/u/")){const a=n("file");
p(a)}c.includes("https://pixeldrain.com/l/")&&n("gallery").bypassUrlList.forEach(a=>{p(a)})}function p(c){const a=document.createElement("a");a.href=c;a.click()}function u(){const c=document.getElementById("popupBox");var a=document.createElement("span");a.innerHTML="&times;";a.style.position="absolute";a.style.top="1px";a.style.right="7px";a.style.cursor="pointer";a.onclick=function(){c.style.display="none"};c.innerHTML="";c.appendChild(a);a=window.location.href;if(a.includes("https://pixeldrain.com/u/")){var d=
n("file");const h=document.createElement("a");h.href=d;h.textContent=d;c.appendChild(h)}if(a.includes("https://pixeldrain.com/l/")){let h=n("gallery").bypassUrlList;const k=document.createElement("div");k.style.maxHeight="calc(100% - 40px)";k.style.overflowY="auto";k.style.paddingBottom="10px";h.forEach(e=>{const f=document.createElement("a");f.href=e;f.textContent=e;f.style.display="block";k.appendChild(f)});c.appendChild(k);c.style.display="flex";c.style.flexDirection="column";c.style.alignItems=
"center";c.style.justifyContent="center";a=document.createElement("div");a.style.display="flex";a.style.justifyContent="center";a.style.marginTop="10px";const g=document.createElement("button");g.textContent="\ud83d\udd17 Copy URL";g.style.marginRight="5px";g.addEventListener("click",function(){const e=h.join("\n");navigator.clipboard.writeText(e).then(function(){g.textContent="\u2714\ufe0f Copied";setTimeout(function(){g.textContent="\ud83d\udd17 Copy URL"},2500)},function(f){console.error("Failed to copy URLs: ",
f)})});a.appendChild(g);d=document.createElement("button");d.textContent="\ud83d\udcc4 Save as Text File";d.style.marginLeft="5px";d.addEventListener("click",function(){var e=document.getElementById("popupBox").querySelectorAll("a");if(0<e.length){var f=window.location.href.match(/\/l\/([^/#?]+)/);if(f&&1<f.length){f=f[1]+".txt";let q="";e.forEach(v=>{q+=v.href+"\n"});e=new Blob([q.trim()],{type:"text/plain"});e=URL.createObjectURL(e);const l=document.createElement("a");l.href=e;l.download=f;document.body.appendChild(l);
l.click();document.body.removeChild(l);URL.revokeObjectURL(e)}else console.error("Failed to extract file identifier from URL.")}else console.error("Popup content not found.")});a.appendChild(d);c.appendChild(a)}c.style.display="block"}const r=/\/api\/file\/(\w+)\//;if(window.location.href.includes("pixeldrain.com")){const c=document.createElement("button");var b=document.createElement("a");b.className="icon";b.textContent="download";b.style.color="#d7dde8";var m=document.createElement("span");m.textContent=
"Download Bypass";c.appendChild(b);c.appendChild(m);const a=document.createElement("button");b=document.createElement("i");b.className="icon";b.textContent="link";m=document.createElement("span");m.textContent="Show Bypass Links";a.appendChild(b);a.appendChild(m);b=document.createElement("div");b.style.zIndex=20;b.style.whiteSpace="pre-line";b.id="popupBox";b.style.display="none";b.style.position="fixed";b.style.top="50%";b.style.left="50%";b.style.transform="translate(-50%, -50%)";b.style.padding=
"20px";b.style.background="#2f3541";b.style.border="2px solid #a4be8c";b.style.color="#d7dde8";b.style.borderRadius="10px";b.style.width="30%";b.style.height="auto";b.style.maxWidth="600px";c.addEventListener("click",t);a.addEventListener("click",u);document.querySelectorAll("div.label").forEach(d=>{"Size"===d.textContent.trim()&&(d=d.nextElementSibling)&&(d.insertAdjacentElement("afterend",a),d.insertAdjacentElement("afterend",c))});document.body.appendChild(b)}})();
