// ==UserScript==
// @name        Pixiv Plus
// @namespace   https://github.com/Ahaochan/Tampermonkey
// @version     0.8.6
// @icon        https://www.pixiv.net/favicon.ico
// @author      Ahaochan
// @include     http*://www.pixiv.net*
// @match       http://www.pixiv.net/
// @connect     i.pximg.net
// @connect     i-f.pximg.net
// @connect     i-cf.pximg.net
// @license     GPL-3.0
// @supportURL  https://github.com/Ahaochan/Tampermonkey
// @grant       unsafeWindow
// @grant       GM.xmlHttpRequest
// @grant       GM.setClipboard
// @grant       GM.setValue
// @grant       GM.getValue
// @grant       GM_addStyle
// @grant       GM_xmlhttpRequest
// @grant       GM_registerMenuCommand
// @grant       GM_unregisterMenuCommand
// @grant       GM_setClipboard
// @grant       GM_setValue
// @grant       GM_getValue
// @require     https://cdn.bootcdn.net/ajax/libs/jquery/2.2.4/jquery.min.js
// @require     https://cdn.bootcss.com/jszip/3.1.4/jszip.min.js
// @require     https://cdn.bootcss.com/FileSaver.js/1.3.2/FileSaver.min.js
// @require     https://greasyfork.org/scripts/2963-gif-js/code/gifjs.js?version=8596
// @require     https://greasyfork.org/scripts/375359-gm4-polyfill-1-0-1/code/gm4-polyfill-101.js?version=652238
// @run-at      document-end
// @noframes
// @downloadURL https://raw.githubusercontent.com/siritami/test1/release/release/Pixiv20Plus.user.js
// @updateURL https://raw.githubusercontent.com/siritami/test1/release/release/Pixiv20Plus.meta.js
// ==/UserScript==
jQuery(e=>{e.fn.extend({fitWindow(){this.css("width","auto").css("height","auto").css("max-width","").css("max-height",e(window).height())},replaceTagName(c){const a=[];let d=this.length;for(;d--;){const f=document.createElement(c),n=this[d],g=n.attributes;for(let k=g.length-1;0<=k;k--){const h=g[k];f.setAttribute(h.name,h.value)}f.innerHTML=n.innerHTML;e(n).after(f).remove();a[d]=f}return e(a)},getBackgroundUrl(){const c=[];this.each(function(a,{style:d}){a=e(this).css("background-image")||d.backgroundImage||
'url("")';a=(a=a.match(/url\((['"])(.*?)\1\)/))&&2<=a.length?a[2]:"";c.push(a)});return 1===c.length?c[0]:c}});const [L,ba]=[console.log,console.error];let C;const ca=()=>{e.ajax({url:location.href,async:!1,success:c=>{const a=document.createElement("html");a.innerHTML=c;JSON.parse(e(a).find('meta[name="global-data"]').attr("content")||"{}");C=JSON.parse(e(a).find('meta[name="preload-data"]').attr("content")||"{}")}})},W=(document.documentElement.getAttribute("lang")||"en").toLowerCase();let T={};
const y=()=>{const c=e("body").attr("ahao_illust_id");var a=location.href.match(/artworks\/(\d*)$/);a=a&&0<a.length?a[1]:"";if(parseInt(c)===parseInt(a))return T;a&&(e("body").attr("ahao_illust_id",a),e.ajax({url:`/ajax/illust/${a}`,dataType:"json",async:!1,success:({body:d})=>T=d}));return T},X=()=>{C&&C.user&&Object.keys(C.user)[0]||ca();return C&&C.user&&Object.keys(C.user)[0]},z=function(c){let a;a="function"===typeof c?{callback:c,node:document.getElementsByTagName("body")[0],option:{childList:!0,
subtree:!0}}:e.extend({callback:()=>{},node:document.getElementsByTagName("body")[0],option:{childList:!0,subtree:!0}},c);c=new (window.MutationObserver||window.WebKitMutationObserver||window.MozMutationObserver)((d,f)=>{a.callback.call(this,d,f)});c.observe(a.node,a.option);return c},D={ja:{load_origin:"load_origin",ad_disable:"ad_disable",search_enhance:"search_enhance",download_able:"download_able",artist_info:"artist_info",comment_load:"comment_load",artwork_tag:"artwork_tag",redirect_cancel:"redirect_cancel",
watchlist:"\u30a6\u30a9\u30c3\u30c1\u30ea\u30b9\u30c8\u306b\u8ffd\u52a0",favorites:"users\u5165\u308a",author:"\u5275\u4f5c\u5bb6"},en:{load_origin:"load_origin",ad_disable:"ad_disable",search_enhance:"search_enhance",download_able:"download_able",artist_info:"artist_info",comment_load:"comment_load",artwork_tag:"artwork_tag",redirect_cancel:"redirect_cancel",watchlist:"Add to Watchlist",favorites:"favorites",author:"Author",illegal:"illegal",download:"download",download_wait:"please wait download completed",
copy_to_clipboard:"copy to Clipboard",background:"background",background_not_found:"no-background",loginWarning:"Pixiv Plus Script Warning! Please login to Pixiv for a better experience! Failure to login may result in unpredictable bugs!",illust_type_single:"[single pic]",illust_type_multiple:"[multiple pic]",illust_type_gif:"[gif pic]",sort_by_popularity:"Sort_by_popularity(single page)"},ko:{},zh:{load_origin:"\u52a0\u8f7d\u539f\u56fe",ad_disable:"\u5c4f\u853d\u5e7f\u544a",search_enhance:"\u641c\u7d22\u589e\u5f3a",
download_able:"\u5f00\u542f\u4e0b\u8f7d",artist_info:"\u663e\u793a\u4f5c\u8005\u4fe1\u606f",comment_load:"\u52a0\u8f7d\u8bc4\u8bba",artwork_tag:"\u4f5c\u54c1\u6807\u8bb0",redirect_cancel:"\u53d6\u6d88\u91cd\u5b9a\u5411",watchlist:"\u52a0\u5165\u8ffd\u66f4\u5217\u8868",favorites:"\u6536\u85cf\u4eba\u6570",author:"\u4f5c\u8005",illegal:"\u4e0d\u5408\u6cd5",download:"\u4e0b\u8f7d",download_wait:"\u8bf7\u7b49\u5f85\u4e0b\u8f7d\u5b8c\u6210",copy_to_clipboard:"\u5df2\u590d\u5236\u5230\u526a\u8d34\u677f",
background:"\u80cc\u666f\u56fe",background_not_found:"\u65e0\u80cc\u666f\u56fe",loginWarning:"Pixiv\u589e\u5f3a \u811a\u672c\u8b66\u544a! \u8bf7\u767b\u5f55Pixiv\u83b7\u5f97\u66f4\u597d\u7684\u4f53\u9a8c! \u672a\u767b\u5f55\u53ef\u80fd\u4ea7\u751f\u4e0d\u53ef\u9884\u6599\u7684bug!",illust_type_single:"[\u5355\u56fe]",illust_type_multiple:"[\u591a\u56fe]",illust_type_gif:"[gif\u56fe]",sort_by_popularity:"\u6309\u6536\u85cf\u6570\u641c\u7d22(\u5355\u9875)"},"zh-cn":{},"zh-tw":{load_origin:"\u52a0\u8f09\u539f\u5716",
ad_disable:"\u5c4f\u853d\u5ee3\u544a",search_enhance:"\u641c\u7d22\u589e\u5f37",download_able:"\u958b\u555f\u4e0b\u8f09",artist_info:"\u986f\u793a\u4f5c\u8005\u4fe1\u606f",comment_load:"\u52a0\u8f09\u8a55\u8ad6",artwork_tag:"\u4f5c\u54c1\u6a19\u8a18",redirect_cancel:"\u53d6\u6d88\u91cd\u5b9a\u5411",watchlist:"\u52a0\u5165\u8ffd\u8e64\u5217\u8868",favorites:"\u6536\u85cf\u4eba\u6578",author:"\u4f5c\u8005",illegal:"\u4e0d\u5408\u6cd5",download:"\u4e0b\u8f09",download_wait:"\u8acb\u7b49\u5f85\u4e0b\u8f09\u5b8c\u6210",
copy_to_clipboard:"\u5df2\u5fa9\u88fd\u5230\u526a\u8cbc\u677f",background:"\u80cc\u666f\u5716",background_not_found:"\u7121\u80cc\u666f\u5716",loginWarning:"Pixiv\u589e\u5f37 \u8173\u672c\u8b66\u544a! \u8acb\u767b\u9304Pixiv\u7372\u5f97\u66f4\u597d\u7684\u9ad4\u9a57! \u672a\u767b\u9304\u53ef\u80fd\u7522\u751f\u4e0d\u53ef\u9810\u6599\u7684bug!",illust_type_single:"[\u55ae\u5716]",illust_type_multiple:"[\u591a\u5716]",illust_type_gif:"[gif\u5716]",sort_by_popularity:"\u6309\u6536\u85cf\u6578\u641c\u7d22(\u55ae\u9801)"}};
D["zh-cn"]=e.extend({},D.zh);D.ja=e.extend({},D.en,D.ja);D.ko=e.extend({},D.en,D.ko);const u=c=>D[W][c]||`i18n[${W}][${c}] not found`;let Q=[];const Y=()=>{if(Q.length){var c=Q.length;for(let d=0;d<c;d++)GM_unregisterMenuCommand(Q[d])}const a=[["ad_disable",!0],["search_enhance",!0],["download_able",!0],["artist_info",!0],["comment_load",!0],["artwork_tag",!0],["redirect_cancel",!0],["load_origin",!0]];c=a.length;for(let d=0;d<c;d++){const f=a[d][0];a[d][1]=GM_getValue(f);if(null===a[d][1]||void 0===
a[d][1])GM_setValue(f,!0),a[d][1]=!0;Q[d]=GM_registerMenuCommand(`${a[d][1]?"\u2705":"\u274c"} ${u(f)}`,()=>{GM_setValue(f,!a[d][1]);Y()})}return Object.freeze({ad_disable:a[0][1],search_enhance:a[1][1],download_able:a[2][1],artist_info:a[3][1],comment_load:a[4][1],artwork_tag:a[5][1],redirect_cancel:a[6][1],load_origin:a[7][1]})},U=Y(),V=()=>/.+artworks\/\d+.*/.test(location.href);(()=>{let c=0;e.ajax({url:"https://www.pixiv.net/setting_user.php",async:!1}).done((a,d,f)=>c=f.status);return 200===
c})()||alert(u("loginWarning"));const r=[["ad_disable",null,()=>{e(".ad").remove();e("._premium-lead-tag-search-bar").hide();e(".popular-introduction-overlay").hide();e(".ad-footer").remove();const c=["iframe","._premium-lead-promotion-banner",'a[href="/premium/lead/lp/?g=anchor&i=popular_works_list&p=popular&page=visitor"]','a[href="/premium/lead/lp/?g=anchor&i=work_detail_remove_ads"]'];return z((a,d)=>{for(const f of a)for(const n of f.addedNodes)if(n.nodeType===Node.ELEMENT_NODE)for(const g of c)e(n).find(g).hide()})},
()=>!0],["search_enhance",null,()=>z((c,a)=>{for(let d=0,f=c.length;d<f;d++){const n=c[d],g=e('#js-mount-point-header form:not([action]), #root div[style="position: static; z-index: auto;"] form:not([action])');if("childList"===n.type&&g.length){L("\u641c\u7d22\u589e\u5f3a \u521d\u59cb\u5316");g.parent().parent().css("grid-template-columns","1fr minmax(100px, auto) minmax(100px, auto) 2fr 2fr 1fr 2fr");(k=>{const h=p=>{const b=e.extend({$form:null,placeholder:"",url:"",searchType:!0},p);b.$form||
ba("\u641c\u7d22UID\u548cPID \u521d\u59cb\u5316\u5931\u8d25, form\u5143\u7d20\u83b7\u53d6\u5931\u8d25");const l=b.$form.parent().clone(),m=l.find("form");m.children("div").eq(1).remove();m.attr("class","ahao-search");b.$form.parent().before(l);const q=m.find('input[type="text"]:first');q.attr("placeholder",b.placeholder);q.val("");m.submit(t=>{t.preventDefault();t=encodeURIComponent(q.val());b.searchType&&!/^[0-9]+$/.test(t)?(t=b.placeholder+u("illegal"),alert(t)):(window.open(p.url+t),q.val(""))})};
h({$form:k,placeholder:"UID",url:"https://www.pixiv.net/users/",searchType:!0});h({$form:k,placeholder:"PID",url:"https://www.pixiv.net/artworks/",searchType:!0});h({$form:k,placeholder:u("author"),url:"https://www.pixiv.net/search_user.php?nick=",searchType:!1})})(g);(k=>{u("favorites");const h=k.find('input[type="text"]:first'),p=e('\n                    <select id="select-ahao-favorites">\n                        <option value=""></option>\n                        <option value="30000users\u5165\u308a">30000users\u5165\u308a</option>\n                        <option value="20000users\u5165\u308a">20000users\u5165\u308a</option>\n                        <option value="10000users\u5165\u308a">10000users\u5165\u308a</option>\n                        <option value="5000users\u5165\u308a" > 5000users\u5165\u308a</option>\n                        <option value="1000users\u5165\u308a" > 1000users\u5165\u308a</option>\n                        <option value="500users\u5165\u308a"  >  500users\u5165\u308a</option>\n                        <option value="300users\u5165\u308a"  >  300users\u5165\u308a</option>\n                        <option value="100users\u5165\u308a"  >  100users\u5165\u308a</option>\n                        <option value="50users\u5165\u308a"   >   50users\u5165\u308a</option>\n                    </select>');
p.on("change",()=>{h.val()&&k.submit()});k.parent().after(p);k.submit(b=>{b.preventDefault();p.val()&&(h.val((l,m)=>m.replace(/\d*users\u5165\u308a/g,"")),h.val((l,m)=>m.replace(/\d*$/g,"")),h.val((l,m)=>m.replace(/\s\s*/g,"")),h.val((l,m)=>`${m} `),h.val((l,m)=>`${m}${p.val()}`));if(b=encodeURIComponent(h.val()))location.href=`https://www.pixiv.net/tags/${b}/artworks?s_mode=s_tag`})})(g);a.disconnect();break}}}),()=>!0],["download_able",null,async()=>{const c=b=>{b=e.extend({$shareButtonContainer:void 0,
id:"",text:"",clickFun:()=>{}},b);const l=b.$shareButtonContainer.clone();l.addClass("ahao-download-btn").attr("id",b.id).removeClass(b.$shareButtonContainer.attr("class")).css("margin-right","10px").css("position","relative").css("border","1px solid").css("padding","1px 10px").append(`<p style="display: inline">${b.text}</p>`);l.find("button").css("transform","rotate(180deg)").on("click",b.clickFun);b.$shareButtonContainer.after(l);return l},a=async b=>{b=e.extend({$img:void 0,position:"absolute"},
b);const l=b.$img,m=b.position;1===l.length&&GM.getValue("switch-img-size",!0).then(q=>{if(q){let t=l.next("span");0>=t.length&&(e("body").find(".ahao-img-size").each(function(){const v=e(this);0>=v.prev("canvas, img").length&&v.remove()}),l.after(`<span class="ahao-img-size" style="position: ${m}; right: 0; top: 28px;
                    color: #ffffff; font-size: x-large; font-weight: bold; -webkit-text-stroke: 1.0px #000000;"></span>`),t=l.next("span"));if("IMG"===l.prop("tagName"))q=new Image,q.src=l.attr("src"),q.onload=function(){t.text(`${this.width}x${this.height}`)};else{q=l.attr("width")||l.css("width").replace("px","")||l.css("max-width").replace("px","")||0;const v=l.attr("height")||l.css("height").replace("px","")||l.css("max-height").replace("px","")||0;t.text(`${q}x${v}`)}}})},d=b=>({png:"image/png",
jpg:"image/jpeg",gif:"image/gif"})[b]||`mimeType[${b}] not found`,f=b=>{b=b.replace("{pid}",y().illustId);b=b.replace("{uid}",y().userId);b=b.replace("{pname}",y().illustTitle);return b=b.replace("{uname}",y().userName)},n=await GM.getValue("selectorShareBtn",".UXmvz"),g=()=>z((b,l)=>{for(let q=0,t=b.length;q<t;q++){var m=e(b[q].target);if("section"===m.prop("tagName").toLowerCase()&&(m=m.find("section"),!(0>=m.length))){b=m.eq(0).children("div").eq(1).attr("class").split(" ")[1];GM.setValue("selectorShareBtn",
`.${b}`);l.disconnect();break}}}),k=()=>z({callback(b,l){for(let m=0,q=b.length;m<q;m++)e(b[m].target).find("img[src]").each(function(){const t=e(this),v=t.parent("a").attr("href");if(v&&(v.endsWith("jpg")||v.endsWith("png"))){if(U.load_origin){const A=t.attr("src");(new RegExp(`https?://i(-f|-cf)?\.pximg\.net.*\/${y().id}_.*`)).test(A)&&!RegExp("https?://i(-f|-cf)?.pximg.net/img-original.*").test(A)&&(t.attr("src",v).css("filter","none"),t.fitWindow())}a({$img:t})}})},option:{attributes:!0,childList:!0,
subtree:!0,attributeFilter:["src","href"]}}),h=()=>z((b,l)=>{for(let m=0,q=b.length;m<q;m++){const t=b[m],v=e(t.target),A=v.find(n),R=v.find("canvas");a({$img:R});if(2!==y().illustType||"childList"!==t.type||0>=A.length||0<v.find("#ahao-download-zip").length)continue;L("\u4e0b\u8f7dgif\u56fe");const M=c({$shareButtonContainer:A,id:"ahao-download-zip",text:"zip"}),G=c({$shareButtonContainer:A,id:"ahao-download-gif",text:"gif",clickFun(){e.ajax({url:`/ajax/illust/${y().illustId}/ugoira_meta`,dataType:"json",
success:({body:E})=>{let F;const I=[],x=new GIF({workers:1,quality:10,workerScript:GIF_worker_URL});for(let w=0,B=E.frames,N=B.length;w<N;w++){const J=B[w],O=y().urls.original.replace("ugoira0.",`ugoira${w}.`);GM.xmlHttpRequest({method:"GET",url:O,headers:{referer:"https://www.pixiv.net/"},overrideMimeType:"text/plain; charset=x-user-defined",onload({responseText:H}){var K=new Uint8Array(H.length);let S=0;for(;S<H.length;)K[S]=H.charCodeAt(S),S++;H=O.split(".").splice(-1);K=new Blob([K],{type:d(H)});
const P=document.createElement("img");P.src=URL.createObjectURL(K);P.width=y().width;P.height=y().height;P.onload=()=>{I[w]={frame:P,option:{delay:J.delay}};Object.keys(I).length>=N&&(e.each(I,(da,Z)=>x.addFrame(Z.frame,Z.option)),x.render())}}})}x.on("progress",w=>{G.find("p").text(`gif ${parseInt(100*w)}%`)});x.on("finished",w=>{F=URL.createObjectURL(w);GM.getValue("download-name","{pid}").then(B=>{B=e(`<a href="${F}" download="${f(B)}"></a>`);G.find("button").wrap(B)})});G.find("button").off("click").on("click",
()=>{F||alert("Gif\u672a\u52a0\u8f7d\u5b8c\u6bd5, \u8bf7\u7a0d\u7b49\u7247\u523b!")})}})}});e.ajax({url:`/ajax/illust/${y().illustId}/ugoira_meta`,dataType:"json",success:({body:E})=>{GM.getValue("download-name","{pid}").then(F=>{F=e(`<a href="${E.originalSrc}" download="${f(F)}"></a>`);M.find("button").wrap(F)})}});GM.getValue("switch-img-preload",!0).then(E=>{E&&G.find("button").click()});GM.getValue("MO",!0).then(E=>{E||l.disconnect()})}}),p=()=>z((b,l)=>{for(let m=0,q=b.length;m<q;m++){const t=
b[m],v=e(t.target),A=v.find(n);if(!(1<y().pageCount&&"childList"===t.type&&A.length)||v.find("#ahao-download-zip").length)continue;L("\u4e0b\u8f7d\u591a\u56fe");GM.getValue("switchImgMulti",!0).then(x=>{x&&A.parent("section").next("button").click()});const R=new JSZip;let M=0;const G=y().pageCount,E=y().urls.original,F=Array(parseInt(G)).fill().map((x,w)=>E.replace(/_p\d\./,`_p${w}.`)),I=c({$shareButtonContainer:A,id:"ahao-download-zip",text:`${u("download")}`,clickFun(){"true"!==e(this).attr("start")?
(e(this).attr("start",!0),e.each(F,(x,w)=>{GM.xmlHttpRequest({method:"GET",url:w,headers:{referer:"https://www.pixiv.net/"},overrideMimeType:"text/plain; charset=x-user-defined",onload({responseText:B}){const N=new Uint8Array(B.length);let J=0;for(;J<B.length;)N[J]=B.charCodeAt(J),J++;const O=w.split(".").splice(-1),H=new Blob([N],{type:d(O)});GM.getValue("download-name","{pid}").then(K=>{R.file(`${f(K)}_${x}.${O}`,H,{binary:!0})});M++;I.find("p").html(`${u("download")}${M}/${G}`)}})})):M<G?alert(u("download_wait")):
GM.getValue("download-name","{pid}").then(x=>{R.generateAsync({type:"blob",base64:!0}).then(w=>saveAs(w,f(x)))})}});GM.getValue("switch-img-preload",!0).then(x=>{x&&I.find("button").click()});GM.getValue("MO",!0).then(x=>{x||l.disconnect()})}});return[[g(),g],[k(),k],[h(),h],[p(),p]]},()=>V()],["artist_info",null,()=>{const c=()=>z((f,n)=>{for(let p=0,b=f.length;p<b;p++){var g=f[p];e(g.target);var k=e("ul._2AOtfl9").parent();if("childList"!==g.type||0>=k.length||0<e("body").find("#uid").length)continue;
var h=k.clone();g=h.children("ul");h.children(":not(ul)").remove();g.empty();k.before(h);const l=X();k=e(`<li id="uid"><div style="font-size: 20px;font-weight: 700;color: #333;margin-right: 8px;line-height: 1">UID:${l}</div></li>`).on("click",function(){const q=e(this);q.html(`<span>UID${u("copy_to_clipboard")}</span>`);GM.setClipboard(l);setTimeout(()=>{q.html(`<span>UID${l}</span>`)},2E3)});g.append(k);k=(k=C.user[l].background)&&k.url||"";h=e('<li><div style="font-size: 20px;font-weight: 700;color: #333;margin-right: 8px;line-height: 1"></div></li>');
const m=h.find("div");k&&"none"!==k?m.append(`<img src="${k}" width="30px"><a target="_blank" href="${k}">${u("background")}</a>`):m.append(`<span>${u("background_not_found")}</span>`);g.append(h);GM.getValue("MO",!0).then(q=>{q||n.disconnect()})}}),a=()=>z((f,n)=>{for(let h=0,p=f.length;h<p;h++){var g=f[h],k=e(g.target).parent().find("main").next("aside");if("childList"!==g.type||0>=k.length)continue;g=k.find("section:first").find("h2");if(0>=g.length||0<k.find("#ahao-background").length)continue;
const b=X(),l=(k=C.user[b].background)&&k.url||"";k=g.clone().attr("id","ahao-background");k.children("a").remove();k.children("div").children("div").remove();k.prepend(`<img src="${l}" width="10%"/>`);k.find("div a").attr("href",l?l:"javascript:void(0)").attr("target","_blank").text(l?u("background"):u("background_not_found"));g.after(k);g=g.clone();g.children("a").remove();g.children("div").children("div").remove();g.find("a").attr("href","javascript:void(0)").attr("id","ahao-uid").text(`UID: ${b}`);
g.on("click",function(){const m=e(this);m.find("a").text(`UID${u("copy_to_clipboard")}`);GM.setClipboard(b);setTimeout(()=>{m.find("a").text(`UID: ${b}`)},2E3)});k.after(g);GM.getValue("MO",!0).then(m=>{m||n.disconnect()})}}),d=()=>z((f,n)=>{for(let g=0,k=f.length;g<k;g++)n=f[g],"childList"===n.type&&(n=e(n.target),n.find('div[role="img"]').each(function(){const h=e(this),p=h.prop("tagName"),b=h.getBackgroundUrl();if(b){var l=e('<img class="ahao-user-img" src=""/>').attr("src",b);l.css("width",h.css("width")).css("height",
h.css("height"));"div"===p.toLowerCase()&&(l.attr("class",h.attr("class")),l.html(h.html()),h.replaceWith(()=>l))}}),n.find("a[data-user_id][data-src]").each(function(){const h=e(this),p=h.find("div"),b=e("<img/>");b.attr("src",h.attr("data-src"));p.length&&(b.attr("class",p.attr("class")).css("width",p.css("width")).css("height",p.css("height")),h.html(b))}))});return[[c(),c,()=>/.+\/users\/\d+.*/.test(location.href)],[a(),a,()=>V()],[d(),d,()=>!0]]},()=>!0],["comment_load",null,()=>{let c=null;
L("\u52a0\u8f7d\u8bc4\u8bba \u521d\u59cb\u5316");GM.getValue("switch-comment",!0).then(a=>{const d=u("watchlist");c=z((f,n)=>{if(a&&V())for(let g=0,k=f.length;g<k;g++){n=f[g];if("childList"!==n.type)continue;const h=e("div > div:eq(2) > div div[role='button']");let p=h[0];p&&(p.textContent===d?1<h.length&&(p=h[1],p.click()):p.click());e(n.target).find("._28zR1MQ").click()}})});return c},()=>!0],["artwork_tag",null,()=>{L("\u6807\u8bb0\u4f5c\u54c1 \u521d\u59cb\u5316");return z((c,a)=>{for(let d=0,
f=c.length;d<f;d++){a=c[d];const n=e(a.target).find(".stacc_ref_illust_title");"childList"===a.type&&n.length&&n.each(function(){const g=e(this).find("a");if(!g.attr("ahao-illust-id")){var k=(new URL(`${location.origin}/${g.attr("href")}`)).searchParams.get("illust_id");g.attr("ahao-illust-id",k);e.ajax({url:`/ajax/illust/${k}`,dataType:"json",success:({body:h})=>{const p=parseInt(h.illustType);h=1<parseInt(h.pageCount);switch(p){case 0:case 1:g.after(`<p>${h?u("illust_type_multiple"):u("illust_type_single")}</p>`);
break;case 2:g.after(`<p>${u("illust_type_gif")}</p>`)}}})}})}})},()=>/.+\/stacc.+/.test(location.href)],["redirect_cancel",null,()=>z((c,a)=>{for(let d=0,f=c.length;d<f;d++)a=c[d],"childList"===a.type&&e(a.target).find('a[href*="jump.php"]').each(function(){const n=e(this),g=n.attr("href").match(/jump\.php\?(url=)?(.*)$/)[2];n.attr("href",decodeURIComponent(g))})}),()=>!0]],aa=r.length;for(let c=0;c<aa;c++)if(U[r[c][0]]&&null===r[c][1]){const a=r[c][2]();a instanceof Promise?a.then(d=>r[c][1]=d):
r[c][1]=a}window.navigation.addEventListener("navigate",()=>{for(let f=0;f<aa;f++)if(!U[r[f][0]]){if(null!==r[f][1])if(r[f][1]instanceof Array){var c=r[f][1];for(var a=0;a<c;a++){var d=r[f][1][a];null!==d[0]&&(d[0].disconnect(),d[0]=null)}}else r[f][1].disconnect(),r[f][1]=null}else if(r[f][3]())if(r[f][1]instanceof Array)for(c=r[f][1],a=0;a<c;a++)d=r[f][1][a],d[2]()?null===d[0]&&(d[0]=d[1]()):(d[0].disconnect(),d[0]=null);else null===r[f][1]&&(r[f][1]=r[f][2]());else if(null!==r[f][1])if(r[f][1]instanceof
Array)for(c=r[f][1],a=0;a<c;a++)d=r[f][1][a],d[0].disconnect(),d[0]=null;else r[f][1].disconnect(),r[f][1]=null});/.+\/search\.php.*/.test(location.href)||/.+\/tags\/.*\/artworks.*/.test(location.href)});
