// ==UserScript==
// @name         Reddit Fix
// @namespace    http://tampermonkey.net/
// @version      1.9.8
// @author       Bum
// @require      http://code.jquery.com/jquery-3.4.1.min.js
// @match        https://www.reddit.com/*
// @match        https://new.reddit.com/*
// @grant        GM_addStyle
// @downloadURL https://raw.githubusercontent.com/siritami/test1/release/release/Reddit20Fix.user.js
// @updateURL https://raw.githubusercontent.com/siritami/test1/release/release/Reddit20Fix.meta.js
// ==/UserScript==
var holdTopicsInMemory="false",commentEffects="false",originalBehavior="false",topicLimitInDom=70,lastScrollTop=0,scrollTopWhenREmoved=-1,menuButtonWasAdded=!1,subsToHide="",removeBorderRadius=!1,hideRecentSection=!1,customFeedState="open",hidePromotedlinks=!0,lastTopicRemovedTime=(new Date).getTime();null!=localStorage.getItem("removeBorderRadius")&&(removeBorderRadius=localStorage.getItem("removeBorderRadius"));null!=localStorage.getItem("holdTopicsInMemory")&&(holdTopicsInMemory=localStorage.getItem("holdTopicsInMemory"));
null!=localStorage.getItem("commentEffects")&&(commentEffects=localStorage.getItem("commentEffects"));null!=localStorage.getItem("originalBehavior")&&(originalBehavior=localStorage.getItem("originalBehavior"));null!=localStorage.getItem("subsToHide")&&(subsToHide=localStorage.getItem("subsToHide"));null!=localStorage.getItem("hidePromotedlinks")&&(hidePromotedlinks=localStorage.getItem("hidePromotedlinks"));null!=localStorage.getItem("hideRecentSection")&&(hideRecentSection=localStorage.getItem("hideRecentSection"));
null!=localStorage.getItem("customFeedState")&&(customFeedState=localStorage.getItem("customFeedState"));var topicsInMemory=[],isAPop=!1,maxOffset=0;
(function(){function c(a){var b;(b=document.getElementById("GM_addStyle"))||(b=document.createElement("style"),b.type="text/css",b.id="GM_addStyle",document.head.appendChild(b));b=b.sheet;b.insertRule(a,(b.rules||b.cssRules||[]).length)}function l(a){var b;(b=document.getElementById("GM_addStyle"))||(b=document.createElement("style"),b.type="text/css",b.id="GM_addStyle",document.head.appendChild(b));b=b.sheet;for(var d=0;d<b.cssRules.length;d++)b.cssRules[d].selectorText==a&&b.deleteRule(d)}function t(a,
b){return'<a class="M2Hk_S2yvXpsNPfZMBMur customRedditFixMenu" id = "'+a+'" ><div class="_1lwNBHmCQJObvqs1fXKSYR" style="margin-right: 0px;">'+b+"</div></a>"}function g(a,b,d){return"true"==a||1==a?'  <span style="width: 100%;"><input type="checkbox" checked id="'+b+'" name="'+d+'" /> '+d+"</span>":'<span style="width: 100%;"><input type="checkbox" id="'+b+'" name="'+d+'" /> '+d+"</span>"}function u(){var a=$("._2pUO1Sfe7WlIHvq6goN3Pz");0<a.find(".customRedditFixMenu").length||(a.append(t("redditFixReloadAll",
"Reload All")),$("#redditFixReloadAll").click(function(){for(var b=topicsInMemory.length-1;0<=b;--b){var d=topicsInMemory.pop(b);$(".rpBJOHq2PR60pnwJlUyP0").prepend(d)}maxOffset=$(document).height()}),a.append(t("redditFixReload25","Reload 25")),$("#redditFixReload25").click(function(){for(var b=0;25>b;++b){var d=topicsInMemory.pop(b);$(".rpBJOHq2PR60pnwJlUyP0").prepend(d)}maxOffset=$(document).height()}))}function v(){if(0<$('[aria-controls="multireddits_section"]').length){var a=$('[aria-controls="multireddits_section"]').closest("faceplate-expandable-section-helper");
a.bind("click",function(){$(this).is("[open]")?(customFeedState="open",localStorage.setItem("customFeedState","open")):(localStorage.setItem("customFeedState",""),customFeedState="")});""==customFeedState&&a.removeAttr("open")}else setTimeout(v,300)}function m(){if(0<$(".subgrid-container").length&&1!=$(".observerIsAttached").length){k();$(".subgrid-container").addClass("observerIsAttached");var a=$(".subgrid-container").first().get(0);(new MutationObserver(function(b,d){for(var n of b)n.addedNodes.forEach(function(C){$(C).find("article.w-full")&&
k()})})).observe(a,{attributes:!1,childList:!0,subtree:!0})}else setTimeout(m,300)}function w(){$(".fixmodal").fadeOut("fast");document.removeEventListener("click",w)}function p(a){"true"==a||1==a?c(".promotedlink{display: none !important;}"):l(".promotedlink")}function q(a){"true"==a||1==a?c("reddit-recent-pages{display: none !important;}"):l("reddit-recent-pages")}function r(a){"true"==a||1==a?c("*:not(.shreddit-subreddit-icon__icon){border-radius: 0 !important;}"):l(":not(.shreddit-subreddit-icon__icon)")}
function k(){var a=subsToHide.split(";");let b=0;for(;b<a.length;){let d=$("a[href*='"+a[b]+"']").closest("article");$(d).closest("hr").remove();$(d).remove();b++}}r(removeBorderRadius);q(hideRecentSection);p(hidePromotedlinks);k();"false"==commentEffects&&(c('img[src*="flame"]{display:none;}'),c('div[aria-role="presentation"]{box-shadow:none !important;background : transparent !important;}'));c(".wwHbgRV0ZXGp5CHHlpo5u{display:block !important;}");c("._1Q2mF3u7v9hBVu_4bkC7R4{display:block !important;}");
c("._3hUbl08LBz2mbXjy0iYhOS,._3b8u2OJXaSDdBWoRB7zUoK {height: 50px !important;width: 100% !important; bottom: 0 !important;}");c("._3UEq__yL-82zX4EyuluREz,.gUpEQXQu8G8UvISmBIPsj,._1RZSSlyqzokrcxh0ESwE2e{display:none !important;}");c(".vLH0XV-l8Y4mNGUvw4HHy{display:none !important;}");c(".eI6Ep6BNFA5DZjPWNVb4,._2XQ3ZY6qCbEm9_WtvLLFru{display:none !important;}");c(".fixmodal {position:fixed;background-color:rgba(0, 0, 0, 0.5);height:100%;width:100%;top:0;left:0;display:none; z-index: 1000;}");c("#fixPopup {padding:5px;text-align:center;}");
c(".fixmodalWrap {margin: 50px auto; position:relative;width: fit-content;} ");var x=window.screen.height-200;c("#fixPopup img {max-height:"+x+"px;}");c("._2f5uYHvlfzs2DngQsiCdvB {height: 50px !important;width: 100% !important; position: relative !important; bottom: 50px !important;}");c('.videoFixIcon {margin: 50px auto; background: url("https://www.pngall.com/white-play-png")} ');c(".expandDivCaption {padding: 5px!important; white-space: pre-wrap !important;max-height: max-content !important; display: inline-block !important; overflow-wrap: break-word !important;} ");
c(".expandSpanCaption{height: auto !important; position: absolute !important; bottom: 0;} ");c(".expandDisableClick{pointer-events: none; } ");c(".expandEnableClick{pointer-events: auto; !important; } ");c(".expandGarbageRedditCaptions{position:relative !important; } ");window.addEventListener("scroll",function(a,b){var d=Date.now();return function(){0>d+b-Date.now()&&(a(),d=Date.now())}}(function(){if("true"!=originalBehavior){"true"==holdTopicsInMemory&&u();var a=$(document).scrollTop();a>maxOffset&&
(lastScrollTop=a,maxOffset=0)}},300));let y=location.href;setInterval(()=>{location.href!==y&&(y=location.href,m())},500);$(document).on("mousedown","._15nNdGlBIgryHV04IfAfpA",function(a){$(this).parent().toggleClass("expandSpanCaption");$(this).toggleClass("expandDivCaption");0<$(".DraftEditor-root").length&&$(this).parent().toggleClass("expandGarbageRedditCaptions");a.stopPropagation();a.preventDefault();a.cancelBubble=!0;a.stopImmediatePropagation();return!1});var z=!1;$("img").on("keyup keydown",
function(a){z=a.ctrlKey});$("img").on("click",function(){if(z)return e.stopPropagation(),e.preventDefault(),e.cancelBubble=!0,e.stopImmediatePropagation(),!1});$(document).on("mousedown","._3b8u2OJXaSDdBWoRB7zUoK,._3hUbl08LBz2mbXjy0iYhOS,._2f5uYHvlfzs2DngQsiCdvB",function(a){$(".fixmodal").fadeIn("fast");$("#fixPopup img").remove();$("#fixPopup iframe").remove();var b=$(this).parent().find("iframe");0<b.length?(b=b.clone(),b.appendTo("#fixPopup"),b.css({width:"800px","max-height":x+"px"})):(b=$(this).parent().find("img").attr("src"),
$('<img src="'+b+'" alt="image3" />').appendTo("#fixPopup"));setTimeout(()=>{document.addEventListener("click",w)},100);a.stopPropagation();a.preventDefault();a.cancelBubble=!0;a.stopImmediatePropagation();return!1});m();v();$("body").append('<div class="fixmodal"> <div class="fixmodalWrap"><div id="fixPopup"></div> </div></div>');c("\n.container__menu {\n                /* Absolute position */\n                position: absolute;\n\n                /* Reset */\n                list-style: none;\n                margin: 0;\n                padding: 0;\n                display: none;\n\n                /* Misc */\n                border: 1px solid #cbd5e0;\n                border-radius: 0.25rem;\n                background-color: #f7fafc;\n            }\n");
c("\n    .open {\n    display: block;\n    z-index: 9999;\n}\n");c("\n.container__item {\n                padding: 0.5rem 1rem;\n                white-space: nowrap;\n                cursor: pointer;\n    color: black;\n            }\n");c("\n .container__item:hover {\n                background-color: #bee3f8;\n            }\n");c("\n.container__divider {\n                border-bottom: 1px solid #cbd5e0;\n                height: 1px;\n            }\n");$("body").append('\n    <ul id="redditfixShowImage" class="container__menu">\n                    <li class="container__item">Show Image</li>\n                </ul>\n                ');
var f=$("#redditfixShowImage"),A,B,h=null;$(document).mousemove(function(a){A=a.pageX;B=a.pageY});$(document).on("mousedown",function(a){if($(event.target).is("img")){$(this).on("contextmenu",b);function b(d){f.hasClass("open")?f.removeClass("open"):!1;0<=$(d.target).attr("src").toUpperCase().indexOf("BLUR=")&&(f.css({top:B,left:A}).addClass("open"),d.preventDefault(),h=d.target)}f.click(function(d){d.stopPropagation()});$(document).click(function(){f.hasClass("open")?f.removeClass("open"):!1});$(".container__item").click(function(){var d=
$(h).attr("src"),n=/^.*\/(.*)\.?(.*)?\?/g.exec(d);0<=d.toUpperCase().indexOf("EXTERNAL")?(d=$(h).parents(".STit0dLageRsa2yR4te_b").parent().find(".styled-outbound-link"),$(h).attr("src",d.attr("href"))):$(h).attr("src","https://i.redd.it/"+n[1]);$(h).attr("style","filter:none; width: auto; height: 100%;");f.removeClass("open")})}});(function(){$("body").append('\n    <div class="enhancecontainer" style="display:none;">\n\n    </div>\n    ');$(".enhancecontainer").append('<div class="tw-border-t tw-mg-t-1 tw-mg-x-05 tw-pd-b-1 customEnhanceMenu"" ></div><div class="tw-mg-y-05 tw-pd-x-05" style="width: 100%;"><p class="tw-c-text-alt-2 tw-font-size-6 tw-strong tw-upcase" style="color: var(--color-text-alt-2)!important;    font-size: var(--font-size-6)!important;    font-weight: 600!important;    text-transform: uppercase!important;">Reddit enhance</p></div>');
$(".enhancecontainer").append(g(commentEffects,"redditFixCheckBoxBackground","Remove comment effects"));$("#redditFixCheckBoxBackground").click(function(){var a=$(this);a.prop("checked")?(a.removeClass("_1L5kUnhRYhUJ4TkMbOTKkI"),localStorage.setItem("commentEffects",!1),commentEffects="false"):(a.addClass("_1L5kUnhRYhUJ4TkMbOTKkI"),localStorage.setItem("commentEffects",!0),commentEffects="true")});$(".enhancecontainer").append(g(holdTopicsInMemory,"fixRedditKeepTopicsInMemory","Save topics in ram"));
$("#fixRedditKeepTopicsInMemory").click(function(){$(this).prop("checked")?(localStorage.setItem("holdTopicsInMemory",!0),holdTopicsInMemory="true",u()):(localStorage.setItem("holdTopicsInMemory",!1),holdTopicsInMemory="false",$("#redditFixReloadAll").remove(),$("#redditFixReload25").remove())});$(".enhancecontainer").append(g(originalBehavior,"fixRedditoriginalBehavior","Original behavior"));$("#fixRedditoriginalBehavior").click(function(){var a=$(this);a.prop("checked")?(localStorage.setItem("originalBehavior",
!0),originalBehavior="true"):(a.addClass("_1L5kUnhRYhUJ4TkMbOTKkI"),localStorage.setItem("originalBehavior",!1),originalBehavior="false")});$(".enhancecontainer").append(g(hidePromotedlinks,"fixhidePromotedlinks","Hide promoted links"));$("#fixhidePromotedlinks").click(function(){var a=$(this);a.prop("checked")?(localStorage.setItem("hidePromotedlinks",!0),p(!0),hidePromotedlinks="true"):(a.addClass("_1L5kUnhRYhUJ4TkMbOTKkI"),localStorage.setItem("hidePromotedlinks",!1),p(!1),hidePromotedlinks="false")});
$(".enhancecontainer").append(g(removeBorderRadius,"fixremoveBorderRadius","Remove border radius"));$("#fixremoveBorderRadius").click(function(){var a=$(this);a.prop("checked")?(localStorage.setItem("removeBorderRadius",!0),r(!0),removeBorderRadius="true"):(a.addClass("_1L5kUnhRYhUJ4TkMbOTKkI"),localStorage.setItem("removeBorderRadius",!1),r(!1),removeBorderRadius="false")});$(".enhancecontainer").append(g(hideRecentSection,"fixHideRecentSection","Hide recent section"));$("#fixHideRecentSection").click(function(){$(this).prop("checked")?
(localStorage.setItem("hideRecentSection",!0),q(!0)):(localStorage.setItem("hideRecentSection",!1),q(!1))});$(".enhancecontainer").append('<span style="margin-top: 10px;">Hide subreddit from appearing in feed. If you remove subs you have to restart. If you add just click save, no need to restart.</span>');$(".enhancecontainer").append('\n        <textarea id="fixHideSubreddits" name="fixHideSubreddits" rows="3" cols="40" style = "flex:1">'+subsToHide+"</textarea>\n        ");$(".enhancecontainer").append(" <button type='button' id='fixSaveSubredditsHidden' style = 'background:darkgreen; flex: 2'>Save</button> ");
$(".enhancecontainer").append('<div class="tw-border-t tw-mg-t-1 tw-mg-x-05 tw-pd-b-1 customEnhanceMenu"" ></div><div class="tw-mg-y-05 tw-pd-x-05" style="width: 100%;"><p class="tw-c-text-alt-2 tw-font-size-6 tw-strong tw-upcase"\n\nstyle="color: var(--color-text-alt-2)!important;\n    font-size: smaller;line-height: 1.4;\n    margin-top: 6px;">Any subreddit containing this word will be hidden from your feed. This is Case Sensitive. Write the exact subreddit name if you only target that subreddit. Use ; to separate keywords. Example: funny;tiktok;celebrity</p></div>');
$("body").append('\n    <div class="Layout-sc-nxg1ff-0 jA-dUUY"><div class="Layout-sc-nxg1ff-0 dDnLci">\n    <div class="Layout-sc-nxg1ff-0 bYXYej">\n    <div class="InjectLayout-sc-588ddc-0 iETGeJ">\n    <button class="ScCoreButton-sc-1qn4ixc-0 enhanceButton jGqsfG ScButtonIcon-sc-o7ndmn-0 fNzXyu"  style="\n    background: url(https://i.imgur.com/kWu713g.png);\n    background-size: 22px;\n    z-index:999;\n    background-repeat: no-repeat;\n    background-position: center; width: 25px;\n    height: 25px; top: 60px; right: 60px; position:fixed;" ></button>\n  </div>\n  </div>\n  <div aria-label="Whispers" role="button" data-click-out-id="threads-box" data-a-target="threads-box-closed" class="Layout-sc-nxg1ff-0 emWtQg InjectLayout-sc-588ddc-0 kgrtoC whispers-threads-box__container"></div></div></div>\n\n    ');
$(".enhanceButton").click(function(){$(".enhancecontainer").toggle()});$("#fixSaveSubredditsHidden").click(function(){subsToHide=$("#fixHideSubreddits").val();localStorage.setItem("subsToHide",subsToHide);k()})})();c(".enhanceButton:hover{    background-color:var(--color-background-button-text-hover) !important;}");c("\n    .enhancecontainer {\ndisplay: flex;\n    flex-wrap: wrap;\n    justify-content: center;\n    background: #393939;\n    padding: 10px;\n    width: 200px;\n    position: fixed;\n    right: 100px;\n    z-index: 100;\n    margin-top: 66px;\n    width: 500px;\n    height: auto;\n    top: 0;\n}\n    ");
c("\n    input.enhancCheck[type=checkbox] + label {\n  display: block;\n    cursor: pointer;\n    height: fit-content;\n    flex: 1 0 35%;\n    margin-top: 5px;\n}\n");c("\n    input.enhancCheck[type=checkbox] {\n  display: none;\n}");c("\n    ._1L5kUnhRYhUJ4TkMbOTKkI{\n    background: green !important;\n    }\n\n    ");c("\n    #redditFixCheckBoxBackground,#fixRedditKeepTopicsInMemory,#fixRedditoriginalBehavior{\n    background: red;\n    }\n\n    ");c(' input.enhancCheck[type=checkbox] + label:before {\n  content: "\\2714";\n  border: 0.1em solid #fff;\n  border-radius: 0.2em;\n  display: inline-block;\n  width: 1em;\n  height: 1em;\n  padding-left: 0.2em;\n  padding-bottom: 0.3em;\n  margin-right: 0.2em;\n  vertical-align: bottom;\n  color: transparent;\n}');
c("input.enhancCheck[type=checkbox]:checked + label:before {\n  background-color: #ED820A;\n  border-color:white;\n  color: #fff;\n}")})();
