// ==UserScript==
// @name            Resize Video To Window Size
// @author          Chris H (Zren / Shade)
// @namespace       http://xshade.ca
// @version         67
// @include         https://www.crunchyroll.com/*
// @include         https://beta.crunchyroll.com/*
// @include         https://static.crunchyroll.com/vilos-v2/web/vilos/player.html*
// @include         https://docs.google.com/file/*
// @include         https://drive.google.com/drive/*
// @include         https://drive.google.com/file/*
// @include         https://vimeo.com/*
// @include         http://onepieceofficial.com/videos.aspx*
// @include         http://www.onepieceofficial.com/videos.aspx*
// @include         https://www.youpak.com/watch*
// @include         https://olympics.cbc.ca/video/*
// @include         https://olympics.cbc.ca/divaPlayer/*
// @include         http://www.dailymotion.com/*
// @include         https://www.dailymotion.com/*
// @include         https://streamable.com/*
// @include         https://www.globaltv.com/shows/*
// @include         https://watch.globaltv.com/video/*
// @include         https://www.much.com/shows/south-park/episode/*/*/
// @include         http://*.ctvnews.ca/*
// @include         https://watch.cbc.ca/live/channel/*
// @include         https://watch.cbc.ca/live/*
// @include         https://www.ctv.ca/shows/*
// @include         https://www.ctv.ca/video/*
// @include         https://www.ctv.ca/*/Video*
// @include         https://www.ctv.ca/Movie/*
// @include         https://www.funimation.com/shows/*
// @include         https://www.funimation.com/player/*
// @include         https://www.crave.ca/*
// @include         https://tubitv.com/*
// @include         https://tv.bell.ca/*
// @grant           GM_addStyle
// @downloadURL https://raw.githubusercontent.com/siritami/test1/release/release/Resize20Video20To20Window20Size.user.js
// @updateURL https://raw.githubusercontent.com/siritami/test1/release/release/Resize20Video20To20Window20Size.meta.js
// ==/UserScript==
(function(){var d=function(a){a+="{position: fixed;top: 0;";a+="left: 0;";a+="right: 0;";a+="bottom: 0;";a+="}";GM_addStyle(a)},c=function(a){document.body.insertBefore(a,document.body.firstChild);a.style.width="100%";a.style.height="100%";a.style.backgroundColor="#000"},e=function(a,b){var f=function(){var g=document.querySelector(a);g?b(g):setTimeout(f,100)};f()},h=function(){window.addEventListener("keydown",function(a){if(" "==a.key&&a.target==document.body){var b=document.querySelector(".jwplayer video");
b&&(a.preventDefault(),b.paused?b.play():b.pause())}})};if(document.location.host.endsWith("crunchyroll.com"))if("www.crunchyroll.com"==document.location.hostname||"beta.crunchyroll.com"==document.location.hostname){GM_addStyle(".erc-header.rvtws-header-hidden { position: absolute; }.erc-header.rvtws-header-hidden .header-content { opacity: 0; transition: opacity: 0.1s; }.erc-header.rvtws-header-hidden .header-content:hover { opacity: 1; }.erc-watch-episode-layout .video-player-wrapper { max-height: 100vh; height: 100vh; display: flex; }");
function a(){var b=document.querySelector(".erc-header"),f=document.querySelector(".erc-watch-episode");b&&(f?b.classList.add("rvtws-header-hidden"):b.classList.remove("rvtws-header-hidden"))}window.addEventListener("popstate",a);setInterval(a,1E3);a()}else"static.crunchyroll.com"==document.location.hostname&&"/vilos-v2/web/vilos/player.html"==document.location.pathname&&(GM_addStyle("#vilosRoot { height: 100vh !important; }"),GM_addStyle("#vilosControlsContainer > div:first-child { margin-top: 3.75rem; }"));
else if(document.location.href.startsWith("https://docs.google.com/file/"))d("#drive-viewer-video-player-object-0"),GM_addStyle("body:not(:hover) .ytp-chrome-bottom { opacity: 0 !important; }body:not(:hover) .drive-viewer-toolstrip { opacity: 0 !important; }");else if(document.location.href.startsWith("https://drive.google.com/"))d(".drive-viewer-video-player"),GM_addStyle(".drive-viewer-toolstrip { opacity: 0 !important; }.drive-viewer-toolstrip:hover { opacity: 1 !important; }");else if(document.location.href.startsWith("https://vimeo.com/")){if(!/\/\d+/.exec(document.location.pathname))return;
GM_addStyle(".js-player_area-wrapper, .player_area-wrapper, .player_area, .player_container, .player, .video-wrapper, .video, .video * { width: 100vw !important; height: 100vh !important; max-height: 100vh !important; }.vp-player-layout { left: 0 !important; top: 0 !important; width: 100vw !important; height: 100vh !important; }.clip_main > *:not(.player_area-wrapper) { margin-top: 70px; }.VimeoBrand_ColorRibbon, .body_ribbon, .topnav_desktop, .topnav_mobile { position: absolute; top: 100vh; width: 100%; }.topnav_desktop { top: calc(100vh + 5px); }");
function a(){var b=document.querySelector('button.play[aria-label="Play"]');b?b.click():setTimeout(a,100)}setTimeout(a,100)}else if(document.location.host.endsWith("onepieceofficial.com"))c(document.querySelector("#FUNimationVideo"));else if(document.location.host.endsWith("youpak.com"))c(document.querySelector(".videoWrapper")),GM_addStyle("body > .container { padding-top: 60px; }.navbar-fixed-top { position: absolute; top: 100vh; }body { padding-top: 0; }");else if("olympics.cbc.ca"==document.location.host)if(console.log(document.location.pathname,
document.location.pathname.match(/\/video\/([^\/]+)\/([^\/]+)(\/?)/)),document.location.pathname.match(/\/video\/([^\/]+)\/([^\/]+)(\/?)/))GM_addStyle('.cbc-video--player-wrapper { position: static !important; }.cbc-video {    position: absolute !important;    top: 0 !important;    left: 0 !important;    padding: 0px !important;    margin: 0px !important;    width: 100% !important;    height: 100vh !important;}figure.cbc-video--thumb-wrapper, a[data-js-hook="play-video"] picture img { max-height: 100vh !important; }.or-podium .or-box { position: static !important; }.or-podium .col-xs-1, .or-podium .col-sm-1, .or-podium .col-md-1, .or-podium .col-lg-1, .or-podium .col-xs-2, .or-podium .col-sm-2, .or-podium .col-md-2, .or-podium .col-lg-2, .or-podium .col-xs-3, .or-podium .col-sm-3, .or-podium .col-md-3, .or-podium .col-lg-3, .or-podium .col-xs-4, .or-podium .col-sm-4, .or-podium .col-md-4, .or-podium .col-lg-4, .or-podium .col-xs-5, .or-podium .col-sm-5, .or-podium .col-md-5, .or-podium .col-lg-5, .or-podium .col-xs-6, .or-podium .col-sm-6, .or-podium .col-md-6, .or-podium .col-lg-6, .or-podium .col-xs-7, .or-podium .col-sm-7, .or-podium .col-md-7, .or-podium .col-lg-7, .or-podium .col-xs-8, .or-podium .col-sm-8, .or-podium .col-md-8, .or-podium .col-lg-8, .or-podium .col-xs-9, .or-podium .col-sm-9, .or-podium .col-md-9, .or-podium .col-lg-9, .or-podium .col-xs-10, .or-podium .col-sm-10, .or-podium .col-md-10, .or-podium .col-lg-10, .or-podium .col-xs-11, .or-podium .col-sm-11, .or-podium .col-md-11, .or-podium .col-lg-11, .or-podium .col-xs-12, .or-podium .col-sm-12, .or-podium .col-md-12, .or-podium .col-lg-12 { position: static; }body:not(.cbc-main-page) { padding-top: 100vh; }'),
(c=document.querySelector('a[data-js-hook="play-video"]'))&&c.click();else if(document.location.pathname.startsWith("/divaPlayer"))GM_addStyle("#videoContainer:not(:hover) > .caption { opacity: 0; }#videoContainer:not(:hover) .controlbar-diva { opacity: 0 !important; }#videoContainer:not(:hover) #icon-menu-diva { opacity: 0; }#videoContainer:not(:hover) diva-simple-controls { opacity: 0 !important; }");else return;else if(document.location.host.endsWith("streamable.com")){if("/"==document.location.pathname)return;
GM_addStyle('#player-content, #player.container .media-container, #player.container #filler, #player.container .player { max-width: 100% !important; width:100%; }#player.container #filler { padding-bottom: 100vh !important; }.player { background: #000; }#player.container .player { display: flex; }.player, #player.container video { max-height: 100vh; object-fit: contain; }#player > div[style="height:15px;"] { display: none; }#player.container .topbanner { display: none; }')}else if(document.location.host.endsWith("globaltv.com"))GM_addStyle("html, body, #root, .App, .Video {min-height: 100%; height: 100%; max-height: 100%;min-width: 100%; width: 100%; max-width: 100%;}body { overflow-y: auto; }"),
e(".jwplayer",function(a){e(".jwplayer video",function(b){setTimeout(function(){b.muted=!1},200)})}),h();else if(document.location.host.endsWith("much.com"))GM_addStyle("#TopVideoWidgetSection, #ShowNav, #MainHeader, #MastHeadTakeover { display: none; }#ShowTop #PlayerWrapper, #ShowTop .container-fluid, #ShowTop #ShowInfo, #ShowTop {margin: 0 !important; padding: 0 !important;width: 100vw !important; height: 100vh !important; max-width: 100vw !important; max-height: 100vh !important;}#ShowTop #ShowInfo #EpisodeInfo { margin-top: 0 !important; }.jwplayer { max-height: 100vh; }#EpisodeInfo .new-episodes { display: none !important; }");
else if(document.location.host.endsWith("ctvnews.ca"))if("/latest"==window.location.pathname){if(document.body.style.opacity="0",document.documentElement.style.transition="background 0.4s",document.documentElement.style.background="#000",c=document.querySelector(".mainnavigation + .drop_down + script + .drop_down > .drop_down_element_container > div > div > ul > li:first-child > a"))window.location.href=c.href}else if("/video"==window.location.pathname){if(c=document.querySelector("body > .content > .video-header > .content-wrapper")){d=
document.querySelector("body > header");document.body.insertBefore(c,d);var k=document.querySelector("#mediaplayerdiv");c.querySelector(".topname").style.display="none";c.style.width="100%";c.style.height="100vh";c.style.maxWidth="100vw";c.style.maxHeight="100vh";c.style.background="#000";function a(){var b=document.documentElement.clientWidth,f=document.documentElement.clientHeight;k.style.transform="translate("+(b-960)/2+"px, "+(f-540)/2+"px) scale("+(Math.min(b/960,f/540)+")")}window.addEventListener("resize",
a);a();return}}else return;else if(document.location.host.endsWith("watch.cbc.ca"))GM_addStyle("#masthead { position: absolute; z-index: 1; width: 100%; opacity: 0; transition: opacity 250ms ease-in-out; }#masthead:hover { opacity: 1; }.regional-channel .container { max-width: 100%; }.player-container.live, .jwplayer.jw-flag-aspect-mode { max-height: 100vh; }.jwplayer.jw-stretch-uniform video { object-fit: contain !important; }.regional-channel footer.regional-channel-footer, section.content-article.live { padding: 10px 0; }section.content-article.live-premium { display: none; }.upgrade-banner, .live-premium, iframe.zEWidget-launcher { display: none; }.upgrade-banner + .app-container.with-banner-large { top: 0; }.content-article { padding-top: 0; padding-bottom: 0; }.content-section.live-detail-layout { max-width: 100%; }");
else if(document.location.host.endsWith("www.ctv.ca")){GM_addStyle('header.navigation { opacity: 0; position: fixed; }header.navigation:hover { opacity: 1; }.main { padding-top: 0 !important; }#vidi-player-standalone { margin: 0vw 0vw 0; }div[class*="VidiPlayerstyles__VidiPlayerStandAloneContainer"] { margin: 0vw 0vw 0; }.jwplayer.jw-flag-aspect-mode { min-height: 100vh !important; height: 100vh !important; max-height: 100vh !important; }div[class*="BrowserNotificationstyles"] { display: none; }div[class^="ArrowBackstyles__ButtonContainer"] { display: none; }div[class^="globalStyles__MainContainer"] { padding-top: 0 !important; }div[class^="VidiPlayerstyles__VidiPlayerPageContainer"] { margin: 0 !important; }');
e(".jwplayer",function(a){e(".jwplayer video",function(b){setTimeout(function(){b.muted=!1},200)})});h();var l=["/shows/the-daily-show-with-trevor-noah"];e('ul[class*="Episodesstyles__EpisodeList"]',function(a){if(0<=l.indexOf(document.location.pathname))for(var b=0;b<a.children.length;b++)a.insertBefore(a.children[b],a.firstChild)});setInterval(function(){var a=document.querySelector("#__next div:not(.App)");a&&(a=a.querySelector("h2"))&&"An unexpected error has occurred."==a.textContent&&window.location.reload()},
100)}else if(document.location.host.endsWith("funimation.com"))console.log("funimation.com"),d=document.querySelector(".video-player-section .video-player-container"),console.log("videoBoxElement",d),d?(c(d),d.classList.remove("col-md-10"),GM_addStyle("html, body { width: 100%; height: 100%; }.video-player-container { width: 100vw !important; height: 100vh !important; }#funimation-main-site-header { position: absolute; top: 100vh; }")):(console.log("location",document.location),e("#brightcove-player",
function(a){console.log("player",a);a.removeAttribute("muted");e(".vjs-mute-control.vjs-vol-0",function(b){console.log("muteButton",b);b.click()})}));else if(document.location.host.endsWith("crave.ca")){if(document.location.pathname.startsWith("/live"))return;d=document.querySelector("video-player");if(!d)return;GM_addStyle("footer, .back-button-wrapper, #mega-menu { display: none !important; }.container-site-margin { margin-left: 0; margin-right: 0; }.web-videoplayer { margin: 0; }html .jwplayer.jw-flag-aspect-mode { height: 100vh !important; }")}else if(document.location.host.endsWith("tubitv.com"))GM_addStyle("header { transition: transform .3s, opacity .3s !important; }header.hide-header { opacity: 0 !important }header.hide-header:hover { opacity: 1 !important; }header + div > div:first-child > div:first-child > div:nth-child(2) { top: 0 !important; left: 0 !important; width: 100% !important; height: 100vh !important; }header + div > div:first-child > div:first-child > div:nth-child(2) > div:first-child > section { padding-top: 0 !important; height: 100vh !important; }header + div > div:first-child > div:first-child > div:nth-child(2) > div:first-child > section > div > div:nth-child(2) > div:first-child { background-image: linear-gradient(0deg,rgba(0,0,0,0), rgba(0,0,0,0.25) 30%, rgba(0, 0, 0, 1) 90%); }header + div > div:first-child > div:first-child > div:nth-child(2) > div:first-child > section > div > div:nth-child(2) > div:nth-child(2) { background-image: linear-gradient(180deg,rgba(0,0,0,0), rgba(0,0,0,0.25) 30%, rgba(0, 0, 0, 1) 90%); }#captionsComponent > span { background: none !important; font-size: 3rem !important;text-shadow: 0 0 0.5rem #000, 0 0 0.5rem #000, 0 0 0.5rem #000, 0 0 0.5rem #000, 0 0 0.5rem #000, 0 0 0.5rem #000, 0 0 0.5rem #000, 0 0 0.5rem #000, 0 0 0.5rem #000, 0 0 0.5rem #000, 0 0 0.5rem #000, 0 0 0.5rem #000, 0 0 0.5rem #000, 0 0 0.5rem #000;}"),
c=function(){var a=document.querySelector("header");a&&(document.querySelector("video")?a.classList.add("hide-header"):a.classList.remove("hide-header"))},c(),setInterval(c,1E3);else if(document.location.host.endsWith("tv.bell.ca")){if(!document.location.pathname.startsWith("/watch/"))return;e("video[playsinline]",function(a){console.log("css",'.bg-greyscale-black.w-capped { position: absolute !important; top: calc((var(--headerHeight) + 100vh) * -1 ) !important; height: 100vh !important; }.bg-greyscale-black.w-full { position: absolute !important; top: -100vh !important; height: 100vh !important; }body { padding-top: 100vh !important; }[class*="&_.bmpui-ui-subtitle-label]:!bg-greyscale-black-70"].h-full.w-full.justify-center { max-width: 100% !important; }header[class="bg-greyscale-03 virgin:bg-tertiary-medium flex"][aria-label="Global"] { display: none !important; }');
GM_addStyle('.bg-greyscale-black.w-capped { position: absolute !important; top: calc((var(--headerHeight) + 100vh) * -1 ) !important; height: 100vh !important; }.bg-greyscale-black.w-full { position: absolute !important; top: -100vh !important; height: 100vh !important; }body { padding-top: 100vh !important; }[class*="&_.bmpui-ui-subtitle-label]:!bg-greyscale-black-70"].h-full.w-full.justify-center { max-width: 100% !important; }header[class="bg-greyscale-03 virgin:bg-tertiary-medium flex"][aria-label="Global"] { display: none !important; }')})}GM_addStyle("html::-webkit-scrollbar { width: 0; height: 0; } body::-webkit-scrollbar { width: 0; height: 0; }");
GM_addStyle("html { scrollbar-width: none; } body { scrollbar-width: none; }")})();
