// ==UserScript==
// @name            Resize YT To Window Size
// @author          Chris H (Zren / Shade)
// @license         MIT
// @icon            https://s.ytimg.com/yts/img/favicon_32-vflOogEID.png
// @homepageURL     https://github.com/Zren/ResizeYoutubePlayerToWindowSize/
// @namespace       http://xshade.ca
// @version         139
// @include         http*://*.youtube.com/*
// @include         http*://youtube.com/*
// @include         http*://*.youtu.be/*
// @include         http*://youtu.be/*
// @grant           none
// @downloadURL https://raw.githubusercontent.com/siritami/test1/release/release/Resize20YT20To20Window20Size.user.js
// @updateURL https://raw.githubusercontent.com/siritami/test1/release/release/Resize20YT20To20Window20Size.meta.js
// ==/UserScript==
(function(h){function t(b){return"undefined"===typeof b}function n(b,d){var e={},f;for(f in b)e[b[f]]=d;return e}function w(b,d,e){var f=new MutationObserver(function(k){k.forEach(function(p){e(p)})});b=document.querySelector(b);if(!b)return null;f.observe(b,d);return f}function u(b,d){var e="w"===d.key,f;if(!(f=d.target===document.body||"player-api"===d.target.id||"movie_player"===d.target.id))a:{var k=d.target;f=document.querySelector("#movie_player");for(k=k.parentNode;k;){if(k==f){f=!0;break a}k=
k.parentNode}f=!1}f&&e&&(d.preventDefault(),d.stopPropagation(),console.log("cancelIfToggleKey.validKeyCallback",b,"e",d),b&&b())}if(!h.ytwp){try{var v=h.self!==h.top}catch(b){v=!0}if(!v){var m=function(b){this.id=b;this.stylesheet=""};m.prototype.buildRule=function(b,d){var e="",f;for(f in d)e+="\t"+f+": "+d[f]+";\n";return b+" {\n"+e+"}\n"};m.prototype.appendRule=function(b,d,e){b instanceof Array&&(b=b.join(",\n"));if(t(d)||t(e)||"string"!==typeof d)if(!t(d)&&t(e)&&"object"===typeof d)var f=this.buildRule(b,
d);else{console.log("Illegal arguments",arguments);return}else f={},f[d]=e,f=this.buildRule(b,f);this.stylesheet+=f};m.injectIntoHeader=function(b,d){var e=document.getElementById(b);e||(e=document.createElement("style"),e.type="text/css",e.id=b,document.getElementsByTagName("head")[0].appendChild(e));e.appendChild(document.createTextNode(d))};m.prototype.injectIntoHeader=function(){m.injectIntoHeader(this.id,this.stylesheet)};var g=function(){};g.listeners=[];g.dispatch=function(b,d,e){for(var f=
this.listeners,k=0,p=f.length;k<p;k++)f[k].call(this,b,d,e)};g.onPushState=function(b,d,e){g.dispatch(b,d,e);return g.origPushState.apply(h.history,arguments)};g.onReplaceState=function(b,d,e){g.dispatch(b,d,e);return g.origReplaceState.apply(h.history,arguments)};g.inject=function(){g.injected||(g.origPushState=h.history.pushState,g.origReplaceState=h.history.replaceState,h.history.pushState=g.onPushState,h.history.replaceState=g.onReplaceState,g.injected=!0)};g.timerId=0;g.onTick=function(){var b=
h.location.pathname+h.location.search;g.lastPage!=b&&(g.dispatch({},document.title,h.location.href),g.lastPage=b)};g.startTimer=function(){g.lastPage=h.location.pathname+h.location.search;g.timerId=setInterval(g.onTick,500)};g.stopTimer=function(){clearInterval(g.timerId)};h.ytwpHistoryEvent=g;var l="body.ytwp-window-player";l+=":not(.enhancer-for-youtube-pinned-player)";var c='html:not([fullscreen="true"]) '+l,r=["transition","-ms-transition","-moz-transition","-webkit-transition","-o-transition"],
x=["transform","-ms-transform","-moz-transform","-webkit-transform","-o-transform"],a=h.ytwp={scriptShortName:"ytwp",log_:function(b,d){b.apply(console,["["+this.scriptShortName+"] "].concat(Array.prototype.slice.call(d)));return 1},log:function(){return this.log_(console.log,arguments)},error:function(){return this.log_(console.error,arguments)},initialized:!1,pageReady:!1,isWatchPage:!1};a.debugPage=function(){for(var b={display:"block",position:"static",left:"auto",right:"auto",top:"auto",bottom:"auto",
"padding-left":"0px","padding-right":"0px","padding-top":"0px","padding-bottom":"0px","margin-left":"0px","margin-right":"0px","margin-top":"0px","margin-bottom":"0px",width:"auto","min-width":"auto","max-width":"auto",height:"auto","min-height":"auto","max-height":"auto"},d=Object.keys(b),e=document.querySelector("#movie_player video"),f="";e&&e.parentNode;){var k=getComputedStyle(e),p={},q;for(q of k)d.includes(q)&&k[q]!=b[q]&&(p[q]=k[q]);k=e.outerHTML;k=k.substr(0,k.indexOf(">")+1);f+=k+" "+JSON.stringify(p)+
"\n";e=e.parentNode}f=f.split("\n").reverse().join("\n");a.log("debugPage",f)};a.hasYoutubeChanged=function(){var b="html body ytd-app #content.ytd-app ytd-page-manager#page-manager.ytd-app ytd-watch-flexy.ytd-page-manager #full-bleed-container.ytd-watch-flexy #player-full-bleed-container.ytd-watch-flexy #player-container.ytd-watch-flexy ytd-player#ytd-player.ytd-watch-flexy #container.ytd-player .html5-video-player .html5-video-container video.html5-main-video".split(" ");b=b.reverse();var d=document.querySelector(b[0]);
if(!d)return a.error("YT has changed!",b[0],"no longer exists!"),!0;for(var e=1;e<b.length;e++){var f=d.parentNode,k=b[e];f.matches(k)?d=f:a.error("YT has changed!",k,"no longer exists!")}return!1};a.isWatchUrl=function(b){b||(b=h.location.href);return b.match(/https?:\/\/(www\.)?youtube.com\/(c|channel|user)\/[^\/]+\/live/)?document.querySelector("ytd-browse")?!1:!0:b.match(/https?:\/\/(www\.)?youtube.com\/watch\?/)};a.setTheaterMode=function(b){var d=document.querySelector("ytd-watch:not([hidden])")||
document.querySelector("ytd-watch-flexy:not([hidden])")||document.querySelector("ytd-watch-grid:not([hidden])");if(d){var e=d.hasAttribute("theater");b!=e&&((b=document.querySelector(d.tagName+":not([hidden]) button.ytp-size-button"))||(b=document.querySelectorAll(d.tagName+":not([hidden]) button.ytp-screen-mode-settings-button")[1]),b&&b.click());d.canFitTheater_=!0}else if(d=document.querySelector("#page.watch"))e=d.classList.contains("watch-stage-mode"),b!=e&&(b=d.querySelector("button.ytp-size-button"))&&
b.click()};a.enterTheaterMode=function(){document.body.classList.contains("ytwp-window-player")&&a.setTheaterMode(!0)};a.enterTheaterMode();h.addEventListener("resize",a.enterTheaterMode);a.detectPlayerUnavailable=function(){document.querySelector("[player-unavailable]")&&a.event.removeBodyClass()};a.init=function(){a.log("init");a.initialized||(a.isWatchPage=a.isWatchUrl(),a.isWatchPage&&(a.removeSearchAutofocus(),document.getElementById("ytwp-style")||a.event.initStyle(),a.initScroller(),a.initialized=
!0,a.pageReady=!1));a.event.onWatchInit();a.isWatchPage&&a.html5PlayerFix()};a.initScroller=function(){h.addEventListener("scroll",a.onScroll,!1);h.addEventListener("resize",a.onScroll,!1);a.onScroll()};a.onScroll=function(){var b=document.documentElement.clientHeight;a.isWatchPage&&0==h.scrollY?document.body.classList.add("ytwp-scrolltop"):document.body.classList.remove("ytwp-scrolltop");a.isWatchPage&&h.scrollY<=b?document.body.classList.add("ytwp-viewing-video"):document.body.classList.remove("ytwp-viewing-video")};
a.event={initStyle:function(){a.log("initStyle");a.style=new m("ytwp-style");a.event.buildStylesheet();h.spf&&(l='body[data-spf-name="watch"]',c='html:not([fullscreen="true"]) '+l,a.event.buildStylesheet(),a.style.appendRule('body[data-spf-name="watch"]:not(.ytwp-window-player) #masthead-positioner',{position:"absolute",top:"100vh !important"}));a.style.injectIntoHeader()},buildStylesheet:function(){a.log("buildStylesheet");a.style.appendRule(l+"::-webkit-scrollbar",{width:"0 !important",height:"0 !important"});
a.style.appendRule("html",{"scrollbar-width":"none"});var b=n(r,"left 0s linear, padding-left 0s linear");b.padding="0 !important";b.margin="0 !important";a.style.appendRule([l+" #player",l+".ytcenter-site-center.ytcenter-non-resize.ytcenter-guide-visible #player",l+".ltr.ytcenter-site-center.ytcenter-non-resize.ytcenter-guide-visible.guide-collapsed #player",l+".ltr.ytcenter-site-center.ytcenter-non-resize.ytcenter-guide-visible.guide-collapsed #player-legacy",l+".ltr.ytcenter-site-center.ytcenter-non-resize.ytcenter-guide-visible.guide-collapsed #watch7-main-container"],
b);b=n(r,"width 0s linear, left 0s linear");b["float"]="initial";b.left=0;b["margin-left"]=0;a.style.appendRule(l+" #player-api",b);a.style.appendRule(l+" .watch-stage-mode #player .player-api",{left:"initial !important","margin-left":"initial !important"});a.style.appendRule([c+" #player",c+" #player-wrap",c+" #player-api",'html:not([fullscreen="true"]):not(.floater):not(.iri-always-visible) '+l+" #movie_player",c+" #player-mole-container",'html:not([fullscreen="true"]):not(.floater):not(.iri-always-visible) '+
l+" .html5-video-container",'html:not([fullscreen="true"]):not(.floater):not(.iri-always-visible) '+l+" .html5-main-video",c+" ytd-watch-flexy[theater] #player-theater-container.ytd-watch-flexy",c+" ytd-watch-flexy[flexy] #player-container-outer.ytd-watch-flexy",c+" ytd-watch-flexy[flexy] #player-container-inner.ytd-watch-flexy",c+" ytd-watch-flexy[flexy] #player-container.ytd-watch-flexy",c+" ytd-watch-grid[theater] #player-theater-container.ytd-watch-grid",c+" ytd-watch-grid[flexy] #player-container-outer.ytd-watch-grid",
c+" ytd-watch-grid[flexy] #player-container-inner.ytd-watch-grid",c+" ytd-watch-grid[flexy] #player-container.ytd-watch-grid"],{width:"100% !important","min-width":"100% !important","max-width":"100% !important",height:"100vh !important","min-height":"100vh !important","max-height":"100vh !important"});a.style.appendRule([c+" #player",c+" .html5-main-video"],{top:"0 !important",right:"0 !important",bottom:"0 !important",left:"0 !important"});a.style.appendRule(c+" #player .player-width","width","100% !important");
a.style.appendRule(c+" #player .player-height","height","100% !important");a.style.appendRule([c+" .html5-video-player .ad-container-single-media-element-annotations",c+" .html5-video-player .ytp-upnext"],"top","0");a.style.appendRule(c+" .ytp-fit-cover-video .html5-main-video","object-fit","contain !important");a.style.appendRule(c+" .ytp-cued-thumbnail-overlay-image",{"background-size":"contain !important","-moz-background-size":"contain !important","-webkit-background-size":"contain !important"});
a.style.appendRule(c+" #movie_player","background-color","#000000");a.style.appendRule(c+" #player",{position:"absolute"});a.style.appendRule(c,{"margin-top":"100vh"});a.style.appendRule(c+" button.ytp-button.ytp-cards-button","top","0");b=n(r,"margin-top 0s linear, padding-top 0s linear");b["margin-top"]="0 !important";b.top="0 !important";a.style.appendRule(c+" #watch7-sidebar",b);a.style.appendRule(c+".cardified-page #watch7-sidebar-contents","padding-top","0");a.style.appendRule("#skip-navigation.ytd-masthead",
"top","-150vh");b=n(r,"top 0s linear !important");a.style.appendRule(c+".hide-header-transition #masthead-positioner",b);a.style.appendRule(c+".ytwp-viewing-video #masthead-positioner",{position:"absolute",top:"100vh !important"});a.style.appendRule("html.floater "+l+".ytwp-viewing-video #masthead-positioner",{"z-index":"5"});a.style.appendRule(c+" .sbdd_a",{top:"56px"});a.style.appendRule(c+".ytwp-viewing-video .sbdd_a",{top:"calc(100vh + 56px) !important",position:"absolute !important"});a.style.appendRule(c+
".ytwp-viewing-video #appbar-guide-menu",{display:"initial",position:"absolute",top:"100% !important"});a.style.appendRule(c+".ytwp-viewing-video #page.watch #guide",{display:"initial",margin:"0",position:"initial"});a.style.appendRule(c+".lock-scrollbar",{top:"0 !important",position:"static !important"});a.style.appendRule(c+" #miniplayer-bar #player",{position:"static"});a.style.appendRule([c+" #miniplayer-bar #player",c+" #miniplayer-bar #player-api",'html:not([fullscreen="true"]):not(.floater):not(.iri-always-visible) '+
l+" #miniplayer-bar #movie_player",c+" #player-mole-container",'html:not([fullscreen="true"]):not(.floater):not(.iri-always-visible) '+l+" #miniplayer-bar .html5-video-container",'html:not([fullscreen="true"]):not(.floater):not(.iri-always-visible) '+l+" #miniplayer-bar .html5-main-video"],{width:"252px !important","min-width":"252px !important","max-width":"252px !important",height:"142px !important","min-height":"142px !important","max-height":"142px !important"});a.style.appendRule(".video-stream.html5-main-video",
{top:"0 !important"});a.style.appendRule(c+".ytwp-scrolltop","overflow-x","hidden");a.style.appendRule(c+" #placeholder-player","display","none");a.style.appendRule(c+" #watch-sidebar-spacer","display","none");a.style.appendRule(c+" .skip-nav","display","none");a.style.appendRule(c+" #page.watch","padding-top","0");a.style.appendRule(c+" .player-branded-banner","height","0");a.style.appendRule(c+" #body-container","position","static");a.style.appendRule('html:not([fullscreen="true"]).part_static_size:not(.content-snap-width-skinny-mode) '+
l+" .watch-non-stage-mode #player-playlist","width","1066px");a.style.appendRule([c+" #placeholder-playlist",c+" #player .player-height#watch-appbar-playlist"],{height:"540px !important","max-height":"540px !important"});b=n(r,"transform 0s linear");a.style.appendRule(c+" #watch-appbar-playlist",b);b=n(x,"translateY(0px)");b["margin-left"]="0";b.top="calc(100vh + 60px)";a.style.appendRule(c+" #player .player-height#watch-appbar-playlist",b);a.style.appendRule(c+" .playlist-videos-list",{"max-height":"470px !important",
height:"initial !important"});a.style.appendRule(c+" #player .player-height#watch-appbar-playlist",{left:"calc((100vw - 1066px)/2 + 640px + 10px)",width:"416px"});a.style.stylesheet+="@media screen and (min-height: 630px) and (min-width: 1294px) {\n";a.style.appendRule(c+" #player .player-height#watch-appbar-playlist",{left:"calc((100vw - 1280px)/2 + 854px + 10px)"});a.style.stylesheet+="}\n @media screen and (min-width: 1720px) and (min-height:980px) {\n";a.style.appendRule(c+" #player .player-height#watch-appbar-playlist",
{left:"calc((100vw - 1706px)/2 + 1280px + 10px)"});a.style.stylesheet+="}\n";a.style.appendRule(c+".ytwp-scrolltop #extra-buttons","display","none !important");a.style.appendRule("ytd-app","position","static !important");a.style.appendRule("ytd-watch #top","margin-top","71px !important");a.style.appendRule("ytd-watch #container","margin-top","0 !important");a.style.appendRule("ytd-watch #content-separator","margin-top","0 !important");a.style.appendRule([c+" ytd-watch-flexy[theater] #player-wide-container.ytd-watch-flexy",
c+" ytd-watch-flexy[fullscreen] #player-wide-container.ytd-watch-flexy",c+" ytd-watch-flexy[full-bleed-player] #player-full-bleed-container.ytd-watch-flexy",c+" ytd-watch-flexy[full-bleed-player] #full-bleed-container.ytd-watch-flexy",c+" ytd-watch-grid[theater] #player-wide-container.ytd-watch-grid",c+" ytd-watch-grid[fullscreen] #player-wide-container.ytd-watch-grid",c+" ytd-watch-grid[full-bleed-player] #player-full-bleed-container.ytd-watch-grid",c+" ytd-watch-grid[full-bleed-player] #full-bleed-container.ytd-watch-grid"],
{position:"static",height:0,"min-height":0});a.style.appendRule(c+".ytwp-viewing-video ytd-app #masthead-container.ytd-app",{position:"absolute",top:"100vh","z-index":0});a.style.appendRule(c+".ytwp-viewing-video ytd-watch #masthead-positioner",{top:"100vh !important"});a.style.appendRule(c+" .ytp-cued-thumbnail-overlay","z-index","10");a.style.appendRule([c+" ytd-watch-flexy[theater] #player-theater-container.ytd-watch-flexy",c+" ytd-watch-grid[theater] #player-theater-container.ytd-watch-grid"],
{position:"absolute",top:"0"});a.style.appendRule("#page-manager.ytd-app","padding-top","var(--ytd-masthead-height,var(--ytd-toolbar-height))");a.style.appendRule(c+" #error-screen","z-index","11")},onWatchInit:function(){a.log("onWatchInit");a.initialized&&!a.pageReady&&(a.event.addBodyClass(),a.hasYoutubeChanged()&&a.debugPage(),a.pageReady=!0)},onDispose:function(){a.log("onDispose");a.initialized=!1;a.pageReady=!1;a.isWatchPage=!1},addBodyClass:function(){document.body.classList.add("ytwp-window-player");
a.log("Applied "+l)},removeBodyClass:function(){document.body.classList.remove("ytwp-window-player");a.log("Removed "+l)}};a.html5PlayerFix=function(){a.log("html5PlayerFix")};a.fixMasthead=function(){a.log("fixMasthead");var b=document.querySelector("#masthead-positioner-height-offset");b&&a.fixMastheadElement(b)};a.fixMastheadElement=function(b){a.log("fixMastheadElement",b);b.style.height&&setTimeout(function(){b.style.height="";document.querySelector("#appbar-guide-menu").style.marginTop=""},
0)};m.injectIntoHeader("ytwp-style-focusfix","input#search[autofocus] { display: none; }");a.removeSearchAutofocus=function(){var b=document.querySelector("input#search");b&&b.removeAttribute("autofocus")};a.registerMastheadFix=function(){a.log("registerMastheadFix");w("#masthead-positioner-height-offset",{attributes:!0},function(b){console.log(b.type,b);if("style"===b.attributeName){var d=b.target;d.style.height&&setTimeout(function(){d.style.height="";document.querySelector("#appbar-guide-menu").style.marginTop=
""},0)}})};a.materialPageTransition=function(){a.log("materialPageTransition");a.init();a.isWatchUrl()?(a.removeSearchAutofocus(),a.event.addBodyClass(),a.initialized||(a.log("materialPageTransition !ytwp.html5.app",a.html5.app),setTimeout(a.materialPageTransition,100))):(a.event.onDispose(),document.body.classList.remove("ytwp-window-player"));a.onScroll();a.fixMasthead();a.attemptToUpdatePlayer()};a.registerListeners=function(){a.registerMaterialListeners();a.registerMastheadFix()};a.registerMaterialListeners=
function(){document.addEventListener("yt-page-data-fetched",a.materialPageTransition);document.addEventListener("yt-navigate-finish",a.materialPageTransition);document.addEventListener("yt-page-data-fetched",function(b){a.log("document.yt-page-data-fetched",b)});document.addEventListener("yt-navigate-finish",function(b){a.log("document.yt-navigate-finish",b)})};a.main=function(){a.registerListeners();a.init();a.fixMasthead()};a.main();a.updatePlayerAttempts=-1;a.updatePlayerMaxAttempts=150;a.attemptToUpdatePlayer=
function(){0<=a.updatePlayerAttempts&&a.updatePlayerAttempts<a.updatePlayerMaxAttempts?a.updatePlayerAttempts=0:(a.updatePlayerAttempts=0,a.attemptToUpdatePlayerTick())};a.attemptToUpdatePlayerTick=function(){a.updatePlayerAttempts<a.updatePlayerMaxAttempts&&(a.updatePlayerAttempts+=1,a.updatePlayer(),requestAnimationFrame(a.attemptToUpdatePlayerTick))};a.updatePlayer=function(){a.removeSearchAutofocus();a.enterTheaterMode();a.detectPlayerUnavailable()};a.toggleExtension=function(){document.body.classList.toggle("ytwp-window-player");
a.setTheaterMode(document.body.classList.contains("ytwp-window-player"))};a.materialPageTransition();setInterval(a.updatePlayer,2500);h.addEventListener("keydown",u.bind(null,a.toggleExtension),!0);h.addEventListener("keyup",u.bind(null,null),!0);h.addEventListener("keypress",u.bind(null,null),!0);"undefined"!==typeof browser&&browser.runtime.onMessage.addListener(b=>"toggle"==b.id?(a.toggleExtension(),Promise.resolve({enabled:document.body.classList.contains("ytwp-window-player")})):Promise.reject(Error("Unreconized message.id")))}}})(window);
