// ==UserScript==
// @name Smoothscroll
// @author       Creec Winceptor
// @namespace https://greasyfork.org/users/3167
// @include     *
// @version 12
// @downloadURL https://raw.githubusercontent.com/siritami/test1/release/release/Smoothscroll.user.js
// @updateURL https://raw.githubusercontent.com/siritami/test1/release/release/Smoothscroll.meta.js
// ==/UserScript==
var Smoothscroll={Smoothness:.5,Acceleration:.5,Debug:0,Refreshrate:60,MaxRefreshrate:300,MinRefreshrate:1};function ScrollSubpixels(a,b){if(void 0!=b)return a.scrollsubpixels=b;a=a.scrollsubpixels;return void 0!=a?a:0}function ScrollPixels(a,b){if(void 0!=b)return a.scrollpixels=b,ScrollSubpixels(a,0),b;a=a.scrollpixels;return void 0!=a?a:0}var last=0;
function AnimateScroll(a,b){var d=ScrollSubpixels(a),c=ScrollPixels(a);3<Smoothscroll.Debug&&console.log("scrollpixels: "+c);3<Smoothscroll.Debug&&(console.log("target: ",a),a==document.documentElement&&console.log("document.documentElement"));var e=0;0<c&&(e=1);0>c&&(e=-1);var f=c*(1-Math.pow(b,-1/(b*Smoothscroll.Smoothness)));2<Math.abs(c)?(b=Math.floor(Math.abs(f))*e,f-=b,e*=Math.floor(Math.abs(d+f)),d=d+f-e,ScrollPixels(a,c-b-e),ScrollSubpixels(a,d),c=b+e,1<Smoothscroll.Debug&&console.log("scrolldelta: "+
c),a.style.scrollBehavior="auto",a.scrollTop+=c,1<Smoothscroll.Debug&&console.log("target.scrollTop: "+a.scrollTop),a.scrollanimated=!0,RequestAnimationUpdate(function(g){AnimateScroll(a,g)})):(RequestAnimationUpdate(function(g){ScrollPixels(a,0)}),a.scrollanimated=!1)}function RequestAnimationUpdate(a){var b=performance.now();window.requestAnimationFrame(()=>{var d=performance.now()-b;a(Math.min(Math.max(1E3/Math.max(d,1),Smoothscroll.MinRefreshrate),Smoothscroll.MaxRefreshrate))})}
Smoothscroll.Stop=function(a){a&&ScrollPixels(a,0)};Smoothscroll.Start=function(a,b){a&&(ScrollPixels(a,b),a.scrollanimated||AnimateScroll(a,Smoothscroll.Refreshrate))};"undefined"!==typeof module&&(module.exports=Smoothscroll);
function CanScroll(a,b){if(0>b)return 0<a.scrollTop;if(0<b){if(a==document.body){if(0==a.scrollTop){a.scrollTop=3;if(0==a.scrollTop)return!1;a.scrollTop=0}return Math.round(a.clientHeight+a.scrollTop)<a.offsetHeight}return Math.round(a.clientHeight+a.scrollTop)<a.scrollHeight}}
function HasScrollbar(a){if(a==window||a==document)return!1;if(a==document.body)return"hidden"!=window.getComputedStyle(document.body)["overflow-y"];if(a==document.documentElement)return window.innerWidth>document.documentElement.clientWidth;a=window.getComputedStyle(a);return"hidden"!=a["overflow-y"]&&"visible"!=a["overflow-y"]}
function Scrollable(a,b){b=CanScroll(a,b);if(!b)return 1<Smoothscroll.Debug&&console.log("scrollablecheck: "+b),!1;a=HasScrollbar(a);if(!a)return 1<Smoothscroll.Debug&&console.log("scrollbarcheck: "+a),!1;1<Smoothscroll.Debug&&(console.log("scrollablecheck: "+b),console.log("scrollbarcheck: "+a));return!0}function GetPath(a){if(a.path)return a.path;if(a.composedPath)return a.composedPath();1<Smoothscroll.Debug&&console.log("Smoothscroll: e.path is undefined");return null}
function GetTarget(a){var b=a.deltaY;a=GetPath(a);if(!a)return null;2<Smoothscroll.Debug&&(console.log("nodes: "),console.log(a),console.log("target: "));for(var d=0;d<a.length;d++){var c=a[d];2<Smoothscroll.Debug&&console.log(c);if(Scrollable(c,b))return 2<Smoothscroll.Debug&&console.log("true"),c}1<Smoothscroll.Debug&&console.log("false");return null}
function GetStyleProperty(a,b){if(window.getComputedStyle){if(a=document.defaultView.getComputedStyle(a,null).getPropertyValue(b))return parseInt(a)}else if(a.currentStyle&&(a=a.currentStyle[b.encamel()]))return parseInt(a);return null}function StopScroll(a){a=GetPath(a);if(!a)return null;for(var b=0;b<a.length;b++)Smoothscroll.Stop(a[b])}
function StartScroll(a,b){if(a.defaultPrevented)return!0;var d=a.deltaY;Smoothscroll.Debug&&console.log("e: ",a);if(a.deltaMode&&1==a.deltaMode){var c=GetStyleProperty(b,"line-height");Smoothscroll.Debug&&console.log("line: "+c);c&&0<c&&(d=a.deltaY*c)}a.deltaMode&&2==a.deltaMode&&(c=b.clientHeight,Smoothscroll.Debug&&console.log("page: "+c),c&&0<c&&(d=a.deltaY*c));c=ScrollPixels(b);var e=Math.round(d*Math.sqrt(Math.abs(c/d*Smoothscroll.Acceleration))),f=c+d+e;Smoothscroll.Debug&&(console.log("scrollpixels: "+
c),console.log("delta: "+d),console.log("acceleration: "+e),console.log("totalscroll: "+f));Smoothscroll.Start(b,f);a.preventDefault()}function WheelEvent(a){var b=GetTarget(a);b&&StartScroll(a,b)}function ClickEvent(a){StopScroll(a)}
function Init(){if(window.top!=window.self||window.Smoothscroll&&window.Smoothscroll.Loaded)return null;window.requestAnimationFrame||(window.requestAnimationFrame=window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame);document.documentElement.addEventListener("wheel",function(a){WheelEvent(a);0<Smoothscroll.Debug&&console.log(a)},{passive:!1});document.documentElement.addEventListener("mousedown",function(a){ClickEvent(a);0<Smoothscroll.Debug&&console.log(a)});window.Smoothscroll=Smoothscroll;
window.Smoothscroll.Loaded=!0;console.log("Smoothscroll: loaded")}Init();
