// ==UserScript==
// @name         Soundcloud Downloader Clean
// @namespace    https://openuserjs.org/users/webketje
// @version      1.0.0
// @author       webketje
// @license      MIT
// @icon         https://a-v2.sndcdn.com/assets/images/sc-icons/favicon-2cadd14bdb.ico
// @homepageURL  https://gist.github.com/webketje/8cd2e6ae8a86dbe0533c5d2c612c42c6
// @supportURL   https://gist.github.com/webketje/8cd2e6ae8a86dbe0533c5d2c612c42c6#comments
// @noframes
// @match        https://soundcloud.com/*
// @grant        unsafeWindow
// @require      https://cdn.jsdelivr.net/npm/file-saver@2.0.5/dist/FileSaver.min.js
// @downloadURL https://raw.githubusercontent.com/siritami/test1/release/release/Soundcloud20Downloader20Clean.user.js
// @updateURL https://raw.githubusercontent.com/siritami/test1/release/release/Soundcloud20Downloader20Clean.meta.js
// ==/UserScript==
(function(){function k(){var a=(new Date).toLocaleString(),b=[].slice.call(arguments);a=["SCDLC",a,"-"].join(" ");d.debug&&console.log.apply(console,[a+b[0]].concat(b.slice(1)))}function m(a,b){var f=g.XMLHttpRequest.prototype.open;g.XMLHttpRequest.prototype.open=function(){f.apply(this,arguments);var e=a.apply(this,arguments);e&&(g.XMLHttpRequest.prototype.open=f,b(e))}}var g=unsafeWindow||window,d={debug:!1,client_id:"",dlButtonId:"scdlc-btn",modalId:"scdl-third-party-modal"},h={en:{download:"Download",
downloading:"Downloading",copy:"Copy",copy_success:"Copied to clipboard",copy_failure:"Failed to copy to clipboard!",close:"Close",modal_title:"could not download this track. Use one of these third-party services instead?"},es:{download:"Descargar",downloading:"Descargando..",copy:"Copiar",copy_success:"Copiada al portapapeles",copy_failure:"\u00a1No se pudo copiar al portapapeles!",close:"",modal_title:"no se pudo descargar esta banda sonora. \u00bfUtilizar uno de estos servicios de terceros en su lugar?"},
fr:{download:"T\u00e9l\u00e9charger",downloading:"T\u00e9l\u00e9chargement..",copy:"Copier",copy_success:"Copi\u00e9 dans le presse-papiers!",copy_failure:"\u00c9chec de la copie dans le presse-papiers !",close:"Fermer",modal_title:"ne peut pas t\u00e9l\u00e9charger ce fichier. Utiliser l\u2019un de ces services tiers ?"},nl:{download:"Downloaden",downloading:"Downloaden..",copy:"Kopi\u00ebren",copy_success:"Naar klembord gekopieerd!",copy_failure:"Kopi\u00ebren naar klembord mislukt!",close:"Sluiten",
modal_title:"kon dit bestand niet downloaden. Een van deze externe diensten gebruiken?"},de:{download:"Herunterladen",downloading:"Herunterladen..",copy:"Kopieren",copy_success:"In die Zwischenablage kopiert",copy_failure:"Kopieren in die Zwischenablage fehlgeschlagen!",close:"Schlie\u00dfen",modal_title:"konnte diesen Sound nicht herunterladen. Nutzen Sie stattdessen einen dieser Drittanbieterdienste?"},pl:{download:"\u015aci\u0105gnij",downloading:"\u015aci\u0105ganie..",copy:"Kopiuj",copy_success:"Skopiowano do schowka",
copy_failure:"Nie uda\u0142o si\u0119 skopiowa\u0107 do schowka!!",close:"Zamknij",modal_title:"nie uda\u0142o si\u0119 pobra\u0107 tego utworu. Zamiast tego skorzysta\u0107 z jednej z us\u0142ug stron trzecich?"},it:{download:"Scaricare",downloading:"Scaricando..",copy:"Copia",copy_success:"Copiato negli appunti",copy_failure:"Impossibile copiare negli appunti!",close:"Chiudi",modal_title:"non \u00e8 stato possibile scaricare questo suono. Utilizzi invece uno di questi servizi di terze parti?"},
pt_BR:{download:"Baixar",downloading:"Baixando..",copy:"Copiar",copy_success:"Copiado para a \u00e1rea de transfer\u00eancia",copy_failure:"Falha ao copiar para a \u00e1rea de transfer\u00eancia!!",close:"Fechar",modal_title:"n\u00e3o foi poss\u00edvel baixar este som. Usar um desses servi\u00e7os de terceiros?"},sv:{download:"Ladda ner",downloading:"Laddar ner..",copy:"Kopiera",copy_success:"Kopierat till urklipp",copy_failure:"Det gick inte att kopiera till urklipp!",close:"St\u00e4ng",modal_title:"han kunde inte ladda ner det h\u00e4r ljudet. Anv\u00e4nd n\u00e5gon av dessa tredjepartstj\u00e4nster ist\u00e4llet?"}}[document.documentElement.lang||
"en"];d.getTrackName=function(a){return[a.user.username,a.title].join(" - ")};d.getMediaURL=function(a,b,f){if(a.media&&a.media.transcodings)if(a=a.media.transcodings.filter(function(c){return c.format&&"progressive"===c.format.protocol})[0]){var e=new XMLHttpRequest;e.onload=function(){try{var c=JSON.parse(e.responseText)}catch(l){}c&&c.url?b(c.url):f(!1)};e.onerror=f;e.open("GET",a.url+"?client_id="+d.client_id);e.send()}else f(!1);else f(!1)};d.getStreamURL=function(a,b,f){var e=new XMLHttpRequest;
e.onload=function(){var c=JSON.parse(e.responseText);d.getMediaURL(c,function(l){b({stream_url:l,track_name:d.getTrackName(c)})},function(){f(!1)})}.bind(this);e.onerror=function(){f(!1)};e.open("GET","https://api-v2.soundcloud.com/resolve?url="+encodeURIComponent(a)+"&client_id="+this.client_id);e.send()};d.button={download:function(a){a.preventDefault();var b=document.getElementById(d.dlButtonId);b&&(b.textContent=h.downloading);setTimeout(function(){saveAs(a.target.href,a.target.dataset.title);
b&&(b.textContent=h.download)},100)},render:function(a,b,f){var e=h.download,c=document.createElement("a");c.className="sc-button sc-button-medium sc-button-responsive sc-button-download";c.href=a;c.id=d.dlButtonId;c.textContent=e;c.title=e;c.dataset.title=b+".mp3";c.setAttribute("download",b+".mp3");c.target="_blank";c.onclick=f;c.style.marginLeft="5px";c.style.cssFloat="left";c.style.border="1px solid orangered";return c},attach:function(){var a=arguments,b=this,f=0,e=setInterval(function(){var c=
document.querySelector(".soundActions.sc-button-toolbar .sc-button-group");f++;c&&!document.getElementById(d.dlButtonId)?(c.insertAdjacentElement("beforeend",b.render.apply(b,a)),k("Attaching download button to element:",c),clearInterval(e)):50===f&&(k('%c Couldn\'t find element ".soundActions.sc-button-toolbar .sc-button-group" after 2 seconds',"color: #FF0000;"),clearInterval(e))},100)},remove:function(){var a=document.getElementById(d.dlButtonId);a&&a.parentNode.removeChild(a)}};d.modal={providers:["aHR0cHM6Ly9zY2xvdWRkb3dubG9hZGVyLm5ldA==",
"aHR0cHM6Ly93d3cuc291bmRjbG91ZG1wMy5vcmc=","aHR0cHM6Ly9zb3VuZGNsb3VkbWUuY29t"],render:function(a){var b=document.createElement("div"),f=this;a=['<div class="modal g-z-index-modal-background g-opacity-transition g-z-index-overlay modalWhiteout showBackground g-backdrop-filter-grayscale" style="outline: none; padding-right: 0px; display: flex; justify-content: center;" tabindex="-1" id="scdl-third-party-modal"><div class="modal__modal sc-border-box g-z-index-modal-content transparentBackground" style="height: auto;">',
'<button type="button" title="'+h.close+'" class="modal__closeButton">'+h.close+"</button>",'<div class="modal__content"><div class="tabs"><div class="tabs__content"><div class="tabs__contentSlot" style="display: block;"><article class="shareContent"><div class="publicShare"><section class="g-modal-section sc-clearfix sc-pt-2x">','<h2 class="sc-orange">Soundcloud Downloader Clean '+h.modal_title+"</h2>",'</section><section class="g-modal-section sc-clearfix sc-pt-2x">','<h3 style="margin-bottom: 0.5rem;">'+
h.download+" <em>"+a+"</em> via: </h3>",this.providers.map(c=>['<div><a href="',g.atob(c),'" target="_blank" style="display: inline-block; font-size: 14px; padding: 0.25rem 0;">',g.atob(c),"</a></div>"].join("")).join(""),'<div class="shareLink sc-clearfix publicShare__link sc-pt-2x m-showPositionOption" style="margin-top: 1rem;"><label for="shareLink__field" style="margin-right:0.5rem;">Link</label>','<input type="text" value="'+g.location.href+'" class="shareLink__field sc-input" id="shareLink__field" readonly="readonly">',
'<button class="sc-button sc-button-copy">'+h.copy+"</button>",'<span class="sc-copy-feedback" style="margin-left: 1rem;"></span></div></section></div></article></div></div></div></div></div></div>'].join("");b.innerHTML=a;var e=b.firstElementChild;e.addEventListener("click",function(c){this===c.target||c.target.classList.contains("modal__closeButton")?f.remove():c.target.classList.contains("sc-button-copy")&&navigator.clipboard.writeText(g.location.href).then(function(){e.querySelector(".sc-copy-feedback").innerHTML=
'<span style="color: green;">Copied to clipboard!</span>'},function(l){k("Failed to write URL to the clipboard.",l);e.querySelector(".sc-copy-feedback").innerHTML='<span style="color: red;">Failed to copy to clipboard!</span>'})});return e},attach:function(){this.remove();document.body.appendChild(this.render.apply(this,arguments))},remove:function(){var a=document.getElementById(d.modalId);a&&a.parentNode.removeChild(a)}};d.parseClientIdFromURL=function(a){var b=/client_id=([\w\d]+)&*/;return a&&
a.match(b)&&a.match(b)[1]};d.getClientID=function(a){m(function(b,f){return d.parseClientIdFromURL(f)},a)};d.load=function(a){/^(\/(you|stations|discover|stream|upload|search|settings|.+?\/sets))/.test(g.location.pathname)?d.button.remove():d.getStreamURL(a,function(b){b?(k("Detected valid Soundcloud artist track URL. Requesting info..."),d.button.attach(b.stream_url,b.track_name,d.button.download)):d.button.remove()},function(){k("%c No compatible media transcoding found.","color: #FF0000;");d.button.attach("javascript:void(0);",
"None",function(){var b=document.querySelector(".soundTitle__title"),f=document.querySelector(".soundTitle__username");d.modal.attach([f.textContent.trim(),"-",b.textContent.trim()].join(" "))})})};["pushState","replaceState","forward","back","go"].forEach(function(a){var b=g.history.pushState;g.history[a]=function(){b.apply(g.history,arguments);d.load(g.location.href)}});d.debug&&(g.scdl=d);d.getClientID(function(a){k("Found Soundcloud client id:",a,". Initializing...");d.client_id=a;d.load(g.location.href)})})();
