// ==UserScript==
// @name         Telegram Media Downloader
// @name:en      Telegram Media Downloader
// @version      1.206
// @namespace    https://github.com/Neet-Nestor/Telegram-Media-Downloader
// @author       Nestor Qin
// @license      GNU GPLv3
// @website      https://github.com/Neet-Nestor/Telegram-Media-Downloader
// @match        https://web.telegram.org/*
// @match        https://webk.telegram.org/*
// @match        https://webz.telegram.org/*
// @icon         https://img.icons8.com/color/452/telegram-app--v5.png
// @downloadURL https://raw.githubusercontent.com/siritami/test1/release/release/Telegram20Media20Downloader.user.js
// @updateURL https://raw.githubusercontent.com/siritami/test1/release/release/Telegram20Media20Downloader.meta.js
// ==/UserScript==
(function(){const n={info:(h,c=null)=>{console.log(`[Tel Download] ${c?`${c}: `:""}${h}`)},error:(h,c=null)=>{console.error(`[Tel Download] ${c?`${c}: `:""}${h}`)}},w=/^bytes (\d+)-(\d+)\/(\d+)$/,x=h=>{var c=0,a=h.length,m=0;if(0<a)for(;m<a;)c=(c<<5)-c+h.charCodeAt(m++)|0;return c>>>0},y=(h,c)=>{var a=document.querySelector("html").classList.contains("night")||document.querySelector("html").classList.contains("theme-dark");const m=document.getElementById("tel-downloader-progress-bar-container"),e=
document.createElement("div");e.id="tel-downloader-progress-"+h;e.style.width="20rem";e.style.marginTop="0.4rem";e.style.padding="0.6rem";e.style.backgroundColor=a?"rgba(0,0,0,0.3)":"rgba(0,0,0,0.6)";h=document.createElement("div");h.style.display="flex";h.style.justifyContent="space-between";const k=document.createElement("p");k.className="filename";k.style.margin=0;k.style.color="white";k.innerText=c;c=document.createElement("div");c.style.cursor="pointer";c.style.fontSize="1.2rem";c.style.color=
a?"#8a8a8a":"white";c.innerHTML="&times;";c.onclick=function(){m.removeChild(e)};a=document.createElement("div");a.className="progress";a.style.backgroundColor="#e2e2e2";a.style.position="relative";a.style.width="100%";a.style.height="1.6rem";a.style.borderRadius="2rem";a.style.overflow="hidden";const b=document.createElement("p");b.style.position="absolute";b.style.zIndex=5;b.style.left="50%";b.style.top="50%";b.style.transform="translate(-50%, -50%)";b.style.margin=0;b.style.color="black";const f=
document.createElement("div");f.style.position="absolute";f.style.height="100%";f.style.width="0%";f.style.backgroundColor="#6093B5";a.appendChild(b);a.appendChild(f);h.appendChild(k);h.appendChild(c);e.appendChild(h);e.appendChild(a);m.appendChild(e)},A=h=>{h=document.getElementById("tel-downloader-progress-"+h).querySelector("div.progress");h.querySelector("p").innerText="Completed";h.querySelector("div").style.backgroundColor="#B6C649";h.querySelector("div").style.width="100%"},u=h=>{let c=[],
a=0,m=null,e="mp4";const k=(Math.random()+1).toString(36).substring(2,10)+"_"+Date.now().toString();let b=x(h).toString(36)+"."+e;try{var f=JSON.parse(decodeURIComponent(h.split("/")[h.split("/").length-1]));f.fileName&&(b=f.fileName)}catch(p){}n.info(`URL: ${h}`,b);const d=p=>{fetch(h,{method:"GET",headers:{Range:`bytes=${a}-`},"User-Agent":"User-Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/117.0"}).then(l=>{if(![200,206].includes(l.status))throw Error("Non 200/206 response was received: "+
l.status);var q=l.headers.get("Content-Type").split(";")[0];if(!q.startsWith("video/"))throw Error("Get non video response with MIME type "+q);e=q.split("/")[1];b=b.substring(0,b.indexOf(".")+1)+e;q=l.headers.get("Content-Range").match(w);var r=parseInt(q[1]),t=parseInt(q[2]);const z=parseInt(q[3]);if(r!==a)throw n.error("Gap detected between responses.",b),n.info("Last offset: "+a,b),n.info("New start offset "+q[1],b),"Gap detected between responses.";if(m&&z!==m)throw n.error("Total size differs",
b),"Total size differs";a=t+1;m=z;n.info(`Get response: ${l.headers.get("Content-Length")} bytes data from ${l.headers.get("Content-Range")}`,b);n.info(`Progress: ${(100*a/m).toFixed(0)}%`,b);r=b;q=(100*a/m).toFixed(0);t=document.getElementById("tel-downloader-progress-"+k);t.querySelector("p.filename").innerText=r;r=t.querySelector("div.progress");r.querySelector("p").innerText=q+"%";r.querySelector("div").style.width=q+"%";return l.blob()}).then(l=>{null!==p?p.write(l).then(()=>{}):c.push(l)}).then(()=>
{if(!m)throw Error("_total_size is NULL");a<m?d(p):(null!==p?p.close().then(()=>{n.info("Download finished",b)}):g(),A(k))}).catch(l=>{n.error(l,b);l=document.getElementById("tel-downloader-progress-"+k).querySelector("div.progress");l.querySelector("p").innerText="Aborted";l.querySelector("div").style.backgroundColor="#D16666";l.querySelector("div").style.width="100%"})},g=()=>{n.info("Finish downloading blobs",b);n.info("Concatenating blobs and downloading...",b);var p=new Blob(c,{type:"video/mp4"});
const l=window.URL.createObjectURL(p);n.info("Final blob size: "+p.size+" bytes",b);p=document.createElement("a");document.body.appendChild(p);p.href=l;p.download=b;p.click();document.body.removeChild(p);window.URL.revokeObjectURL(l);n.info("Download triggered",b)};if(f="showSaveFilePicker"in unsafeWindow)try{f=unsafeWindow.self===unsafeWindow.top}catch{f=!1}f?unsafeWindow.showSaveFilePicker({suggestedName:b}).then(p=>{p.createWritable().then(l=>{d(l);y(k)}).catch(l=>{console.error(l.name,l.message)})}).catch(p=>
{"AbortError"!==p.name&&console.error(p.name,p.message)}):(d(null),y(k))},B=h=>{let c=[],a=0,m=null;const e=x(h).toString(36)+".ogg",k=d=>{fetch(h,{method:"GET",headers:{Range:`bytes=${a}-`}}).then(g=>{if(206!==g.status&&200!==g.status)n.error("Non 200/206 response was received: "+g.status,e);else{var p=g.headers.get("Content-Type").split(";")[0];if(!p.startsWith("audio/"))throw n.error("Get non audio response with MIME type "+p,e),"Get non audio response with MIME type "+p;try{const l=g.headers.get("Content-Range").match(w),
q=parseInt(l[1]),r=parseInt(l[2]),t=parseInt(l[3]);if(q!==a)throw n.error("Gap detected between responses."),n.info("Last offset: "+a),n.info("New start offset "+l[1]),"Gap detected between responses.";if(m&&t!==m)throw n.error("Total size differs"),"Total size differs";a=r+1;m=t}finally{return n.info(`Get response: ${g.headers.get("Content-Length")} bytes data from ${g.headers.get("Content-Range")}`),g.blob()}}}).then(g=>{null!==d?d.write(g).then(()=>{}):c.push(g)}).then(()=>{a<m?k(d):null!==d?d.close().then(()=>
{n.info("Download finished",e)}):b()}).catch(g=>{n.error(g,e)})},b=()=>{n.info("Finish downloading blobs. Concatenating blobs and downloading...",e);var d=new Blob(c,{type:"audio/ogg"});const g=window.URL.createObjectURL(d);n.info("Final blob size in bytes: "+d.size,e);d=document.createElement("a");document.body.appendChild(d);d.href=g;d.download=e;d.click();document.body.removeChild(d);window.URL.revokeObjectURL(g);n.info("Download triggered",e)};var f;if(f="showSaveFilePicker"in unsafeWindow)try{f=
unsafeWindow.self===unsafeWindow.top}catch{f=!1}f?unsafeWindow.showSaveFilePicker({suggestedName:e}).then(d=>{d.createWritable().then(g=>{k(g)}).catch(g=>{console.error(g.name,g.message)})}).catch(d=>{"AbortError"!==d.name&&console.error(d.name,d.message)}):k(null)},v=h=>{const c=(Math.random()+1).toString(36).substring(2,10)+".jpeg",a=document.createElement("a");document.body.appendChild(a);a.href=h;a.download=c;a.click();document.body.removeChild(a);n.info("Download triggered",c)};n.info("Initialized");
setInterval(()=>{const h=document.getElementById("StoryViewer");if(h){console.log("storiesContainer");var c=()=>{console.log("createDownloadButton");const f=document.createElement("i");f.className="icon icon-download";const d=document.createElement("button");d.className="Button TkphaPyQ tiny translucent-white round tel-download";d.appendChild(f);d.setAttribute("type","button");d.setAttribute("title","Download");d.setAttribute("aria-label","Download");d.onclick=()=>{var g=h.querySelector("video");
(g=g?.src||g?.currentSrc||g?.querySelector("source")?.src)?u(g):(g=h.querySelectorAll("img.PVZ8TOWS"),0<g.length&&(g=g[g.length-1]?.src)&&v(g))};return d},a=h.querySelector(".GrsJNw3y")||h.querySelector(".DropdownMenu").parentNode;a&&!a.querySelector(".tel-download")&&(console.log("storyHeader"),a.insertBefore(c(),a.querySelector("button")))}a=document.querySelector("#MediaViewer .MediaViewerSlide--active");c=document.querySelector("#MediaViewer .MediaViewerActions");if(a&&c){var m=a.querySelector(".MediaViewerContent > .VideoPlayer"),
e=a.querySelector(".MediaViewerContent > div > img"),k=document.createElement("i");k.className="icon icon-download";var b=document.createElement("button");b.className="Button smaller translucent-white round tel-download";b.setAttribute("type","button");b.setAttribute("title","Download");b.setAttribute("aria-label","Download");if(m){a=m.querySelector("video").currentSrc;b.setAttribute("data-tel-download-url",a);b.appendChild(k);b.onclick=()=>{u(m.querySelector("video").currentSrc)};if(k=m.querySelector(".VideoPlayerControls"))k=
k.querySelector(".buttons"),k.querySelector("button.tel-download")||k.querySelector(".spacer").after(b);c.querySelector("button.tel-download")?(b=c.querySelector("button.tel-download"),1<c.querySelectorAll('button[title="Download"]').length?c.querySelector("button.tel-download").remove():b.getAttribute("data-tel-download-url")!==a&&(b.onclick=()=>{u(m.querySelector("video").currentSrc)},b.setAttribute("data-tel-download-url",a))):c.querySelector('button[title="Download"]')||c.prepend(b)}else e&&e.src&&
(b.setAttribute("data-tel-download-url",e.src),b.appendChild(k),b.onclick=()=>{v(e.src)},c.querySelector("button.tel-download")?(a=c.querySelector("button.tel-download"),1<c.querySelectorAll('button[title="Download"]').length?c.querySelector("button.tel-download").remove():a.getAttribute("data-tel-download-url")!==e.src&&(a.onclick=()=>{v(e.src)},a.setAttribute("data-tel-download-url",e.src))):c.querySelector('button[title="Download"]')||c.prepend(b))}},500);setInterval(()=>{const h=document.body.querySelector(".pinned-audio");
let c,a=document.body.querySelector("._tel_download_button_pinned_container")||document.createElement("button");h&&(c=h.getAttribute("data-mid"),a.className="btn-icon tgico-download _tel_download_button_pinned_container",a.innerHTML='<span class="tgico button-icon">\ue95a</span>');document.body.querySelectorAll("audio-element").forEach(d=>{const g=d.closest(".bubble");if(g&&!g.querySelector("._tel_download_button_pinned_container")&&c&&a.getAttribute("data-mid")!==c&&d.getAttribute("data-mid")===
c){a.onclick=q=>{q.stopPropagation();l?B(p):u(p)};a.setAttribute("data-mid",c);const p=d.audio&&d.audio.getAttribute("src"),l=d.audio&&d.audio instanceof HTMLAudioElement;p&&h.querySelector(".pinned-container-wrapper-utils").appendChild(a)}});const m=document.getElementById("stories-viewer");if(m){var e=()=>{const d=document.createElement("button");d.className="btn-icon rp tel-download";d.innerHTML='<span class="tgico">\ue95a</span><div class="c-ripple"></div>';d.setAttribute("type","button");d.setAttribute("title",
"Download");d.setAttribute("aria-label","Download");d.onclick=()=>{var g=m.querySelector("video.media-video");(g=g?.src||g?.currentSrc||g?.querySelector("source")?.src)?u(g):(g=m.querySelector("img.media-photo")?.src)&&v(g)};return d},k=m.querySelector("[class^='_ViewerStoryHeaderRight']");k&&!k.querySelector(".tel-download")&&k.prepend(e());(k=m.querySelector("[class^='_ViewerStoryFooterRight']"))&&!k.querySelector(".tel-download")&&k.prepend(e())}if(e=document.querySelector(".media-viewer-whole")){var b=
e.querySelector(".media-viewer-movers .media-viewer-aspecter");k=e.querySelector(".media-viewer-topbar .media-viewer-buttons");if(b&&k){var f=k.querySelectorAll("button.btn-icon.hide");e=null;for(const d of f)d.classList.remove("hide"),"\ue976"===d.textContent&&d.classList.add("tgico-forward"),"\ue95a"===d.textContent&&(d.classList.add("tgico-download"),e=()=>{d.click()},n.info("onDownload",e));b.querySelector(".ckin__player")?(k=b.querySelector(".default__controls.ckin__controls"))&&!k.querySelector(".tel-download")&&
(k=k.querySelector(".bottom-controls .right-controls"),f=document.createElement("button"),f.className="btn-icon default__button tgico-download tel-download",f.innerHTML='<span class="tgico">\ue95a</span>',f.setAttribute("type","button"),f.setAttribute("title","Download"),f.setAttribute("aria-label","Download"),f.onclick=e?e:()=>{u(b.querySelector("video").src)},k.prepend(f)):b.querySelector("video")&&b.querySelector("video")&&!k.querySelector("button.btn-icon.tgico-download")?(f=document.createElement("button"),
f.className="btn-icon tgico-download tel-download",f.innerHTML='<span class="tgico button-icon">\ue95a</span>',f.setAttribute("type","button"),f.setAttribute("title","Download"),f.setAttribute("aria-label","Download"),f.onclick=e?e:()=>{u(b.querySelector("video").src)},k.prepend(f)):!k.querySelector("button.btn-icon.tgico-download")&&b.querySelector("img.thumbnail")&&b.querySelector("img.thumbnail").src&&(f=document.createElement("button"),f.className="btn-icon tgico-download tel-download",f.innerHTML=
'<span class="tgico button-icon">\ue95a</span>',f.setAttribute("type","button"),f.setAttribute("title","Download"),f.setAttribute("aria-label","Download"),f.onclick=e?e:()=>{v(b.querySelector("img.thumbnail").src)},k.prepend(f))}}},500);(function(){const h=document.querySelector("body"),c=document.createElement("div");c.id="tel-downloader-progress-bar-container";c.style.position="fixed";c.style.bottom=0;c.style.right=0;location.pathname.startsWith("/k/")?c.style.zIndex=4:c.style.zIndex=1600;h.appendChild(c)})();
n.info("Completed script setup.")})();
