// ==UserScript==
// @name         TwitchAdSolutions (vaft)
// @namespace    https://github.com/pixeltris/TwitchAdSolutions
// @version      17.0.0
// @updateURL https://raw.githubusercontent.com/siritami/test1/release/release/vaft.meta.js
// @downloadURL https://raw.githubusercontent.com/siritami/test1/release/release/vaft.user.js
// @author       https://github.com/cleanlock/VideoAdBlockForTwitch#credits
// @match        *://*.twitch.tv/*
// @run-at       document-start
// @inject-into  page
// @grant        none
// ==/UserScript==
(function(){function A(a){a.AdSignifier="stitched";a.ClientID="kimne78kx3ncx6brgo4mv6wki5h1ko";a.ClientVersion="null";a.ClientSession="null";a.PlayerType2="embed";a.PlayerType3="site";a.PlayerType4="autoplay";a.CurrentChannelName=null;a.UsherParams=null;a.WasShowingAd=!1;a.GQLDeviceID=null;a.IsSquadStream=!1;a.StreamInfos=[];a.StreamInfosByUrl=[];a.MainUrlByUrl=[];a.EncodingCacheTimeout=6E4;a.ClientIntegrityHeader=null;a.AuthorizationHeader=null}function J(a){for(var b=null,c=null;a;){var d=a.toString();
B.some(h=>d.includes(h))&&!C.some(h=>d.includes(h))?null!==c&&Object.setPrototypeOf(c,Object.getPrototypeOf(a)):(null===b&&(b=a),c=a);a=Object.getPrototypeOf(a)}return b}function K(a){for(var b=[];a;){var c=a.toString();D.some(d=>c.includes(d))&&b.push(a);a=Object.getPrototypeOf(a)}return b}function L(a,b){for(var c=0;c<b.length;c++)Object.setPrototypeOf(b[c],a),a=b[c];return a}function M(a){var b=a.toString();return!B.some(c=>b.includes(c))||C.some(c=>b.includes(c))||D.some(c=>b.includes(c))}function N(a){var b=
new XMLHttpRequest;b.open("GET",a,!1);b.overrideMimeType("text/javascript");b.send();return b.responseText}function O(){console.log("hookWorkerFetch (vaft)");var a=fetch;fetch=async function(b,c){if("string"===typeof b){if(b.endsWith("m3u8"))return new Promise(function(h,f){var l=async function(e){if(200===e.status){e=await e.text();var g=await v(b,e,a,PlayerType2);g.includes(AdSignifier)&&(g=await v(b,e,a,PlayerType3));g.includes(AdSignifier)&&(g=await v(b,e,a,PlayerType4));h(new Response(g))}else h(e)};
(function(){return a(b,c).then(function(e){l(e)})["catch"](function(e){f(e)})})()});if(b.includes("/api/channel/hls/")){var d=(new URL(b)).pathname.match(/([^\/]+)(?=\.\w+$)/)[0];UsherParams=(new URL(b)).search;CurrentChannelName=d;b.includes("picture-by-picture")&&(b="");return new Promise(function(h,f){var l=async function(e){if(200==e.status){encodingsM3u8=await e.text();e=StreamInfos[d];null==e&&(StreamInfos[d]=e={});e.ChannelName=d;e.RequestedAds=new Set;e.Urls=[];e.EncodingsM3U8Cache=[];e.EncodingsM3U8=
encodingsM3u8;for(var g=encodingsM3u8.replace("\r","").split("\n"),m=0;m<g.length;m++)if(!g[m].startsWith("#")&&g[m].includes(".m3u8")){e.Urls[g[m]]=-1;if(0<m&&g[m-1].startsWith("#EXT-X-STREAM-INF")){var p=w(g[m-1]),k=p.RESOLUTION;p=p["FRAME-RATE"];k&&(e.Urls[g[m]]={Resolution:k,FrameRate:p})}StreamInfosByUrl[g[m]]=e;MainUrlByUrl[g[m]]=b}h(new Response(encodingsM3u8))}else h(e)};(function(){return a(b,c).then(function(e){l(e)})["catch"](function(e){f(e)})})()})}}return a.apply(this,arguments)}}function E(a,
b,c){var d=0;c&&c.endsWith("p")&&(d=c.substr(0,c.length-1)|0);a=a.replace("\r","").split("\n");for(var h=c=null,f=null,l=!1,e=0;e<a.length;e++)if(!a[e].startsWith("#")&&a[e].includes(".m3u8")&&0<e&&a[e-1].startsWith("#EXT-X-STREAM-INF")){var g=w(a[e-1]);h=g.RESOLUTION;g=g["FRAME-RATE"];if(h)if(d)if(h=h.toLowerCase().split("x")[1],h==d){if(f=a[e],40>g)return f}else{if(h<d)return f?f:a[e]}else if(!(b&&h!=b.Resolution||f&&(l||g!=b.FrameRate))&&(f=a[e],l=g==b.FrameRate))return f;null==c&&(c=a[e]);h=a[e]}return d?
h:f?f:c}async function y(a,b,c,d,h,f){(a.EncodingsM3U8Cache[h].Resolution!=b.Resolution||a.EncodingsM3U8Cache[h].RequestTime<Date.now()-EncodingCacheTimeout)&&console.log(`Blocking ads (type:${h}, resolution:${b.Resolution}, frameRate:${b.FrameRate}, qualityOverride:${null})`);a.EncodingsM3U8Cache[h].RequestTime=Date.now();a.EncodingsM3U8Cache[h].Value=c;a.EncodingsM3U8Cache[h].Resolution=b.Resolution;b=E(c,b,null);f=await f(b);if(200==f.status){d=await f.text();WasShowingAd=!0;postMessage({key:"ShowAdBlockBanner"});
postMessage({key:"ForceChangeQuality"});if(!d||d.includes(AdSignifier))a.EncodingsM3U8Cache[h].Value=null;return d}a.EncodingsM3U8Cache[h].Value=null;return d}function P(a,b){b||=["token","sig"];a=new URL("https://localhost/"+a);for(var c=0;c<b.length;c++)a.searchParams.delete(b[c]);return a.pathname.substring(1)+a.search}async function v(a,b,c,d){var h=StreamInfosByUrl[a];if(1==IsSquadStream||!b||!b.includes(".ts")&&!b.includes(".mp4"))return b;if(b.includes(AdSignifier)){if(!b.includes('"MIDROLL"')&&
!b.includes('"midroll"')&&d===PlayerType2)for(var f=b.replace("\r","").split("\n"),l=0;l<f.length;l++){var e=f[l];if(e.startsWith("#EXTINF")&&f.length>l+1&&!e.includes(",live")&&!h.RequestedAds.has(f[l+1])){h.RequestedAds.add(f[l+1]);fetch(f[l+1]).then(k=>{k.blob()});break}}f=null;if(h&&h.Urls)for(const [k,n]of Object.entries(h.Urls))if(k==a){f=n;break}if(a=h.EncodingsM3U8Cache[d]){if(a.Value&&a.RequestTime>=Date.now()-EncodingCacheTimeout)try{var g=y(h,f,a.Value,null,d,c);if(g)return g}catch(k){a.Value=
null}}else h.EncodingsM3U8Cache[d]={RequestTime:Date.now(),Value:null,Resolution:null};g=await F(CurrentChannelName,d);if(200===g.status){g=await g.json();try{var m=new URL("https://usher.ttvnw.net/api/channel/hls/"+CurrentChannelName+".m3u8"+UsherParams);m.searchParams.set("sig",g.data.streamPlaybackAccessToken.signature);m.searchParams.set("token",g.data.streamPlaybackAccessToken.value);var p=await c(m.href);return 200===p.status?y(h,f,await p.text(),b,d,c):b}catch(k){}}}else WasShowingAd&&(console.log("Finished blocking ads"),
WasShowingAd=!1,postMessage({key:"ForceChangeQuality",value:"original"}),postMessage({key:"PauseResumePlayer"}),postMessage({key:"HideAdBlockBanner"}));return b}function w(a){return Object.fromEntries(a.split(/(?:^|,)((?:[^=]*)=(?:"[^"]*"|[^,]*))/).filter(Boolean).map(b=>{var c=b.indexOf("=");const d=b.substring(0,c);b=b.substring(c+1);c=Number(b);return[d,Number.isNaN(c)?b.startsWith('"')?JSON.parse(b):b:c]}))}async function Q(a){a=a.match(/#EXT-X-DATERANGE:(ID="stitched-ad-[^\n]+)\n/);if(1<a.length){var b=
w(a[1]);a=parseInt(b["X-TV-TWITCH-AD-POD-LENGTH"]?b["X-TV-TWITCH-AD-POD-LENGTH"]:"1");parseInt(b["X-TV-TWITCH-AD-POD-POSITION"]?b["X-TV-TWITCH-AD-POD-POSITION"]:"0");var c=b["X-TV-TWITCH-AD-RADS-TOKEN"],d=b["X-TV-TWITCH-AD-LINE-ITEM-ID"],h=b["X-TV-TWITCH-AD-ORDER-ID"],f=b["X-TV-TWITCH-AD-CREATIVE-ID"],l=b["X-TV-TWITCH-AD-ADVERTISER-ID"];b={stitched:!0,roll_type:b["X-TV-TWITCH-AD-ROLL-TYPE"].toLowerCase(),player_mute:!0,player_volume:0,visible:!1};for(let e=0;e<a;e++){const g={...b,ad_id:l,ad_position:e,
duration:0,creative_id:f,total_ads:a,order_id:h,line_item_id:d};await t(x("video_ad_impression",c,g));for(let m=0;4>m;m++)await t(x("video_ad_quartile_complete",c,{...g,quartile:m+1}));await t(x("video_ad_pod_complete",c,b))}}}function x(a,b,c){return[{operationName:"ClientSideAdEventHandling_RecordAdEvent",variables:{input:{eventName:a,eventPayload:JSON.stringify(c),radToken:b}},extensions:{persistedQuery:{version:1,sha256Hash:"7e6c69e6eb59f8ccb97ab73686f3d8b7d85a72a0298745ccd8bfc68e4054ca5b"}}}]}
function F(a,b,c){return t({operationName:"PlaybackAccessToken_Template",query:'query PlaybackAccessToken_Template($login: String!, $isLive: Boolean!, $vodID: ID!, $isVod: Boolean!, $playerType: String!) {  streamPlaybackAccessToken(channelName: $login, params: {platform: "ios", playerBackend: "mediaplayer", playerType: $playerType}) @include(if: $isLive) {    value    signature    __typename  }  videoPlaybackAccessToken(id: $vodID, params: {platform: "ios", playerBackend: "mediaplayer", playerType: $playerType}) @include(if: $isVod) {    value    signature    __typename  }}',
variables:{isLive:!0,login:a,isVod:!1,vodID:"",playerType:b}},c)}function t(a,b){b=b?b:fetch;if(!GQLDeviceID)for(var c=0;32>c;c++)GQLDeviceID+="abcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(36*Math.random()));return b("https://gql.twitch.tv/gql",{method:"POST",body:JSON.stringify(a),headers:{"Client-ID":ClientID,"Client-Integrity":ClientIntegrityHeader,"Device-ID":GQLDeviceID,"X-Device-Id":GQLDeviceID,"Client-Version":ClientVersion,"Client-Session-Id":ClientSession,Authorization:AuthorizationHeader}})}
function G(a,b,c,d,h){try{var f=null;function p(k,n){if(k.stateNode&&n(k.stateNode))return k.stateNode;for(k=k.child;k;){const u=p(k,n);if(u)return u;k=k.sibling}return null}var l=function(){var k=null,n=document.querySelector("#root");n&&n._reactRootContainer&&n._reactRootContainer._internalRoot&&n._reactRootContainer._internalRoot.current&&(k=n._reactRootContainer._internalRoot.current);if(null==k){var u=Object.keys(n).find(R=>R.startsWith("__reactContainer"));null!=u&&(k=n[u])}return k}();if(l)if(f=
(f=p(l,k=>k.setPlayerActive&&k.props&&k.props.mediaPlayerInstance))&&f.props&&f.props.mediaPlayerInstance?f.props.mediaPlayerInstance:null,a)f.pause(),f.play();else if(b){if("undefined"!=typeof f.getQuality()){var e=JSON.stringify(f.getQuality());if(e)return e}}else{if(d){if("undefined"==typeof f.isAutoQualityMode())return!1;var g=f.isAutoQualityMode();return g?(f.setAutoQualityMode(!1),g):!1}if(h)f.setAutoQualityMode(!0);else try{var m=document.URL;a=!0;if(m.includes("videos/")||m.includes("clip/"))a=
!1;c&&a&&setTimeout(function(){f.isLiveLowLatency()&&5<f.getLiveLatency()?(f.pause(),f.play()):15<f.getLiveLatency()&&(f.pause(),f.play())},3E3)}catch(k){}}else console.log("Could not find react root")}catch(p){}}function q(a,b){H.forEach(c=>{c.postMessage({key:a,value:b})})}function I(){try{Object.defineProperty(document,"visibilityState",{get(){return"visible"}})}catch{}try{Object.defineProperty(document,"hidden",{get(){return!1}})}catch{}var a=b=>{b.preventDefault();b.stopPropagation();b.stopImmediatePropagation()};
document.addEventListener("visibilitychange",a,!0);document.addEventListener("webkitvisibilitychange",a,!0);document.addEventListener("mozvisibilitychange",a,!0);document.addEventListener("hasFocus",a,!0);try{/Firefox/.test(navigator.userAgent)?Object.defineProperty(document,"mozHidden",{get(){return!1}}):Object.defineProperty(document,"webkitHidden",{get(){return!1}})}catch{}}if(window.twitchAdSolutionsVersion&&2<=window.twitchAdSolutionsVersion)console.log("skipping vaft as there's another script active. ourVersion:2 activeVersion:"+
window.twitchAdSolutionsVersion),window.twitchAdSolutionsVersion=2;else{window.twitchAdSolutionsVersion=2;var H=[],r=null,B=["twitch","isVariantA"],C=[],D=["isVariantA","besuper/","${patch_url}"];window.reloadTwitchPlayer=G;var z=null;z=window.localStorage.getItem("local_copy_unique_id");A(window);(function(){var a=K(window.Worker),b=class extends J(window.Worker){constructor(d,h){function f(){var e=document.querySelector(".video-player"),g=null;null!=e&&(g=e.querySelector(".adblock-overlay"),null==
g&&(g=document.createElement("div"),g.className="adblock-overlay",g.innerHTML='<div class="player-adblock-notice" style="color: white; background-color: rgba(0, 0, 0, 0.8); position: absolute; top: 0px; left: 0px; padding: 5px;"><p></p></div>',g.style.display="none",g.P=g.querySelector("p"),e.appendChild(g)));return g}var l=!1;try{l=(new URL(d)).origin.endsWith(".twitch.tv")}catch{}l?(d=`
                    ${E.toString()}
                    ${y.toString()}
                    ${P.toString()}
                    ${v.toString()}
                    ${O.toString()}
                    ${A.toString()}
                    ${F.toString()}
                    ${t.toString()}
                    ${x.toString()}
                    ${Q.toString()}
                    ${w.toString()}
                    ${N.toString()}
                    var workerString = getWasmWorkerJs('${d.replaceAll("'","%27")}');
                    declareOptions(self);
                    self.addEventListener('message', function(e) {
                        if (e.data.key == 'UpdateIsSquadStream') {
                            IsSquadStream = e.data.value;
                        } else if (e.data.key == 'UpdateClientVersion') {
                            ClientVersion = e.data.value;
                        } else if (e.data.key == 'UpdateClientSession') {
                            ClientSession = e.data.value;
                        } else if (e.data.key == 'UpdateClientId') {
                            ClientID = e.data.value;
                        } else if (e.data.key == 'UpdateDeviceId') {
                            GQLDeviceID = e.data.value;
                        } else if (e.data.key == 'UpdateClientIntegrityHeader') {
                            ClientIntegrityHeader = e.data.value;
                        } else if (e.data.key == 'UpdateAuthorizationHeader') {
                            AuthorizationHeader = e.data.value;
                        }
                    });
                    hookWorkerFetch();
                    eval(workerString);
                `,super(URL.createObjectURL(new Blob([d])),h),H.push(this),this.addEventListener("message",e=>{"ShowAdBlockBanner"==e.data.key?(null==r&&(r=f()),r.P.textContent="Blocking ads",r.style.display="block"):"HideAdBlockBanner"==e.data.key?(null==r&&(r=f()),r.style.display="none"):"PauseResumePlayer"==e.data.key&&G(!0,!1,!1,!1,!1)})):super(d,h)}},c=L(b,a);Object.defineProperty(window,"Worker",{get:function(){return c},set:function(d){M(d)?c=d:console.log("Attempt to set twitch worker denied")}})})();
(function(){var a=window.fetch;window.fetch=function(b,c,...d){"string"===typeof b&&(window.location.pathname.includes("/squad")?q("UpdateIsSquadStream",!0):q("UpdateIsSquadStream",!1),b.includes("/access_token")||b.includes("gql"))&&(d=c.headers["X-Device-Id"],"string"!==typeof d&&(d=c.headers["Device-ID"]),"string"!==typeof d||d.includes("twitch-web-wall-mason")?z&&(GQLDeviceID=z.replace('"',""),GQLDeviceID=GQLDeviceID.replace('"',"")):GQLDeviceID=d,GQLDeviceID&&("string"===typeof c.headers["X-Device-Id"]&&
(c.headers["X-Device-Id"]=GQLDeviceID),"string"===typeof c.headers["Device-ID"]&&(c.headers["Device-ID"]=GQLDeviceID),q("UpdateDeviceId",GQLDeviceID)),(d=c.headers["Client-Version"])&&"string"==typeof d&&(ClientVersion=d),ClientVersion&&q("UpdateClientVersion",ClientVersion),(d=c.headers["Client-Session-Id"])&&"string"==typeof d&&(ClientSession=d),ClientSession&&q("UpdateClientSession",ClientSession),b.includes("gql")&&c&&"string"===typeof c.body&&c.body.includes("PlaybackAccessToken")&&((d=c.headers["Client-ID"])&&
"string"==typeof d?ClientID=d:(d=c.headers["Client-Id"])&&"string"==typeof d&&(ClientID=d),ClientID&&q("UpdateClientId",ClientID),(ClientIntegrityHeader=c.headers["Client-Integrity"])&&q("UpdateClientIntegrityHeader",ClientIntegrityHeader),(AuthorizationHeader=c.headers.Authorization)&&q("UpdateAuthorizationHeader",AuthorizationHeader)),b.includes("gql")&&c&&"string"===typeof c.body&&c.body.includes("PlaybackAccessToken")&&c.body.includes("picture-by-picture")&&(c.body=""),b.includes("picture-by-picture")&&
(b=""));return a.apply(this,arguments)}})();"complete"===document.readyState||"loaded"===document.readyState||"interactive"===document.readyState?I():window.addEventListener("DOMContentLoaded",function(){I()})}})();
