// ==UserScript==
// @name         TwitchAdSolutions (video-swap-new)
// @namespace    https://github.com/pixeltris/TwitchAdSolutions
// @version      1.35
// @updateURL https://raw.githubusercontent.com/siritami/test1/release/release/videoswapnew.meta.js
// @downloadURL https://raw.githubusercontent.com/siritami/test1/release/release/videoswapnew.user.js
// @author       pixeltris
// @match        *://*.twitch.tv/*
// @run-at       document-start
// @inject-into  page
// @grant        none
// ==/UserScript==
(function(){function w(a){a.OPT_MODE_STRIP_AD_SEGMENTS=!0;a.OPT_MODE_NOTIFY_ADS_WATCHED=!0;a.OPT_MODE_NOTIFY_ADS_WATCHED_MIN_REQUESTS=!1;a.OPT_BACKUP_PLAYER_TYPE="autoplay";a.OPT_BACKUP_PLATFORM="ios";a.OPT_REGULAR_PLAYER_TYPE="site";a.OPT_ACCESS_TOKEN_PLAYER_TYPE=null;a.OPT_SHOW_AD_BANNER=!0;a.AD_SIGNIFIER="stitched-ad";a.LIVE_SIGNIFIER=",live";a.CLIENT_ID="kimne78kx3ncx6brgo4mv6wki5h1ko";a.StreamInfos=[];a.StreamInfosByUrl=[];a.CurrentChannelNameFromM3U8=null;a.gql_device_id=null;a.ClientIntegrityHeader=
null;a.AuthorizationHeader=null}function E(a){for(var b=null,c=null;a;){var f=a.toString();x.some(e=>f.includes(e))&&!y.some(e=>f.includes(e))?null!==c&&Object.setPrototypeOf(c,Object.getPrototypeOf(a)):(null===b&&(b=a),c=a);a=Object.getPrototypeOf(a)}return b}function F(a){for(var b=[];a;){var c=a.toString();z.some(f=>c.includes(f))&&b.push(a);a=Object.getPrototypeOf(a)}return b}function G(a,b){for(var c=0;c<b.length;c++)Object.setPrototypeOf(b[c],a),a=b[c];return a}function H(a){var b=a.toString();
return!x.some(c=>b.includes(c))||y.some(c=>b.includes(c))||z.some(c=>b.includes(c))}function I(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.overrideMimeType("text/javascript");b.send();return b.responseText}function u(a,b,c){console.log("Found ads, switch to backup");a.UseBackupStream=!0;a.IsMidroll=b.includes('"MIDROLL"')||b.includes('"midroll"');c&&postMessage({key:"UboReloadPlayer"});postMessage({key:"UboShowAdBanner",isMidroll:a.IsMidroll})}async function A(a,b,c){var f=StreamInfosByUrl[a];
if(null==f)return console.log("Unknown stream url "+a),b;if(!OPT_MODE_STRIP_AD_SEGMENTS)return b;a=b.includes(AD_SIGNIFIER);if(f.UseBackupStream){if(null==f.Encodings)return console.log("Found backup stream but not main stream?"),f.UseBackupStream=!1,postMessage({key:"UboReloadPlayer"}),"";var e=f.Encodings.match(/^https:.*\.m3u8$/m)[0];e=await c(e);if(200==e.status&&(e=await e.text(),null!=e))if(!e.includes(AD_SIGNIFIER))console.log("No more ads on main stream. Triggering player reload to go back to main stream..."),
f.UseBackupStream=!1,postMessage({key:"UboHideAdBanner"}),postMessage({key:"UboReloadPlayer"});else if(!e.includes('"MIDROLL"')&&!e.includes('"midroll"')){e=e.replace("\r","").split("\n");for(var h=0;h<e.length;h++){var l=e[h];if(l.startsWith("#EXTINF")&&e.length>h+1&&!l.includes(LIVE_SIGNIFIER)&&!f.RequestedAds.has(e[h+1])){f.RequestedAds.add(e[h+1]);fetch(e[h+1]).then(g=>{g.blob()});break}}}}else a?u(f,b,!0):postMessage({key:"UboHideAdBanner"});a&&null!=f.BackupEncodings&&(e=f.BackupEncodings.match(/^https:.*\.m3u8.*$/m)[0],
e=await c(e),200==e.status&&(b=await e.text()));return b}function J(){console.log("hookWorkerFetch (video-swap-new)");var a=fetch;fetch=async function(b,c){if("string"===typeof b){b=b.trimEnd();if(b.endsWith("m3u8"))return new Promise(function(e,h){var l=async function(g){var d=await A(b,await g.text(),a);e(new Response(d,{status:g.status,statusText:g.statusText,headers:g.headers}))};(function(){return a(b,c).then(function(g){l(g)})["catch"](function(g){console.log("fetch hook err "+g);h(g)})})()});
if(b.includes("/api/channel/hls/")&&!b.includes("picture-by-picture")){var f=(new URL(b)).pathname.match(/([^\/]+)(?=\.\w+$)/)[0];CurrentChannelNameFromM3U8!=f&&postMessage({key:"UboChannelNameM3U8Changed",value:f});CurrentChannelNameFromM3U8=f;if(OPT_MODE_STRIP_AD_SEGMENTS)return new Promise(async function(e,h){h=StreamInfos[f];null!=h&&null!=h.Encodings&&200!==(await a(h.Encodings.match(/^https:.*\.m3u8$/m)[0])).status&&(h=null);if(null==h||null==h.Encodings||null==h.BackupEncodings){StreamInfos[f]=
h={RequestedAds:new Set,Encodings:null,BackupEncodings:null,IsMidroll:!1,UseBackupStream:!1,ChannelName:f};for(var l=0;2>l;l++){var g=b;if(1==l)if(g=await B(f,OPT_BACKUP_PLAYER_TYPE,OPT_BACKUP_PLATFORM,a),null!=g&&200===g.status){g=await g.json();var d=new URL("https://usher.ttvnw.net/api/channel/hls/"+f+".m3u8"+(new URL(b)).search);d.searchParams.set("sig",g.data.streamPlaybackAccessToken.signature);d.searchParams.set("token",g.data.streamPlaybackAccessToken.value);g=d.href}else{e(g);return}g=await a(g,
c);if(null!=g&&200===g.status){g=await g.text();if(0==l)if(h.Encodings=g,d=g.match(/^https:.*\.m3u8$/m)[0],d=await a(d),200==d.status)d=await d.text(),d.includes(AD_SIGNIFIER)&&u(h,d,!1);else{e(d);return}else{var k=g.replace("\r","").split("\n"),m=null;for(d=0;d<k.length;d++)if(k[d].startsWith("#EXT-X-STREAM-INF")){var q=p(k[d]).RESOLUTION;if(q&&k[d+1].endsWith(".m3u8")){m=k[d+1];break}}if(null!=m&&null!=h.Encodings){g=h.Encodings.replace("\r","").split("\n");for(d=0;d<g.length-1;d++)g[d].startsWith("#EXT-X-STREAM-INF")&&
(q=p(g[d]).RESOLUTION)&&(m+=" ",g[d+1]=m);g=g.join("\r\n")}h.BackupEncodings=g}g=g.replace("\r","").split("\n");for(d=0;d<g.length;d++)!g[d].startsWith("#")&&g[d].includes(".m3u8")&&(StreamInfosByUrl[g[d].trimEnd()]=h)}else{e(g);return}}}h.UseBackupStream?e(new Response(h.BackupEncodings)):e(new Response(h.Encodings))})}}return a.apply(this,arguments)}}function r(a,b,c){return[{operationName:"ClientSideAdEventHandling_RecordAdEvent",variables:{input:{eventName:a,eventPayload:JSON.stringify(c),radToken:b}},
extensions:{persistedQuery:{version:1,sha256Hash:"7e6c69e6eb59f8ccb97ab73686f3d8b7d85a72a0298745ccd8bfc68e4054ca5b"}}}]}function B(a,b,c,f){c||="web";return n({operationName:"PlaybackAccessToken_Template",query:'query PlaybackAccessToken_Template($login: String!, $isLive: Boolean!, $vodID: ID!, $isVod: Boolean!, $playerType: String!) {  streamPlaybackAccessToken(channelName: $login, params: {platform: "'+c+'", playerBackend: "mediaplayer", playerType: $playerType}) @include(if: $isLive) {    value    signature    __typename  }  videoPlaybackAccessToken(id: $vodID, params: {platform: "'+
c+'", playerBackend: "mediaplayer", playerType: $playerType}) @include(if: $isVod) {    value    signature    __typename  }}',variables:{isLive:!0,login:a,isVod:!1,vodID:"",playerType:b}},f)}function n(a,b){return(b?b:fetch)("https://gql.twitch.tv/gql",{method:"POST",body:JSON.stringify(a),headers:{"Client-Id":CLIENT_ID,"Client-Integrity":ClientIntegrityHeader,"X-Device-Id":gql_device_id,Authorization:AuthorizationHeader}})}function p(a){return Object.fromEntries(a.split(/(?:^|,)((?:[^=]*)=(?:"[^"]*"|[^,]*))/).filter(Boolean).map(b=>
{var c=b.indexOf("=");const f=b.substring(0,c);b=b.substring(c+1);c=Number(b);return[f,Number.isNaN(c)?b.startsWith('"')?JSON.parse(b):b:c]}))}async function K(a){try{if(!a||!a.includes(AD_SIGNIFIER))return 1;var b=a.match(/#EXT-X-DATERANGE:(ID="stitched-ad-[^\n]+)\n/);if(1<b.length){var c=p(b[1]),f=parseInt(c["X-TV-TWITCH-AD-POD-LENGTH"]?c["X-TV-TWITCH-AD-POD-LENGTH"]:"1");parseInt(c["X-TV-TWITCH-AD-POD-POSITION"]?c["X-TV-TWITCH-AD-POD-POSITION"]:"0");var e=c["X-TV-TWITCH-AD-RADS-TOKEN"],h=c["X-TV-TWITCH-AD-LINE-ITEM-ID"],
l=c["X-TV-TWITCH-AD-ORDER-ID"],g=c["X-TV-TWITCH-AD-CREATIVE-ID"],d=c["X-TV-TWITCH-AD-ADVERTISER-ID"];const k={stitched:!0,roll_type:c["X-TV-TWITCH-AD-ROLL-TYPE"].toLowerCase(),player_mute:!1,player_volume:.5,visible:!0};for(a=0;a<f;a++){if(!OPT_MODE_NOTIFY_ADS_WATCHED_MIN_REQUESTS)for(b={...k,ad_id:d,ad_position:a,duration:30,creative_id:g,total_ads:f,order_id:l,line_item_id:h},await n(r("video_ad_impression",e,b)),c=0;4>c;c++)await n(r("video_ad_quartile_complete",e,{...b,quartile:c+1}));await n(r("video_ad_pod_complete",
e,k))}}return 0}catch(k){return console.log(k),0}}function v(a,b){C.forEach(c=>{c.postMessage({key:a,value:b})})}function t(a,b){function c(d,k){if(d.stateNode&&k(d.stateNode))return d.stateNode;for(d=d.child;d;){const m=c(d,k);if(m)return m;d=d.sibling}return null}var f=function(){var d=null,k=document.querySelector("#root");k&&k._reactRootContainer&&k._reactRootContainer._internalRoot&&k._reactRootContainer._internalRoot.current&&(d=k._reactRootContainer._internalRoot.current);if(null==d){var m=
Object.keys(k).find(q=>q.startsWith("__reactContainer"));null!=m&&(d=k[m])}return d}();if(f){var e=c(f,d=>d.setPlayerActive&&d.props&&d.props.mediaPlayerInstance);e=e&&e.props&&e.props.mediaPlayerInstance?e.props.mediaPlayerInstance:null;f=c(f,d=>d.setSrc&&d.setInitialPlaybackSettings);if(!e)console.log("Could not find player");else if(!f)console.log("Could not find player state");else if(!e.paused&&!e.core?.paused)if(a)console.log("Force seek to reset player (hopefully fixing any audio desync) pos:"+
e.getPosition()+" range:"+JSON.stringify(e.getBuffered())),a=e.getPosition(),e.seekTo(0),e.seekTo(a);else if(b)e.pause(),e.play();else{var h=localStorage.getItem("video-quality"),l=localStorage.getItem("video-muted"),g=localStorage.getItem("volume");e?.core?.state&&(localStorage.setItem("video-muted",JSON.stringify({default:e.core.state.muted})),localStorage.setItem("volume",e.core.state.volume));e?.core?.state?.quality?.group&&localStorage.setItem("video-quality",JSON.stringify({default:e.core.state.quality.group}));
f.setSrc({isNewMediaPlayerInstance:!0,refreshAccessToken:!0});setTimeout(()=>{localStorage.setItem("video-quality",h);localStorage.setItem("video-muted",l);localStorage.setItem("volume",g)},3E3)}}else console.log("Could not find react root")}function D(){try{Object.defineProperty(document,"visibilityState",{get(){return"visible"}})}catch{}try{Object.defineProperty(document,"hidden",{get(){return!1}})}catch{}var a=h=>{h.preventDefault();h.stopPropagation();h.stopImmediatePropagation()};document.addEventListener("visibilitychange",
a,!0);document.addEventListener("webkitvisibilitychange",a,!0);document.addEventListener("mozvisibilitychange",a,!0);document.addEventListener("hasFocus",a,!0);try{/Firefox/.test(navigator.userAgent)?Object.defineProperty(document,"mozHidden",{get(){return!1}}):Object.defineProperty(document,"webkitHidden",{get(){return!1}})}catch{}a=["video-quality","video-muted","volume","lowLatencyModeEnabled","persistenceEnabled"];for(var b=new Map,c=0;c<a.length;c++)b.set(a[c],localStorage.getItem(a[c]));var f=
localStorage.setItem;localStorage.setItem=function(h,l){b.has(h)&&b.set(h,l);f.apply(this,arguments)};var e=localStorage.getItem;localStorage.getItem=function(h){return b.has(h)?b.get(h):e.apply(this,arguments)}}if(window.twitchAdSolutionsVersion&&2<=window.twitchAdSolutionsVersion)console.log("skipping video-swap-new as there's another script active. ourVersion:2 activeVersion:"+window.twitchAdSolutionsVersion),window.twitchAdSolutionsVersion=2;else{window.twitchAdSolutionsVersion=2;var C=[],x=["twitch",
"isVariantA"],y=[],z=["isVariantA","besuper/","${patch_url}"];window.reloadTwitchPlayer=t;w(window);(function(){var a=F(window.Worker),b=class extends E(window.Worker){constructor(f,e){function h(){var g=document.querySelector(".video-player"),d=null;null!=g&&(d=g.querySelector(".ubo-overlay"),null==d&&(d=document.createElement("div"),d.className="ubo-overlay",d.innerHTML='<div class="player-ad-notice" style="color: white; background-color: rgba(0, 0, 0, 0.8); position: absolute; top: 0px; left: 0px; padding: 5px;"><p></p></div>',
d.style.display="none",d.P=d.querySelector("p"),g.appendChild(d)));return d}var l=!1;try{l=(new URL(f)).origin.endsWith(".twitch.tv")}catch{}l?(f=`
                    ${A.toString()}
                    ${J.toString()}
                    ${w.toString()}
                    ${B.toString()}
                    ${n.toString()}
                    ${r.toString()}
                    ${K.toString()}
                    ${p.toString()}
                    ${u.toString()}
                    ${I.toString()}
                    var workerString = getWasmWorkerJs('${f.replaceAll("'","%27")}');
                    declareOptions(self);
                    self.addEventListener('message', function(e) {
                        if (e.data.key == 'UboUpdateDeviceId') {
                            gql_device_id = e.data.value;
                        } else if (e.data.key == 'UpdateClientIntegrityHeader') {
                            ClientIntegrityHeader = e.data.value;
                        } else if (e.data.key == 'UpdateAuthorizationHeader') {
                            AuthorizationHeader = e.data.value;
                        }
                    });
                    hookWorkerFetch();
                    eval(workerString);
                `,super(URL.createObjectURL(new Blob([f])),e),C.push(this),this.addEventListener("message",g=>{if("UboShowAdBanner"==g.data.key){var d=h();null!=d&&(d.P.textContent="Blocking"+(g.data.isMidroll?" midroll":"")+" ads",OPT_SHOW_AD_BANNER&&(d.style.display="block"))}else"UboHideAdBanner"==g.data.key?(d=h(),null!=d&&(d.style.display="none")):"UboChannelNameM3U8Changed"!=g.data.key&&("UboReloadPlayer"==g.data.key?t():"UboPauseResumePlayer"==g.data.key?t(!1,!0):"UboSeekPlayer"==g.data.key&&
t(!0))})):super(f,e)}},c=G(b,a);Object.defineProperty(window,"Worker",{get:function(){return c},set:function(f){H(f)?c=f:console.log("Attempt to set twitch worker denied")}})})();(function(){var a=window.fetch;window.fetch=function(b,c,...f){if("string"===typeof b&&b.includes("gql")&&(f=c.headers["X-Device-Id"],"string"!==typeof f&&(f=c.headers["Device-ID"]),"string"===typeof f&&(gql_device_id=f),gql_device_id&&v("UboUpdateDeviceId",gql_device_id),"string"===typeof c.body&&c.body.includes("PlaybackAccessToken"))){if(OPT_ACCESS_TOKEN_PLAYER_TYPE){f=
JSON.parse(c.body);if(Array.isArray(f))for(let e=0;e<f.length;e++)f[e].variables.playerType=OPT_ACCESS_TOKEN_PLAYER_TYPE;else f.variables.playerType=OPT_ACCESS_TOKEN_PLAYER_TYPE;c.body=JSON.stringify(f)}"string"===typeof c.headers["Client-Integrity"]&&(ClientIntegrityHeader=c.headers["Client-Integrity"])&&v("UpdateClientIntegrityHeader",c.headers["Client-Integrity"]);"string"===typeof c.headers.Authorization&&(AuthorizationHeader=c.headers.Authorization)&&v("UpdateAuthorizationHeader",c.headers.Authorization)}return a.apply(this,
arguments)}})();"complete"===document.readyState||"loaded"===document.readyState||"interactive"===document.readyState?D():window.addEventListener("DOMContentLoaded",function(){D()})}})();
