// ==UserScript==
// @name         youtube-adb
// @namespace    https://github.com/iamfugui/youtube-adb
// @version      6.21
// @match        *://*.youtube.com/*
// @exclude      *://accounts.youtube.com/*
// @exclude      *://www.youtube.com/live_chat_replay*
// @exclude      *://www.youtube.com/persist_identity*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=YouTube.com
// @grant        none
// @license MIT
// @downloadURL https://raw.githubusercontent.com/siritami/test1/release/release/YouTubeE58EBBE5B9BFE5918A.user.js
// @updateURL https://raw.githubusercontent.com/siritami/test1/release/release/YouTubeE58EBBE5B9BFE5918A.meta.js
// ==/UserScript==
(function(){function d(a){if(!window.dev)return!1;console.log(window.location.href);var b=console,e=b.log,c=new Date;let g=c.getFullYear(),n=(c.getMonth()+1).toString().padStart(2,"0"),p=c.getDate().toString().padStart(2,"0"),q=c.getHours().toString().padStart(2,"0"),r=c.getMinutes().toString().padStart(2,"0");c=c.getSeconds().toString().padStart(2,"0");e.call(b,`${`${g}-${n}-${p} ${q}:${r}:${c}`}  ${a}`)}function h(a){if(document.getElementById(a))return!0;let b=document.createElement("style");b.id=
a;(document.head||document.body).appendChild(b);return!1}function t(a){a.forEach((b,e)=>{a[e]=`${b}{display:none!important}`});return a.join(" ")}function u(){var a=[...document.querySelectorAll("ytd-popup-container")].filter(b=>b.querySelector('a[href="/premium"]'));0<a.length&&(a.forEach(b=>b.remove()),d("\u79fb\u9664YT\u62e6\u622a\u5668"));a=document.querySelectorAll("tp-yt-iron-overlay-backdrop");if(a=Array.from(a).find(b=>"2201"===b.style.zIndex))a.className="",a.removeAttribute("opened"),d("\u5173\u95ed\u906e\u7f69\u5c42")}
function k(a,b){a=document.querySelector(".ytp-ad-skip-button")||document.querySelector(".ytp-skip-ad-button")||document.querySelector(".ytp-ad-skip-button-modern");b=document.querySelector(".video-ads.ytp-ad-module .ytp-ad-player-overlay")||document.querySelector(".ytp-ad-button-icon");(a||b)&&-1===window.location.href.indexOf("https://m.youtube.com/")&&(f.muted=!0);if(a)if(setTimeout(k,500),.5<f.currentTime)f.currentTime=f.duration,d("\u7279\u6b8a\u8d26\u53f7\u8df3\u8fc7\u6309\u94ae\u5e7f\u544a");
else{a.click();b=new Touch({identifier:Date.now(),target:a,clientX:12,clientY:34,radiusX:56,radiusY:78,rotationAngle:0,force:1});var e=new TouchEvent("touchstart",{bubbles:!0,cancelable:!0,view:window,touches:[b],targetTouches:[b],changedTouches:[b]});a.dispatchEvent(e);b=new TouchEvent("touchend",{bubbles:!0,cancelable:!0,view:window,touches:[],targetTouches:[],changedTouches:[b]});a.dispatchEvent(b);d("\u6309\u94ae\u8df3\u8fc7\u5e7f\u544a")}else b&&(f.currentTime=f.duration,d("\u5f3a\u5236\u7ed3\u675f\u4e86\u8be5\u5e7f\u544a"))}
function v(a){if(h(a))return d("\u53bb\u9664\u64ad\u653e\u4e2d\u7684\u5e7f\u544a\u529f\u80fd\u5df2\u5728\u8fd0\u884c"),!1;a=document.body;(new MutationObserver(()=>{f=document.querySelector(".ad-showing video")||document.querySelector("video");u();k();f.paused&&1>f.currentTime&&(f.play(),d("\u81ea\u52a8\u64ad\u653e\u89c6\u9891"))})).observe(a,{childList:!0,subtree:!0});d("\u8fd0\u884c\u53bb\u9664\u64ad\u653e\u4e2d\u7684\u5e7f\u544a\u529f\u80fd\u6210\u529f")}function l(){if(h("removeADHTMLElement"))d("\u5c4f\u853d\u9875\u9762\u5e7f\u544a\u8282\u70b9\u5df2\u751f\u6210");
else{var a=document.createElement("style");(document.head||document.body).appendChild(a);a.appendChild(document.createTextNode(t(w)));d("\u751f\u6210\u5c4f\u853d\u9875\u9762\u5e7f\u544a\u8282\u70b9\u6210\u529f")}v("removePlayerAD")}"use strict";let f;const w='#masthead-ad;ytd-rich-item-renderer.style-scope.ytd-rich-grid-row #content:has(.ytd-display-ad-renderer);.video-ads.ytp-ad-module;tp-yt-paper-dialog:has(yt-mealbar-promo-renderer);ytd-engagement-panel-section-list-renderer[target-id="engagement-panel-ads"];#related #player-ads;#related ytd-ad-slot-renderer;ytd-ad-slot-renderer;yt-mealbar-promo-renderer;ytd-popup-container:has(a[href="/premium"]);ad-slot-renderer;ytm-companion-ad-renderer'.split(";");
window.dev=!1;"loading"===document.readyState?(document.addEventListener("DOMContentLoaded",l),d("YouTube\u53bb\u5e7f\u544a\u811a\u672c\u5373\u5c06\u8c03\u7528:")):(l(),d("YouTube\u53bb\u5e7f\u544a\u811a\u672c\u5feb\u901f\u8c03\u7528:"));let m=()=>{const a=document.body.querySelector("video.html5-main-video");a&&a.paused&&(console.log("resume video"),a.play())};(new MutationObserver(a=>a.forEach(b=>{"childList"===b.type&&Array.from(b.addedNodes).filter(e=>1===e.nodeType).map(e=>{var c=e.querySelector(".ytd-popup-container > .ytd-popup-container > .ytd-enforcement-message-view-model");
if(c){c.parentNode.remove();console.log("remove popup",c);const g=document.getElementsByTagName("tp-yt-iron-overlay-backdrop");for(c=(g||[]).length;c--;)g[c].remove();m()}"tp-yt-iron-overlay-backdrop"===e.tagName.toLowerCase()&&(e.remove(),m(),console.log("remove backdrop",e))})}))).observe(document.body,{childList:!0,subtree:!0})})();
