name: 1.Build
on:
  workflow_dispatch:
jobs:
  Build:
    name: Download
    permissions: write-all
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install Python
        uses: actions/setup-python@main
        with:
          python-version: 3.11
      - name: Install JDK Zulu
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Insstall Python Packages
        run: |
          pip install -r src\requirements.txt
      - name: Download
        run: python src\build\Revanced_Extended.py
      - name: Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: |
            download_apk\*
          name: Revanced & Revanced Extended
          tag: all
          body: "Hello"
          allowUpdates: true