name: Manual Patch
permissions: write-all
env:
  repository: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  org_input: ${{ inputs.org }}
  org_event_input: ${{ github.event.inputs.org }}
on:
  workflow_dispatch:
    inputs:
      org:
        description: 'Which "Revanced" do you want to patch?'
        required: true
        default: 'Revanced'
        type: choice
        options:
          - 'Revanced Extended'
  workflow_call:
    inputs:
      org:
        required: true
        type: string
jobs:
  patch_rve:
    name: Patch Revanced Extended Stable in Sandbox
    if: ${{ github.event.inputs.org == 'Revanced Extended' || inputs.org == 'Revanced Extended' }}
    runs-on: ubuntu-latest
    container:
      image: arm64v8/ubuntu:24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Preparing to patch
        uses: ./.github/actions/preparing

      - name: Patch apk in Sandbox
        id: patch-rve
        if: steps.check-gh-rve.outputs.internet_error == '0'
        run: |
          apt-get update
          apt-get install -y curl jq wget
          bash src/build/Revanced-Extended.sh

      - name: Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: |
            ./release/*.apk
          name: Revanced & Revanced Extended
          tag: all
          body: "hello"
          allowUpdates: true