name: Manual Patch
permissions: write-all
env:
  repository: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  org_input: ${{ inputs.org }}
  org_event_input: ${{ github.event.inputs.org }}

on:
  workflow_dispatch:
    inputs:
      org:
        description: 'Which "Revanced" do you want to patch?'
        required: true
        default: 'Revanced'
        type: choice
        options:
          - 'Revanced Extended'
  workflow_call:
    inputs:
      org:
        required: true
        type: string

jobs:
  patch_rve:
    name: Patch Revanced Extended Stable
    if: ${{ github.event.inputs.org == 'Revanced Extended' || inputs.org == 'Revanced Extended' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Build Docker image
        run: |
          docker build -t revanced-patch-sandbox .

      - name: Run patching inside Docker container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            -w /workspace/src/build \
            revanced-patch-sandbox bash Revanced-Extended.sh

      - name: Releasing APK files
        if: success()
        uses: ./.github/actions/release
