name: Manual Patch
permissions: write-all
env:
  repository: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  org_input: ${{ inputs.org }}
  org_event_input: ${{ github.event.inputs.org }}
on:
  workflow_dispatch:
    inputs:
      org:
        description: 'Which "Revanced" do you want to patch?'
        required: true
        default: 'Revanced'
        type: choice
        options:
          - 'Revanced'
          - 'Revanced Beta'
          - 'Revanced Extended'
          - 'Revanced Extended Beta'
          - 'Revanced Extended Reddit'
          - 'RVE-anddea-stable'
          - 'RVE-anddea-beta'
          - 'Twitter Piko Stable'
          - 'Twitter Piko Beta'
          - 'Revanced Extended Android 6,7'
          - 'Revanced Extended Android 5'
          - 'BiliRoamingM'
          - 'Dropped Patches - indrastorms'
  workflow_call:
    inputs:
      org:
        required: true
        type: string
jobs:
  patch_rve:
    name: Patch Revanced Extended Stable
    if: ${{ github.event.inputs.org == 'Revanced Extended' || inputs.org == 'Revanced Extended' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        run: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: Build Docker Image
        run: |
          docker build -t patch-env ./src

      - name: Run Patching in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/src:/src \
            patch-env /bin/bash -c "/src/build/Revanced-Extended.sh ${{ matrix.run }}"

      - name: Releasing APK files
        if: success()
        uses: ./.github/actions/release
